### ISSUE TITLE
CoqIDE 8.7.2 crashes on OS X when selecting any text

### ISSUE THREAD

**Issue by varkor** [coq/coq#6778] opened 2018-02-17 13:31 UTC
**CoqIDE version: 8.7.2** (was also present in 8.7.1 and 8.7.0 — I haven't tried any earlier versions)
**OS: OS X 10.11.6** (El Capitan)

Selecting any text (by pressing command-A, highlighting with the cursor, or any similar method) immediately crashes CoqIDE. This is making it exceedingly difficult to use.

[This bug report](https://github.com/coq/coq/issues/6509) seems similar, but was apparently fixed, so it seemed more sensible to open up a new bug report.

**Comment by Zimmi48** [comment] 2018-02-17 14:36
Thanks for the bug report. That's quite unfortunate to learn about this only now. Can someone on MacOS reproduce this behavior? If yes, please specify if it is with the same version of MacOS or another one.

**Comment by ejgallego** [comment] 2018-02-17 15:11
Where is the OSX build log @Zimmi48 ?

**Comment by herbelin** [comment] 2018-02-17 15:22
Selecting any text in CoqIDE (by pressing command-A, highlighting with the cursor, or any similar method) works for me with the package found [here](https://github.com/coq/coq/releases/download/V8.7.2/coq-8.7.2-installer-macos.dmg), running OS X 10.11.1.

One would need more testers...

**Comment by Zimmi48** [comment] 2018-02-17 21:50
@ejgallego it is here https://travis-ci.org/coq/coq/jobs/342090079 but I don't think you'll learn much from it.

**Comment by Zimmi48** [comment] 2018-02-19 13:53
@varkor Can you confirm how you installed CoqIDE? Using the package provided at https://github.com/coq/coq/releases/download/V8.7.2/coq-8.7.2-installer-macos.dmg or using another method?

**Comment by anton-trunov** [comment] 2018-02-19 14:03
macOS High Sierra (10.13.3) user here. I've installed CoqIDE using the [recommended installer](https://github.com/coq/coq/releases/download/V8.7.2/coq-8.7.2-installer-macos.dmg). I haven't thoroughly tested it, but Cmd-A, selecting text with the mouse works fine. No crushes were observed.

**Comment by varkor** [comment] 2018-02-19 14:03
@Zimmi48: I used the package you link in your post, from the GitHub releases, yes.

**Comment by Zimmi48** [comment] 2018-02-19 14:08
@anton-trunov is on a later version but @herbelin is on 10.11.1 which is an earlier version of El Capitan.

**Comment by vbgl** [comment] 2018-02-27 14:21
Just tested on MacOS 10.11.6 (15G19009); `coqide` version 8.7.2, compiled with OCaml-4.04.2.

Keyboard short-cut (command-A) and mouse selection both work as expected.

**Comment by Zimmi48** [comment] 2018-02-27 15:08
@vbgl Could you also try with the [official installer](https://github.com/coq/coq/releases/download/V8.7.2/coq-8.7.2-installer-macos.dmg)?
Anyways, if nobody can reproduce, even with the same MacOS version, we're going to have to close this bug report...

**Comment by vbgl** [comment] 2018-02-27 15:23
Same behaviour with the official installer.

**Comment by Zimmi48** [comment] 2018-02-27 16:40
So @varkor, that's probably an issue coming from your machine. Sorry we couldn't be of any help.

**Closed by Zimmi48** 2018-02-27 16:40 UTC
Labels: help wanted, needs: feedback, part: IDE, platform: macOS
