### ISSUE TITLE
"tactic1. Back. Back." gives the same proof state as "tactic1."

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#7945] opened 2018-06-28 05:01 UTC
#### Description of the problem

"tactic1. Back." gets you to the proof state just before tactic1 was applied.  If you do "Back." again, you get the same proof state as if you only entered "tactic1."  Surely this is not useful this way.  I'm guessing it's related to stm creating a new state for "Back." rather than just popping the last state.

I don't know whether this is important to fix for coqtop; coqide seems to use a different mechanism for its navigation buttons that works I expected.

```
Coq < Lemma ev_even_firsttry : forall n,
Coq <   ev n -> exists k, n = double k.
1 subgoal

  ============================
  forall n : nat, ev n -> exists k : nat, n = double k

ev_even_firsttry < Proof.

ev_even_firsttry < intros n E.
1 subgoal

  n : nat
  E : ev n
  ============================
  exists k : nat, n = double k

ev_even_firsttry < Back.
1 subgoal

  ============================
  forall n : nat, ev n -> exists k : nat, n = double k

ev_even_firsttry < Back.
1 subgoal

  n : nat
  E : ev n
  ============================
  exists k : nat, n = double k

ev_even_firsttry <
```

**Comment by JasonGross** [comment] 2018-06-28 05:15
I believe the supported answer for this is to use `Undo n.`, which lets you go back multiple steps at once.

**Comment by jfehrle** [comment] 2018-06-28 05:47
Interesting,  `Undo` works as I expected: `tactic1. tactic2. Undo. Undo.` is a no-op.

There is a `Back n.` form that goes back multiple steps at once, but `Back n. Back` is a no-op (provided n is in range).  I don't see how this is useful.

**Comment by ppedrot** [comment] 2020-02-09 16:16
This is not a bug and was part of the design of the meta-commands. @gares and @ejgallego can probably explain more about that, but in any case this is not bug, so I am closing this.

**Closed by ppedrot** 2020-02-09 16:16 UTC
Labels: part: STM
