### ISSUE TITLE
Anomaly "Uncaught exception Not_found." when trying to annotate Set with a modality

### ISSUE THREAD

**Issue by elefthei** [coq/coq#15310] opened 2021-12-07 19:44 UTC
#### Description of the problem

Small Coq snippet below, depends on Coq ext-lib slightly. What I am trying to do is annotate `Type` with a modality `K[i]`

#### Coq Version
```coq
From ExtLib Require Import
     Structures.Monad.

Set Implicit Arguments.

Module Foo.
  Variable uid : Set.
 
  (** An indexed Monad by uid *)
  Variable K: uid -> Type -> Type.
  Parameter K_monad: forall u, Monad (K u).
 (* A family of instances *)
  Global Existing Instance K_monad. 

  Notation "'K[' u ']' t" := (K u t) (at level 10).
  Inductive cmd : forall u, K[u] Type -> Type :=
    | Return {result : Set} (r : result) : cmd (ret result).
```

### Coq version
```
The Coq Proof Assistant, version 8.13.2 (July 2021)
compiled on Jul 19 2021 2:56:48 with OCaml 4.07.1
```

**Comment by SkySkimmer** [comment] 2021-12-07 19:56
Cannot reproduce on master

**Comment by SkySkimmer** [comment] 2021-12-07 20:07
Actually cannot reproduce on 8.13.2 either.

**Comment by elefthei** [comment] 2021-12-07 22:18
Missed one thing 
`Set Implicit Arguments`

editted to include it as it.

**Comment by SkySkimmer** [comment] 2021-12-07 22:30
Duplicate of #13946, or at least fixed by the same commit.

**Closed by SkySkimmer** 2021-12-07 22:30 UTC
