### ISSUE TITLE
lia does not handle renaming of types well.

### ISSUE THREAD

**Issue by FlorianSteinberg** [coq/coq#6936] opened 2018-03-07 14:18 UTC
#### Version
8.7

#### Operating system
n\a

#### Description of the problem

lia does not handle renaming of types well. Here is a minimal working example:

```
Require Import Psatz Arith.

Definition N := nat.
Lemma ex (n : N):
	n <= 0 -> n = 0.
Proof.
intros.
Fail lia.
unfold N in n.
Fail lia.
unfold N.
lia.
Qed.
```

**Comment by pi8027** [comment] 2019-09-18 14:27
Duplicate of #4717.

**Comment by ppedrot** [comment] 2019-09-18 15:41
Let's close then.

**Closed by ppedrot** 2019-09-18 15:41 UTC
Labels: kind: enhancement, needs: triage, part: tactics
