### ISSUE TITLE
CoqIDE links to old documentation

### ISSUE THREAD

**Issue by HJvT** [coq/coq#10432] opened 2019-06-25 13:24 UTC
#### Description of the problem
Selecting _Help > Browse Coq Manual_ brings me at:
https://coq.inria.fr/distrib/8.5beta2/refman/
Selecting _Help > Browse Coq Library_ leads to:
https://coq.inria.fr/distrib/8.5beta2/stdlib/

#### Coq Version
8.9.1

**Comment by vbgl** [comment] 2019-06-25 14:22
Thanks for your report. This is a duplicate of #8749.

**Closed by vbgl** 2019-06-25 14:22 UTC
Labels: resolved: duplicate(d)
