### ISSUE TITLE
Ltac2 `match! goal` should be able to handle bodies

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16618] opened 2022-10-06 11:31 UTC
```coq
Require Import Ltac2.Ltac2.
Require Import Ltac2.Printf.
Goal let x := True in True.
  intro.
  lazy_match! goal with
  | [ x := ?v |- _ ] => printf "%t" v
  end.
  (* Error: Syntax error: ':' expected after [name] (in [gmatch_hyp_pattern]). *)
```

**Comment by SkySkimmer** [comment] 2022-10-13 10:28
Duplicate of #12803

**Closed by SkySkimmer** 2022-10-13 10:28 UTC
Labels: part: ltac2
