### ISSUE TITLE
Set Silent is broken

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6645] opened 2018-01-23 21:18 UTC
#### Version

8.8+alpha (e2d1c676b23a335b4fb8a528c99dfca2b82a1a39)

#### Description of the problem

This is wrong, and makes it extremely painful to do some proofs because every period incurs an overhead of multiple seconds while Coq does useless work trying to print goals.

```coq
$ ~/.local64/coq/coq-master/bin/coqtop -emacs
Welcome to Coq jgross-Leopard-WS:/home/jgross/Downloads/coq/coq-master,master (e2d1c676b23a335b4fb8a528c99dfca2b82a1a39)

<prompt>Coq < 3 || 0 < </prompt>Set Silent.

<prompt>Coq < 4 || 0 < </prompt>Goal True.
1 subgoal (ID 1)
  
  ============================
  True

<prompt>Unnamed_thm < 5 |branch| 0 < </prompt>
jgross@jgross-Leopard-WS:~/Documents/repos/coq$ ~/.local64/coq/coq-master/bin/coqtop -emacs
Welcome to Coq jgross-Leopard-WS:/home/jgross/Downloads/coq/coq-master,master (e2d1c676b23a335b4fb8a528c99dfca2b82a1a39)

<prompt>Coq < 3 || 0 < </prompt>Goal True.
1 subgoal (ID 1)
  
  ============================
  True

<prompt>Unnamed_thm < 4 |branch| 0 < </prompt>Set Silent.

<prompt>Unnamed_thm < 6 |branch| 0 < </prompt>idtac.
1 subgoal (ID 1)
  
  ============================
  True

<prompt>Unnamed_thm < 7 |branch| 0 < </prompt>
```

**Comment by ejgallego** [comment] 2018-01-23 22:00
Well, `Set Silent` is broken by design, so not sure what kind of brokeness we are seeing here. I'd like to see #6374 merged before addressing this, but that'll require some more work.

**Comment by JasonGross** [comment] 2018-01-23 22:08
`Set Silent` is supposed to suppress printing of the goal, at least for commands other than `Show.`

**Comment by ejgallego** [comment] 2018-01-23 22:15
Umm, this is strange, I'll do a bisect [but not before Fri as I am on the road right now, so feel free to provide a bad commit if you can]. Looking at the code I still see the `not !Flags.quiet` so I wonder what's going wrong.

**Comment by ejgallego** [comment] 2018-01-23 22:29
Ok so I found the problem, the `Flags.verbosely` combinator does indeed disable "quiet" mode. [what a mess]

It seems some refactoring of the code made the core toplevel function to be called under the `verbosely` combinator, thus the flag is always disabled and the goal gets printed. Will try to locate the bad snippet and fix ASAP.

**Comment by ejgallego** [comment] 2018-01-23 22:34
Umm, I am not sure the problem is that one. Strange... but for some reason, even after `Set Silent` the `quiet` flags is false at goal printing time.

**Closed** 2018-02-01 17:58 UTC
Labels: kind: regression, kind: user messages, priority: blocker
