### ISSUE TITLE
Anomaly "existential variable 166 not found." in a Program Definition

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6498] opened 2017-12-23 01:10 UTC
Maybe for superficial reasons but the following raises "Anomaly "existential variable 166 not found." since 8.7.0.

```coq
Require Coq.Lists.List.
Global Set Implicit Arguments.
Import Coq.Lists.List.
Class IndexBound {A : Set} (a : A) (Bound : list A) :=
  { ibound :> nat;
    boundi : nth_error Bound ibound = Some a}.
Global Arguments ibound {A} [a Bound] _ .
Global Arguments boundi {A} [a Bound] _.
Record BoundedIndex {A : Set} (Bound : list A) :=
  { bindex : A;
    indexb :> IndexBound bindex Bound }.

Context {A : Type} {C : Set}.
Variable (projAC : A -> C).
Axiom None_neq_Some : forall (AnyT AnyT' : Type) (a : AnyT), None = Some a -> AnyT'.

Definition nth_Bounded'
           (Bound : list A)
           (c : C)
           (a_opt : option A)
           (nth_n : option_map projAC a_opt = Some c)
: A := match a_opt as x
             return (option_map projAC x = Some c) -> A with
         | Some a => fun _ => a
         | None => fun f => None_neq_Some _ f
       end nth_n.

Axiom nth_error_map : forall n As c_opt, nth_error (map projAC As) n = c_opt -> option_map projAC (nth_error As n) = c_opt.

Definition nth_Bounded
           (Bound : list A)
           (idx : BoundedIndex (map projAC Bound))
: A := nth_Bounded' Bound (nth_error Bound (ibound idx))
                    (nth_error_map _ _ (boundi idx)).

Program Definition nth_Bounded_ind2
        (P : forall As, BoundedIndex (map projAC As)
                        -> BoundedIndex (map projAC As)
                        -> A -> A -> Prop)
: forall (Bound : list A)
         (idx : BoundedIndex (map projAC Bound))
         (idx' : BoundedIndex (map projAC Bound)),
    match nth_error Bound (ibound idx), nth_error Bound (ibound idx') with
      | Some a, Some a' => P Bound idx idx' a a'
      | _, _ => True
    end
    -> P Bound idx idx' (nth_Bounded _ idx) (nth_Bounded _ idx'):=
  fun Bound idx idx' =>
    match (nth_error Bound (ibound idx)) as e, (nth_error Bound (ibound idx')) as e'
          return
          (forall (f : option_map _ e = Some (bindex idx))
                  (f' : option_map _ e' = Some (bindex idx')),
             (match e, e' with
                | Some a, Some a' => P Bound idx idx' a a'
                | _, _ => True
              end)
             -> P Bound idx idx'
                  (match e as e'' return
                         option_map _ e'' = Some (bindex idx)
                         -> A
                   with
                     | Some a => fun _ => a
                     | _ => fun f => _
                   end f)
                  (match e' as e'' return
                         option_map _ e'' = Some (bindex idx')
                         -> A
                   with
                     | Some a => fun _ => a
                     | _ => fun f => _
                   end f')) with
      | Some a, Some a' => fun _ _ H => _
      | _, _ => fun f => _
    end (nth_error_map _ _ (boundi idx))
        (nth_error_map _ _ (boundi idx')).
```

**Comment by Zimmi48** [comment] 2018-02-09 15:22
Any volunteer to investigate this regression?

**Comment by maximedenes** [comment] 2018-03-07 10:40
No assignee, so removing the milestone.

**Comment by Zimmi48** [comment] 2018-03-07 16:54
I suppose then that you think that this regression is not too worrying. Otherwise I guess you should assign someone instead...

**Comment by maximedenes** [comment] 2018-03-07 17:03
It does seem a bit worrying, so let's assign @mattam82. I hope it makes sense.

**Comment by ejgallego** [comment] 2018-03-07 17:08
I am really against this milestone removal from issues, when we did discuss that? In fact all issues should have a milestone, otherwise we'll do bugzilla 2

**Comment by maximedenes** [comment] 2018-04-11 17:49
Apparently @Zimmi48 and @ejgallego decided that @mattam82 would look at this for 8.8.0... What is the current status?

**Comment by maximedenes** [comment] 2018-04-12 15:50
Didn't hear back, removing the milestone. @mattam82 please put back one that reflects your schedule. Thanks!

**Comment by ejgallego** [comment] 2018-10-14 15:02
Seems to be fixed in `master`.

**Closed** 2018-10-14 15:02 UTC
Labels: help wanted, kind: anomaly, kind: regression
