### ISSUE TITLE
Binding conflicts between ssreflect and Ltac(1)

### ISSUE THREAD

**Issue by Blaisorblade** [coq/coq#10928] opened 2019-10-21 15:57 UTC
I have a case where ssreflect tactic `bar` works (and is closed) but `Ltac foo := bar.` fails. It seems an issue against Ltac(1?) scoping. See
https://gist.github.com/Blaisorblade/b22dc557018e6ee8c048df9cec206f1b#file-bugltacssreflect-v-L30-L39.

Tactic `Ltac foo := rewrite -[ER in (_ = ER)]addn0.` gives error
```
The reference ER was not found in the current environment.
```
even tho `ER` is bound by the later pattern.

Somehow, extra parens fix that, and `Ltac foo := rewrite -[(ER in (_ = ER))]addn0.` works.

Is this one of the Ltac1 ident weirdnesses fixed by Ltac2? (/cc @ppedrot). In this case, after checking this can be handled correctly with Ltac2, maybe this should be closed as WONTFIX.

**Comment by ppedrot** [comment] 2019-10-21 20:05
If anything, it is rather a bug of the ssreflect implementation which is likely missing some context enrichment in the interpretation of rewrite pattern. As for Ltac2, ssr is still waiting for its Ltac2 bindings, so don't expect too much on that side in a near future.

**Comment by Blaisorblade** [comment] 2019-10-21 22:35
Seems an actual bug then. /cc @gares.

**Comment by gares** [comment] 2019-10-22 08:25
This could be a duplicate of #6687 but the fix is harder than what I thought (that is #8314 is not going to work).

Wrt Ltac2, I'd like to work on that, but it is unlikely to be done for 8.11

**Comment by ppedrot** [comment] 2019-11-11 13:11
Duplicate of #6687

**Closed by ppedrot** 2019-11-11 13:11 UTC
