### ISSUE TITLE
Asynchronous proofs cause a spurious universe inconsistency in CoqIDE

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#9423] opened 2019-01-28 15:05 UTC
#### Version

Coq 8.8.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following actions cause a spurious universe inconsistency.

* Open CoqIDE.
* Insert the following pedagogical showcase into the buffer.
* Navigate to the end.

```coq
Require Omega.
Require Recdef.

Fixpoint plus' (n p : nat) : nat :=
  match n with
  | O => p
  | S q => S (plus' q p)
  end.

Fail Fixpoint mult' (n p : nat) : nat :=
  match n with
  | O => O
  | S q => plus' p (mult' p q)
  end.

Section Decreasing.

Import Omega.
Import Recdef.

Function f_mult' (np : nat * nat) {measure (fun '(n, p) => n + p) np} : nat :=
  let (n, p) := np in
  match n with
  | O => O
  | S q => plus' p (f_mult' (p, q))
  end.
Proof. intros _ _ p q _ _. omega. Qed.

Definition mult' (n p : nat) : nat := f_mult' (n, p).

End Decreasing.
```

```
Universe inconsistency.
```

There are two ways to recover.
The more convenient one is to be more patient.

* Navigate to any point before `Proof` of `mult''`.
* Navigate to any point between `omega` and `Qed` of `mult''`.
* Wait for the proof workers to catch up.
* Navigate to the end.

The less convenient one is to disable asynchronous proofs altogether.

* Open the *Tools* menu.
* Open the *Coqtop arguments* dialog.
* Enter `-async-proofs off` into the text field.
* Push the `OK` button.
* Navigate to the end.

**Comment by ejgallego** [comment] 2019-04-01 11:48
I added the milestone as to close this bug if no reproduction in the 8.10 branch is confirmed.

**Comment by vbgl** [comment] 2019-04-24 13:25
Cannot reproduce on branch v8.10. Closing.

**Closed by vbgl** 2019-04-24 13:25 UTC
Labels: needs: triage, part: STM, part: funind
