### ISSUE TITLE
"Anomaly "last_arg." Please report at http://coq.inria.fr/bugs/."

### ISSUE THREAD

**Issue by LaltonDundy** [coq/coq#10689] opened 2019-08-22 21:14 UTC
I was told by the CoqIDE to post this bug here.

The error reading is this

"Anomaly "last_arg." Please report at http://coq.inria.fr/bugs/."

Here is my Code.

```
Inductive Nec_Nat : Type :=
| Unit : Nec_Nat
| More : Nec_Nat -> Nec_Nat
.

Fixpoint Nec_Nat_f (a : Nec_Nat) : nat :=
match a with
| Unit   => 0
| More x => 1 + (Nec_Nat_f x)
end .

Fixpoint Nec_Nat_g (a : nat) : Nec_Nat :=
match a with
| 0   => Unit
| S n => More (Nec_Nat_g n)
end .

Definition Pos_Nat := option Nec_Nat.

Fixpoint Pos_Nat_f (a : Pos_Nat) : nat :=
match a with
| None          => 0
| Some x        => 1 + (Nec_Nat_f x)
end.

Fixpoint Pos_Nat_g (a : nat) : Pos_Nat :=
match a with
| 0     => None
| S n   => Some (Nec_Nat_g n)
end.

Inductive Nec_Int : Type :=
| Pos : Nec_Nat -> Nec_Int
| Neg : Nec_Nat -> Nec_Int
.

Definition Pos_Int := option Nec_Int.

Definition Iso (A : Type) (B : Type) : Prop :=
    forall x : A         ,
    forall y : B         ,
    exists f : A   -> B  ,
    exists g : B   -> A  ,
    (f (g y) = y) /\ (g (f x) = x).

Module Type Countable.
  Parameter A : Type.
  Parameter Next : A -> A.
  Axiom iso_nat : Iso A nat.    
End Countable.

Module Nec_Nat_Count <: Countable.
  Definition A    := Nec_Nat.
  Definition Next := More.
  Lemma iso_nat : Iso Nec_Nat nat.
  Proof.
    intros a.
    intros n.
    refine (ex_intro _ Nec_Nat_f _).
    refine (ex_intro _ Nec_Nat_g _).
    split.
    elim n.
    elim a.
    simpl ; auto.
    intros.
    rewrite H ; auto.
    intros.
    simpl ; auto.
    elim a.
    simpl ; auto.
    intros.
    simpl.
    rewrite H ; auto.
  Qed.

Module Pos_Nat_Count <: Countable.
Definition A := Pos_Nat.
Definition Next := (fun x => match x with
    | None   => Some Unit
    | Some x => Some (More x)
    end ).
Lemma iso_nat : Iso Pos_Nat nat.
 Proof.

    intros n a.
    refine (ex_intro _ Pos_Nat_f _).
    refine (ex_intro _ Pos_Nat_g _).
    split.

    cut (Iso Nec_Nat nat).
    intros H.
    eelim H using 

    (forall x : Nec_Nat         ,
    forall y : nat        ,
    exists f : Nec_Nat   -> nat  ,
    exists g : nat   -> Nec_Nat  ,
    (f (g y) = y) /\ (g (f x) = x))
.
```

The error is detected by the IDE from "eelim H using" till the end. 

I am new to Coq, so there are probably things I am doing wrong.

After this posting I am going to change the code but I thought it would be nice to leave this here since the IDE told me too. 

cheers!

**Comment by ppedrot** [comment] 2019-08-22 21:30
Duplicate of #5679

**Closed by ppedrot** 2019-08-22 21:30 UTC

**Comment by JasonGross** [comment] 2019-08-23 07:11
> I am new to Coq, so there are probably things I am doing wrong.
> 
> After this posting I am going to change the code but I thought it would be nice to leave this here since the IDE told me too.

Thanks for the report (even though it is a duplicate), and welcome to Coq!
