### ISSUE TITLE
Implicit and explicit declarations of hint databases have opposite effect on transparent state

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#8980] opened 2018-11-12 17:55 UTC
As documented in https://github.com/coq/coq/commit/a49d5036279440e6c35e54eda05f425696aba8ca, `Create HintDb` has the opposite default for transparent state, compared to implicit declaration of databases.

I don't understand the logic behind the design, but currently it is a blocker for #4117, since implicit and explicit declarations have different semantics.

What should I do?

**Comment by maximedenes** [comment] 2018-11-12 17:56
cc @mattam82

**Comment by Zimmi48** [comment] 2018-11-20 16:32
Duplicate of #5381

**Closed by Zimmi48** 2018-11-20 16:32 UTC
