### ISSUE TITLE
Anomaly when trying to eliminate `False` or `Empty_set` into `Type@{Set+1}`.

### ISSUE THREAD

**Issue by Alizter** [coq/coq#16019] opened 2022-05-13 11:18 UTC
```coq
Axiom absurd_prop : False.
Axiom absurd : Empty_set.

Goal Type@{Set+1}.
Fail destruct absurd_prop.
Fail destruct absurd.
Abort.

Goal Set.
Succeed destruct absurd_prop.
Succeed destruct absurd.
Abort.
```

```
Conversion test raised an anomaly:
Anomaly
"Unable to handle arbitrary u+k <= v constraints."
Please report at http://coq.inria.fr/bugs/.
```

<details>
<summary>Backtrace</summary>

```
Raised at Exninfo.iraise in file "clib/exninfo.ml", line 79, characters 4-11
Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
Called from UnivSubst.enforce_leq in file "engine/univSubst.ml" (inlined), line 81, characters 7-56
Called from UState.enforce_leq_up in file "engine/uState.ml", line 231, characters 27-84
Called from Stdlib__Set.Make.fold in file "set.ml", line 383, characters 34-55
Called from UState.process_universe_constraints in file "engine/uState.ml", line 392, characters 14-62
Called from UState.add_universe_constraints in file "engine/uState.ml", line 418, characters 28-67
Called from Evd.add_universe_constraints in file "engine/evd.ml", line 787, characters 23-68
Called from Reductionops.infer_conv_gen in file "pretyping/reductionops.ml", line 1143, characters 17-58
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Unification.unify_0_with_initial_metas in file "pretyping/unification.ml", line 1172, characters 28-84
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Unification.w_unify_core_0 in file "pretyping/unification.ml", line 1550, characters 22-111
Called from Clenv.clenv_unify in file "proofs/clenv.ml", line 310, characters 25-73
Called from Clenv.res_pf.(fun) in file "proofs/clenv.ml", line 646, characters 16-56
Called from Proofview.Goal.enter.f in file "engine/proofview.ml", line 1120, characters 40-46
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Proof.run_tactic in file "proofs/proof.ml", line 381, characters 4-49
Called from Proof.solve in file "proofs/proof.ml", line 490, characters 31-52
Called from ComTactic.solve_core.(fun) in file "vernac/comTactic.ml", line 46, characters 23-59
Called from Declare.Proof.map_fold_endline in file "vernac/declare.ml", line 1447, characters 20-33
Called from ComTactic.solve_core in file "vernac/comTactic.ml", line 43, characters 23-442
Called from Vernacextend.vtmodifyproof.(fun) in file "vernac/vernacextend.ml", line 163, characters 32-47
Called from Vernacinterp.interp_typed_vernac in file "vernac/vernacinterp.ml", line 20, characters 20-113
Called from Vernacinterp.interp_control.(fun) in file "vernac/vernacinterp.ml", line 205, characters 24-69
Called from Flags.with_modified_ref in file "lib/flags.ml", line 17, characters 14-17
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Vernacinterp.interp_gen.(fun) in file "vernac/vernacinterp.ml", line 255, characters 18-43
Called from Vernacinterp.interp_gen in file "vernac/vernacinterp.ml", line 253, characters 6-279
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Stm.Reach.known_state.reach.(fun) in file "stm/stm.ml", line 2168, characters 20-47
Called from Stm.Reach.known_state.resilient_tactic in file "stm/stm.ml", line 2110, characters 10-14
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Stm.State.define in file "stm/stm.ml", line 964, characters 6-10
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Stm.Reach.known_state.reach in file "stm/stm.ml", line 2319, characters 4-105
Called from Stm.observe in file "stm/stm.ml", line 2420, characters 4-60
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Stm.finish in file "stm/stm.ml", line 2431, characters 12-50
Called from Dune__exe__Idetop.subgoals in file "ide/coqide/idetop.ml", line 229, characters 13-28
Called from Dune__exe__Idetop.eval_call.interruptible in file "ide/coqide/idetop.ml", line 496, characters 12-15
Called from Xmlprotocol.abstract_eval_call in file "ide/coqide/protocol/xmlprotocol.ml", line 814, characters 29-49
```

</details>

**Comment by silene** [comment] 2024-04-18 12:50
I cannot reproduce the issue in 8.19.1, so closing as fixed.

**Closed by silene** 2024-04-18 12:50 UTC
Labels: kind: anomaly, part: universes, kind: bug
