### ISSUE TITLE
CoqIDE crashes at particular position

### ISSUE THREAD

**Issue by bcip** [coq/coq#10321] opened 2019-06-06 13:01 UTC
#### Description of the problem

1. Clone and compile VST;
```
git clone https://github.com/PrincetonUniversity/VST.git
cd VST
make progs/verif_append.vo -j4 # or -j8 depending on number of cores you have
```
2. Open `progs/verif_append.v` in CoqIDE, move cursor to the end of line 51, then press "Go to Cursor" or press shortcut keys;
3. Now CoqIDE crashes.

It doesn't crash if go to the end directly.

#### Coq Version
The Coq Proof Assistant, version 8.9.1 (May 2019)
compiled on May 18 2019 6:57:53 with OCaml 4.07.0

OS: Windows 10 64-bit

My friend tested this, and he didn't have this issue. He's using Coq 8.9.0 32-bit.

**Comment by Alizter** [comment] 2021-07-09 01:01
I am unable to compile the files you mention on a newer version of VST. Are you able to provide the version of VST this happened in?

**Comment by QinshiWang** [comment] 2021-07-09 16:24
Thank you for revisiting this issue after a long time. But I am not sure if this issue can be still reproduced now. I think I referred to this version: https://github.com/PrincetonUniversity/VST/tree/2f7d966b5375f2a32d01858795aa15b1e075959c. As I remember, CoqIDE was ported to a new framework sometime after I posted this issue.

**Comment by Alizter** [comment] 2021-07-10 13:45
I've tried this on coq 8.9.1 with ocaml 4.09.1 and carried out the instructions you described. I am unable to get coqide to crash. I suspected it might be something to do with memory limits, so I also tried it in a restricted memory setting but coqide correct raised an exception. Since you mentioned that your friend tested this with 8.9.0 and had no issue, I therefore suspect that the crash was unrelated to coqide.

It could also be from a bug in gtksourceview2 which as you said, we don't use any more. This probably isn't worth tracking down. I'm therefore closing this issue.

**Closed by Alizter** 2021-07-10 13:45 UTC
Labels: kind: bug, needs: more info, needs: triage, part: IDE
