### ISSUE TITLE
DestKO on Scheme Equality

### ISSUE THREAD

**Issue by gares** [coq/coq#8492] opened 2018-09-18 11:44 UTC
```coq
Require Import List.
Inductive tree (A : Type) := Node (siblings : list (tree A)).
Scheme Equality for tree.
```

backtrace:
```
Unexpected error during scheme creation: Anomaly "Uncaught exception Constr.DestKO."
Please report at http://coq.inria.fr/bugs/.
frame @ file "ide/xmlprotocol.ml", line 667, characters 29-46
frame @ file "ide/ide_slave.ml", line 406, characters 12-15
frame @ file "ide/ide_slave.ml", line 208, characters 13-28
frame @ file "stm/stm.ml", line 2646, characters 11-49
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 2635, characters 4-55
frame @ file "stm/stm.ml", line 2525, characters 4-100
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 934, characters 6-10
frame @ file "stm/stm.ml", line 2398, characters 16-43
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 1087, characters 12-91
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/vernacentries.ml", line 2343, characters 4-36
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/vernacentries.ml", line 2310, characters 8-666
frame @ file "lib/flags.ml", line 100, characters 20-44
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/indschemes.ml", line 142, characters 6-25
frame @ file "vernac/indschemes.ml", line 267, characters 11-70
frame @ file "tactics/ind_tables.ml", line 167, characters 23-34
frame @ file "vernac/auto_ind_decl.ml", line 980, characters 22-193
frame @ file "proofs/pfedit.ml", line 157, characters 4-64
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "proofs/pfedit.ml", line 142, characters 17-23
frame @ file "proofs/proof_global.ml", line 168, characters 24-36
raise @ unknown
frame @ file "proofs/pfedit.ml", line 114, characters 28-67
frame @ file "proofs/proof.ml", line 360, characters 4-30
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "engine/proofview.ml", line 1139, characters 10-34
frame @ file "engine/proofview.ml", line 1134, characters 40-46
raise @ unknown
frame @ file "vernac/auto_ind_decl.ml", line 906, characters 23-53
frame @ file "tactics/ind_tables.ml", line 202, characters 20-67
frame @ file "tactics/ind_tables.ml", line 167, characters 23-34
frame @ file "vernac/auto_ind_decl.ml", line 685, characters 22-184
frame @ file "proofs/pfedit.ml", line 157, characters 4-64
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "proofs/pfedit.ml", line 142, characters 17-23
frame @ file "proofs/proof_global.ml", line 168, characters 24-36
raise @ unknown
frame @ file "proofs/pfedit.ml", line 114, characters 28-67
frame @ file "proofs/proof.ml", line 360, characters 4-30
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "engine/proofview.ml", line 1139, characters 10-34
frame @ file "engine/proofview.ml", line 1134, characters 40-46
frame @ file "vernac/auto_ind_decl.ml", line 484, characters 26-68
frame @ file "array.ml", line 101, characters 21-40
frame @ file "vernac/auto_ind_decl.ml", line 442, characters 45-64
raise @ file "engine/eConstr.ml", line 255, characters 7-19
list_beq is defined
tree_beq is defined
```

**Comment by JasonGross** [comment] 2018-09-19 17:50
Duplicate of #4612

**Closed by JasonGross** 2018-09-19 17:50 UTC
