### ISSUE TITLE
CoqIde - Browse Coq Manual

### ISSUE THREAD

**Issue by dharmatech** [coq/coq#10619] opened 2019-08-05 04:19 UTC
Version of CoqIde on windows:

![image](https://user-images.githubusercontent.com/20816/62438667-13230c80-b70e-11e9-87bc-fcad85212bde.png)

The 'Help -> Browse Coq Manual' link goes to 

    https://coq.inria.fr/distrib/V8.9.1/refman/

which currently results in a 404 message.

**Comment by JasonGross** [comment] 2019-08-05 04:52
Is the releasing doc missing a step about uploading the manual when doing point releases?  https://coq.inria.fr/distrib/V8.9.0/refman/ exists but https://coq.inria.fr/distrib/V8.9.1/refman/ does not

**Comment by Zimmi48** [comment] 2019-08-05 21:59
Note that I can also reproduce the issue with Coq 8.10+beta1 which opens the link https://coq.inria.fr/distrib/V8.10+beta1/refman/ which does not exist either.

I don't think the release doc is missing a step but the uploading was simply not done. However, nowadays, we also deploy the manual automatically to another URL so this would be good to take advantage of it.

This bug is related to coq/www#118. @maximedenes Can we put a redirection from https://coq.inria.fr/distrib/xxxxx/refman/ to https://coq.github.io/doc/xxxxx/refman as soon as the former URL does not already exist? As I said before, I would prefer if this was an "invisible" redirection but if it is simpler to put a visible redirection, that's already OK.

**Comment by Zimmi48** [comment] 2019-09-10 15:52
@maximedenes This is still an issue because while the "current" version of the manual is now the 8.9.1 version, the link https://coq.inria.fr/distrib/V8.9.1/refman/ still does not exist (nor https://coq.inria.fr/distrib/V8.10+beta1/refman/ or https://coq.inria.fr/distrib/V8.10+beta2/refman/). Could you setup the appropriate proxy for those (ideally as a generic mechanism that would avoid you to do this every time a new version is published?).

**Comment by Zimmi48** [comment] 2019-09-23 09:37
Ping @maximedenes: you may have missed this. Would it be easy to add these URLs to the "reverse proxy"?

**Comment by Zimmi48** [comment] 2019-10-28 15:17
This is now fixed. Cf. coq/www#111 for the follow-up.

**Closed by Zimmi48** 2019-10-28 15:17 UTC
Labels: kind: documentation, part: website
