### ISSUE TITLE
Anomaly: uncaught exception Not_found when closing Module Type when a proof is in progress

### ISSUE THREAD

**Issue by sliedes** [coq/coq#15010] opened 2021-10-08 23:35 UTC
#### Description of the problem

This code causes an uncaught exception Not_found at the "End M." line:

```
Module Type M.
    Parameter p : nat -> Prop.
    Lemma m : forall (n: nat), p n.
End M.
```

It feels there's generally something fishy with how ending a module type definition interacts with an ongoing proof. For example, Coq seems to be perfectly happy about this code:

```
Module Type M.
    Parameter p : nat -> Prop.
    Lemma m : forall (n: nat), bool. intro.
End M.
    exact true.
Qed.
```

#### Coq Version

The Coq Proof Assistant, version 8.13.2 (July 2021)
compiled on Jul 27 2021 14:53:47 with OCaml 4.12.0

**Comment by SkySkimmer** [comment] 2021-10-09 07:26
Fixed in 6e41dd8c6ba0279b9c882c02053c4d34eb251971 (https://github.com/coq/coq/pull/13790, 8.14)
Duplicate of #13755

**Closed** 2021-10-09 07:26 UTC
