### ISSUE TITLE
[Ltac2] "rec ... with" is not documented

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10347] opened 2019-06-09 08:31 UTC
The syntax for mutual recursive functions using "rec ... with" is not documented. I thought that I need an Ltac2 keyword for each function and then it was no so obvious how the syntax should look or if this works at all. It is obvious once one knows the syntax.

**Comment by Blaisorblade** [comment] 2020-06-26 07:15
Duplicate of #11757 (right?).

**Closed by Blaisorblade** 2020-06-26 07:15 UTC
Labels: kind: documentation, part: ltac2, resolved: duplicate(d)
