### ISSUE TITLE
Exponential slowdown when type checking a degenerate expression

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#10820] opened 2019-10-03 17:33 UTC
#### Description of the problem

The following snippet typechecks around 3 sec. on my machine and the typechecking (type inference) time increases exponentially as I add more `let id := fun A => id A in` lines.

```coq
Time Check
let id := fun A => fun (x : A) => x in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
let id := fun A => id A in
id.
```

And if I add type annotation it typechecks almost instantaneously (it has the same number of `let`-bindings):

```coq
Time Check
let id : forall A, A -> A := fun A => fun (x : A) => x in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
let id : forall A, A -> A := fun A => id A in
id : forall A, A -> A.
```

#### Coq Version

Coq 8.9.1 and Coq 8.10alpha (3612ac1f639e361504cf3b2ded5609f5b643dfaa)

**Comment by ppedrot** [comment] 2019-10-03 17:38
Duplicate of #10206.

**Closed by ppedrot** 2019-10-03 17:38 UTC
Labels: kind: performance

**Comment by JasonGross** [comment] 2020-06-16 19:43
Duplicate of #10206

**Comment by JasonGross** [comment] 2020-06-16 19:43
(The duplication message needs to not have a period)
