### ISSUE TITLE
Ltac2, CoqIDE and parentheses

### ISSUE THREAD

**Issue by vbgl** [coq/coq#10845] opened 2019-10-07 12:48 UTC
In current coq master, the following file is accepted by `coqc` but in CoqIDE, you can’t navigate beyond “Proof.”

~~~
From Ltac2
Require Import Ltac2.

Goal True.
Proof.
Control.refine (fun _ => constr:((I) ) ).
Qed.
~~~

Apparently, the double parentheses must be well-bracketed: “((…))” is accepted but “(␣(…))” is not.

cc @eponier

**Comment by ppedrot** [comment] 2019-10-07 12:52
Yet another manifestation of the Elpi quotation system, I guess. Summoning @gares.

**Comment by gares** [comment] 2019-10-07 14:22
Didn't we revert the PR touching CoqIDE? Are we talking about master or v8.10?

**Comment by gares** [comment] 2019-10-07 14:23
Here it is: https://github.com/coq/coq/pull/10485

**Comment by gares** [comment] 2019-10-07 14:24
Oh, sorry, I now see you mention master. Well, the same PR should be merged in master...

**Comment by ppedrot** [comment] 2019-10-07 14:43
@gares in retrospective it's probably not a good idea to allow quotations with parentheses, it's going to conflict with a lot of stuff...

**Comment by gares** [comment] 2019-10-07 15:13
Unless the quotation[1] is a single ident, then you are delimiting text, and parentheses are for that precise purpose. Similar stuff is `{xx|...|xx}` in OCaml, `[==[...]==]` in Lua but other languages prefer delimiters reminiscent of strings such as `""" ... """` in python or `r##"...."##` in Rust. Most of them let one disambiguate by making the delimiter extensible, eg adding more `x` or `=` or `#`. My choice is not so different, AFAICT.

Given we have an extensible syntax, conflicts can never be ruled out, and the choice was to start a quotation by a registered keyword immediately followed by the opening delimiter. The bug here is that `constr:` does not start a quotation (as understood by the parser, i.e. it is not a keyword and not flagged as a quotation starter) but the UI is not using the parser of Coq, but a surrogate that does not know about keywords. My patch was very optimistic (read stupid) so should be reverted without mercy.

With LSP based UIs the problem will vanish since parsing is only done at the prover side.

[1] `constr:` is never going to be a quotation in the sense of Elpi, since the text is to be parsed by the same parser of Coq. I call a quotation a barrier between two languages, with distinct parsers. Indeed I don't want a Coq `Notation "foo :- bar"` to break the parsing of Elpi programs, nor vice versa (lambdaProlog too has "extensible" syntax, brr). Just to be clear.

**Comment by ppedrot** [comment] 2020-01-17 11:25
Duplicate of #10481

**Closed by ppedrot** 2020-01-17 11:25 UTC
Labels: kind: bug, part: IDE, part: ltac2
