### ISSUE TITLE
Anomaly "Evar ?X67 was not declared" thrown on `case H: eqb ... true`

### ISSUE THREAD

**Issue by ComFreek** [coq/coq#10175] opened 2019-05-16 12:24 UTC
#### Description of the Problem

Case distinction on a bool by `case H: eqb … true` throws an anomaly, where `...` is an Expression of type `bool`. Just doing `case H: ...` works fine.

```coq
From Coq Require Import ssreflect ssrbool ssrfun.
From Coq Require Import List.

Import Nat.

Definition partition {X : Type}
                     (test : X -> bool)
                     (l : list X)
                   : list X * list X
  := (filter test l, filter (fun x => negb (test x)) l).

Definition fold (A B: Type) f l b:= @fold_right B A f b l.

Theorem partition_fst: forall (X : Type)  (test : X -> bool) (l : list X),
                         fold_right andb true (map test (fst (partition test l))) = true.
Proof.
  move => ? test.
  elim => [|x xs IHxs] //.
  case H: eqb (test x) true.  (* <-- anomaly here! *)
```

(Code adapted from [Software Foundations](https://softwarefoundations.cis.upenn.edu/))

Error message:

> Anomaly "Evar ?X67 was not declared."
> Please report at http://coq.inria.fr/bugs/.

#### Coq Version

Coq 8.9.0 on Windows 10 Pro 64-bit.

Details:

> The Coq Proof Assistant, version 8.9.0 (January 2019)
compiled on Jan 17 2019 16:07:40 with OCaml 4.07.0

**Comment by LasseBlaauwbroek** [comment] 2023-01-30 07:08
This appears to have been fixed in v8.11. Recommend closing. CC @gares as someone who could confirm.

**Comment by SkySkimmer** [comment] 2023-02-23 14:08
@LasseBlaauwbroek I can reproduce on 8.16 but not master, did you mean it seems to have been fixed in 8.17?

**Comment by LasseBlaauwbroek** [comment] 2023-02-23 16:25
Oh, oops that might be true. What happened is that I probably fixed this issue some time ago and then backported that fix all the way back to 8.11 for my own purposes. So that's why I cannot reproduce it on 8.11.

In any case, it appears to be fixed.

**Comment by LasseBlaauwbroek** [comment] 2023-02-23 16:32
What is the policy on this btw? When I find an issue that is solved, am I encouraged to close it myself, or should I just flag it up (or do nothing)?

**Comment by ppedrot** [comment] 2023-02-23 16:38
@LasseBlaauwbroek You should open a PR adding the test with an explicit mention that it fixes the issue.

**Closed** 2023-02-26 07:34 UTC
Labels: part: ssreflect, kind: anomaly
