### ISSUE TITLE
Windows build fails frequently due to not being able to resolve cygwin.com

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#11927] opened 2020-03-26 18:14 UTC
Is it possible to cache cygwin on Azure? The success rate of the Windows job is abysmal (65%, currently, cf https://dev.azure.com/coq/coq/_pipeline/analytics/stageawareoutcome?definitionId=1 ), and it tends to fail with `The remote name could not be resolved: 'www.cygwin.com'` (cf https://dev.azure.com/coq/coq/_build/results?buildId=8436&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3 )  This is not the first time I've seen this particular error, and it is in fact the most frequent error I've seen on the Windows build.

**Comment by ejgallego** [comment] 2020-03-26 19:47
Indeed that's a PITA; I wonder tho if we should not just try to setup a Docker env for Windows?

**Comment by JasonGross** [comment] 2020-04-09 19:44
Interestingly, GitHub Actions has the same issue, which I'm looking at with them here: https://github.com/actions/virtual-environments/issues/698

**Comment by JasonGross** [comment] 2020-04-15 16:54
There's a suggestion for a workaround at https://github.com/actions/virtual-environments/issues/698#issuecomment-614082622 : 
> @JasonGross we took packet captures from inside the VM and found differences in the DNS response for succeeding and failed requests. These differences are not observable when using other DNS providers.
>
> I have escalated to the Azure DNS team.

> As a workaround, consider forcing a different DNS server:
>
>     Get-NetAdapter | Set-DnsClientServerAddress -ServerAddresses 8.8.8.8
>     cmd /c "ipconfig /flushdns 2>&1"

**Comment by ejgallego** [comment] 2020-04-15 20:42
@JasonGross azure and GH actions are the same animal but with different skins.

**Comment by ejgallego** [comment] 2020-05-14 17:46
@JasonGross I think we should close this as not a bug in Coq and indeed defer to https://github.com/actions/virtual-environments/issues/698

**Comment by JasonGross** [comment] 2020-05-14 18:00
I think we should at least work around it for now, perhaps with

> @JasonGross yeah, got it. Powershell treats  `Non-authoritative answer:` as an error, so let's use direct cmd calling instead
> ```
>     steps:
>       - uses: actions/checkout@v2
>       - name: Download cygwin
>         run: |
>           & cmd /c 'nslookup www.cygwin.com 2>&1'
>           while ($true)
>           {
>               try
>               {
>                   (New-Object Net.WebClient).DownloadFile('http://www.cygwin.com/setup-x86_64.exe', 'setup-x86_64.exe')
>                   break
>               }
>               catch
>               {
>                   Write-Host "There is an error during package downloading:`n $_"
>               }
>           }
>           & cmd /c 'nslookup www.cygwin.com 8.8.8.8 2>&1'
>         shell: powershell
> ```
> 

_Originally posted by @miketimofeev in https://github.com/actions/virtual-environments/issues/698#issuecomment-613549747_

**Comment by ejgallego** [comment] 2020-05-14 18:05
Ugh, I'd rather host it in some of our mirrors.

**Comment by ejgallego** [comment] 2020-09-16 16:14
Seems fixed.

**Closed by ejgallego** 2020-09-16 16:14 UTC
Labels: kind: ci-failure, kind: infrastructure, resolved: moved
