### ISSUE TITLE
Proof of False with template polymorphism and (nonuniform parameters OR explicit universe annotation)

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#11039] opened 2019-11-04 14:22 UTC
Found while investigating https://github.com/coq/coq/issues/10504

The critical part is that we can define 
~~~coq
#[universes(template)]
Inductive foo@{i} (A:Type@{i}) : Type@{i+1} := bar (X:Type@{i}) : foo A.
~~~
Then `foo nat : Type@{Set+1}` and can be inhabited by applications of `bar` to arbitrarily large things.

A similar manipulation uses non uniformly recursive parameters to produce a similar template inductive, allowing the bug to be used in older versions (probably since the introduction of template poly, tested with 8.9.0):
~~~coq
Inductive foo (A:Type) := bar X : foo X -> foo A | nonempty.
~~~
This has the same `foo : Type@{i} -> Type@{i+1}` with the `X` argument to `bar` being in `Type@{i}`, we have to add a constructor to deal with the recursion but this is no big deal.

EDIT: we can also use `Inductive foo (A:Type) := bar (X:ltac:(let t := type of A in exact t)) : foo A.` which works in 8.5.

This passes both coqc and coqchk.

Full reproduction
~~~coq
Require Hurkens.

Module TypeNequivSmallType.
Import Hurkens.

Section Paradox.

(* I feel like this version of the paradox should already by in
   Hurkens.v but can't find it, there's only the version with A=U *)

Definition U := Type.
Variable A:U.

Variable down : U -> A.
Variable up : A -> U.
Hypothesis up_down : forall (X:U), up (down X) = X.

Theorem paradox : False.
Proof.
  Generic.paradox p.
  (** Large universe *)
  + exact U.
  + exact (fun X=>X).
  + cbn. exact (fun X F => forall x:X, F x).
  + cbn. exact (fun _ _ x => x).
  + cbn. exact (fun _ _ x => x).
  + exact (fun F => forall x:A, F (up x)).
  + cbn. exact (fun _ f => fun x:A => f (up x)).
  + cbn. intros * f X.
    specialize (f (down X)).
    rewrite up_down in f.
    exact f.
  (** Small universe *)
  + exact A.
  (** The interpretation of [A] as a universe is [U]. *)
  + cbn. exact up.
  + cbn. exact (fun _ F => down (forall x, up (F x))).
  + cbn. exact (fun _ F => down (forall x, up (F x))).
  + cbn. exact (down False).
  + rewrite up_down in p.
    exact p.
  + cbn. easy.
  + cbn. intros ? f X.
    destruct (up_down X). cbn.
    reflexivity.
  + cbn. intros ? ? f.
    rewrite up_down.
    exact f.
  + cbn. intros ? ? f.
    rewrite up_down in f.
    exact f.
  + cbn. intros ? ? f.
    rewrite up_down.
    exact f.
  + cbn. intros ? ? f.
    rewrite up_down in f.
    exact f.
Qed.

End Paradox.

End TypeNequivSmallType.

(* Using non uniform parameters to trick template poly. Alternatively
but requiring explicit annotations and #[universes(template)] we can do

#[universes(template)]
Inductive foo@{i} (A:Type@{i}) : Type@{i+1} := bar (X:Type@{i}) : foo A.
*)
Inductive foo (A:Type) := bar X : foo X -> foo A | nonempty.
Arguments nonempty {_}.

Notation U := TypeNequivSmallType.U.

Definition A : U := foo nat.

Definition down : U -> A := fun u => bar nat u nonempty.

Definition up : A -> U := fun a => match a with bar _ u _ => u | nonempty => nat end.

Lemma up_down : forall (X:U), up (down X) = X.
Proof.
  reflexivity.
Qed.

Theorem bad : False.
Proof.
  exact (TypeNequivSmallType.paradox A down up up_down).
Qed.
Print Assumptions bad. (* nothing *)
~~~

**Comment by Zimmi48** [comment] 2019-11-04 14:32
This proof of False is already present in 8.6 but the definition of `down` gives a universe inconsistency in 8.5. Does this mean that it is an 8.6 regression, or is 8.5 only accidentally saved from this bug?

**Comment by SkySkimmer** [comment] 2019-11-04 14:33
BTW why don't we have this version of the paradox in the stdlib?
~~~ coq
Definition U := Type.
Variable A:U.

Variable down : U -> A.
Variable up : A -> U.
Hypothesis up_down : forall (X:U), up (down X) = X.

Theorem paradox : False.
~~~

**Comment by SkySkimmer** [comment] 2019-11-04 14:42
>This proof of False is already present in 8.6 but the definition of down gives a universe inconsistency in 8.5. Does this mean that it is an 8.6 regression, or is 8.5 only accidentally saved from this bug?

Interesting, on the other issue @silene said (https://github.com/coq/coq/issues/10504#issuecomment-509556758)
>The issue was introduced at some point between 8.5 and 8.6.

**Comment by SkySkimmer** [comment] 2019-11-04 14:55
It looks like in 8.5 we get 
~~~coq
Inductive foo (A : Type@{Top.9}) : Type@{max(Set, Top.12+1)} :=
    bar : forall X : Type@{Top.12}, foo X -> foo A | nonempty : foo A
(* Top.9 Top.12 |= Top.12 <= Top.9
                    *)
~~~
ie the type for X doesn't get unified with the one for A.
We can still get the proof of False though using `Inductive foo (A:Type) := bar (X:ltac:(let t := type of A in exact t)) : foo X -> foo A | nonempty.`

**Comment by SkySkimmer** [comment] 2019-11-04 15:12
(nb `ltac:` was introduced in 8.5, I don't know how to get universes unified in such a way as to create the issue before that)

**Comment by JasonGross** [comment] 2019-11-04 19:14
Interestingly, the replacement for `ltac:` that I propose at https://github.com/coq/coq/issues/9294#issuecomment-524974594 doesn't actually work for this bug in 8.4; it creates a new universe and a constraint that it be equal to the existing universe.

**Comment by SkySkimmer** [comment] 2019-11-04 19:46
I got `Inductive foo A : Type := bar (X:match _ with T => match (A : T) -> A with _ => T end end) : foo A.` to produce something that looks right when `Print`ed but it's not template poly. It seems there's an upper constraint generated with a disappeared universe (ie you get `foo : Type@{Top.9} -> Type@{Top.9 + 1}` with a constraint `Top.9 < Top.2` and `Top.2` appears nowhere in the final result).

**Comment by JasonGross** [comment] 2019-11-04 20:00
Tangentially, it seems very strange that I can get an inductive in 8.10 whose constraints include `Prop = Prop` and `Set = Set` and a handful of other reflexive constraints:
```coq
Set Printing Universes.
Definition U := Type.
Inductive foo A := bar (X:match _ as T return match _ : U return U with TT => let v : Prop := (T : TT) -> True in TT end with T => match (A : T) -> True with _ => T en\
d end) : foo A.
Set Printing All.
Print foo.
Inductive foo (A : Type@{foo.u0}) : Type@{foo.u0+1} :=
    bar : forall _ : Type@{foo.u0}, foo A
(* {foo.u0} |= Prop < U.u0
               foo.u0 < U.u0
               Prop = Prop
               Set = Set
               U.u0 = U.u0
               foo.u0 = foo.u0 *)
```

**Comment by ejgallego** [comment] 2019-11-05 00:16
> Tangentially, it seems very strange that I can get an inductive in 8.10 whose constraints include `Prop = Prop` and `Set = Set` and a handful of other reflexive constraints:

At least that seems fixed in `master`

**Comment by ppedrot** [comment] 2019-11-05 07:40
Seriously, when do we get rid of template poly?

**Comment by gares** [comment] 2019-11-05 09:43
I tried to put this on the table a few times, and the only argument against this was "but X, Y, Z uses (_,_) for both data and proofs". Maybe we should be bold and give it a try?

**Comment by Zimmi48** [comment] 2019-11-05 10:05
> Seriously, when do we get rid of template poly?

I thought everyone agreed that this was the plan...

**Comment by gares** [comment] 2019-11-05 10:18
The plan I've perceived was that univpoly would be able to subsume it (up to minor improvements) in its sound instances. This is orthogonal to remove template now, fix the developments using it (what I was suggesting). Then one can reintroduce it later as just an instance of univpoly when ready.

**Comment by Zimmi48** [comment] 2019-11-06 10:41
Thanks for making your alternative plan explicit. This is not orthogonal since the idea being subsuming template poly with full poly was precisely to make the transition easier, I think. The cost of removing it now, without any alternative should be evaluated, but could be prohibitive.

**Comment by herbelin** [comment] 2019-11-06 10:47
Congratulations for finding this problem (and mea culpa). I don't know if @mattam82 will agree with my analysis: I would see this as another instance of lost downwards constraints on the type of parameters but this time insiduously hidden behind an equality constraint. It is insiduous in the sense that the equality constraint is not kept explicitly but substituted. Let's indeed talk about it this [afternoon](https://github.com/coq/coq/wiki/Coq-Call-2019-11-06).

**Comment by gares** [comment] 2019-11-06 16:57
At the Coq call the discussion pointed out this plan
1. short term: patch by @SkySkimmer to avoid the bug and release 8.11 without the known soundness bug
2. medium term: evaluate the breakage and repair cost of CI is template was removed
3. long term: improve cumulative universe polymorphism in order to regain the functionality

**Comment by herbelin** [comment] 2019-11-06 17:02
Thanks for the summary. I arrived late in the discussion and did not follow everything, sorry. Does "improve" means "supporting polymorphic quantification over a domain which may include Prop"?

**Comment by gares** [comment] 2019-11-06 18:15
Yes

**Closed** 2019-11-27 10:40 UTC
Labels: part: universes, priority: critical
