### ISSUE TITLE
Custom entry breakage in 8.11 (notations leak out of custom entries)

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#11627] opened 2020-02-19 03:20 UTC
#### Description of the problem

The following snippet breaks in 8.11:

```coq
Declare Custom Entry test.
Notation "'test' '{|' n '|}'" := (S n) (in custom test, n constr at level 0).

Record r := { f: nat }.
Check {| f := 1 |}.
```

The message is `Error: Syntax error: ['|}'] expected after [constr:record_declaration] (in [constr:operconstr]).`, and it highlights the `|}`.

It worked fine in 8.10.

**Comment by maximedenes** [comment] 2020-03-02 12:51
Notations don't leak out but they share the same lexer. This is a duplicate of #4867.

[CEP 42](https://github.com/coq/ceps/pull/42) suggests a solution.

**Closed by maximedenes** 2020-03-02 12:51 UTC
Labels: part: notations, resolved: duplicate(d)

**Comment by maximedenes** [comment] 2020-03-02 12:52
Sorry, I meant CEP 41 (edited).

**Comment by cpitclaudel** [comment] 2020-03-02 13:40
Hmm, but `|}` is not a new token in 8.11, so why did it work in 8.10?

**Comment by maximedenes** [comment] 2020-03-02 13:44
That's the other way around. It used to be parsed as a `|}` token, but is now parsed as `|` `}`. It has become more polite (will less often break user notations) but also more fragile (can be broken by your notation). See https://github.com/coq/coq/pull/10167.

If your notation had been `[| n |]`, it would also break (via lexing) the parsing of Ltac (e.g. `destruct x; [| idtac ]`).

**Comment by cpitclaudel** [comment] 2020-03-02 13:54
I see.  Is there a workaround, or should we stick with 8.10 for now?

**Comment by maximedenes** [comment] 2020-03-02 13:58
The standard workaround in user notations is to split the tokens (i.e. `|` `}`), but it means it will allow spaces, which you may not want.

From a plugin, you can parse the tokens separately and use lookahead combinators to check that they are contiguous (cf #11695).
