### ISSUE TITLE
Make OCaml's `-warn-error` the default in `coq_makefile`

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6974] opened 2018-03-12 09:21 UTC
As of today ML plugins are accumulating lots of ML-side warnings [mainly about deprecation] and authors have little incentive to clean them up.

IMHO plugins should be held to the same standard the main codebase is so I suggest we make `coq_makefile` call `ocamlc` with `-warn-error` by default.

**edit:** deprecation warnings are indeed special, so I've moved discussion to a new issue https://github.com/coq/coq/issues/9606

**Comment by Zimmi48** [comment] 2018-03-25 16:36
It seems a bit drastic as deprecation warnings are precisely there to give heads-up. We could start by requiring plugins that we track in our CI to compile without warnings (that would already be a pretty big step I guess).

**Comment by SkySkimmer** [comment] 2018-03-25 16:40
It is regularly impossible to compile without warnings while being 
backward compatible (ie when we move some type) so it's a big step indeed.

Gaëtan Gilbert

**Comment by ejgallego** [comment] 2018-03-25 17:04
Not so drastic I think, plugins following `master` have to be adapted anyways, and plugins not following master can disable the warning while they port.

**Comment by Zimmi48** [comment] 2018-03-25 20:58
Right now it's virtually impossible for a plugin to target several versions of Coq without maintaining several branches anyways.

**Comment by ejgallego** [comment] 2018-03-25 21:03
> Right now it's virtually impossible for a plugin to target several versions of Coq without maintaining several branches anyways.

Yeah, this is a bit my point for making this request. Of course it should be well documented how to disable it.

**Comment by maximedenes** [comment] 2018-04-11 17:41
This change needs discussion, so postponing it.

**Comment by ejgallego** [comment] 2018-04-26 17:30
Ok I am trying a branch here, let's see if it works https://github.com/ejgallego/coq/tree/ci%2Bstrict_deprecation_flags

**Comment by ejgallego** [comment] 2019-02-19 17:20
When doing porting of overlays I use Dune and the amount of warning I see is staggering, some of them really critical.

In particular, warning 8 is not fatal so Primitive Integers where not really ported to a lot of plugins [which will now segfault] This is a almost a critical issue.

Thus I propose we update Coq Makefile to use the same set of fatal warnings than in Coq, except for 3 (deprecation)

**Comment by maximedenes** [comment] 2019-02-19 17:36
> In particular, warning 8 is not fatal so Primitive Integers where not really ported to a lot of plugins [which will now segfault] This is a almost a critical issue.

Oh! I wasn't aware that the issue was so serious. Can you explain how the segfault occurs?

**Comment by ejgallego** [comment] 2019-02-19 17:55
> Oh! I wasn't aware that the issue was so serious. Can you explain how the segfault occurs?

Missing case in pattern matching.

**Comment by maximedenes** [comment] 2019-02-19 17:58
But how does it trigger a segfault?

**Comment by ejgallego** [comment] 2019-02-19 18:02
Oh indeed maybe it is just an anomaly, I was under the impression that missing pattern cases would trigger segfaults under some conditions (flamba?) anyways missing match case is pretty much fatal.

**Comment by ejgallego** [comment] 2019-02-19 18:10
PR submitted here, https://github.com/coq/coq/pull/9605

**Comment by ejgallego** [comment] 2019-02-19 18:12
I'd like to remove the `needs: discussion` tag that I added; IMHO I gathered plenty of evidence on why this is a good idea [i.e. many many bugs are signaled by warnings and ignored by plugin writers.

**Comment by maximedenes** [comment] 2019-02-19 18:20
> missing pattern cases would trigger segfaults under some conditions

That would be a bug I think, as a well typed OCaml program should not segfault. Of course, I'm not saying this is ideal, but at least it is easier to debug than a segfault.

> I'd like to remove the `needs: discussion` tag that I added; IMHO I gathered plenty of evidence on why this is a good idea [i.e. many many bugs are signaled by warnings and ignored by plugin writers]

The "needs: discussion" was added for the original issue, where you wanted to enable all warnings, including deprecation ones. I personally still strongly oppose to that.

On the other hand, the PR you marked as fixing the issue is enabling only other warnings, which is find and desirable IMHO.

**Comment by ejgallego** [comment] 2019-02-19 18:25
> The "needs: discussion" was added for the original issue, where you wanted to enable all warnings, including deprecation ones. I personally still strongly oppose to that.

Oh indeed it is clear that making deprecation warnings as fatal is for now not possible with our current infrastructure / tooling; I am happy to allow that warning for now, and we may revisit deprecation warnings in the future once tooling improves.

Indeed it is a good point that deprecation warnings should get their own issue, but I think it belongs to a different one which I'll open now.

**Closed** 2019-04-28 17:21 UTC
