### ISSUE TITLE
Coqide failures in a section report a vernacextend anomaly

### ISSUE THREAD

**Issue by herbelin** [coq/coq#15574] opened 2022-01-31 10:54 UTC
#### Description of the problem

Since 8.15, when evaluating directly to the end in Coqide, an error in a section leads to a `"File "vernac/vernacextend.ml", line 77, characters 66-72: Assertion failed."` on the `End` of the section. The original error itself is correctly highlighted thuogh.

Example:
```
Section S.
Check True True.
End S.
```

Apparently due to #14780 that fixed #14446. For instance, if I remove the `assert false` there by `orig` it stops failing.

Apparently a problem of parenthesizing the Push and Pop instructions associated to `VernacBeginSegment` and `VernacEndSegment` but I have no idea of why an error in the section breaks the parenthesizing.

#### Coq Version

8.15 and master

**Comment by herbelin** [comment] 2022-01-31 11:02
@gares: I don't know if you see the issue. Would you have an hint of what could desynchronize sections when evaluating to the end in CoqIDE and an error occurs in the middle of the section?

**Comment by Alizter** [comment] 2022-01-31 11:48
I think this is a duplicate of #14981

**Comment by Alizter** [comment] 2022-01-31 11:50
Seems to again go away with `-async-proofs-command-error-resilience off`

**Comment by SkySkimmer** [comment] 2022-01-31 11:56
Duplicate indeed

**Closed by SkySkimmer** 2022-01-31 11:56 UTC
Labels: part: IDE, kind: regression, priority: high
