### ISSUE TITLE
Ltac2 : Unexpected behavior with goal focusing

### ISSUE THREAD

**Issue by euisuny** [coq/coq#12825] opened 2020-08-11 21:45 UTC
#### Description of the problem

```
From Ltac2 Require Import Ltac2.

Goal forall b : bool, b = b.
  intros b; destruct b.
  2 : {
    (* Doesn't work. *)
  }.
```
Whenever `Ltac2` is imported and I'm not on "Classic" mode (Ltac1 mode), goal focusing using `2 : { }` doesn't seem to work.
Using `Focus 2.` works, but this behavior seems undesirable since the command is deprecated.

(FWIW, `(ltac1:(2 : { ... })` doesn't appear to work, either.)

#### Coq Version

8.11.0, Mac OS X

**Comment by Zimmi48** [comment] 2020-09-10 20:18
Sorry that this was not answered before. Indeed, this is a known issue that is pretty frustrating. @coq/ltac2-maintainers any plan to address this soon? See #12004 for a proposal for a general solution, but this could also be addressed in an ad-hoc way.

**Comment by ppedrot** [comment] 2020-09-11 09:19
I think that #12004 is the cleanest solution.

**Comment by ppedrot** [comment] 2021-04-23 18:27
Duplicate of #12825

**Closed by ppedrot** 2021-04-23 18:27 UTC
Labels: part: ltac2

**Comment by Zimmi48** [comment] 2021-04-27 15:02
@ppedrot You've marked this issue as a duplicate of itself.

**Comment by ejgallego** [comment] 2021-04-27 15:08
He is pen testing github's termination checker.

**Comment by Zimmi48** [comment] 2021-04-27 15:11
@ppedrot Maybe you meant to mark it as a duplicate of #12004 instead. Do you think that this is something that could be implemented easily BTW? And if yes, would you be willing to do it?

**Comment by ppedrot** [comment] 2021-04-27 17:20
I actually meant #10386.
