### ISSUE TITLE
nia spends a long time proving that 0 = 0

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#9161] opened 2018-12-07 06:25 UTC
#### Version

master (8.10+alpha)

#### Operating system

Linux

#### Description of the problem

```coq
Require Import Coq.micromega.Lia Coq.ZArith.ZArith.
Local Open Scope Z_scope.
Goal
forall a b c q0 q r r0 : Z,
  b <> 0 ->
  c <> 0 ->
  c * b <> 0 ->
  a <> 0 ->
  c * a <> 0 ->
  q0 = 0 ->
  q = 0 ->
  c * a = c * b * q + r ->
  (0 < c * b -> 0 <= c * a -> 0 <= r < c * b) ->
  (0 < c * b -> c * a <= 0 -> - (c * b) < r <= 0) ->
  (c * b < 0 -> 0 <= c * a -> 0 <= r < - (c * b)) ->
  (c * b < 0 -> c * a <= 0 -> c * b < r <= 0) ->
  a = b * q0 + r0 ->
  (0 < b -> 0 <= a -> 0 <= r0 < b) ->
  (0 < b -> a <= 0 -> - b < r0 <= 0) ->
  (b < 0 -> 0 <= a -> 0 <= r0 < - b) -> (b < 0 -> a <= 0 -> b < r0 <= 0) -> q = q0.
Proof.
  intros; subst.
  Time exact (eq_refl 0).
  (* Finished transaction in 0. secs (0.004u,0.s) (successful) *)
  Undo.
  Time nia.
  (* Cold cache: Finished transaction in 36.043 secs (35.98u,0.068s) (successful) *)
  Undo.
  Time nia.
  (* Warm cache: Finished transaction in 0.234 secs (0.235u,0.s) (successful) *)
```

36 seconds is ridiculously slow.  If I don't do `subst` at the beginning, somehow it takes less time on a cold cache: around 21 seconds.

**Comment by ppedrot** [comment] 2018-12-07 12:38
I cannot reproduce on e5909ae2043fedf57b64005ba57aedd209e6d42d.

**Comment by ppedrot** [comment] 2019-05-05 17:56
Still cannot reproduce, I'm closing this.

**Closed by ppedrot** 2019-05-05 17:56 UTC
Labels: kind: performance, part: micromega
