### ISSUE TITLE
Anomaly with -mangle-names

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#12880] opened 2020-08-24 10:19 UTC
#### Description of the problem

When building std++ with latest Coq master with name mangling enabled, I get an anomaly:
```
$ COQEXTRAFLAGS="-mangle-names mangled_" make -j8
"coq_makefile" -f _CoqProject -o Makefile.coq 
make[1]: Entering directory '/home/r/Dokumente/Unisachen/iris/stdpp'
COQDEP VFILES
COQDEP TESTFILES
COQC theories/base.v
COQC theories/proof_irrel.v
COQC theories/decidable.v
File "./theories/decidable.v", line 188, characters 7-22:
Error: Anomaly "variable diseq unbound."
Please report at http://coq.inria.fr/bugs/.
```

#### Coq Version

Coq master (98734a2d)

**Comment by SkySkimmer** [comment] 2020-08-24 10:22
Looks like a duplicate of https://github.com/coq/coq/issues/12676

**Closed by SkySkimmer** 2020-08-24 10:22 UTC
