### ISSUE TITLE
A "proof" of False by wrong context of existential variable

### ISSUE THREAD

**Issue by bcip** [coq/coq#8215] opened 2018-08-04 00:58 UTC
I find a "proof" of False that has no goals left, although error is detected by Qed.

#### Version

The Coq Proof Assistant, version 8.8.1 (July 2018)
compiled on Jul 3 2018 10:30:00 with OCaml 4.06.1

#### Operating system
Windows 10

#### Description of the problem

```
Goal False.
Proof.
  pose (n := 1).
  evar (m:nat).
  Show Existentials.
  (* Existential 1 = ?m : [n := 1 : nat |- nat] (shelved) *)
  subst n.
  Fail pose (i := ?m).
  (* The command has indeed failed with message:
     Cannot interpret ?m in current context: no binding for n. *)
  pose (n := 0).
  (* Now n is bound with another value. *)
  pose (i := ?m).
  (* It succeeds... But introducing a new variable that only
     shares the name should be irrelevant. *)
  assert (i = m).
  {
    unfold i. unfold m. reflexivity.
  }
  assert (m = 1).
  {
    subst m.
    instantiate (1 := n).
    reflexivity.
  }
  (* ?m is replaced with different n's. *)
  subst n m i.
  assert (0 <> 1) by discriminate.
  tauto.
  (* No more subgoals.
     But the proof is obviously wrong. *)
  Show Proof.
Qed. (* It fails here. *)
```

**Comment by herbelin** [comment] 2018-08-04 10:54
Hi @bcip, thanks a lot for the example.

There is indeed a "critical" bug of the type checking of existential variables, namely in the (second, non-failing) line `pose (i := ?m)`. Fortunately, existential variables live outside the core type-checker (kernel), so that the final correctness of proofs is not endangered, as the failure of `Qed` indicates.

I fixed the issue in PR #8217. With the fix, `pose (i := ?m)` now fails with error `Cannot interpret ?m in current context: binding for n is not convertible to its expected definition (cannot unify "1" and "0").`

As for `subst`, I don't think that it is wrong. Existential variables come with an instance, which you can display with `Set Printing Existential Instances` (for CoqIDE, in menu View), and `subst` can safely substitute in the instance. Try:
```coq
Goal False.
Proof.
  pose (n := 1).
  Set Printing Existential Instances.
  evar (m:nat).
  (* Displays "m := ?m@{n:=n} : nat" which shows that the "n" of the context of "?m"
     is instantiated by the "n" of the context of the current goal *) 
  subst n.
  (* Displays "m := ?m@{n:=1} : nat" which shows that the "n" of the context of "?m"
     is now instantiated by "1" *) 
```

**Comment by herbelin** [comment] 2018-08-04 16:38
Cases when a variable in the context of an existential variable cannot be used is indeed after a `clear` in a goal which mentions this existential variable. (There are other reasons, like as a result of some unification problems requiring a variable to not be used, but I guess this is not what you are asking.)

Do you have an example of a variable not marked as "cannot be used" after a `clear`?

> In my work, I need to access the existential variable after some variables are cleared (and those variables should not be used in existential variable. Is there any way to do so?

Assuming that I understood your question well, you can clear explicitly a variable `x` in an existential variable `?n` of which you gave the name (typically using `?[n]`) by doing `[n]:clear`, as in:
```coq
Goal forall x:nat, exists y, y = 0.
intro x. eexists ?[n].
[n]:clear x.
Show Existentials.
(*
Existential 1 = ?Goal : [x : nat |- ?n = 0]
Existential 2 = ?n : [ |- nat]
*)
```

**Comment by bcip** [comment] 2018-08-05 02:49
I took some time to find a simple example

```
Goal exists (n:nat), n = 0.
Proof.
  pose (m := 0).
  fold m.
  evar (n : nat).
  apply ex_intro with n.
  subst n.
  (* or just eexists. *)
  unfold m.
  clear m.
  Show Existentials.
  (* Existential 1 = ?n : [m := 0 : nat |- nat] (shelved) *)
Abort.
```
It is hard to use `[n]:clear` in my case. Multiple existential variables may be created in ltac. It is hard to track the existential variables. So the only way to do that is to pass the variables I want to clear to the ltac that creates existential variables. That will make the code harder to understand.

**Comment by herbelin** [comment] 2018-08-05 09:56
OK, I see your case. The point is that `clear m` shall clear `m` only in the existential variables which depend on the `m` which you are clearing, but, here, after the `unfold m`, your existential variable does not any longer depend on the `m` that you are clearing, as the `Set Printing Existential Instances` mode would show:
```
Goal exists (n:nat), n = 0.
Proof.
  pose (m := 0).
  fold m.
  evar (n : nat).
  apply ex_intro with n.
  Set Printing Existential Instances.
  subst n.
  (* ?n@{m:=m} = m *)
  unfold m.
  (* ?n@{m:=0} = m : the ex. var. now depend on 0, not on m *)
  clear m.
  Show Existentials.
```
Note in particular that the name `m` exists independently in two different places. There is a variable `m` in the defining context of `?n` and there is another variable `m` in the goal that you are proving. The `@{m:=m}` says that you instantiate the `m` of `?n` with the `m` of the current goal, thus connecting the two `m`. But after the `unfold`, you get `@{m:=0}` and the two `m` are not anymore connected in the instance of `?n` that occurs in your current goal.

Whether it is a problem in your concrete cases that the `m` of the given instance of `?n` behaves as a `0` I don't know. I would naively think that it is not a problem and that you can continue without having to clear the `m` of `?n` but maybe no. I would need to look at your example in a bigger context where the dependence of `?n` in `m` happens to be a problem.

**Comment by bcip** [comment] 2018-08-05 17:01
That makes sense. But what I need is to access `?n`, e.g. in `pose (n := ?n)` or `rewrite foo with ?n`.
```
Goal exists (n:nat), n = 0.
Proof.
  pose (m := 0).
  fold m.
  evar (n : nat).
  apply ex_intro with n.
  Set Printing Existential Instances.
  subst n.
  (* ?n@{m:=m} = m *)
  unfold m.
  (* ?n@{m:=0} = m : the ex. var. now depend on 0, not on m *)
  clear m.
  pose (n := ?n).
  (* Cannot interpret ?n in current context: no binding for m. *)
```
Using If there is `m := 0`, that this `m` does not depend on any `m` in current context. It should be okay to interpret `?n` without `m` in context.

**Comment by herbelin** [comment] 2018-08-05 18:07
To use `?n` even without an `m` in the current context, you can give yourself an instance for `m`, e.g. by doing `pose (n := ?n@{m:=0})`. But I don't know if this answers your question.

About `unfold`, you could indeed avoid unfolding the `m` occurring in the instance of `?n`. It is a bit tedious but the following works:
```coq
Goal exists (n:nat), n = 0.
Proof.
  pose (m := 0).
  fold m.
  evar (n : nat).
  apply ex_intro with n.
  Set Printing Existential Instances.
  subst n.
  (* ?n@{m:=m} = m *)
  unfold m at 2.
  (* ?n@{m:=m} = 0 *)
```
PS: Note that I made a typo in my previous message, `?n@{m:=0} = m` should have been `?n@{m:=0} = 0`. Sorry.

**Comment by bcip** [comment] 2018-08-05 18:52
I cannot do `pose (n := ?n@{m:=0})`, because what I actually have is not `0` but a really long expression. But I think it is already shown in existential instance that `{m := 0}` or `{m := a long expression of other variables}`, we already have binding for `m`, as this `m` is variable in existential instance, not in current context, and we know it is bound to `0` or something.

I cannot really use `unfold m at 2` because I don't know whether it should be 2 or another number in ltac.

**Comment by herbelin** [comment] 2018-08-05 20:31
> because what I actually have is not 0 but a really long expression

>  I don't know whether it should be 2 or another number in ltac.

I agree that both of those are not very convenient.

So, what you would like is to be able to clear a variable in the context of an existential variable, and to do this in an Ltac function, right? Maybe, if you give the Ltac function you have in mind, we could help better.

**Comment by bcip** [comment] 2018-08-05 20:40
I think access to `?n@{m := 0}` should be allow even if there isn't `m` in context, because these two `m`s are different, `?n` only depends on `m := 0` but not `m` in context.

I am working on [VST](https://github.com/PrincetonUniversity/VST). The following tactic is applied on an entailment in separation logic denoted by `_ |-- _`. We may want to remember the left hand side with `z` to prevent rewriting on left hand side.

```
Ltac EExists'' :=
  let EExists_core :=
    let my_evar name T cb :=
      let x := fresh name
      in
      evar (x : T);
      let x' := eval unfold x in x in clear x; cb x'
    in
    match goal with [ |- _ |-- EX x:?T, _ ] =>
      my_evar x T ltac: (fun x => apply exp_right with x)
    end; idtac
  in
  first [ EExists_core
         | rewrite exp_andp1; EExists''
         | rewrite exp_andp2; EExists''
         | rewrite exp_sepcon1; EExists''
         | rewrite exp_sepcon2; EExists''
         | extract_exists_from_SEP_right; EExists_core
         ].

Ltac EExists' :=
  match goal with |- ?A |-- ?B =>
     let z := fresh "z" in pose (z:=A); change (z|--B); EExists''; unfold z; clear z
  end.
```

**Comment by ejgallego** [comment] 2018-08-06 05:05
The more I look into clear the less clear my understanding of it becomes. It seems to me that clear is mainly a hack for two use cases: avoid tactics from considering some hypotheses; unclutter the goal display.

It seems to me that in both cases, implementation should be done using a flag in the environment, but not by modifying it.

(There is of course the performance cost for O(|env|) operations, but that seems like a different matter)

**Comment by JasonGross** [comment] 2018-08-06 13:16
@ejgallego there are three uses, not two, if you consider "unclutter goal display".  The other two are:
1. Remove it from the list of hypotheses considered by `(e)assumption`, `(e)auto`, `(lazy)match goal`, etc.
2. Prevent the hypothesis from occurring in the proof term that eventually fills the current hole.

There is perhaps another splitting of 1, about whether tactics that modify the context, such as `destruct`, `subst`, etc, should treat the hypothesis as present or not.

Disentangling these (and the merely cosmetic "hide display") should resolve the current confusion with cleared section variables, among other things.

**Comment by herbelin** [comment] 2018-08-06 13:48
@bcip: Then, the problem is that the `unfold z` will prevent the `clear z` to clear the z of the new evar, right?

I don't know what your `exp_` lemmas are doing, but if ever the existential variables uniformly appears in the first occurrence of the result of applying an `exp_` lemma, so that the `z` in the ex. var. instance occurs in second position in the goal (after the occurrence of `z` on the left of `|--`), then, replacing `unfold z` by `unfold z at -2` might help.

But I agree that this is not ideal. Maybe someone like @jasongross would have a trick (maybe using `shelve` and `unshelve`) to explicitly clear a variable of a given variable? Otherwise, I would add this as a feature wish.

@ejgallego: somehow, there is already a form of `clear` made with a flag, using the 'filtering" mechanism of the variable, as the message "cannot be used" reports. However, this filtering is intended to mean that the variable cannot be used in a type-checkability-preserving way, so this is maybe not what you intend, if what you intend is that the flag can be toggled.

**Comment by bcip** [comment] 2018-08-06 14:37
@herbelin Yes. I find it does work for me. Actually the annoying variable `z` is on the left hand side and existential variables are on the right so `unfold z at 1` can do that.

But I want to make a point that `?n@{m := 0}` does not depend on any variable `m` in current context. To clarify, `?n@{m := k}` doesn't depend on `m` but actually depends on `k`. So we should be able to use `?n` without having "Cannot interpret ?n in current context: no binding for m.".

**Comment by ejgallego** [comment] 2018-08-06 16:08
> @ejgallego there are three uses, not two, if you consider "unclutter goal display". The other two are:
> 
> Remove it from the list of hypotheses considered by (e)assumption, (e)auto, (lazy)match goal, etc.

This is mainly the use I had in mind, mainly for efficiency reasons; IMHO a structured solution [such as some form of bracketing] could be used.

> Prevent the hypothesis from occurring in the proof term that eventually fills the current hole.

I am not sure I understand the specification of this case; on a very quick thought all the possibilities here seem like a fragile pattern to me; things in the context can leak into the proof in many ways, so IMHO if that is an issue the top-level structure of the proof should be somehow reified.

**Comment by bcip** [comment] 2018-08-06 19:35
I understand. See the example below. An existential variable is like a function. When `unfold m`, the `m` as argument of `?n` in goal is unfolded. I can understand its mechanism but it seems existential variable should be a goal of its context instead of a function of something changeable.

```
Goal True.
Proof.
  Set Printing Existential Instances.
  pose (m := 0).
  evar (n : nat).
  assert (?n = m).
  unfold m.
  (*
  2 subgoals
  m := 0 : nat
  n := ?n@{m:=m} : nat
  ______________________________________(1/2)
  ?n@{m:=0} = 0
  ______________________________________(2/2)
  True
  *)
```

And why the following lines work? Is it also fixed?
```
assert (?n@{m:=1} = ?n@{m:=m}) by reflexivity.
```

**Comment by JasonGross** [comment] 2018-08-06 20:13
> > Prevent the hypothesis from occurring in the proof term that eventually fills the current hole.
>
> I am not sure I understand the specification of this case; on a very quick thought all the possibilities here seem like a fragile pattern to me; things in the context can leak into the proof in many ways, so IMHO if that is an issue the top-level structure of the proof should be somehow reified.

The specification here is clearest for section variables.  If I `strong_clear x` for `x` a section variable at the beginning of a proof, it should be impossible to complete the proof and hit `Qed` in a way that has the lemma I'm proving depend on `x` when I close the section.  That is, when you set `Proof using` to automatically clear variables you don't depend on, `strong_clear` is what you want to happen to variables not mentioned in the `Proof using` list.

It is not clear to me that `strong_clear` has a use other than when crossing proof-object boundaries (i.e., section variables for any proof, or proof variables right before `abstract`, `transparent_abstract`, etc.)

**Comment by JasonGross** [comment] 2018-08-06 20:16
> Maybe someone like @JasonGross would have a trick (maybe using shelve and unshelve) to explicitly clear a variable of a given existential variable?

```coq
Ltac subst_all_lets :=
  repeat match goal with
         | [ x := _ |- _ ] => subst x
         end.
Ltac clear_local_vars_in ev :=
  let Hev := fresh in
  pose ev as Hev;
  instantiate (1:=ltac:(subst_all_lets)) in (Value of Hev);
  subst Hev.
```

**Comment by JasonGross** [comment] 2018-08-06 20:26
@bcip I'm a bit confused by your example.  How are you getting your hands on the bare existential name without its context in VST?  If you are writing tactic scripts, and have the evar from, e.g., a `match goal`, or an `evar (n : ...)`, or whatever, then `pose` should work fine, because the evar should still have the context.  Consider, e.g.,
```coq
Goal True.
Proof.
  Set Printing Existential Instances.
  pose (m := 0).
  evar (n : nat).
  subst m.
  Fail pose ?n. (* this fails, but you're sort-of taking advantage of global names here *)
  let n' := (eval cbv delta [n] in n) in
  pose n'. (* this succeeds *)
  match goal with
  | [ n := ?ev |- _ ] => is_evar ev; pose ev
  end. (* this also succeeds *)
```

**Comment by JasonGross** [comment] 2018-08-06 20:29
Also, here is another instance of this sort of thing, which I think behaves correctly, which does not depend on `clear`:
```coq
Goal True.
Proof.
  Set Printing Existential Instances.
  pose (m := 0).
  unshelve evar (n : nat); revgoals.
  pose ?n. (* success *)
  2:rename m into z.
  Fail pose ?n. (* Cannot interpret ?n in current context: no binding for z. *)
```
@bcip do you think this should behave differently?

**Comment by bcip** [comment] 2018-08-06 22:36
@JasonGross Your comments help a lot. What I want to do is  to write an `eexists` for entailments in separation logic in VST. There is a simplified version below. I `subst x` and only keep `?x`, so I can use it for unification later. In this simplified version, `z` is not needed, but in real version, `z` is used to prevent rewriting on left hand side. I already have some compromised way to do that. But I still think it doesn't make sense.

```
Ltac EExists :=
  match goal with |- ?A |-- ?B =>
     let z := fresh "z" in pose (z:=A); change (z|--B);
     (* This part is simplified. *)
     match goal with [ |- _ |-- EX _:?T, _ ] =>
       let x := fresh "x" in evar (x : T); apply exp_right with x; subst x
     end;
     subst z
  end.

Goal forall (P : Z -> mpred) (n : Z), P n |-- EX n:Z, P n.
Proof.
  intros.
  (* P n |-- EX n0 : Z, P n0 *)
  EExists.
  (* P n |-- P ?x *)
  apply derives_refl.
  (* No more subgoals. *)
Qed.
```

**Comment by JasonGross** [comment] 2018-08-06 22:54
I do not see you using `?x` anywhere in that proof script.

Trying to guess at your use of `?x`: If you are relying on the fact that `let x := fresh "x" in evar (x : T)` will generate an evar named `?x`, that is fragile, and I think you shouldn't do that.  Instead, you can either CPS `EExists` so that it calls its continuation with the evar directly; or you can pass the name `x` into `EExists` and do `unfold x` rather than `subst x`, so that whatever name you pass in to `EExists` will still exist later so you can pull the evar from it; or you can pull the evar from the goal with `match goal` later (e.g., `match goal with |- context[?e] => is_evar e; ... end`).

**Comment by bcip** [comment] 2018-08-06 23:14
@JasonGross I do use CPS in real version. But the name `x` and `?x` is always not guaranteed because `x` could be  already used. In real version, I use the name, e.g. `y` in (EX y:Z, _). I will use `?x` in following example.
```
Ltac EExists :=
  match goal with |- ?A |-- ?B =>
     let z := fresh "z" in pose (z:=A); change (z|--B);
     (* This part is simplified. *)
     match goal with [ |- _ |-- EX _:?T, _ ] =>
       let x := fresh "x" in evar (x : T); apply exp_right with x; subst x
     end;
     subst z
  end.

Parameter P Q : Z -> mpred.
Axiom PQ: forall n, P n = Q n.

Goal forall (P : Z -> mpred) (n : Z), P n |-- EX n:Z, Q n.
Proof.
  intros.
  (* P n |-- EX n0 : Z, P n0 *)
  EExists.
  (* P n |-- P ?x *)
  rewrite PQ with ?x.
  (* ?x is not necessary here, but necessary in some real cases. *)
  (* Cannot interpret ?x in current context: no binding for z. *)
  apply derives_refl.
Qed.
```

**Comment by bcip** [comment] 2018-08-06 23:27
@JasonGross In my opinion, existential variable should be a variable implemented by a function using its context as arguments, but not a function that accepts any other arguments. Expression like `?n@{m:=1} = ?n@{m:=m}` doesn't make any sense at all. `?n` should always be bound to its own context, but not some strange things like `?n@{m:=1}`.

```
Goal True.
Proof.
  Set Printing Existential Instances.
  pose (m := 0).
  unshelve evar (n : nat); revgoals.
  pose ?n. (* success *)
  2:rename m into z.
(* Now ?n still depends on `m` in context of `Goal`. it is fine to access `?n`. It's irrelevant whether there is `z` here. *)
  Fail pose ?n.
```

**Comment by JasonGross** [comment] 2018-08-07 00:42
@bcip Are you saying that some step of this proof should fail?  Or should behave differently?
```coq
Goal True.
Proof.
  Set Printing Existential Instances.
  clear.
  pose (a := 0).
  (* 1 subgoal (ID 3)
  
  a := 0 : nat
  ============================
  True
*)
  unshelve evar (n : nat); revgoals.
  (* 2 subgoals (ID 6)
  
  a := 0 : nat
  n := ?n@{a:=a} : nat
  ============================
  True

subgoal 2 (ID 4) is:
 nat
*)
  pose (eq_refl : n = n) as H. (*
2 subgoals (ID 12)
  
  a := 0 : nat
  n := ?n@{a:=a} : nat
  H := (eq_refl : n = n) : n = n
  ============================
  True

subgoal 2 (ID 4) is:
 nat
*)
  unfold n in H. (* 2 subgoals (ID 13)
  
  a := 0 : nat
  n := ?n@{a:=a} : nat
  H := eq_refl : ?n@{a:=a} = ?n@{a:=a}
  ============================
  True

subgoal 2 (ID 4) is:
 nat
*)
  2:refine (let k := a in _); clearbody k; clear a. (* 2 subgoals (ID 13)
  
  a := 0 : nat
  n := let k := a in ?Goal0@{k:=k} : nat
  H := eq_refl : (let k := a in ?Goal0@{k:=k}) = (let k := a in ?Goal0@{k:=k})
  ============================
  True

subgoal 2 (ID 17) is:
 nat
                                                     *)
  change a with 0 in (type of H) at 1. (* 2 subgoals (ID 18)
  
  a := 0 : nat
  n := let k := a in ?Goal@{k:=k} : nat
  H := eq_refl : (let k := 0 in ?Goal@{k:=k}) = (let k := a in ?Goal@{k:=k})
  ============================
  True

subgoal 2 (ID 17) is:
 nat
                                        *)
  clearbody H. (* 2 subgoals (ID 19)
  
  a := 0 : nat
  n := let k := a in ?Goal@{k:=k} : nat
  H : (let k := 0 in ?Goal@{k:=k}) = (let k := a in ?Goal@{k:=k})
  ============================
  True

subgoal 2 (ID 17) is:
 nat
 *)
  clearbody a. (* 2 subgoals (ID 20)
  
  a : nat
  n := let k := a in ?Goal@{k:=k} : nat
  H : (let k := 0 in ?Goal@{k:=k}) = (let k := a in ?Goal@{k:=k})
  ============================
  True

subgoal 2 (ID 17) is:
 nat
 *)
  2:exact k. (* 1 subgoal (ID 20)
  
  a : nat
  n := let k := a in k : nat
  H : (let k := 0 in k) = (let k := a in k)
  ============================
  True
*)
  pose (H : 0 = a). (* 1 subgoal (ID 24)
  
  a : nat
  n := let k := a in k : nat
  H : (let k := 0 in k) = (let k := a in k)
  e := (H : 0 = a) : 0 = a
  ============================
  True
*)
```

Alternatively, if I swap the lines `2:refine (let k := a in _); clearbody k; clear a.` and `change a with 0 in (type of H) at 1.` so that that part of the proof becomes
```coq
  change a with 0 in (type of H) at 1. (* 2 subgoals (ID 14)
  
  a := 0 : nat
  n := ?n@{a:=a} : nat
  H := eq_refl : ?n@{a:=0} = ?n@{a:=a}
  ============================
  True

subgoal 2 (ID 4) is:
 nat
*)
  2:refine (let k := a in _); clearbody k; clear a. (* 2 subgoals (ID 14)
  
  a := 0 : nat
  n := let k := a in ?Goal0@{k:=k} : nat
  H := eq_refl : (let k := 0 in ?Goal0@{k:=k}) = (let k := a in ?Goal0@{k:=k})
  ============================
  True

subgoal 2 (ID 18) is:
 nat
*)
```
are you saying that one of these lines should fail, or behave differently?

**Comment by bcip** [comment] 2018-08-07 00:52
@JasonGross I don't think there is any problem in your example.

**Comment by bcip** [comment] 2018-08-07 01:02
@JasonGross I think an existential variable, e.g. `?n`, should always have virtually only one instance. If there are multiple instances, they must be equivalent. But they may be not convertible as below.
```
Parameter f : nat -> nat.
Axiom f_mult2: forall n, f n = n*2.

Goal forall x, exists n, n = x*2.
Proof.
  Set Printing Existential Instances.
  intros.
  pose (m := x * 2).
  evar (n:nat).
  exists n.
  subst n.
  unfold m.
  rewrite <- f_mult2.
  pose (n := ?n@{x:=x; m:=f x}).
  assert (n = m).
  unfold n.
  reflexivity.
  rewrite f_mult2.
  reflexivity.
Qed.
```
I don't know why `Qed.` succeeded in previous example as `2*x` and `f x` are not convertible.

Maybe it is a better way to bind existential variable to one instance. If it is rewritten somewhere, it is rewritten everywhere. Or another one-instance manipulation is to not allow to be rewritten.

**Comment by HuStmpHrrr** [comment] 2018-08-19 15:25
I am not sure in which case we would be interested in fill in the context of evar explicitly? I personally find that we should not be able to fill in the context by hand to begin with. It sounds virtually the same as changing goal context at will to me. Then it's not surprising that it does not have to be consistent. Are there any existing use cases?

**Closed** 2018-09-26 09:02 UTC
Labels: part: tactics, priority: high
