### ISSUE TITLE
Anomaly "File "kernel/safe_typing.ml", line 462, chars 2-8

### ISSUE THREAD

**Issue by jmikedupont2** [coq/coq#18582] opened 2024-01-29 10:05 UTC
running dune build in assistants/coq_of_assistants/lib

https://github.com/meta-introspector/assistants/pull/new/bugreport/crash1_coq

```
Entering directory '/mnt/data1/2024/01/27/assistants/coq_of_assistants'
File "./lib/assistants_api_communication.v", line 1336, characters 4-99:
Error:
Anomaly
"File "kernel/safe_typing.ml", line 462, characters 2-8: As```

**Comment by ppedrot** [comment] 2024-01-29 10:08
@jmikedupont2 your link is not correct, it leads to the opening of an issue.

**Comment by jmikedupont2** [comment] 2024-01-29 10:09
https://github.com/stellar-amenities/assistants/pull/87
ok so the error was the module was not closed

**Comment by ppedrot** [comment] 2024-01-29 10:13
Looks like a duplicate of #18401 then.

**Closed** 2024-02-05 13:45 UTC
