### ISSUE TITLE
coqtop can no longer Require files that were not available when it started

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6780] opened 2018-02-18 19:00 UTC
#### Version

8.8+alpha

#### Description of the problem

Consider this bash script.  It succeeds with Coq 8.7.1, but fails with Coq master:
```bash
#!/usr/bin/env bash

set -ex

cd /tmp
rm -rf testreq
mkdir testreq
cd testreq

for i in $(seq 0 3); do
    cat > A${i}.v <<EOF
Require Import Coq.ZArith.ZArith.
Definition foo := Eval vm_compute in (Z.div_eucl, Z.div_eucl, Z.div_eucl, Z.div_eucl).
EOF
done

cat > B.v <<EOF
Require Import Coq.ZArith.ZArith.
Time Definition foo0 := Eval vm_compute in (Z.div_eucl, Z.div_eucl, Z.div_eucl, Z.div_eucl).
Time Definition foo1 := Eval vm_compute in (Z.div_eucl, Z.div_eucl, Z.div_eucl, Z.div_eucl).
Time Definition foo2 := Eval vm_compute in (Z.div_eucl, Z.div_eucl, Z.div_eucl, Z.div_eucl).
Require Import Test.A0.
Time Definition foo3 := Eval vm_compute in (Z.div_eucl, Z.div_eucl, Z.div_eucl, Z.div_eucl).
Time Definition foo4 := Eval vm_compute in (Z.div_eucl, Z.div_eucl, Z.div_eucl, Z.div_eucl).
Time Definition foo5 := Eval vm_compute in (Z.div_eucl, Z.div_eucl, Z.div_eucl, Z.div_eucl).
Require Import Test.A1.
Time Definition foo6 := Eval vm_compute in (Z.div_eucl, Z.div_eucl, Z.div_eucl, Z.div_eucl).
Time Definition foo7 := Eval vm_compute in (Z.div_eucl, Z.div_eucl, Z.div_eucl, Z.div_eucl).
Time Definition foo8 := Eval vm_compute in (Z.div_eucl, Z.div_eucl, Z.div_eucl, Z.div_eucl).
Require Import Test.A2.
EOF

function compile() {
    for i in $(seq 0 3); do
        ${COQBIN}coqc -q -R . Test A${i}
    done
}

compile &

echo | ${COQBIN}coqtop -q -R . Test -load-vernac-source B.v || exit $?
```
On 8.7.1:
```
$ COQBIN="$HOME/.local64/coq/coq-8.7.1/bin/" ./test.sh ; echo $?
+ cd /tmp
+ rm -rf testreq
+ mkdir testreq
+ cd testreq
++ seq 0 3
+ for i in '$(seq 0 3)'
+ cat
+ for i in '$(seq 0 3)'
+ cat
+ for i in '$(seq 0 3)'
+ cat
+ for i in '$(seq 0 3)'
+ cat
+ cat
+ compile
+ echo
++ seq 0 3
+ /home/jgross/.local64/coq/coq-8.7.1/bin/coqtop -q -R . Test -load-vernac-source B.v
+ for i in '$(seq 0 3)'
+ /home/jgross/.local64/coq/coq-8.7.1/bin/coqc -q -R . Test A0
Welcome to Coq 8.7.1 (December 2017)
Skipping rcfile loading.
Finished transaction in 0.26 secs (0.248u,0.011s) (successful)
+ for i in '$(seq 0 3)'
+ /home/jgross/.local64/coq/coq-8.7.1/bin/coqc -q -R . Test A1
Finished transaction in 0.256 secs (0.256u,0.s) (successful)
Finished transaction in 0.244 secs (0.24u,0.008s) (successful)
+ for i in '$(seq 0 3)'
+ /home/jgross/.local64/coq/coq-8.7.1/bin/coqc -q -R . Test A2
Finished transaction in 0.211 secs (0.211u,0.s) (successful)
Finished transaction in 0.21 secs (0.211u,0.s) (successful)
Finished transaction in 0.212 secs (0.212u,0.s) (successful)
+ for i in '$(seq 0 3)'
+ /home/jgross/.local64/coq/coq-8.7.1/bin/coqc -q -R . Test A3
Finished transaction in 0.217 secs (0.215u,0.s) (successful)
Finished transaction in 0.231 secs (0.232u,0.s) (successful)
Finished transaction in 0.229 secs (0.227u,0.s) (successful)

Coq < Coq <
0
```
On master:
```
$ COQBIN="$HOME/.local64/coq/coq-master/bin/" ./test.sh ; echo $?
+ cd /tmp
+ rm -rf testreq
+ mkdir testreq
+ cd testreq
++ seq 0 3
+ for i in '$(seq 0 3)'
+ cat
+ for i in '$(seq 0 3)'
+ cat
+ for i in '$(seq 0 3)'
+ cat
+ for i in '$(seq 0 3)'
+ cat
+ cat
+ compile
+ echo
++ seq 0 3
+ /home/jgross/.local64/coq/coq-master/bin/coqtop -q -R . Test -load-vernac-source B.v
+ for i in '$(seq 0 3)'
+ /home/jgross/.local64/coq/coq-master/bin/coqc -q -R . Test A0
Welcome to Coq jgross-Leopard-WS:/home/jgross/Downloads/coq/coq-master,master (41893cb647fbdce87b40acd5763e837370d61ece)
Skipping rcfile loading.
Finished transaction in 0.267 secs (0.256u,0.012s) (successful)
+ for i in '$(seq 0 3)'
+ /home/jgross/.local64/coq/coq-master/bin/coqc -q -R . Test A1
Finished transaction in 0.238 secs (0.236u,0.004s) (successful)
Finished transaction in 0.224 secs (0.223u,0.s) (successful)
File "/tmp/testreq/B.v", line 5, characters 15-22:
Error: Unable to locate library Test.A0.

+ exit 1
1
```

This is an issue when working on files interactively in PG, as it means I have to quit Coq to `Require Import` a new file

**Comment by ejgallego** [comment] 2018-02-18 19:14
Duplicate of #6751

**Closed by ejgallego** 2018-02-18 19:14 UTC
Labels: kind: regression, priority: high
