### ISSUE TITLE
`List.rev` has quadratic complexity

### ISSUE THREAD

**Issue by MathisBD** [coq/coq#19839] opened 2024-11-17 21:43 UTC
### Is your feature request related to a problem?

The definition of `List.rev` in the standard library is quadratic :
```Coq 
Fixpoint rev (l:list A) : list A :=
    match l with
      | [] => []
      | x :: l' => rev l' ++ [x]
    end.
```
This is very bad for such a common function. 

### Proposed solution

It should instead use an accumulator to obtain linear complexity :
```Coq 
Fixpoint rev (l : list A) :=
  let fix aux l acc :=
    match l with
    | [] => acc
    | x :: l => aux l (x :: acc)
    end
  in aux l []
```

**Comment by ppedrot** [comment] 2024-11-17 21:51
Duplicate of #17847

**Closed by ppedrot** 2024-11-17 21:51 UTC
Labels: needs: triage, kind: wish
