### ISSUE TITLE
Conversion test raised an anomaly when using lots of functions

### ISSUE THREAD

**Issue by JonasOberhauser** [coq/coq#10384] opened 2019-06-16 19:36 UTC
#### Description of the problem

Ok this one is fun. An anomaly that occurs when I try to do this match which includes a predicate over predicates, if the predicate uses a product, and the goal has functions. 

```
Variable Q : (nat  -> Prop) -> Prop.


Ltac bogus := 
  match goal with
  | H: Q ?p
    |- context [ ?p ] => idtac
  end.


Definition PAnomaly := (fun (n : nat) => nat -> True).
Goal Q PAnomaly -> plus 4 = plus 4.
intros H.
Fail bogus. (* Conversion test raised an anomaly: Anomaly "conversion was given ill-typed terms (FProd)."
 *)
Abort.

(* remove function in goal -- no anomaly *)
Goal Q PAnomaly -> 4 = plus 3 6.
intros H.
Fail bogus. (* no anomaly *)
Abort.

(* remove product in assumption -- no anomaly *)
Definition PNoanomaly := (fun n : nat => True).
Goal Q PNoanomaly -> plus 4 = plus 4.
intros H.
Fail bogus. (* no anomaly *)
Abort.
```

#### Coq Version

CoqIDE 8.9.0

**Comment by ejgallego** [comment] 2020-06-26 13:44
Seems fixed in master, and likely a duplicate of a similar bug using the match construction.

**Closed by ejgallego** 2020-06-26 13:44 UTC
