### ISSUE TITLE
Int63 operations not reduced by `vm_compute` when used with modules and functors

### ISSUE THREAD

**Issue by DIJamner** [coq/coq#14849] opened 2021-09-07 00:51 UTC
#### Description of the problem

The following code declares a module wrapping an Int63 operation, passes that module to a functor, and then attempts to evaluate a call to the resulting module's function using `vm_compute`. I would expect this computation to evaluate to 1, but `vm_compute` produces `if (0 =? 0)%int63 then 1 else 0)`. If I run `vm_compute` on that, I then get 1.

```
Require Import Int63.

Module Type Eqb.

  Parameter t : Type.
  Parameter eqb : t -> t -> bool.

End Eqb.

Module Int63Eqb <: Eqb.

  Definition t := int.
  Definition eqb := eqb.

End Int63Eqb.

Module UseEq (E : Eqb).

  Definition use_eq x :=
    if E.eqb x x then 1 else 0.

End UseEq.

Module M := UseEq Int63Eqb.

Eval vm_compute in
    (M.use_eq 0)%int63. (* should compute to 1 *)
Eval vm_compute in
    (if (0 =? 0)%int63 then 1 else 0).
```

#### Coq Version

The Coq Proof Assistant, version 8.15+alpha
compiled with OCaml 4.09.1

**Comment by herbelin** [comment] 2021-09-07 17:44
Suspectingly related to #14822 which proposes a solution (cc @coq/vm-native-maintainers).

**Comment by silene** [comment] 2021-09-07 18:23
That is a duplicate of #12519.

**Closed by silene** 2021-09-07 18:23 UTC
Labels: part: VM
