### ISSUE TITLE
Dune build: CoqIDE startup (developer build) error dialog at startup

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14191] opened 2021-04-27 22:28 UTC
`dune exec -- dev/shim/coqide-prelude` gives this error before the main window comes up.

![image](https://user-images.githubusercontent.com/1253341/116320358-f42f9e00-a76c-11eb-9ff7-703612fa8a1c.png)

**Comment by ejgallego** [comment] 2021-04-27 23:51
Duplicate of #14181

**Closed by ejgallego** 2021-04-27 23:51 UTC
Labels: part: build
