### ISSUE TITLE
coq-makefile: having a non-existent file in _CoqProject leads to coqdep step being silently skipped

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#10393] opened 2019-06-17 17:33 UTC
#### Description of the problem

Have a `_CoqProject` with a non-existent file in it and run the usual `coq_makefile -f _CoqProject -o Makefile`. Then run `make`.

I would expect `make` to fail loudly. Instead, it tries to build all the remaining files *but in a random order*. No `.coqdeps.d` is created, and from `VERBOSE=1` output it seems lke the `coqdep` step gets silently skipped.

#### Coq Version

8.9.1

**Comment by RalfJung** [comment] 2019-06-17 17:37
The reason it gets skipped is the following:
```
$(VDFILE).d: $(VFILES)
```
However nothing depends on even having a `.coqdeps.d` present, so if that file does not get crated, the rest of the build proceeds as normal.
Probably `$(VDFILE).d` should be added as a dependency for a bunch of things, in particular the `$(VOFILES)` rule.

**Comment by SkySkimmer** [comment] 2019-06-17 17:41
Duplicate of https://github.com/coq/coq/issues/9319

**Closed by SkySkimmer** 2019-06-17 17:41 UTC
