### ISSUE TITLE
Selectors reorder goals

### ISSUE THREAD

**Issue by herbelin** [coq/coq#12339] opened 2020-05-16 21:23 UTC
#### Description of the problem

Is this expected?
```
Goal 0=1 /\ 0=2 /\ 0=3.
repeat split.
1,3: idtac.
(*
______________________________________(1/3)
0 = 1
______________________________________(2/3)
0 = 3
______________________________________(3/3)
0 = 2
```

Added: apparently, this was done like this because focusing was only able to focus consecutive goals. Should we try to preserve the order?

#### Coq Version

At least since 8.7

**Comment by Zimmi48** [comment] 2020-05-17 14:24
No, this is correctly following the specification. This was done like this because multi-goal tactics may generate several goals, but we cannot associate them to any one of the selected sub-goals. And the tactic monad doesn't have a notion of single goal tactics, for which this tracking could be done more precisely.

cc @cmangin who implemented the feature

**Comment by herbelin** [comment] 2020-05-17 17:08
> And the tactic monad doesn't have a notion of single goal tactics, for which this tracking could be done more precisely.

The tactic monad could be changed to reflect what would be (at least in this case) a (more) intuitive semantics. For instance, it would be understandable that the focused goal are systematically moved to the first position, but it is strange that the first one is left at the same place but not the other ones.

More generally, I agree that it is not always clear how subgoals should optimally be ordered (for instance when it is about side conditions of or new evars)... many questions pending for the next generations...

**Comment by Zimmi48** [comment] 2020-05-18 09:01
> > And the tactic monad doesn't have a notion of single goal tactics, for which this tracking could be done more precisely.
> 
> The tactic monad could be changed to reflect what would be (at least in this case) a (more) intuitive semantics. For instance, it would be understandable that the focused goal are systematically moved to the first position, but it is strange that the first one is left at the same place but not the other ones.

I've had very similar thoughts than you, cf. for instance this interesting discussion that you may have missed: https://github.com/coq/coq/issues/10688#issuecomment-594014556

Anyway, I'd be glad if we could adapt the tactic monad to give a reality to some of our intuitive notions, like side conditions, the relation between goals and subgoals, etc. Food for thoughts for the long-term.

**Comment by kyoDralliam** [comment] 2020-08-15 14:15
Duplicate of #8481

**Closed** 2020-08-15 14:40 UTC
