### ISSUE TITLE
Creating a module alias introduces redundant hints.

### ISSUE THREAD

**Issue by charguer** [coq/coq#15367] opened 2021-12-15 11:27 UTC
Bug tested on 8.13 and master.

```
Axiom P : Prop.
Axiom foo : P -> P.

Module MYMODULE.
Hint Resolve foo : mybase.
End MYMODULE.

Lemma test1 : P.
(* simple search, 6 nodes *)
debug eauto with mybase.
Abort.

Module M := MYMODULE. (* a short-name alias *)

(* At this point, [foo] is registered twice as a hint:
   once from MYMODULE and once from M. *)
(* Note that neither MYMODULE nor M are imported. *)

Lemma test2 : P.
debug eauto with mybase.
(* exponential search, 65 nodes *)
Abort.

(* On practical examples, this leads to significant slowdown. *)
```

**Comment by ppedrot** [comment] 2021-12-15 13:24
I agree that this is a dubious behaviour, but this is quite a sensitive topic. Aliasing kind of changes the syntactic shape of the type, since you get a renaming in the types. There are many moving parts there.

See also https://github.com/coq/coq/issues/4783

**Comment by ppedrot** [comment] 2021-12-15 13:25
Duplicate of #6731

**Closed by ppedrot** 2021-12-15 13:25 UTC
Labels: part: modules, part: auto
