### ISSUE TITLE
Anomaly from "Print HintDb typeclass_instances." with MathClasses

### ISSUE THREAD

**Issue by NeilStrickland** [coq/coq#6035] opened 2017-10-28 15:37 UTC
I am using Coq 8.7.0 under Windows 10.  I have the following file:

```
Require Import MathClasses.implementations.stdlib_binary_naturals.
Print HintDb typeclass_instances.
``` 

Coq reports:
```
Error:
Anomaly "index to an anonymous variable." Please report at http://coq.inria.fr/bugs/.
```
The anomaly goes away if I remove the "Require" line.  I should mention that I had to replace some files from my copy of MathClasses with empty files to make it compile, because of the issues described at https://github.com/coq/coq/issues/5776.  But it does compile now without complaining, so I presume that that is not the problem.

(As a side issue, note that the suggested URL for reporting bugs is out of date.)

**Comment by herbelin** [comment] 2017-10-28 15:43
Duplicate of #5401.

**Closed by herbelin** 2017-10-28 15:43 UTC

**Comment by Zimmi48** [comment] 2017-10-29 11:46
> As a side issue, note that the suggested URL for reporting bugs is out of date.

We don't really intend to change this URL because it is advantageously independent on the bug tracker that we are using. For now, the page indicates both the old bug tracker and the new one but in a few months we can decide to turn this page into a simple redirection.
