### ISSUE TITLE
Intermittent segfaults while building 8.11.0

### ISSUE THREAD

**Issue by jamesjer** [coq/coq#11939] opened 2020-03-27 17:31 UTC
I am attempting to build coq 8.11.0 for the upcoming Fedora 32 release, using ocaml 4.10.  We build for 6 architectures: x86_64, i686, ppc64le, s390x, armv7hl, and aarch64.  Repeated build attempts have failed.  Each time, coqc has either segfaulted or encountered an illegal instruction on at least one architecture.  The architecture in question varies from build to build.  Information gathered by Richard Jones suggests that the garbage collector is involved, and that weak references may play a role (which would help explain the nondeterminism).  Please see https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/AEPCSIRZMPRG4ZGXAPAIX45LW7ZQA5XI/ for the discussion on fedora-devel-list.

Any suggestions you can give on how to track this down would be much appreciated.

**Comment by ejgallego** [comment] 2020-03-27 19:03
Hi @jamesjer , thanks for the report and for the detailed analysis. First thing, what patch are you using for OCaml 4.10 support? Note that we don't support 4.10 officially yet.

There is something you could try to see if you can reproduce, in particular, configure Coq with: `-bytecode-compiler no -native-compiler no`.

If you can still reproduce with that settings there is a high probability that the bug is in GCC / OCaml, next step I guess would be start trying to reproduce with 4.09 / 4.08, etc...

**Comment by jamesjer** [comment] 2020-03-27 19:21
We are using this patch: https://github.com/coq/coq/commit/4af1f7ec60b442ef815c056ce95519cfe1621ca3.  I realize you don't support 4.10 officially, but Fedora has updated to 4.10 already, so I have no choice but to try to make coq work with it.  I will try configuring coq as you describe.  Thanks for the suggestion.

**Comment by ejgallego** [comment] 2020-03-27 19:56
I'm not sure that patch is correct, on the other hand 4.10 support has landed into master and should find its way to the 8.11 branch shortly, I'd suggest you update the package to that branch.

**Comment by jamesjer** [comment] 2020-03-27 20:17
That's good information.  Thank you.  Meanwhile, my first build with `-bytecode-compiler no -native-compiler no` finished successfully.  However, since the problem is intermittent, I will have to try several more times before I can say that it "works".

**Comment by ejgallego** [comment] 2020-03-27 20:21
The patch you used has a high change to actually be the cause of the problems you are experiencing; the patch for 4.10 we have proposed is this #11102 , but even if merged it is not very well tested yet.

**Comment by jamesjer** [comment] 2020-03-27 20:37
Thanks for the pointer.  I'll try using that patch locally and see if I encounter any problems.  Thank you, @ejgallego, you have been very helpful.

**Comment by ejgallego** [comment] 2020-03-27 20:38
Thanks to you for the careful reporting and for keeping Coq up to date in Fedora.

**Comment by rwmjones** [comment] 2020-03-27 20:40
BTW I tried `-runtime-variant d` and that didn't make any difference (except making things run slower).

**Comment by SkySkimmer** [comment] 2020-05-08 21:27
@jamesjer Is this issue still happening?

**Comment by jamesjer** [comment] 2020-05-09 04:55
I tried a scratch build tonight, with a prerelease of ocaml 4.11.0.  It succeeded on all architectures:

https://koji.fedoraproject.org/koji/taskinfo?taskID=44237522

Of course, the problem is intermittent, so this is no guarantee that the issue is gone.

**Comment by Blaisorblade** [comment] 2020-05-10 13:01
@jamesjer I notice your link is building Coq 8.11.0 on Rawhide (Fedora/RH unstable, right) — I see Fedora 32 was released, but Rawhide might want to try 8.11.1.

-----------

BTW, there's something wrong with the Coq package, @jamesjer — the description "Python 3 runtime support for ANTLR4" is certainly wrong; I see how that's possible from the RPM spec (https://apps.fedoraproject.org/packages/coq/sources/), but not sure how to fix it. I'm afraid I'm not going to file a Fedora ticket myself.

See these snapshot from https://apps.fedoraproject.org/packages/coq:

![image](https://user-images.githubusercontent.com/289960/81499907-f506c000-92ce-11ea-880f-64c0345d49ef.png)

**Comment by jamesjer** [comment] 2020-05-19 21:10
Sorry for the delay responding; $DAYJOB got extra busy there for a few days.  Okay, I will update to 8.11.1 and see what I can do about fixing that package description.  Thanks for pointing that out.

**Comment by ejgallego** [comment] 2021-02-13 23:07
Closing for lack of info / reproduction; please reopen with more info if the problem comes back.

**Closed by ejgallego** 2021-02-13 23:07 UTC
Labels: needs: triage, part: build
