### ISSUE TITLE
Anomaly "File "clib/int.ml", line 46, characters 14-20: Assertion failed."

### ISSUE THREAD

**Issue by emmarion** [coq/coq#13834] opened 2021-02-07 12:31 UTC
#### Description of the problem
```coq
Inductive myeq (A : Type) (x : A) : A -> Prop :=
| myeq_refl : myeq A x x.

Arguments myeq [A].
Arguments myeq_refl {A} {x}.

Definition myeqss (A : Type) (a b : A) (H : myeq (Some a) (Some b)) : myeq a b.
  pose (Some b) as Someb.
  rewrite (myeq_refl : myeq (Some b) Someb) in *.
  rewrite (myeq_refl : myeq b (match Someb with None => a | Some b_ => b_ end)).
  destruct H.
  reflexivity.
Qed.
```

#### Coq Version

The Coq Proof Assistant, version 8.13.0 (February 2021)
compiled on Feb 7 2021 12:13:04 with OCaml 4.11.1

**Comment by SkySkimmer** [comment] 2021-02-08 11:52
It looks like `internal_myeq_rew_r` is defined after the first rewrite, but not used in the proof until the second rewrite. I guess it somehow gets dropped from the side effect list.

**Comment by herbelin** [comment] 2021-02-10 09:04
This is a regression starting with 8.11. Worth a bisection if no intuition about the possible cause.

**Comment by ejgallego** [comment] 2021-03-10 17:34
If the side-effect is dropped from the list [not surprised] shouldn't we try to figure out where it is dropped? Adding a printf for run_tactic could help us pinpoint the problem, IIRC there are already a few FIXME in rewrite about dropping side effects.

Indeed as we have discussed quite a few times, the current seff api is very prone to errors as users have to explicitly thread them [hence the FIXMEs], it would be much better if side-effects could be just computed at `Qed` time.

**Comment by MSoegtropIMC** [comment] 2021-04-16 13:17
I also run into this anomaly today, but my case is rather intricate and only happens if I use `par:`. It would be quite some work to construct a sharable test case from that, but if it helps, I could do that.

In any case: if you have a solution and want me to test it on my case, please let me know.

**Comment by ppedrot** [comment] 2021-04-16 13:34
@MSoegtropIMC this anomaly is pretty generic, are you sure it's related to this bug? (We should probably adapt the title accordingly actually.)

**Comment by MSoegtropIMC** [comment] 2021-04-16 14:21
No - all I can say is that the error message is the same. The circumstances are definitely quite different. But since my case is complicated, I would suggest that when you have a solution for the case given here I test if we are lucky, and if not I try to strip down my case to something manageable and publishable. I archived it in a GIT tag of my development. Of cause if you say the case discussed here is highly unlikely to have something to do with a `par:` vs. `all:` discrepancy, I could look into it right away.

**Comment by SkySkimmer** [comment] 2021-04-16 14:33
Is it possible to test on https://github.com/coq/coq/commit/a74d87aca7dd5d09f305be5772b1ee14c926d904 (first bad commit) 's parent?

**Comment by MSoegtropIMC** [comment] 2021-04-16 15:28
@SkySkimmer : sure will do.

**Comment by SkySkimmer** [comment] 2021-08-10 15:05
@MSoegtropIMC ping

**Comment by ppedrot** [comment] 2022-02-25 16:13
Seems to be fixed on master, I'll push a test.

**Closed** 2022-02-27 18:02 UTC
Labels: kind: regression, kind: anomaly
