### ISSUE TITLE
End of input in CoqIDE

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#9488] opened 2019-02-06 11:00 UTC
#### Version

Coq 8.8.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following actions cause an anomaly.

* Open CoqIDE.
* Insert the following code into the buffer.
* Try to navigate to the end.
* Navigate backward.
* Navigate backward.
* Delete everything from any point within `idtac 1` to the end of the document.

```
Goal True.
Proof. idtac 1. idtac 2. qed.
```

```
Anomaly "Uncaught exception Stm.End_of_input."
```

The only way to recover is to delete the remaining proof.

#### Notes

This reliably reproduces #8647.
Even though this bug may already be fixed,
this report should at least give peace of mind
to the past victims of this elusive anomaly.

**Comment by maximedenes** [comment] 2019-02-08 14:45
On master I get:

```
Anomaly
"File "ide/idetop.ml", line 95, characters 12-18: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

@gares can I assign this to you?

**Comment by gares** [comment] 2019-02-08 16:46
I can't get the anomaly on master, but I sometimes get coqide to advance for me toward the end of the document when I *delete* something.

@Tuplanolla many thanks for your many bugreports. I see you use Red Hat. If you also happen to use gnome, it is quite easy to record screencasts (  https://help.gnome.org/users/gnome-help/stable/screen-shot-record.html.en ).

**Comment by gares** [comment] 2019-02-08 16:51
The anomaly you get seems to indicate that coqide did not "reparse" the text in order to update the gtk_marks that delimit sentences, and that then sent to Coq a partial sentence (without the trailing `.`). This is turn makes the stream, out of the string, terminate too early. 882 misses the exception, while master seems to catch it and return None.

The code not being called seems to be `Coq_lex.delimit_sentences`, see `sentence.ml`.
Without being able to reproduce it, I can hardly test I fix it :-/

**Comment by maximedenes** [comment] 2019-02-08 17:27
> I can't get the anomaly on master

This is strange, I can trigger it reliably. Are you sure you copied the text as it is and followed the steps described above? What could we be doing differently?

**Closed** 2019-02-17 13:14 UTC
Labels: kind: anomaly, part: IDE
