### ISSUE TITLE
Ltac2 "match! goal with  | H : _ |- _ =>" fails (is it implemented?)

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12669] opened 2020-07-10 04:07 UTC
I was trying to convert this example from the Ltac1 chapter to Ltac2:

```
         Goal forall A B : Prop, A -> B -> (A->B).
         intros.
         match goal with
         | H : _ |- _ => idtac "apply " H; apply H
         end.
```
which produces
```
apply  H1
apply  H0
No more subgoals.
```

but this replacement for the `match` following gives this error.

```
      match! goal with
      | [ H : _ |- _ ] => print (of_constr H); apply H
      end.

Toplevel input, characters 31-77:
>       | [ H : _ |- _ ] => print (of_constr H); apply H
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Invalid identifier
```

Changing the initial `H` to `_` and removing the print gives:

```
      match! goal with
      | [ _ : _ |- _ ] => apply H
      end.

Toplevel input, characters 0-61:
> match! goal with
>       | [ _ : _ |- _ ] => apply H
>       end.
Error: Uncaught Ltac2 exception: Match_failure
```

Is this supposed to work or is it something that's not ready yet?

@ppedrot @JasonGross

**Comment by JasonGross** [comment] 2020-07-10 04:31
I think you need `apply &H` or something?

**Comment by ppedrot** [comment] 2020-07-10 06:22
It is supposed to work, but you have to tweak a bit the example to fit into the Ltac2 syntax. Ltac2 doesn't allow uppercase variables, so in the match goal syntax you have to replace `H` with e.g. `h`. Then for primitive tactics that rely on the constr scope, you need to be explicit in the syntax that you're referring to a bound variable. So you need to write `apply $h` instead. By contrast, `apply &H` would have meant "apply the hypothesis literally called `H` in the current context", but since there is none this would dynamically fail.

**Comment by ppedrot** [comment] 2020-07-10 06:30
Forgot to mention that you're inside a proof, so in "non-strict" mode. In this case, `apply &H` and `apply H` behave the same, which is why you get the dynamic error.

**Comment by jfehrle** [comment] 2020-07-10 17:35
This doesn't work, either, and the message is so complex.  What else needs to change?  Furthermore, CoqIDE doesn't show the `File "./user-contrib/Ltac2/Notations.v", line 34, characters 32-33:` line:

```
match! goal with
      | [ h : _ |- _ ] => apply $h
      end.
```

```
File "./user-contrib/Ltac2/Notations.v", line 34, characters 32-33:
Error: This expression has type
(((Pattern.match_kind * pattern) list * (Pattern.match_kind * pattern)) *
  (constr array -> 'c -> 'b -> 'a -> unit)) list
but an expression was expected of type
(((Pattern.match_kind * Pattern.t) list * (Pattern.match_kind * Pattern.t)) *
  (ident array -> Pattern.context array -> constr array -> Pattern.context ->
    'a)) list
```

> Ltac2 doesn't allow uppercase variables

I don't see how restricting pattern variables (and other places?) is helpful to the user.  Substitutions are clearly marked with `$`, right?  Coq generally allows upper case for identifiers; requiring lower case in some places just makes it harder for users and documentation.  The "Invalid identifier" message shown earlier is not specific enough and it doesn't localize the problem to the identifier (it points to the entire expression).  I suggest dropping this restriction with one exception:  Enforcing the well-established lowercase convention for tactic names is reasonable, e.g. `Ltac2 F := msg "x".` gives `The identifier F must be lowercase`.  What do you think?

(BTW, non-Roman characters are allowed, so `Ltac2 Ββ x:= msg "x".` is valid, where "B" is Greek uppercase beta, U+0392.  "β" is also valid in patterns.)

> Then for primitive tactics that rely on the constr scope, you need to be explicit in the syntax that you're referring to a bound variable. So you need to write `apply $h` instead.

I would hope that substitution is always and only represented as `$h` and that your first sentence, which I don't understand, is not needed.

> By contrast, `apply &H` would have meant "apply the hypothesis literally called `H` in the current context", but since there is none this would dynamically fail.

If substitutions are already marked with `$`, why does the `&` syntax exist at all?  It seems to me that applying a specific existing theorem or lemma (same syntax, different use case) would be very common in Ltac.

Also, how can I print the term? `print (of_constr $h)` doesn't parse and `print (of_constr constr:($h))` gets a lengthy type error.

**Comment by ppedrot** [comment] 2020-07-10 17:43
> This doesn't work, either, and the message is so complex. What else needs to change?

I cannot agree more, the message is not pretty. The problem is that the bound variable has type ident but apply expects a term, so you have to write something along the lines of `let h := Control.hyp h in apply $h`.

> Coq generally allows upper case for identifiers

IMHO this is a terrible design choice that has been plaguing the Coq syntax since its inception and has far-reaching implications. It makes very hard to recognize trivial errors in pattern-matching and is not robust to change in constructor names for instance, which can result in silent miscompilations. It has also other similar ambiguity issues with module namespacing, which in turn forces to use a weird syntax for projections. By contrast, OCaml has distinct namespaces for constructors and variables which is the source of inspiration for Ltac2. Also, you can't change that easily, it conditions a lot of things.

> "β" is also valid in patterns.

This is a bug.

> your first sentence, which I don't understand

I am not sure what you don't understand, can you be more specific?

> If substitutions are already marked with $, why does the & syntax exist at all?

Because they don't mean the same? The rationale is explained in Ltac2 documentation.

> Also, how can I print the term? print (of_constr $h) doesn't parse and print (of_constr constr:($h)) gets a lengthy type error.

The type error is the same as the above one, this is an ident and not a constr. I definitely need to find a way to make this human readable.

**Comment by jfehrle** [comment] 2020-07-10 20:12
This works, but `let h := Control.hyp h in ...` seems quite wordy.  Seems like that might be used quite frequently.  It seems strange that h is an ident rather than the value it refers to--if this was a match in OCaml I'd expect h would have the value.  Can that be changed?

```
match! goal with
            | [ h : _ |- _ ] => let h := Control.hyp h in print (of_constr h); apply $h
            end.
```

Oddly enough, I didn't recall that OCaml requires lower case for variables and upper case for constructors.  If you use an identifier starting with lower case in a constructor name, the only message from OCaml is "Syntax error" :-(.

> Then for primitive tactics that rely on the constr scope, you need to be explicit in the syntax that you're referring to a bound variable. So you need to write apply $h instead.

How do you tell if a primitive tactic relies on the constr scope?  You need to read `Std.v` and know that `constr_with_bindings` relies on the constr scope??  How can the doc explain this and why is the qualification (i.e. the first sentence) needed?

```
Ltac2 @ external apply : advanced_flag -> evar_flag ->
  (unit -> constr_with_bindings) list -> (ident * (intro_pattern option)) option -> unit := "ltac2" "tac_apply".
```

>> If substitutions are already marked with $, why does the & syntax exist at all?

> Because they don't mean the same? The rationale is explained in Ltac2 documentation.

It's not adequately explained, especially the motivation.  Why would you want `&id is turned into Std.VarRef id` and when would you use it?  Maybe should be a different conversation.  Also seems like there's quite a large undocumented API associated with Ltac2 (Messsage, Std, Notation, ...).

Do you expect we (most likely meaning you) will get around to fixing the issues mentioned here (and agree on) in the foreseeable future?  If that's not likely to happen, it may not be worth the trouble of writing them up separately.

**Comment by jfehrle** [comment] 2020-07-10 20:16
Also seems strange that the `$` is needed in some places but not others, e.g. `print (of_constr h); apply $h`

**Comment by jfehrle** [comment] 2020-07-10 20:20
The square brackets were added to make the parsing work?

![image](https://user-images.githubusercontent.com/1253341/87199709-11fc4700-c2b0-11ea-93f1-c03730c2f3a0.png)

**Comment by jfehrle** [comment] 2020-07-10 21:46
The only equivalent for `| _ => idtac` is `| [ _ : _ |- _ ] => ()`?  Not having `| [ _ ] => ()` is intentional?

**Comment by JasonGross** [comment] 2020-07-10 21:52
If you cannot do `| _ => ()`, that seems like a missing convenience.  Also, your equivalent is wrong, as it will fail when there are no hypotheses.  You should be able to drop `_ : _`.

**Comment by ppedrot** [comment] 2020-07-10 21:53
@jfehrle it's `| [ |- _ ] => ()`. The requirement for brackets is intentional, IIRC the parsing is ambiguous without them.

**Comment by jfehrle** [comment] 2020-07-10 22:31
> The requirement for brackets is intentional, IIRC the parsing is ambiguous without them.

Alas, now different from match! term.  Not sure I'd advocate adding there too, for consistency.

**Comment by ppedrot** [comment] 2020-07-11 09:33
@jfehrle this is not the same kind of object matched, I don't see why it should be the same. BTW Ltac1 uses the same syntax as well, except that it allows both match goal with and without brackets. I think that the former is historical.

**Comment by ppedrot** [comment] 2021-03-13 13:26
The original issue has been solved, it now prints a proper error message ("Invalid identifier H classifying as an Ltac2 constructor") that is correctly located in CoqIDE. @jfehrle If you want to open more precise bug reports, please write them in fresh issues. In the meantime I am closing this one.

**Closed by ppedrot** 2021-03-13 13:26 UTC
Labels: kind: bug, part: ltac2
