### ISSUE TITLE
Anomaly with existential variables.

### ISSUE THREAD

**Issue by vedgar** [coq/coq#13898] opened 2021-03-04 18:42 UTC
#### Description of the problem

Goal exists a:nat, exists b, a = b. do 2 eexists. easy.

gives Anomaly "Uncaught exception Failure("hd")."
Please report at http://coq.inria.fr/bugs/.

Of course, this is just a minimal example. The original is much longer and much more sensible.

#### Coq Version

8.13.0 on Windows

**Comment by ejgallego** [comment] 2021-03-04 18:52
I can't reproduce in either 8.13.0 nor in `master`.

**Comment by vedgar** [comment] 2021-03-04 18:57
Interesting. So what should I do? Reinstall?

**Comment by ejgallego** [comment] 2021-03-04 19:04
Well I have no idea, are you sure you are running that code with the right Coq version?

For example 8.12 in https://jscoq.github.io also don't seem to produce any problem.

**Comment by vedgar** [comment] 2021-03-04 19:36
Ok, as far as I can see coqtop in the command line doesn't have the problem either. It appears in CoqIDE only. But that only makes it more puzzling. (Screenshot at https://drive.google.com/file/d/1J0maVvF6Yu5t29ka2F_WCOnuwW9EojUX/view?usp=sharing).

**Comment by ejgallego** [comment] 2021-03-04 19:40
Umm, that could make sense, but I failed to reproduce with coqide either.

**Comment by SkySkimmer** [comment] 2021-03-04 20:22
Can reproduce by going to the end in one go
~~~
Anomaly "Uncaught exception Failure("hd")."
Please report at http://coq.inria.fr/bugs/.
Raised at file "stdlib.ml", line 29, characters 17-33
Called from file "list.ml" (inlined), line 30, characters 10-23
Called from file "printing/proof_diffs.ml", line 552, characters 41-49
Called from file "printing/proof_diffs.ml", line 559, characters 19-39
Called from file "printing/proof_diffs.ml", line 644, characters 61-75
Called from file "ide/coqide/idetop.ml", line 238, characters 26-61
Called from file "ide/coqide/idetop.ml", line 456, characters 12-15
Called from file "ide/coqide/protocol/xmlprotocol.ml", line 683, characters 29-46
~~~

**Comment by SkySkimmer** [comment] 2023-06-09 12:06
Seems fixed now

**Closed by SkySkimmer** 2023-06-09 12:06 UTC
Labels: kind: user messages, part: CoqIDE, kind: anomaly
