### ISSUE TITLE
Regression in testing Locality flag

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6260] opened 2017-11-27 18:41 UTC
This is a reminder, suggested in #6197, that something has to be done to alert when a locality modifier is not effective, as e.g. in:
```coq
Require Import FunInd.
Local Function f (n : nat) := n.
```
I put `blocker` as suggested in #6197. Maybe this is a bit exaggerated, strictly speaking, but I guess it is to signal that we have not to forget.

**Comment by Zimmi48** [comment] 2017-11-27 18:43
Duplicate of #6239

**Closed by Zimmi48** 2017-11-27 18:43 UTC
Labels: kind: regression, kind: user messages, priority: blocker

**Comment by herbelin** [comment] 2017-11-27 18:46
Oups, sorry for noise.
