### ISSUE TITLE
Fixpoint with delegated proof produces incorrect {struct}

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#10297] opened 2019-06-04 09:26 UTC
~~~coq
Fixpoint plus (n m : nat) : nat.
Proof.
  destruct n.
  - exact m.
  - exact (S (plus n m)).
Qed. 
(* with -async-proofs on:
Recursive definition of plus is ill-formed.
In environment ...
Recursive call to plus has principal argument equal to 
"m" instead of a subterm of "m".
Recursive definition is: ... *)
~~~
I think this is known in folklore but it didn't have an issue that I could find.

**Comment by ejgallego** [comment] 2019-06-04 10:43
The proof+recthms branch moves the information out of the closure so indeed should allow to fix this as info is safely marshallable.

**Comment by ejgallego** [comment] 2019-06-04 17:14
> The proof+recthms branch moves the information out of the closure so indeed should allow to fix this as info is safely marshallable.

Indeed I just checked and the problem is still there however, the information could be safely passed on.

Will submit this branch as soon as #9566 gets in.

**Comment by maximedenes** [comment] 2019-06-04 21:00
Isn't this #9060?

**Comment by maximedenes** [comment] 2019-06-04 21:05
My personal take on this is that this feature is broken by design (the calculus requires to say what you're doing an induction on upfront, so we are trying to lie to the kernel), and should be removed (when no body is provided, the `struct` annotation should be mandatory).

In particular, even without `-async-proofs`, the intermediate proof term is ill typed, as shown by `Guarded`. AFAIK, tactics are not expected to produce ill-typed proof terms.

**Comment by SkySkimmer** [comment] 2019-06-04 21:06
>Isn't this #9060?

Indeed it looks like it

**Comment by ppedrot** [comment] 2019-06-05 07:01
FTR, this "feature" is one of the few breakers if the indirect opaque abstraction. I am all for its removal.

**Comment by ejgallego** [comment] 2019-06-05 09:39
@ppedrot how does this break the IOA ? I mean, sure, it chains the future but isn't that a problem of the `close_proof` API instead?

The bug here is that is that `possible_indexes` to `adjust_guardeness` are lost, but this can be fixed once we get rid of the closures as then the data can be transmitted [already done in the proof PRs so you may not want to duplicate work folks]

**Comment by ppedrot** [comment] 2019-06-05 10:49
> how does this break the IOA

It's accessing the body, even though it might have been deferred into the opaque table. So, it's not critical, but this is on par with extraction and printing.

**Comment by ejgallego** [comment] 2019-06-05 10:56
Yeah but the problem is that this function should get such a low level object. I mean, morally the access is ok (we didn't even save the constant) however it is the API that is bad.

**Comment by SkySkimmer** [comment] 2019-06-05 11:03
@ppedrot is talking about `retrieve_first_recthm` which is looking at saved opaque constants.

**Comment by ejgallego** [comment] 2019-06-05 11:09
> @ppedrot is talking about `retrieve_first_recthm` which is looking at saved opaque constants.

Oh! I see what you mean, that's actually fixable I think, I did reify quite a lot of that function but not sure to the point we can skip the save_constant there and be uniform, but looks close; let me have a look to the branch again.

**Comment by gares** [comment] 2019-06-06 05:53
I think it is fixable but I concur it is not worth it. A fix point with no recursive argumen is like a match on an unknown inductive, the calculus is simply not made for that. I think we should remove this "feature"

**Comment by gares** [comment] 2019-06-06 05:57
Quiz, what if a fix with no recargs occurs in the type of an evar (a goal), and we call a reduction function?

**Comment by gares** [comment] 2019-06-06 06:04
Another way to put it: incomplete terms are possible via evars, that let us type check/reduce an incomplete term in a sound way. Metavariables for recarg or caseinfo are not there, nobody studied them. That, assuming it is possible, would be a sound way to leave that piece of info unspecified and still do sensible stuff.

Here we hack around putting a dummy integer, and we hope to find one that makes sense by brute force at the very end. All this for, frankly, very little ergonomy.

**Comment by maximedenes** [comment] 2019-06-07 08:57
Closing as this is a duplicate of #9060.

**Closed by maximedenes** 2019-06-07 08:57 UTC
Labels: part: STM
