### ISSUE TITLE
Strict positivity check for types defined using `fix` and `match`

### ISSUE THREAD

**Issue by emarzion** [coq/coq#16998] opened 2022-12-15 05:07 UTC
It would be useful to be have the strict positivity condition extended to cases when a type is defined using fixpoints.  For instance, if we wish to use recursively-defined vectors, it is not possible to use these later in an `Inductive` definition:

```
Fixpoint Vec (X : Type) (n : nat) : Type :=
  match n with
  | 0 => unit
  | S m => X * Vec X m
  end.

Fail Inductive rose (X : Type) : Type :=
  | mk_rose {n} : Vec (rose X) n -> rose X.

(*
The command has indeed failed with message:
Non strictly positive occurrence of 
"rose" in
 "forall n : nat, Vec (rose X) n -> rose X".
*)
```

It's also worth mentioning that this issue exists for types defined with `match`, not just `fix`:

```
Definition foo (X : Type) (b : bool) : Type :=
  if b then X else unit.

Fail Inductive bar (X : Type) : Type :=
  | mk_bar {b} : foo (bar X) b -> bar X.

(*
The command has indeed failed with message:
Non strictly positive occurrence of 
"bar" in
 "forall b : bool, foo (bar X) b -> bar X".
*)
```

I imagine you could extend the strict positivity condition for `match` by saying that a type variable is strictly positive in a match if it is strictly positive in all branches, and in fixpoints you would check if it is strictly positive in the body on the assumption that it is strictly positive in all recursive calls.  Perhaps I am being naive and there are some subtleties that I am missing, however.

**Comment by andres-erbsen** [comment] 2022-12-23 16:10
Here is another example that looks desirable, almost matching on the inductive being defined:

```coq
Inductive branch (A : Type) : Type :=
| Node (l : option (branch A)) (o : option A) (r : option (branch A))
  (_ : match l, o, r with None, None, None => False | _,_,_ => True end).
Inductive branch (A : Type) : Type :=
| Node (l : option (branch A)) (o : option A) (r : option (branch A))
  (_ : l = None -> o = None -> r = None -> False).
```

Both of these definitions fail due to non-positive occurrence in the last argument.

**Comment by ppedrot** [comment] 2022-12-23 16:36
Duplicate of #1433

**Closed by ppedrot** 2022-12-23 16:36 UTC
