### ISSUE TITLE
Coq spends a long time deciding to print nothing

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#9034] opened 2018-11-20 17:03 UTC
#### Version

8.8.1

#### Operating system

Linux

#### Description of the problem

```coq
Require Import Coq.ZArith.ZArith.
Require Import Coq.Lists.List.

Definition Z_div_eucl := Eval compute in Z.div_eucl.
Fixpoint big' (n : nat) (v : Prop)
  := match n with
     | O => v
     | S n' => big' n' (v = v)
     end.
Definition big n := Eval compute in big' n (Z_div_eucl = Z_div_eucl).
Definition x1 := Eval compute in big 1.
Definition x2 := Eval compute in big 2.
Definition x3 := Eval compute in big 3.
Definition x4 := Eval compute in big 4.
Definition x5 := Eval compute in big 5.
Definition x6 := Eval compute in big 6.
Definition x7 := Eval compute in big 7.
Definition x8 := Eval compute in big 8.
Definition x9 := Eval compute in big 9.
Notation hidden := (fun x => _).
Notation hidden' := (forall x, _).
Definition small n := Eval compute in big' n True.
Definition y1 := Eval compute in small 1.
Definition y2 := Eval compute in small 2.
Definition y3 := Eval compute in small 3.
Definition y4 := Eval compute in small 4.
Definition y5 := Eval compute in small 5.
Definition y6 := Eval compute in small 6.
Definition y7 := Eval compute in small 7.
Definition y8 := Eval compute in small 8.
Definition y9 := Eval compute in small 9.

Time Print x1. (* Finished transaction in 0.027 secs (0.027u,0.s) (successful) *)
Time Print x2. (* Finished transaction in 0.046 secs (0.048u,0.s) (successful) *)
Time Print x3. (* Finished transaction in 0.072 secs (0.072u,0.s) (successful) *)
Time Print x4. (* Finished transaction in 0.103 secs (0.103u,0.s) (successful) *)
Time Print x5. (* Finished transaction in 0.157 secs (0.156u,0.s) (successful) *)
Time Print x6. (* Finished transaction in 0.314 secs (0.316u,0.s) (successful) *)
Time Print x7. (* Finished transaction in 0.612 secs (0.611u,0.s) (successful) *)
Time Print x8. (* Finished transaction in 1.188 secs (1.187u,0.s) (successful) *)
Time Print x9. (* Finished transaction in 2.371 secs (2.372u,0.s) (successful) *)
Time Print y1. (* Finished transaction in 0. secs (0.u,0.s) (successful) *)
Time Print y2. (* Finished transaction in 0. secs (0.u,0.s) (successful) *)
Time Print y3. (* Finished transaction in 0. secs (0.u,0.s) (successful) *)
Time Print y4. (* Finished transaction in 0. secs (0.u,0.s) (successful) *)
Time Print y5. (* Finished transaction in 0. secs (0.u,0.s) (successful) *)
Time Print y6. (* Finished transaction in 0. secs (0.u,0.s) (successful) *)
Time Print y7. (* Finished transaction in 0. secs (0.u,0.s) (successful) *)
Time Print y8. (* Finished transaction in 0.001 secs (0.u,0.s) (successful) *)
Time Print y9. (* Finished transaction in 0.002 secs (0.004u,0.s) (successful) *)
```
The printed term is the same size for the `x`s and the `y`s, but the time spent (presumably in detyping) is drastically different.  The time does seem to be linear in the size of the raw term, but it would be much better for the time to be linear in the size of the printed term.  (Presumably by only converting to `glob_constr` the parts that will actually be printed?)

cc @ppedrot 

See Also #9029 for a case where this came up in the wild.

**Comment by JasonGross** [comment] 2018-11-20 19:32
@ppedrot Wait, really?  I thought #8909 was about binder naming slowness, and this version shouldn't spend too much time on binder naming?

**Comment by ppedrot** [comment] 2018-11-20 23:32
Why not? The `x` definitions do contain an important number of binders.

**Comment by ppedrot** [comment] 2018-11-20 23:35
More precisely, the phase that hides the definition through the notation happens after the binder allocation, which thus cannot be delayed, if this is what is puzzling you.

**Comment by JasonGross** [comment] 2018-11-21 21:42
Huh.  In that case, I'd very much like to see a fix to #8909 (even at the cost of compatibility for printing, which is not a thing I care about super-much).

**Comment by ppedrot** [comment] 2018-11-21 22:57
I'm working on that.

**Comment by ppedrot** [comment] 2018-11-21 22:58
Duplicate of #8909

**Closed** 2018-11-21 22:58 UTC
Labels: kind: performance
