### ISSUE TITLE
Proof breaks in 8.11 with a universe anomaly

### ISSUE THREAD

**Issue by jwiegley** [coq/coq#11673] opened 2020-02-24 17:11 UTC
This proof breaks with 8.11 on the `Qed`, and the error does not provide enough information for me to understand what went wrong... I've minified it down to the attached case.

```
File "./Bug.v", line 517, characters 0-4:
Error: Anomaly "Universe Bug.18252 undefined."
Please report at http://coq.inria.fr/bugs/.
```

`Bug.v`:

```coq
(* -*- mode: coq; coq-prog-args: ("-emacs" "-R" "." "Category" "-top" "Transformation") -*- *)
(* File reduced by coq-bug-finder from original input, then from 76 lines to 36 lines, then from 117 lines to 45 lines, then from 220 lines to 54 lines, then from 353 lines to 111 lines, then from 275 lines to 166 lines, then from 430 lines to 244 lines, then from 512 lines to 366 lines, then from 576 lines to 406 lines, then from 664 lines to 475 lines, then from 514 lines to 405 lines, then from 561 lines to 476 lines, then from 585 lines to 513 lines, then from 576 lines to 515 lines, then from 530 lines to 515 lines *)
(* coqc version 8.11.0 (January 1970) compiled on Jan 1 1970 0:00:01 with OCaml 4.07.1
   coqtop version 8.11.0 (January 1970) *)
Axiom proof_admitted : False.
Tactic Notation "admit" := abstract case proof_admitted.
Require Coq.Program.Program.
Export Coq.Program.Program.
Delimit Scope category_theory_scope with category_theory.
Open Scope category_theory_scope.
Export Coq.Classes.CMorphisms.

Generalizable All Variables.

Notation "∀  x .. y , P" := (forall x, .. (forall y, P) ..)
  (at level 200, x binder, y binder, right associativity) :
  category_theory_scope.

Notation "x → y" := (x -> y)
  (at level 99, y at level 200, right associativity): category_theory_scope.
Notation "x ↔ y" := (iffT x y)
  (at level 95, no associativity) : category_theory_scope.

Infix "∧" := prod (at level 80, right associativity) : category_theory_scope.

Class Setoid A := {
  equiv : crelation A;
  setoid_equiv :> Equivalence equiv
}.

Notation "f ≈ g" := (equiv f g) (at level 79) : category_theory_scope.

Program Instance setoid_refl `(sa : Setoid A) :
  Reflexive equiv.
Obligation 1.
admit.
Defined.

Program Instance setoid_sym `(sa : Setoid A) :
  Symmetric equiv.
Obligation 1.
admit.
Defined.

Program Instance setoid_trans `(sa : Setoid A) :
  Transitive equiv.
Obligation 1.
admit.
Defined.
Import Coq.Bool.Bool.

Open Scope lazy_bool_scope.

Ltac simplify :=
  repeat
    (match goal with
     | [ H : () |- _ ] => destruct H
     | [ |- () ] => exact tt

     | [ H : (_ &&& _) = true |- _ ] => rewrite <- andb_lazy_alt in H
     | [ |- (_ &&& _) = true ]       => rewrite <- andb_lazy_alt
     | [ H : (_ && _) = true |- _ ]  => apply andb_true_iff in H
     | [ |- (_ && _) = true ]        => apply andb_true_iff; split

     | [ H : _ ∧ _ |- _ ] =>
       let H' := fresh "H" in destruct H as [H H']
     | [ |- _ ∧ _ ] => split

     | [ H : _ /\ _ |- _ ] =>
       let H' := fresh "H" in destruct H as [H H']
     | [ |- _ /\ _ ] => split

     | [ H : _ ↔ _ |- _ ] =>
       let H' := fresh "H" in destruct H as [H H']
     | [ |- _ ↔ _ ] => split

     | [ H : (_, _) = (_, _) |- _ ] => inversion_clear H

     | [ H : _ * _ |- _ ] =>
       let x := fresh "x" in
       let y := fresh "y" in
       destruct H as [x y]
     | [ |- _ * _ ] => split

     | [ H : { _ : _ & _ } |- _ ] =>
       let x := fresh "x" in
       let e := fresh "e" in
       destruct H as [x e]
     | [ |- { _ : _ & _ } ] =>
       unshelve (refine (existT _ _ _))
     end; intros).

Ltac cat :=
  simplify;
  autorewrite with categories;
  auto with category_laws;
  try reflexivity.
Hint Extern 6 (equiv ?X ?Y) =>
  apply Equivalence_Symmetric : category_laws.

Ltac equivalence := constructor; repeat intro; simpl; try cat; intuition.
Ltac proper := repeat intro; simpl; try cat; intuition.

Ltac cat_simpl :=
  program_simpl; autounfold;
  try solve [
    repeat match goal with
    | [ |- Equivalence _ ] => equivalence
    | [ |- Equivalence _ ] => equivalence
    | [ |- Proper _ _ ] => proper
    | [ |- respectful _ _ _ _ ] => proper
    | [ |- Proper _ _ ] => proper
    | [ |- respectful _ _ _ _ ] => proper
    end;
    program_simpl; autounfold in *;
    simpl in *; intros; simplify;
    simpl in *; cat];
  simpl in *.

Global Obligation Tactic := cat_simpl.

Reserved Infix "~>" (at level 90, right associativity).

Class Category := {
  obj : Type;

  uhom := Type : Type;
  hom : obj -> obj -> uhom where "a ~> b" := (hom a b);
  homset :> ∀ X Y, Setoid (X ~> Y);

  id {x} : x ~> x;
  compose {x y z} (f: y ~> z) (g : x ~> y) : x ~> z
    where "f ∘ g" := (compose f g);

  compose_respects x y z :>
    Proper (equiv ==> equiv ==> equiv) (@compose x y z);

  dom {x y} (f: x ~> y) := x;
  cod {x y} (f: x ~> y) := y;

  id_left  {x y} (f : x ~> y) : id ∘ f ≈ f;
  id_right {x y} (f : x ~> y) : f ∘ id ≈ f;

  comp_assoc {x y z w} (f : z ~> w) (g : y ~> z) (h : x ~> y) :
    f ∘ (g ∘ h) ≈ (f ∘ g) ∘ h;
  comp_assoc_sym {x y z w} (f : z ~> w) (g : y ~> z) (h : x ~> y) :
    (f ∘ g) ∘ h ≈ f ∘ (g ∘ h)
}.

Delimit Scope category_scope with category.
Delimit Scope object_scope with object.
Delimit Scope morphism_scope with morphism.

Notation "x ~> y" := (@hom _%category x%object y%object)
  (at level 90, right associativity) : homset_scope.
Notation "x ~{ C }~> y" := (@hom C%category x%object y%object)
  (at level 90) : homset_scope.

Notation "id[ x ]" := (@id _%category x%object)
  (at level 9, format "id[ x ]") : morphism_scope.

Notation "f ∘ g" :=
  (@compose _%category _%object _%object _%object f%morphism g%morphism)
  : morphism_scope.

Coercion obj : Category >-> Sortclass.

Hint Rewrite @id_left : categories.
Hint Rewrite @id_right : categories.

Open Scope category_scope.
Open Scope homset_scope.
Open Scope morphism_scope.

Hint Extern 10 (?X ∘ (?Y ∘ ?Z) ≈ ?W) =>
  rewrite <- comp_assoc; cat : category_laws.

Section Morphisms.

Context {C : Category}.

Class Section `(f : x ~> y) := {
  section : y ~> x;
  section_comp : section ∘ f ≈ id
}.

Class Retraction `(f : x ~> y) := {
  retract : y ~> x;
  retract_comp : f ∘ retract ≈ id
}.

Class Epic {x y} (f : x ~> y) := {
  epic : ∀ z (g1 g2 : y ~> z), g1 ∘ f ≈ g2 ∘ f → g1 ≈ g2
}.

Class Monic {x y} (f : x ~> y) := {
  monic : ∀ z (g1 g2 : z ~> x), f ∘ g1 ≈ f ∘ g2 → g1 ≈ g2
}.

End Morphisms.

Section Isomorphism.

Context {C : Category}.

Class Isomorphism (x y : C) : Type := {
  to   :> x ~> y;
  from :  y ~> x;

  iso_to_from : to ∘ from ≈ id;
  iso_from_to : from ∘ to ≈ id
}.

Arguments to {x y} _.
Arguments from {x y} _.

Infix "≅" := Isomorphism (at level 91) : category_scope.

Global Program Definition iso_compose {x y z : C} `(f : y ≅ z) `(g : x ≅ y) :
  x ≅ z := {|
  to   := to f ∘ to g;
  from := from g ∘ from f
|}.
Next Obligation.
admit.
Defined.
Next Obligation.
admit.
Defined.

Global Program Instance Isomorphism_Proper :
  Proper (Isomorphism ==> Isomorphism ==> iffT) Isomorphism.
Next Obligation.
admit.
Defined.

Global Program Instance Isomorphism_flip_Proper :
  Proper (Isomorphism ==> Isomorphism ==> Basics.flip iffT) Isomorphism.
Next Obligation.
admit.
Defined.

End Isomorphism.

Delimit Scope isomorphism_scope with isomorphism.
Open Scope isomorphism_scope.

Notation "x ≅ y" := (@Isomorphism _%category x%object y%object)
  (at level 91) : isomorphism_scope.

Arguments to {_%category x%object y%object} _%morphism.
Arguments from {_%category x%object y%object} _%morphism.

Coercion to : Isomorphism >-> hom.

Notation "f '⁻¹'" := (from f) (at level 9, format "f '⁻¹'") : morphism_scope.

Program Instance iso_to_monic {C : Category} {x y} (iso : @Isomorphism C x y) :
  Monic iso.
Next Obligation.
admit.
Defined.

Program Instance iso_from_monic {C : Category} {x y} (iso : @Isomorphism C x y) :
  Monic (iso⁻¹).
Next Obligation.
admit.
Defined.

Program Instance iso_to_epic {C : Category} {x y} (iso : @Isomorphism C x y) :
  Epic iso.
Next Obligation.
admit.
Defined.

Program Instance iso_from_epic {C : Category} {x y} (iso : @Isomorphism C x y) :
  Epic (iso⁻¹).
Next Obligation.
admit.
Defined.

Program Instance Monic_Retraction_Iso
        {C : Category} {x y : C} `(r : @Retraction _ _ _ f) `(m : @Monic _ _ _ f) :
  x ≅ y := {
  to := f;
  from := retract
}.
Next Obligation.
admit.
Defined.
Next Obligation.
admit.
Defined.

Program Instance Epic_Section_Iso
        {C : Category} {x y : C} `(s : @Section _ _ _ f) `(e : @Epic _ _ _ f) :
  x ≅ y := {
  to := f;
  from := section
}.
Next Obligation.
admit.
Defined.
Next Obligation.
admit.
Defined.

Class Functor {C D : Category} := {
  fobj : C -> D;
  fmap {x y : C} (f : x ~> y) : fobj x ~> fobj y;

  fmap_respects :> ∀ x y, Proper (equiv ==> equiv) (@fmap x y);

  fmap_id {x : C} : fmap (@id C x) ≈ id;
  fmap_comp {x y z : C} (f : y ~> z) (g : x ~> y) :
    fmap (f ∘ g) ≈ fmap f ∘ fmap g
}.
Delimit Scope functor_type_scope with functor_type.
Delimit Scope functor_scope with functor.
Open Scope functor_type_scope.

Coercion fobj : Functor >-> Funclass.

Notation "C ⟶ D" := (@Functor C%category D%category)
  (at level 90, right associativity) : functor_type_scope.
Notation "fmap[ F ]" := (@fmap _ _ F%functor _ _)
  (at level 9, format "fmap[ F ]") : morphism_scope.

Hint Rewrite @fmap_id : categories.

Program Instance Functor_Setoid {C D : Category} : Setoid (C ⟶ D) := {
  equiv := fun F G =>

    { iso : ∀ x : C, F x ≅ G x
    & ∀ (x y : C) (f : x ~> y),
        fmap[F] f ≈ from (iso y) ∘ fmap[G] f ∘ to (iso x) }
}.
Next Obligation.
admit.
Defined.

Program Instance fmap_iso `(F : C ⟶ D) :
  Proper (Isomorphism ==> Isomorphism) F.
Next Obligation.
admit.
Defined.

Program Definition Compose
        {C : Category} {D : Category} {E : Category}
        (F : D ⟶ E) (G : C ⟶ D) : C ⟶ E := {|
  fobj := fun x => fobj (fobj x);
  fmap := fun _ _ f => fmap (fmap f)
|}.
Next Obligation.
admit.
Defined.
Next Obligation.
admit.
Defined.

Notation "F ◯ G" := (Compose F%functor G%functor)
  (at level 40, left associativity) : category_scope.

Program Instance Compose_respects {C D E : Category} :
  Proper (equiv ==> equiv ==> equiv) (@Compose C D E).
Next Obligation.
admit.
Defined.

Section Transform.

Context {C : Category}.
Context {D : Category}.
Context {F : C ⟶ D}.
Context {G : C ⟶ D}.

Class Transform := {
  transform {x} : F x ~> G x;

  naturality {x y} (f : x ~> y) :
    fmap[G] f ∘ transform ≈ transform ∘ fmap[F] f;

  naturality_sym {x y} (f : x ~> y) :
    transform ∘ fmap[F] f ≈ fmap[G] f ∘ transform
}.

End Transform.
Delimit Scope transform_type_scope with transform_type.
Delimit Scope transform_scope with transform.
Open Scope transform_type_scope.

Notation "F ⟹ G" := (@Transform _ _ F%functor G%functor)
  (at level 90, right associativity) : transform_type_scope.

Notation "transform[ F ]" := (@transform _ _ _ _ F%transform)
  (at level 9, only parsing, format "transform[ F ]") : morphism_scope.
Notation "naturality[ F ]" := (@naturality _ _ _ _ F%transform)
  (at level 9, only parsing, format "naturality[ F ]") : morphism_scope.

Coercion transform : Transform >-> Funclass.

Ltac transform :=
  unshelve (refine {| transform := _ |}; simpl; intros).

Program Definition whisker_left {C D : Category}
        {E : Category} (X : D ⟶ E)
        {F G : C ⟶ D} `(N : F ⟹ G) : X ◯ F ⟹ X ◯ G := {|
  transform := fun x => fmap[X] (N x)
|}.
Next Obligation.
admit.
Defined.
Next Obligation.
admit.
Defined.

Section Fun.

Context {C : Category}.
Context {D : Category}.

Program Definition nat_equiv {F : C ⟶ D} {G : C ⟶ D} : crelation (F ⟹ G) :=
  fun n m => ∀ A, transform[n] A ≈ transform[m] A.

Hint Unfold nat_equiv.

Global Program Definition nat_equiv_equivalence {F : C ⟶ D} {G : C ⟶ D} :
  Equivalence (@nat_equiv F G).
admit.
Defined.

Global Program Instance nat_Setoid {F : C ⟶ D} {G : C ⟶ D} :
  Setoid (F ⟹ G) := {
  equiv := nat_equiv;
  setoid_equiv := nat_equiv_equivalence
}.

Global Program Definition nat_id {F : C ⟶ D} : F ⟹ F := {|
  transform := fun X => fmap (@id C X)
|}.

Global Program Definition nat_compose {F : C ⟶ D} {G : C ⟶ D} {K : C ⟶ D}
  (f : G ⟹ K) (g : F ⟹ G) : F ⟹ K := {|
  transform := fun X => transform[f] X ∘ transform[g] X
|}.
Next Obligation.
admit.
Defined.
Next Obligation.
admit.
Defined.

Global Program Definition nat_compose_respects
       {F : C ⟶ D} {G : C ⟶ D} {K : C ⟶ D} :
  Proper (equiv ==> equiv ==> equiv) (@nat_compose F G K).
admit.
Defined.

Global Program Definition Fun : Category := {|
  obj     := C ⟶ D;
  hom     := @Transform C D;
  id      := @nat_id;
  compose := @nat_compose;

  compose_respects := @nat_compose_respects
|}.

End Fun.

Notation "[ C , D ]" := (@Fun C D)
  (at level 90, right associativity, format "[ C ,  D ]") : category_scope.
Hint Unfold nat_equiv.
Set Universe Polymorphism.

Program Instance Diagonal {C : Category} (J : Category) : C ⟶ [J, C] := {
  fobj := fun x =>
    {| fobj := fun _ => x
     ; fmap := fun _ _ _ => id[x] |};
  fmap := fun _ _ f =>
    {| transform := fun _ => f |}
}.

Class Cone `(F : J ⟶ C) := {
  vertex_obj : C;
  vertex_map {x : J} : vertex_obj ~{C}~> F x;

  ump_cones {x y : J} (f : x ~{J}~> y) :
    fmap[F] f ∘ @vertex_map x ≈ @vertex_map y
}.

Theorem Cone_Transform {J : Category} {C : Category} (F : J ⟶ C) (d : C) :
  Diagonal J d ⟹ F ↔ { c : Cone F | vertex_obj = d }.
Proof.
  split; intros.
  -
 unshelve eexists.
    +
 unshelve econstructor; intros.
      *
 exact d.
      *
 apply X.
      *
 simpl.
        rewrite (naturality[X]); cat.
    +
 reflexivity.
  -
 transform; simpl; intros;
    destruct X; subst.
    +
 apply x0.
    +
 cat; apply ump_cones.
    +
 cat; symmetry; apply ump_cones.
Qed.
```

**Comment by ejgallego** [comment] 2020-02-24 17:37
@jwiegley actually this doesn't compile in 8.12 / master due to changes in the notation system; @herbelin I have a guess why but maybe you wanna have a look?

**Comment by herbelin** [comment] 2020-02-25 06:46
> @jwiegley actually this doesn't compile in 8.12 / master due to changes in the notation system; @herbelin I have a guess why but maybe you wanna have a look?

Indeed, master is proposing a different semantics for inheritance of implicit arguments through notations. In master, `transform[n]` inherits the implicit arguments of `transform`, so, `transform[n] A` should instead be written `transform[n] (x:=A)` (see PR #11120 for the discussion: the change is motivated by a simplification of the inheritance rules between notations and abbreviations, but, to be honest, I was actually missing examples on whether this was more intuitive than the other semantics or not, so your example is a good one: do we intuitively expect `A` to be implicit or not here?)

[Incidentally, this also shows a bug of #11120: `transform[n]` alone should inherits the implicit argument of `transform[n]` since it is maximal but it doesn't; I'm going to fix this even if the conclusion is to make the inheritance of implicit arguments policy through notations evolve further.]

In any case, after the four occurrences of `transform[_] _` are changed by adding a `(x:= )` around the argument, the undefined universe anomaly arrives.

**Comment by ppedrot** [comment] 2022-02-21 21:46
Duplicate of #14440.

**Closed by ppedrot** 2022-02-21 21:46 UTC
Labels: part: program, kind: anomaly, part: universes
