### ISSUE TITLE
Vscoq legacy broken

### ISSUE THREAD

**Issue by FissoreD** [coq/coq#19288] opened 2024-06-27 13:33 UTC
### Description of the problem

[This PR](https://github.com/coq/coq/pull/19040) broke Vscoq legacy in particular errors are not displayed anymore

@gares @thery

### Version of Coq where this bug occurs

8.20.0

### Last version of Coq where the bug did not occur

8.19.2

**Comment by gares** [comment] 2024-06-27 13:35
@SkySkimmer @proux01

**Comment by SkySkimmer** [comment] 2024-06-27 13:51
I don't see how I'm related to this.
Are there still maintainers for vscoq legacy?

**Comment by SkySkimmer** [comment] 2024-06-27 13:52
This is a vscoq legacy problem, not a coq bug and so cannot be blocker to a coq version.

**Comment by gares** [comment] 2024-06-27 13:58
The problem is that the PR was merged before having the UIs implement the fix, and I believe there was an agreement to not break the legacy protocol.

Call it blocker or not, I think we should either revert the PR or make it so that by the release of 8.20 the other UIs are not broken (vscoq legacy, coqtail, dunno what else)

CC also @herbelin the author of the PR

**Comment by ejgallego** [comment] 2024-06-27 13:59
I agree with @SkySkimmer , this is up to VSCoq folks to fix, AFAICT we never agreed on a freeze for the XML protocol.

If VSCoq legacy is unmaintained that's a different problem.

**Comment by gares** [comment] 2024-06-27 14:01
I don't this any interface using the legacy protocol is unmaintained, but I'm not so sure their maintainers were properly informed of the breakage.

**Comment by ejgallego** [comment] 2024-06-27 14:02
Fix should be pretty easy tho, so for sure it is more efficient to fix it than to keep discussing about XML protocol policy.

**Comment by ejgallego** [comment] 2024-06-27 14:03
> I don't this any interface using the legacy protocol is unmaintained, but I'm not so sure their maintainers were properly informed of the breakage.

It is pretty clear they were if you read the PR.

**Comment by proux01** [comment] 2024-06-27 14:09
In any case ping @thery for vscoq legacy and @whonore for coqtail

**Comment by whonore** [comment] 2024-06-27 15:04
Coqtail has already updated to the protocol change.

**Comment by herbelin** [comment] 2024-06-27 18:20
> I'm not so sure their maintainers were properly informed of the breakage.

See [this information](https://github.com/coq/coq/pull/19040#issuecomment-2144690546) from you (we could have insisted though).

I'm not expert in typescript, but would the following patch fixes the issue:
```typescript
diff --git a/server/src/coqtop/xml-protocol/deserialize.base.ts b/server/src/coqtop/xml-protocol/deserialize.base.ts
index 28cecdd..9b48514 100644
--- a/server/src/coqtop/xml-protocol/deserialize.base.ts
+++ b/server/src/coqtop/xml-protocol/deserialize.base.ts
@@ -471,8 +471,8 @@ export abstract class Deserialize {
           return check(value.$name, {
             status: 'fail',
             stateId: value.$children[0],
-            message: value.$children[1] || "",
-            location: {start: +value.$.loc_s, stop: +value.$.loc_e},
+            location: value.$children[1],
+            message: value.$children[2] || "",
           } as FailValue);
       case 'ltacprof_tactic':
         return check(value.$name, {
```

By the way, didn't you have ill-located errors in vscoq1 too?

**Comment by ejgallego** [comment] 2024-06-27 19:01
@herbelin , in this case I'd suggest that you test in the code for the shape of the XML payload.

Then, you can case on protocol version and have a single codebase work for before and after your patch.

**Comment by herbelin** [comment] 2024-06-27 19:22
> test in the code for the shape of the XML payload.

I don't know how to case on the protocol version. I tried casing on the format though and updated the patch. (This is done blindly, I don't know how to test typescript code.)

**Comment by ejgallego** [comment] 2024-06-27 19:33
Yes, I mean casing on the format, sorry! Usually one can check if a field is present, that means the new message is incoming.

**Comment by herbelin** [comment] 2024-06-27 20:03
If I understand correctly, `export interface FailValueNode` defines a "type". We would also need this type to be dependent on the version. I suspect that this would require pre-processing though?? Or, maybe, as it seems to be used only in `isFailValue` which looks only at the tag, it does not matter??

**Comment by ejgallego** [comment] 2024-06-27 21:09
@herbelin didn't look at the code but often you can make an intersection type in typescript using `|` , example `type PpString = string | Pp`

**Comment by Zimmi48** [comment] 2024-06-28 10:10
As was already discussed, this is a VsCoq1 bug and not a Coq bug, so this issue should be closed and an issue should be opened on the VsCoq repo.

Advertising this change only through the changelog would have been insufficient, but in that case, there was an attempt to contact someone (@thery) from the VsCoq1 maintenance team. However, this appears to have been missed. We should probably have pinged @huynhtrankhanh and @Blaisorblade as well, I suppose.

**Comment by thery** [comment] 2024-06-28 13:02
Ok I've createad a [PR](https://github.com/coq-community/vscoq/pull/811). How can I test if everything is ok?

**Comment by thery** [comment] 2024-06-28 14:58
@FissoreD  normally there is a new release of VsCoq Legacy (0.4.1), can you check if your problem disappears with this release.

**Closed** 2024-06-30 08:25 UTC

**Comment by FissoreD** [comment] 2024-07-01 07:51
> @FissoreD normally there is a new release of VsCoq Legacy (0.4.1), can you check if your problem disappears with this release.

@thery Now it works ! Thank you
