### ISSUE TITLE
Autocompletion in coqide not working

### ISSUE THREAD

**Issue by Alizter** [coq/coq#11354] opened 2020-01-02 15:34 UTC
#### Description of the problem

Sometimes I get some autocompletion, but most of the time it is missing. This only started happening when the ide moved to gtk3. I don't really know how to reproduce this other than the fact that every time I have tried recompiling the ide it happens.

I'd be interested to know if anybody else has this issue also, since I would be surprised if it is just me. 

If I start a new file, I can see some autocompletion but it is usually really misalgined like in #9945. 

What information about my xserver do you need?

#### Coq Version
```
Welcome to CoqIDE, an Integrated Development Environment for Coq
You are running The Coq Proof Assistant, version 8.12+alpha (December 2019)
```
Here is the commit hash I built coq and the ide with:

```
3a9cab5e6df0f4d55520a17f6cb56067b68da92a
```

**Comment by ppedrot** [comment] 2020-01-02 15:37
FTR, the fix for #9945 was not merged, so I think that this is a duplicate of the former.

**Comment by ppedrot** [comment] 2020-01-17 11:36
Duplicate of #9945

**Comment by ppedrot** [comment] 2020-01-17 11:37
@Alizter please open fresh issues if you encounter problems after the merge of #11400, to clearly separate the underlying implementations.

**Closed by ppedrot** 2020-01-17 11:36 UTC
Labels: part: IDE
