### ISSUE TITLE
Timing tests on Travis CI fail

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#8324] opened 2018-08-26 09:02 UTC
Timing Tests in Travis CI seem to fail (at least sometimes) without doing relevant changes.

```
cat A.v.timing.diff
After     | Code                                                | Before    || Change    | % Change
---------------------------------------------------------------------------------------------------
0m01.33s  | Total                                               | 0m01.31s  || +0m00.02s | +1.59%  
---------------------------------------------------------------------------------------------------
0m00.502s | Chars 069 - 162 [Definition~foo0~:=~Eval~comp~i...] | 0m00.489s || +0m00.01s | +2.65%  
0m00.443s | Chars 163 - 208 [Definition~foo1~:=~Eval~comp~i...] | 0m00.449s || -0m00.00s | -1.33%  
0m00.384s | Chars 000 - 026 [Require~Coq.ZArith.BinInt.]        | 0m00.377s || +0m00.00s | +1.85%  
0m00.007s | Chars 027 - 068 [Declare~Reduction~comp~:=~vm_c...] |    N/A    || +0m00.00s | ∞       
   N/A    | Chars 027 - 068 [Declare~Reduction~comp~:=~nati...] | 0m00.s    || +0m00.00s | N/A     
--- A.v.timing.diff.desired.processed	2018-08-25 14:16:28.000000000 +0000
+++ A.v.timing.diff.processed	2018-08-25 14:16:28.000000000 +0000
@@ -4,6 +4,6 @@
 After | Code | Before || Change | % Change
 ms | Chars - 26 [Require~CoqZArithBinInt] | ms || -ms | -%
 ms | Chars 163 - 28 [Definition~foo1~:=~Eval~comp~i] | ms || -ms | -%
-ms | Chars 27 - 68 [Declare~Reduction~comp~:=~vm_c] | N/A || -ms | N/A
+ms | Chars 27 - 68 [Declare~Reduction~comp~:=~vm_c] | N/A || -ms | -%
 ms | Chars 69 - 162 [Definition~foo~:=~Eval~comp~i] | ms || -ms | -%
 ms | Total | ms || -ms | -%
==========> FAILURE <==========
```

See https://travis-ci.org/coq/coq/jobs/420496623. The corresponding PR is #8322 

P.S:: wasn't there a label part:CI?

**Comment by Zimmi48** [comment] 2018-08-27 08:45
Thanks for the report, but this is a duplicate of #5675.

**Closed by Zimmi48** 2018-08-27 08:45 UTC
Labels: ci-failure

**Comment by MSoegtropIMC** [comment] 2018-08-27 09:13
I am not so sure it is the same. In my case the issue is that the "before" time is entirely missing. In #5675 the before time is there, just the delta is very large.

**Comment by Zimmi48** [comment] 2018-08-27 09:29
Maybe not absolutely the same but #5675 has been used to gather all the issues related to this timing test.
