### ISSUE TITLE
`Set Proof Using Clear Unused.` fails to clear unused let-bound definitions

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8154] opened 2018-07-25 17:21 UTC
#### Version

8.8.1

#### Description of the problem

I think this behavior is wrong:
```coq
Set Proof Using Clear Unused.
Section foo.
  Variable (x : nat).

  Let y := x.

  Lemma foo : x = 0 + x.
  Proof using Type. change x with y. (* should not succeed *) reflexivity. Qed.
```
In particular, `Proof using y.` is a valid statement, and so `Proof using Type.` should clear `y` if `y` is not a dependency of the type.

Possibly related to #8153.

**Comment by SkySkimmer** [comment] 2018-08-22 14:32
9ea8867a0fa8f2a52df102732fdc1a931c659826
>- Section variables with a body (let-in) are pulled in automatically
  since they are safe to be used (add no extra quantification)

When using `Proof using` this also adds them to the variables considered to be used by the definition.

This makes #8153 a duplicate of this.

**Comment by JasonGross** [comment] 2018-08-22 15:10
Note that #8153 is significantly worse behavior. While permitting the use of let-bound identifiers not directly mentioned in `Proof using` is a design decision (one that I disagree with), raising an error claiming that I cannot use a theorem because I have cleared a let-bound identifier that it doesn't actually use is obviously wrong, breaks tactic automaton that should be perfectly fine, and can be quite painful.

cc @gares

**Comment by gares** [comment] 2018-08-24 06:44
I'm not so sure I understand this bug report. The behavior follows the doc. The behavior does not fix your needs. Is this is a sort of feature wish?

**Comment by JasonGross** [comment] 2018-08-24 14:58
Sure, you can consider this a feature wish.  But I think it is mandated by #8153.

**Comment by JasonGross** [comment] 2018-08-24 15:04
I guess it is not quite mandated by #8153.  In principle, the dependency analysis could be different for "must not use" (things that should be cleared here) vs "must be available for use" (things that, if cleared, should make `rewrite` and similar tactics error).

**Comment by andres-erbsen** [comment] 2021-10-01 13:20
Has this option gone away? On 8.13.12 I get `There is no flag or option with this name: "Proof Using Clear Unused".`.

**Comment by SkySkimmer** [comment] 2021-10-01 13:21
yes 2e78edb4b8212cc5ab394fde168fc5241ad01660

**Closed** 2021-10-01 13:22 UTC
Labels: part: sections
