### ISSUE TITLE
Windows 32 bit build is broken since native floats were added

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#11176] opened 2019-11-24 23:19 UTC
Since #9867 , the windows build for 32bit is broken, example:
https://coq.gitlab.io/-/coq/-/jobs/359738453/artifacts/artifacts/buildlogs/coq-local-configure_err.txt
```
Detected non IEEE-754 compliant architecture (or wrong rounding mode). Use of Float is thus unsafe.
Configuration script failed!
```
this seems like a blocker bug for 8.11

**Comment by ppedrot** [comment] 2019-11-25 07:53
Summoning @erikmd @proux01 @silene

**Comment by silene** [comment] 2019-11-25 08:30
Is there a way to access that machine? The log does not contain enough information to know what failed.

**Comment by proux01** [comment] 2019-11-25 09:03
This might be due to the following in `configure.ml`
```
tryrun "cc" (["-march=native"; "-dM"; "-E"]
￼                  @ cflags_sse2
￼                  @ [coqtop/"kernel/byterun/coq_interp.h"] (* any file *)) in
```
but indeed, without knowing more, it will be hard to fix.

Auxiliary question : should this build be added to the CI ?

**Comment by Zimmi48** [comment] 2019-11-25 09:05
>Is there a way to access that machine? The log does not contain enough information to know what failed.

I think things are cleaned up at the end of builds, but this can be switched off, and then the machine can be accessed. The list of machines is at https://ci.inria.fr/project/coq/slaves.

FWIW @ejgallego only pointed to the (relevant) configure error log but we have more than this:
- https://gitlab.com/coq/coq/-/jobs/359738453
- https://gitlab.com/coq/coq/-/jobs/359738453/artifacts/browse/artifacts/buildlogs/

The machine was INRIACI-windows-untrusted2 whose architecture is amd64. The 32-bit build is buiild on normal 64-bit machines, on which the 64-bit build succeeded.

**Comment by Zimmi48** [comment] 2019-11-25 09:11
> Auxiliary question : should this build be added to the CI ?

It is already part of the CI. It is only run on main branches (like master) and not on PRs by default because this is an expensive build that is not useful most of the time (and we have few Windows runners). On master, it has indeed been failing for three weeks, since this PR was merged. It is awful that it is only now that somebody notices!

**Comment by proux01** [comment] 2019-11-25 12:19
I can reproduce it locally, I'll try to come up with a fix.

**Closed** 2019-11-26 18:52 UTC
Labels: priority: blocker
