### ISSUE TITLE
Anomaly when wrapping let in within unshelve.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6209] opened 2017-11-21 13:58 UTC
#### Version

Present in all versions from 8.5 to today's master.

#### Description of the problem

```
Goal True. unshelve (let x := I in idtac).
```

```
Anomaly "File "plugins/ltac/tacinterp.ml", line 1132, characters 29-35:
Assertion failed."
```

https://github.com/coq/coq/blob/d0c42fea9edfef645a822e9f12d475c205f93932/plugins/ltac/tacinterp.ml#L1126-L1132

**Comment by ppedrot** [comment] 2017-11-21 14:23
Duplicate of #2800.

**Closed by ppedrot** 2017-11-21 14:23 UTC
Labels: kind: anomaly

**Comment by Zimmi48** [comment] 2017-11-21 14:36
I had searched for the anomaly in existing issues but missed this one, probably because the line and column numbers keep changing. It would be easier to find if this line used a `failwith` with a specific message instead of an `assert false` that we know very well can be reached.
And in fact, I don't understand why at least the anomaly hasn't been fixed already. OK, making ML-tactics handle non-value argument may be difficult but leaving `assert false` that we know can be reached in the code for 5 years is a bit much I think.

**Comment by ppedrot** [comment] 2017-11-21 15:30
@Zimmi48 Just for the record, it's actually not that hard to fix the tactic case alone, but the easy solution does not scale to composition with types like `tactic_opt` and `tactic_list`. While the latter seems pretty much unused, the former is indeed present in Coq standard tactic implementations.

**Comment by Zimmi48** [comment] 2017-11-27 19:14
Duplicate of #2800
