### ISSUE TITLE
Preferences dialog crashes CoqIDE on Mac M1

### ISSUE THREAD

**Issue by alexei-iliasov** [coq/coq#16343] opened 2022-07-23 21:02 UTC
#### Description of the problem

The platform works quite well *so far* on MacOS 12.4 (M1 Pro) with one annoying exception of preferences crashing the tool. Hope something simple in the UI

#### Coq Version

8.15-2022.04

**Comment by ppedrot** [comment] 2022-07-24 18:53
Duplicate of #16136

**Comment by orilahav** [comment] 2022-07-27 07:54
Duplicate of https://github.com/coq/coq/issues/15486 as well

**Closed** 2022-07-29 00:09 UTC
