### ISSUE TITLE
case mismatch for plugins/extraction/ExtrOcaml*.v

### ISSUE THREAD

**Issue by erikmd** [coq/coq#10930] opened 2019-10-22 10:07 UTC
#### Description of the problem

When implementing extraction for primitive floats in #9867 just now, we noticed that all `ExtrOcaml*.v` files in https://github.com/coq/coq/blob/master/plugins/extraction/ (e.g. ExtrOcamlBasic.v) have a lowercase `c`, unlike this one: https://github.com/coq/coq/blob/master/plugins/extraction/ExtrOCamlInt63.v 

Should this be uniformized?

#### Coq Version

`coq >= 8.10`

**Comment by proux01** [comment] 2019-10-30 15:37
This is a duplicate of https://github.com/coq/coq/issues/10706.

**Closed by proux01** 2019-10-30 15:37 UTC
Labels: kind: question, part: extraction
