### ISSUE TITLE
`constr:(ltac:(let v := tac in refine v))` should not be almost 2x slower than `tac`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16412] opened 2022-08-27 06:30 UTC
#### Description of the problem

In https://github.com/mit-plv/rewriter/pull/54, replacing `tac` with `constr:(ltac:(let v := tac in refine v))` doubles the build time of Rewriter/Rewriter/Examples/PerfTesting/SieveOfEratosthenes.v from about 30s to about 1m.  Presumably this is due to evar allocation under binders?

This is almost a blocking issue for porting performance-critical code from Ltac1 to Ltac2, because it makes it essentially impossible to port constr-generating code incrementally without introducing massive slowdowns.  Can anything be done about this? (cc @ppedrot)

#### Coq Version

8.15

**Comment by SkySkimmer** [comment] 2022-08-27 10:01
Where is the relevant change in that 150 line PR?

**Comment by Janno** [comment] 2022-08-27 10:04
I suspect Jason means this here: (https://github.com/mit-plv/rewriter/pull/54/files#diff-71f355c0486a7984d2aaac4479c7daaae11236d46e819a1d0a56036494a112feR338)
```Coq
      | ?term => constr:(ltac:(let f := ltac2:(term |- Control.refine (fun () => reify_preprocess_extra [] (Ltac1.get_to_constr term))) in
                               f term))
```

I've played around with this a fair bit this morning and I think the only way I see to improve it is tu use `Std.exact_no_check` instead of `Control.refine`. `constr:()` typechecks the result anyway so there is no need to waste extra time checking it in Ltac2. But the awkwardness around returning constrs back to Ltac1 is definitely real and I could not find a single way of doing it without solving a goal on the Ltac2 side.

**Comment by JasonGross** [comment] 2022-08-27 13:52
@Janno That's the relevant bit in Ltac2, but the slowdown is visible already in Ltac1 at https://github.com/mit-plv/rewriter/pull/54/commits/da554f755526ccb08475ed3ac1e0c43eae704dbe:
```diff
                           end in
            (*let B := lazymatch type of b with forall x, @?B x => B end in*)
            reify_preprocess rec_val (*(@Let_In A B a b)*)
-      | ?term => reify_preprocess_extra term
+      | ?term => constr:(ltac:(let v := reify_preprocess_extra term in refine v))
       end.

     Ltac reify_ident_preprocess term :=
       let __ := Reify.debug_enter_reify_ident_preprocess term in
+      let reify_ident_preprocess_extra term := constr:(ltac:(let v := reify_ident_preprocess_extra term in refine v)) in
       lazymatch term with
       | Datatypes.S => reify_ident_preprocess Nat.succ
       | @Datatypes.prod_rect ?A ?B ?T0
```
I will see if using `exact_no_check` instead of `refine` changes the performance profile

**Comment by JasonGross** [comment] 2022-08-27 14:34
@Janno replacing `refine` with `exact_no_check` results in the tactic failing with `Error: Cannot infer an internal placeholder of type "Type".`, so this is not a way forward.

**Comment by Janno** [comment] 2022-08-29 14:22
Oh, I think I know why. The temporary goal does not even have a determined type at the time of `exact_no_check`. You could try `lazy_match! goal with | [ |- ?g ] => unify g the_type end` before you use `exact_no_check`. That assumes the type is statically known and doesn't require another retyping step. Otherwise we'd be doing the same work that `refine` does.

**Comment by SkySkimmer** [comment] 2022-08-29 14:32
If you like hacks you could also unify the type with Prop then exact_no_check. It might only fail if the term gets fed to pattern_of_constr without getting evar normalized.

**Comment by SkySkimmer** [comment] 2023-07-11 09:39
Is this related to https://github.com/coq/coq/issues/13977 (the issue asks for uconstr, but the underlying problem is `constr` and `open_constr` doing evar normalization)?

**Comment by JasonGross** [comment] 2023-07-11 15:14
I would buy that the underlying issue is evar normalization.  My other guess is that the expensive operation is evar allocation under many binders.  I guess these can be separated by seeing how long it takes to do `let dummy := open_constr:(_) in unify dummy I` vs the above or something.

**Comment by SkySkimmer** [comment] 2023-10-13 14:56
If using https://github.com/coq/coq/pull/17704 (you can backport pretty easily if needed I think) and open_constr instead of constr works then we know the cause and the fix.

**Comment by ppedrot** [comment] 2024-01-16 13:26
@JasonGross is this fixed on master?

**Comment by SkySkimmer** [comment] 2024-02-22 15:16
ping @JasonGross

**Comment by JasonGross** [comment] 2024-02-22 19:45
Sorry, still haven't found time

**Comment by SkySkimmer** [comment] 2024-09-14 13:27
Probably fixed

**Closed by SkySkimmer** 2024-09-14 13:27 UTC
Labels: kind: performance, part: ltac, part: ltac2
