### ISSUE TITLE
tampering with discharged assumptions of "in" tactical

### ISSUE THREAD

**Issue by jeremydaw** [coq/coq#10405] opened 2019-06-20 07:30 UTC
#### Description of the problem

I'm trying to rewrite a hypothesis in doing a proof, using the
rewrite -> thm
tactic,  but it fails with the message
Ltac call to "rewrite (ssrrwargs) (ssrclauses)" failed.
tampering with discharged assumptions of "in" tactical

This error message doesn't seem to be documented (I'm not sure exactly where I should look to find it, but a web search for the words
"tampering with discharged assumptions"
produces just one result
 https://github.com/math-comp/math-comp/issues/16

#### Coq Version
 version 8.8.2 (January 2019)
compiled on Jan 15 2019 15:19:52 with OCaml 4.02.3

OS is Linux cecs-042179 4.4.0-145-generic

**Comment by gares** [comment] 2019-06-20 10:25
Is thm a theorem about equality or about double implication?

**Comment by RalfJung** [comment] 2020-04-03 13:54
The error sounds like https://github.com/coq/coq/issues/12011, but that does not make any sense with `->`.

@jeremydaw do you have a self-contained example to reproduce the problem?

**Comment by Blaisorblade** [comment] 2020-04-23 17:05
I'm taking the liberty of closing as duplicate of #12011, till evidence comes it's not a duplicate. Somebody could grep the sources for this error message to gain more confidence the error is specific to ssreflect rewrite.

**Closed by Blaisorblade** 2020-04-23 17:05 UTC
Labels: kind: documentation, part: ssreflect
