### ISSUE TITLE
Program Fixpoint causes kernel anomaly

### ISSUE THREAD

**Issue by xuanruiqi** [coq/coq#9581] opened 2019-02-15 03:18 UTC
#### Description of the problem

I get `Anomaly "grounding a non evar-free term".` when using `Program` to define some well-founded recursive functions. I can't pinpoint the exact source of the problem, but here is a [file](https://github.com/affeldt-aist/succinct/blob/program_bug/dynamic_dependent_program.v) that throws this anomaly upon trying to generate obligations for `ddelete`.

If I switch to 8.9.0, then it throws a seemingly related anomaly: "the kernel does not support existential variables", this time upon finishing (or admitting) all obligations of `ddelete`. The same code requires a little modification (mostly renaming automatically-generated assumptions) to work under 8.9.0, and the modified [file](https://github.com/affeldt-aist/succinct/blob/program/dynamic_dependent_program.v) is here.

Then, I switched to 8.8.2, and found the same anomaly thrown. I have not tried yet earlier versions, but doubtful it would work.

#### Coq Version
`master`, 8.9.0 & 8.8.2

**Comment by xuanruiqi** [comment] 2019-02-15 03:45
8.8.0 also suffers from the same issues.

**Comment by ejgallego** [comment] 2019-02-15 08:48
It is strange that you see that anomaly in 8.8 as it was introduced in 8.9

**Comment by xuanruiqi** [comment] 2019-02-15 08:49
Let me recheck.

**Comment by xuanruiqi** [comment] 2019-02-15 09:01
> It is strange that you see that anomaly in 8.8 as it was introduced in 8.9

Only in dev (`master`) Coq do I get the anomaly `"grounding a non evar-free term".` 

8.9.0-release, 8.8.2 and 8.8.0 all report `"the kernel does not support existential variables"`, which has been in Coq for quite a while. 

I suspect the two anomalies are somehow related, but I don't know enough about inner workings of Coq.

**Comment by ejgallego** [comment] 2019-02-15 10:40
Yup, in master you get a debug-check, that is removed in the official release and indeed was revealing a bug as you can see.

The source of your problem is likely some hole not properly filled. Try to workaround it by giving some more explicit terms.

**Comment by xuanruiqi** [comment] 2019-02-15 19:26
I'm not sure I have control over that, though. If I understand correctly, Program should have been filling all the holes, so probably a bug in Program?

**Comment by xuanruiqi** [comment] 2019-02-15 19:58
Also, weirdly `Program` can define `ddelete_func`, but not `ddelete`.

**Comment by maximedenes** [comment] 2019-02-19 12:54
@mattam82 can you be the assignee?

**Comment by mattam82** [comment] 2019-02-19 13:31
Hmm, that's quite a big program! If `ddelete_func` is defined then surely `ddelete` sould be, as it is just a wrapper doing the call to the fixpoint combinator. Let me try to reproduce.

**Comment by mattam82** [comment] 2019-02-19 13:32
With which version does the program_bug branch compile with?

**Comment by xuanruiqi** [comment] 2019-02-19 20:15
program compiles with any released version, program_bug compiles only with master. (BTW, in dev, the naming of extracted hypothesis are named differently as in 8.8 and 8.9.0, breaking old code).

**Comment by mattam82** [comment] 2019-02-19 20:22
Aha, then @maximedenes ‘s refactoring did change something.

**Comment by xuanruiqi** [comment] 2019-02-19 20:24
BTW, I mean they compile up to the end of the last `Program Fixpoint`. In no version does the last `Program Fixpoint` work.

**Comment by xuanruiqi** [comment] 2019-02-21 08:32
By the way, for the naming changes, should I open a new issue to address that? It would break a lot of old code that use `Program` for sure.

**Comment by xuanruiqi** [comment] 2019-03-08 20:02
Hello all! Any updates to this in the mean time?

**Comment by mattam82** [comment] 2019-03-08 21:51
Hi @xuanruiqi, I'll try to reproduce next week. In the meantime, it could also be because of the presence of side-effects that are not properly substituted. It might be that one of the obligations uses an induction scheme that is generated on the fly (you can inspect using Show Proof) or a use of `abstract`. I'm curious, what does `exact` do?

**Comment by mattam82** [comment] 2019-03-08 21:53
@xuanruiqi yes, the naming changes should be addressed. @maximedenes  did his best threading the program_mode to ensure names would be generated the same way but we might have missed a corner case.

**Comment by xuanruiqi** [comment] 2019-03-08 23:35
> I'm curious, what does exact do?

Ssreflect `exact` more or less just tries to solve the current goal using `done`. An explanation is [here](https://coq.inria.fr/refman/proof-engine/ssreflect-proof-language.html#terminators-ssr); you see it's mostly equivalent to `done` unless there's an assumption in the goal.

`done` is implemented [here](https://github.com/coq/coq/blob/v8.9/plugins/ssr/ssreflect.v), and it seems that it just tries to search extensively for a proof, so it's a bit like `tauto` (or a weaker version of Adam Chlipala's `crush`; it doesn't try very hard to split goals).

I don't think either of the two things you've mentioned (generating induction scheme on the fly, or using `abstract`) happen, but I might be wrong. I'll check in the meantime.

**Comment by mattam82** [comment] 2019-03-09 15:16
I found the cuprit. It should be an error rather than an anomaly, but Program Fixpoint does not support existential variables in the type of the fixpoint. Here one is generated by the `if c is Black then d > 0 else true` which gets elaborated to a match by Program, inserting an evar of type `c <> Black` for the second branch, which is not solved until we generate obligations. Before doing that we do an EConstr.of_constr that raises the anomaly, but we should rather check if there are evars in the type and report the error to the user in that case. Easy workaround is to either define an auxiliary 
`Definition blacktest c d := if c is Black then d > 0 else true.` or use an `if c is Black return _ then ...` to avoid the generation of this existential variable.

**Comment by mattam82** [comment] 2019-03-12 14:18
@xuanruiqi does that fix your problem entirely?

**Comment by xuanruiqi** [comment] 2019-03-12 16:59
Yes, it does. Thanks Matthieu!

**Comment by ejgallego** [comment] 2020-06-05 00:42
I think this bug still applies.

**Comment by xuanruiqi** [comment] 2020-06-17 00:35
I haven't re-checked this on latest Coq yet; if I find time I'll check to see if the same error is still raised.

**Comment by herbelin** [comment] 2024-05-06 16:44
I did not test the example but I guess that the remark "Program Fixpoint does not support existential variables in the type of the fixpoint" (an `if` in the binders of `ddelete` from the example) is addressed by #18920 and that the issue can be closed.

**Closed by herbelin** 2024-05-06 16:44 UTC
Labels: part: program, kind: anomaly
