### ISSUE TITLE
Cannot find a physical path bound to logical path matching suffix

### ISSUE THREAD

**Issue by yunoJ** [coq/coq#9942] opened 2019-04-10 09:46 UTC
version: 8.9.0
OS: ubuntu
IDE: coqide
install package manager: opam

Hi, I came up with a new problem which looks common among many beginners. But I couldn't find questions with the above environment. 

I've been getting error message

Cannot find a physical path bound to logical path matching suffix <> and prefix LF.

The line causing this error is "From LF Require Export Basics."

I've been following Software Foundations and have compiled Basics.v without any problem. My _coqproject file has line -Q . LF as is uploaded on the website.

How can I get rid of this error?

Thank you in advance :)

**Comment by Zimmi48** [comment] 2019-04-10 11:19
> My _coqproject file has line -Q . LF as is uploaded on the website.

And it is correctly cased (`_CoqProject` as in the version in the archive)?

Can you verify that it is the same name in the Edit > Preferences > Project menu?

The only way I can reproduce this is if for some reason (such as a casing problem), CoqIDE doesn't pick up the options set in `_CoqProject`.

**Comment by yunoJ** [comment] 2019-04-10 12:50
The file name is _CoqProject and is located in the same folder (lf) as other .v files. 

And yes the Eidt > Preferences > Project menu has _CoqProject as the default name for project file. 

I tried "make clean" just in case that I performed "make" from the terminal and the coq version I used in the terminal is different from the one being used in my coqide. 

I did edit Basic.v file to solve the examples left for the students to take a loot at. Maybe this is causing the problem? The Basic.v compiles without error though.

**Comment by ejgallego** [comment] 2019-04-10 13:04
> I tried "make clean" just in case that I performed "make" from the terminal and the coq version I used in the terminal is different from the one being used in my coqide.

That's going to be a problem for sure. Be sure you are not using Coq from apt [uninstall it indeed]

**Comment by yunoJ** [comment] 2019-04-10 13:36
By using coq from apt do you mean running coq in terminal? As I stated above I'm using coqide so I don't think I'm suing coq from apt. 

 I performed "make clean" just to start from scratch again. Then I compiled Basic.v using coqide and so that my Induction.v can import from Basic. 

Can you elaborate more on "make clean" causing the problem?

**Comment by yunoJ** [comment] 2019-04-14 16:05
Hello, I downloaded the whole archive again from SF and compiled Basics.v and the error message still pops up.
I would really appreciate it if anyone can solve the problem.
@ejgallego what do you mean by using Coq from apt?

**Comment by SkySkimmer** [comment] 2019-04-14 16:09
How did you compile? `make Basics.vo`?

**Comment by yunoJ** [comment] 2019-04-14 16:13
no I used compile buffer in coqide.

**Comment by SkySkimmer** [comment] 2019-04-14 16:28
>The line causing this error is "From LF Require Export Basics."

In what file is this line? One of the other LF files?

**Comment by yunoJ** [comment] 2019-04-14 16:31
Yes, it's induction.v in LF.

**Comment by SkySkimmer** [comment] 2019-04-14 17:41
Can't reproduce. Steps I tried:
- download & unpack https://www.cis.upenn.edu/~bcpierce/sf/lf-current/lf.tgz to /tmp/lf 
- coqide /tmp/lf/Basics.v, compile buffer
- coqide /tmp/If/Inductive.v, step forward: Require Basics succeeds, rest of file also succeeds

**Comment by yunoJ** [comment] 2019-04-15 00:54
Stull doesn't work...

**Comment by yunoJ** [comment] 2019-04-15 01:33
@SkySkimmer  thanks for the reply but the message I get after following your steps is 

tmplf/Basics.vo contains library Basics and not library LF.Basics

**Comment by Zimmi48** [comment] 2019-04-15 06:31
I think that's what it did in Coq 8.6. Are you really sure that you are using CoqIDE from opam and not installed with Ubuntu's package manager? Can you double check the version number (About menu in CoqIDE)?

**Comment by Zimmi48** [comment] 2019-04-15 07:52
I confirm that I could reproduce the exact same problem by following these steps with Coq 8.6, but that it is fixed in Coq 8.7-Coq 8.9.

When running Compile Buffer from CoqIDE, the command used to compile is displayed. In 8.6, `coqc` received a useless `-I` option. Starting with 8.7, it receives the right `-Q` option, coming from `_CoqProject`.

Given that all the recent versions of Ubuntu, including the latest LTS, have Coq 8.6 in their installable packages, I'm pretty confident that the OP accidentally installed CoqIDE from there and that this explains the observed behavior. So closing. We can still reopen if I happened to be wrong.

**Closed by Zimmi48** 2019-04-15 07:52 UTC

**Comment by yunoJ** [comment] 2019-04-15 11:05
I double checked the version and it turned out that I was using 8.6. Sorry for the inconvenience and thanks for the replies.

**Comment by Zimmi48** [comment] 2019-04-15 11:27
No worries :wink: 

Just FTR when using Coq 8.6, just use `make` and avoid the "Compile Buffer" function.

**Comment by umabalaji** [comment] 2020-12-26 00:04
Hi i come up with an error message that
"Cannot find a physical path bound to logical
path matching suffix Kami.Lib." if i compile my file in kami. Please find the solution

**Comment by Zimmi48** [comment] 2020-12-26 18:24
>Please find the solution

Please don't use the bug tracker as a support system. You have plenty of options to ask for help that are listed in https://coq.inria.fr/community. In your case, I would recommend Zulip because it looks like people will need to ask additional information before they can help you.
