### ISSUE TITLE
Coq 8.18 Program Definition bug (also interacts with Classes.SetoidClass in unexpected ways)

### ISSUE THREAD

**Issue by elefthei** [coq/coq#18850] opened 2024-03-26 21:18 UTC
### Description of the problem

This is a two in one bug. In my reproducible example if you comment out the `Classes.SetoidClass` import you get an error:
```
Error: not found in table: core.JMeq.type
```

But if you leave the import you get another error
```
Error:
Anomaly
"File "kernel/constr.ml", line 1485, characters 26-32: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

Neither of those is good behavior afaik.

### Small Coq file to reproduce the bug

```coq
From Coq Require Import
  Fin
  Classes.SetoidClass. (* comment out for different error message *)

Notation fin := t.

Program Definition next_fin {n}: fin (S n) -> fin (S n) :=
  fix loop (f : fin (S n)) : fin (S n) :=
    match f with
    | F1 => F1
    | FS f' => match f' with
              | F1 => F1
              | FS _ => FS (loop f')
              end
    end.
```

### Version of Coq where this bug occurs

8.17 - master

### Last version of Coq where the bug did not occur

<= 8.16

**Comment by SkySkimmer** [comment] 2024-03-29 12:41
Duplicate of https://github.com/coq/coq/issues/18680

**Closed by SkySkimmer** 2024-03-29 12:41 UTC
Labels: kind: bug
