### ISSUE TITLE
Goal diff fail with string mismatch in some occasions

### ISSUE THREAD

**Issue by dramforever** [coq/coq#10326] opened 2019-06-06 18:15 UTC
#### Description of the problem

Put this into CoqIDE, enable goal diff (either added or added+removed), and run whole document:

```coq
Require Import Omega.

Goal True.
  apply Decidable.dec_not_not.
```

CoqIDE fails to display the new goal, and gives this error message

```plain
Anomaly "Uncaught exception Pp_diff.Diff_Failure("string mismatch, shouldn't happen")."
Please report at http://coq.inria.fr/bugs/.
```

Somehow the first line needs to be `Omega`. Just importing `Decidable` doesn't trigger this problem.

#### Coq Version

8.9.1

**Comment by Zimmi48** [comment] 2019-06-07 07:38
cc @jfehrle

**Comment by jfehrle** [comment] 2019-06-07 07:53
@dramforever I just tried this with CoqIDE 8.9.  It is working fine for me.  What version are you using?  What platform are you on?  It is possible some of the library files got modified?  Diffs are turned on even though nothing is highlighed here.

What other examples do you have?

![image](https://user-images.githubusercontent.com/1253341/59089146-b2dc3e00-8909-11e9-8d09-7724aa03370e.png)

**Comment by dramforever** [comment] 2019-06-07 10:17
I'm on Coq 8.9.1 on Arch Linux, using the distribution provided `coq` and `coqide` package.

The build script can be found here: <https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/coq>. I'm not entirely familiar with either Arch packaging or OCaml and Coq,  but I do not find anything fishy there. In particular there are no distribution specific patches in sight.

I'm not aware of any other examples, since I just found this by trying to `apply Decidable.dec_not_not`, but it seems that the goal could be any proposition.

I'll try to ask other Arch Linux users I know to see if they can reproduce this.

**Comment by vbgl** [comment] 2019-06-07 10:28
I could reproduce with Coq 8.9.1 on NixOS. Things work when `Decidable` is imported, not wen only required.

**Comment by jfehrle** [comment] 2019-06-07 11:57
I'm on Windows.  I haven't tried CoqIDE 8.9.1 yet.  It may be that I need help from someone on a platform that shows the problem.  I will look into it.  Also I'll see if 8.10 has the problem once that's available.

BTW, the screen shot above doesn't show the correct diffs.  So 8.9 is not OK.  It may be that 8.9 just hides the exception.  Coqtop looks better:

![image](https://user-images.githubusercontent.com/1253341/59102204-b2549f00-892b-11e9-93a4-02e150b7def9.png)

**Comment by vbgl** [comment] 2019-06-07 12:00
Could not reproduce with Coq 8.10+β1.

**Comment by jfehrle** [comment] 2019-06-07 12:10
Thanks @vbgl.  I will close the issue.  @dramforever, please reopen this if you see it in 8.10.  Thanks for the bug report.

**Closed** 2019-06-07 12:10 UTC
Labels: kind: anomaly

**Comment by dramforever** [comment] 2019-06-08 14:10
Got that. Thanks anyway.
