### ISSUE TITLE
[dune] missing dependency on plugins

### ISSUE THREAD

**Issue by gares** [coq/coq#9727] opened 2019-03-08 16:09 UTC
```
gares@ollypat:~/COQ/wt/master$ dune exec coqtop.byte
Welcome to Coq ollypat:/home/gares/COQ/wt/master/_build/default,quotations (e1e1fc7ea327bf3536b00260c394d0a219e45dbb)
The files /home/gares/COQ/wt/master/_build/install/default/lib/coq/plugins/ltac/ltac_plugin.cma
and /home/gares/COQ/wt/master/_build/install/default/bin/coqtop.byte
disagree over interface Tok
Error: Could not load plugin ltac_plugin.cma
```
I did that to be able to `Drop` as per `dev/doc/build-system.dune.md` but I got this error.

**Comment by gares** [comment] 2019-03-08 16:09
I was indeed editing tok.ml, this is why `Tok` is there.

**Comment by gares** [comment] 2019-03-08 16:11
I did remove `_build` and now I get
```
gares@ollypat:~/COQ/wt/master$ dune exec coqtop.byte
Fatal error: cannot load shared library dllbyterun_stubs
Reason: dllbyterun_stubs.so: cannot open shared object file: No such file or directory
```

**Comment by ejgallego** [comment] 2019-03-08 16:25
This is a know problem, you need to use the dev/shim for now. Indeed coqtop doesnt depend on the plugins as it is an optional dependency (you can load without the prelude)

This will be fixed hopefully in the next iteration by having a command to specify the lib to load.

**Comment by gares** [comment] 2019-03-10 08:35
The first error seems to match your description, but the second one is different. The instructions to run Drop seem to be outdated.

**Comment by ejgallego** [comment] 2019-03-11 11:29
Indeed the second error I think is a bug in Dune, I was aware of it but didn't have time to investigate more, we should add a workaround for now.

**Comment by ejgallego** [comment] 2019-03-11 11:32
@rgrinberg , indeed, given a bytecode binary `a/foo`, `dune exec a/foo.bc` won't properly install the necessary stublibs for it to run. Should I file a bug?

**Comment by rgrinberg** [comment] 2019-03-11 17:37
Yeah, we're aware of this issue. The issue is that the stublibs aren't actually necessary to build the binary but to _run_ it. There's no way to express that runtime dependency in dune at the moment.

**Comment by ejgallego** [comment] 2019-03-11 17:47
> There's no way to express that runtime dependency in dune at the moment.

This seems like a bug in `dune exec`, right? In the same way `dune utop` works, exec should indeed generate the extra rules, right?

Is there an issue already for that?

**Comment by rgrinberg** [comment] 2019-03-12 08:59
> In the same way dune utop works, exec should indeed generate the extra rules, right?

In fact, `$ dune utop` is broken the same way: try to load a library with stubs in the toplevel.

The way exec works is roughly as follows:

* Build the executable `foo.exe` (if it's a target)
* Run the newly built executable.

Obviously, this doesn't really work as running the executable has its own dependencies.

Basically, we need to teach dune that some binaries have runtime dependencies attached to them and executing the binary requires them to be built. For the exec case, it would be enough to just create a fake alias that we execute right away. But this isn't good enough as using these bytecode binaries in other rules will still be broken.

**Comment by ejgallego** [comment] 2019-03-12 11:15
Ok, fix at https://github.com/coq/coq/pull/9748

**Comment by ejgallego** [comment] 2019-03-21 18:10
Upstream bug in Dune is https://github.com/ocaml/dune/issues/108

**Closed by ejgallego** 2019-03-21 18:10 UTC
