### ISSUE TITLE
[win] CoqIDE crash

### ISSUE THREAD

**Issue by gares** [coq/coq#12282] opened 2020-05-08 12:35 UTC
While testing the installer produced by https://github.com/coq/coq/pull/12032 I found out that executing a sentence from the script window crashed coqidetop. Running the same sentence via the query windows works fine, so I suspect is some code specific to the script window, possibly gtksourceview.

![Screenshot from 2020-05-08 14-29-49](https://user-images.githubusercontent.com/1013846/81405959-f900d980-9138-11ea-81bc-b1ae2e0d4793.png)

**Comment by gares** [comment] 2020-05-08 12:36
Note: I was running CoqIDE via wine.

**Comment by Zimmi48** [comment] 2020-06-03 14:33
I couldn't reproduce on Windows 32 bits with Coq 8.11.1 nor Coq master.

**Comment by ejgallego** [comment] 2020-06-11 15:06
I couldn't reproduce it either, let's postpone to 8.12

**Comment by Zimmi48** [comment] 2020-06-23 15:19
@MSoegtropIMC Do you still plan to have a look at this for 8.12.0? Note that according to our testing, this issue seems hard to reproduce, and might be wine-specific. Therefore, it doesn't look very high priority to me.

**Comment by gares** [comment] 2020-06-23 16:00
Btw, didn't the version of lablgtk change too? I seem to recall something like that.

**Comment by Zimmi48** [comment] 2020-06-23 16:18
Yes, that's possible.

**Comment by MSoegtropIMC** [comment] 2020-06-23 16:42
@Zimmi48 : it is on my "final test list" (probably done this week end). If it is not reproducible I will close this.

**Comment by SkySkimmer** [comment] 2020-08-28 13:50
@MSoegtropIMC ping

**Comment by ejgallego** [comment] 2020-09-22 17:50
Looks like not an issue otherwise we would have heard.

**Comment by MSoegtropIMC** [comment] 2020-09-23 07:16
Yes, I think it is a Wine issue. I would say we close this.

**Closed** 2020-09-23 07:42 UTC
Labels: needs: triage, platform: Windows
