### ISSUE TITLE
Number & String Notation should probably use `lazy` not `cbv`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14807] opened 2021-08-24 20:54 UTC
In https://github.com/coq/coq/blob/1c350016c61bda28ff37bd0dd9255b9198cea0ee/interp/notation.ml#L598-L619
we use `Tacred.compute`.  I think this is `cbv`, which means that for parsing/printing functions involving large proofs without lambdas, this is going to blow up.  What should this be changed to for lazy?

cc @proux01 @herbelin @coq/extensible-syntax-maintainers ?

cc @andrew-appel

**Comment by ppedrot** [comment] 2021-08-24 23:44
FTR, this reduction does pop up a lot in profiling traces of printing functions.

**Comment by JasonGross** [comment] 2021-08-25 02:36
Is it worth benching `lazy` vs `cbv` vs vm followed by lazy / cbv?  (We can't do just the vm because parameters of inductive constructors must be normalized.)

**Comment by proux01** [comment] 2021-08-25 07:28
@JasonGross do you have use cases of such parsing/printing functions with large proofs? It seems that this did not happen until now, but number notations are not a widely used feature so that may just be by chance.
On which tests do you plan to bench the change?

@ppedrot thanks for your comment, on which printing functions did you observe this behavior?

(to be clear, I'm not at all against the change, I just fera that lazy could be slower and like to see evidence that the change is useful or at least harmless)

**Comment by andrew-appel** [comment] 2021-08-25 12:25
The examples with large proofs, that @JasonGross refers to, are mine.  I have a complete working implementation of parsing/printing floating point numbers in any size of Flocq's binary_float format.   I'm using Number.number as the parse/print format, and then computing the binary/decimal conversion using functional programs in Coq.  One field of a B754_finite constructor of binary_float is a proof.  If reduced naively, these will blow up (run out of memory in Coq).  I have a workaround (basically, discard and rebuild the proof...).   

When I get it all cleaned up, I'll post it as a test case, and perhaps also as a contribution to the Flocq library.

This is related to issue #14782 and P.R. #14525.  In #14782 I suggested that primitive floats be added to the Number notation system, which (although I didn't know that yet) is what #14525 was already in the process of doing.  However, as @proux01 pointed out in #14782,  that solution will not be accurate for single-precision floats because of double-rounding, and I really want a solution that is accurate for any size of binary_float.  In my implemention, I also discovered (and work around) bug #14806.

**Comment by ppedrot** [comment] 2021-08-25 12:40
> on which printing functions did you observe this behavior?

IIRC just printing a sizable term with `Printer.pr_constr_env` and friends is enough.

I personally doubt that the solution is to go from cbv to lazy. Lazy also has its share of sources of slowdown (notably term reconstruction). Rather we should probably try to be cleverer about when and how much we call these reduction functions.

**Comment by proux01** [comment] 2021-08-30 08:45
@JasonGross I let you close the current issue if you agree.

**Comment by andrew-appel** [comment] 2021-08-30 12:57
Let me correct myself even more:  I am not sure about my claim that "a huge natural number is created"; I recall seeing that behavior in dealing with floats recently, but not necessarily in this parsing/printing system.  So maybe it's possible that a different reduction order could avoid a blow-up.  But I don't think that matters.   The Flocq system already has a `Binary.erase` function which does the same thing that my `rebuild_float` does, and presumably for exactly the same purpose:  to discard large proofs and replace them with small proofs.    Presumably this problem of "large proofs in binary floats" has existed even before there was Number.number notation.  

This systematic method (replace large proofs with small ones) could probably be applied to other applications of Number notation, not only Flocq floating point.  Therefore, there is a (relatively) simple workaround for the user.  And on the other hand, replacing `cbv` by `lazy` won't _reliably_ solve the problem for users.

Therefore, even though my diagnosis of the problem may not have been 100% accurate, I still recommend to close this issue.

**Comment by JasonGross** [comment] 2021-08-30 17:31
I will defer to @ppedrot on closing this issue.  It seems like there's still some performance issue here, it seems like in fact we want lazy reduction and not cbv, even if it's not the current bottleneck (asymptotics matter), and I'm also not clear on what the ideal solution performance-wise is.

> > Also, is there a fastpath in lazy/cbv/vm for terms that are already fully reduced?
>
> Some of them do, but not always and it's not recursive (e.g. it won't handle non-trivial first-order terms made of applications / constructors).

It seems like relatively low-hanging fruit to add such a recursive fast-path?  Or am I missing some complexity?

**Comment by ppedrot** [comment] 2021-08-30 18:34
I'd recommend closing, since I don't have a reproducible test-case at hand. If that were the case, I could have explored the various design choices, but in the meantime there is little point keeping this open.

> It seems like relatively low-hanging fruit to add such a recursive fast-path? Or am I missing some complexity?

It's going to be O(n) in some cases, which you'd pay anyways when reducing, so it's an additional cost. For now we only look at the outermost node of the term in O(1). We could bench to check.

**Comment by JasonGross** [comment] 2021-08-30 18:57
> It's going to be O(n) in some cases, which you'd pay anyways when reducing, so it's an additional cost.

You mean there's an additional O(n) cost to having the fast-path, either in time or in space?  (I guess you get an extra branch at every recursive call?)

**Closed** 2021-12-28 12:00 UTC
Labels: part: notations
