### ISSUE TITLE
`lia` takes >1min and >4GB to fail on non-linear goal

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#15748] opened 2022-02-28 05:06 UTC
Due to a bug in my own code, I accidentally invoked `lia` on a non-linear goal, which I then isolated as follows:

```coq
Require Import Coq.micromega.Lia.
Require Import Coq.ZArith.ZArith. Open Scope Z_scope.
Require Import Coq.Lists.List. Open Scope list_scope.

Lemma test: forall E (width w0 w1 : Z) (sz : Z) (vs1 vs2 vsPrefix vsSuffix : list E),
    0 < sz < 2 ^ 32 ->
    length vs1 = length vsPrefix ->
    length vs2 = length vsSuffix ->
    (w0 - w1) mod 2 ^ width =
      (sz mod 2 ^ width * (Z.of_nat (length vsPrefix) mod 2 ^ width)) mod 2 ^ width ->
    0 <= w0 < 2 ^ width ->
    0 <= w1 < 2 ^ width ->
    w0 = (w1 + (sz * Z.of_nat (length vs1)) mod 2 ^ width) mod 2 ^ width.
Proof.
  intros.
  Z.div_mod_to_equations.
  Time try lia.
Abort.
```

On my machine, this takes more than 1min and more than 4GB of RAM.

If I do `replace width with 32 in * by admit` before `lia`, `lia` solves the goal immediately.

So far I think that this is not a problem for me, because I can be careful to never invoke `lia` on a non-linear goal.
But still, it is a bit unsettling that there's a goal on which `lia` takes so long, so I thought I'd report it.

Coq version: 8.15-rc1

/cc @fajb

**Comment by ppedrot** [comment] 2022-02-28 09:52
Looks like a variant of #10743, since the blowup is caused by CNF normalization it seems.

**Comment by fajb** [comment] 2022-02-28 09:54
hi @samuelgruetter . The culprit seems to be again  `Z.div_mod_to_equations`
Using the factorisation of @thery (see https://github.com/coq/coq/issues/10743#issuecomment-530673037),
the problem vanishes.

Duplicate of #10743

**Closed by fajb** 2022-02-28 09:54 UTC
Labels: kind: performance, part: micromega

**Comment by samuelgruetter** [comment] 2022-02-28 15:19
Ah I see, sorry for not remembering https://github.com/coq/coq/issues/10743 myself 😅
