### ISSUE TITLE
`vm_compute` should not reduce in evar substitutions

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16358] opened 2022-08-01 23:08 UTC
#### Description of the problem

Like #16357

```coq
Fixpoint fact (n : nat) := match n with 0 => 1 | S n' => n * fact n' end.

Goal forall m : nat, fact 100 = m -> exists n : nat, n = n.
  intros.
  eexists.
  subst.
  cbv. (* instantaneous success *)
  vm_compute. (* eventually crashes coqtop with OOM or something *)
```

I'm not sure if reduction in evar substitutions is ever desired, but if it is, it's much better to have it off by default and have an option to enable it.  At the very least there should be an option to disable it.  Reduction in evar instances is a significant performance bottleneck in some cases.

#### Coq Version

8.15

**Comment by Blaisorblade** [comment] 2022-08-05 18:40
IIRC @Janno had to workaround the same problem.

**Comment by silene** [comment] 2023-09-13 06:20
Duplicate of #14405.

**Closed by silene** 2023-09-13 06:20 UTC
Labels: kind: performance, part: VM, part: existential variables

**Comment by ejgallego** [comment] 2023-09-13 08:44
Duplicate of #14405 

[I think the dot at the end prevents the GH regex from working]

**Comment by ejgallego** [comment] 2023-09-13 08:44
Duplicate of #14405

**Comment by SkySkimmer** [comment] 2023-09-13 11:11
@ejgallego we don't care if the github regex works as its effect is useless.
The label is manual.
