### ISSUE TITLE
Error message in match pattern with `@` and to few arguments not precise

### ISSUE THREAD

**Issue by fakusb** [coq/coq#13533] opened 2020-12-01 09:59 UTC
#### Description of the problem
When giving a constructor with the `@` prefix to also bind implicit arguments, the error message does not give the real number of arguments to be expected, but claims that 'one more' would suffice. (I think in general, it just adds together the number of arguments actually given and the number of non-implicit arguments missing)

``` coq
Inductive Test := test : forall {a b c d e f : bool} (g:bool), Test.
About test.
Axiom t : Test.

Fail Check match t with | @test => _ end.
(* The constructor test (in type Test) expects 1 argument.  *)

Fail Check match t with @test _ => _ end.
(* The constructor test (in type Test) expects 2 argument.  *)
```
I would expect this error message to tell me that 6 arguments are expected whenever i give to few arguments.

#### Coq Version

master from a few days ago ( 0501761b95f4fd3e22b93aa6bce8c9f96b88495b )

**Comment by mrhaandi** [comment] 2022-11-24 11:58
Duplicate of (closed) #11112.

**Closed** 2022-11-24 11:59 UTC
Labels: kind: user messages
