### ISSUE TITLE
`concl:` search results disappearing after Import of file with `Set Primitive Projections`

### ISSUE THREAD

**Issue by chdoc** [coq/coq#13298] opened 2020-11-02 20:17 UTC
#### Description of the problem

I have the following two files, the first is named `bij.v` and compiled independently.
```coq
From mathcomp Require Import all_ssreflect.

Set Primitive Projections.

Record bij (A B: Type): Type := Bij
  { bij_fwd:> A -> B;
    bij_bwd: B -> A;
    bijK: cancel bij_fwd bij_bwd (* ; *)
    (* bijK': cancel bij_bwd bij_fwd *) }.
```
In a second file I run the following:
```coq
From mathcomp Require Import all_ssreflect.
Search concl:(mathcomp.ssreflect.path.path).
Require Import bij.
Search concl:(mathcomp.ssreflect.path.path).
```
The first command finds a variety of lemmas mentioning `path`, the second comes up empty-handed. 

All three commands in `bij.v` are necessary for the bug to trigger. Indeed, even removing the `bijK` line makes `path` show up in the second search command. Adding `Unset Primitive Projections` does not seem to help. 

#### Coq Version

The Coq Proof Assistant, version 8.12.0 (August 2020)
compiled on Aug 10 2020 12:25:47 with OCaml 4.09.0

(with coq-mathcomp-ssreflect-1.11.0)

**Comment by herbelin** [comment] 2020-11-02 20:51
If its fully empty, I suspect that a `Not_found` is raised when testing if `bijK` matches the pattern and this interrupted the search (something similar to #12525/#12647 but presumably related here to the table of primitive projections). If ever you find a more self-contained example (e.g. by reducing the dependencies, or testing alternatives to using `cancel`, or alternatives to looking for `path`, or alternatives to looking for `concl:`), that may help. For instance, I could not reproduce with requiring only `ssrfun.v` which defines `cancel`, so something else is in play.

**Comment by chdoc** [comment] 2020-11-02 21:06
Well, for now I'm happy that you can reproduce this as is, because to me it looked pretty bizarre. I'll see whether I can find something more simple.

**Comment by SkySkimmer** [comment] 2020-11-02 21:29
I think this try block https://github.com/coq/coq/blob/dfdecf24210ee287d554cf4296bd0ccfffe310d8/vernac/search.ml#L108-L109 should be done individually for each object rather than around the iter_all (ie move it around https://github.com/coq/coq/blob/dfdecf24210ee287d554cf4296bd0ccfffe310d8/vernac/search.ml#L105)

**Comment by SkySkimmer** [comment] 2020-11-02 21:34
Although I'm not sure that this is the issue here.

**Comment by herbelin** [comment] 2020-11-02 21:44
> I think this try block ... should be done individually for each object rather than around the iter_all (ie move it around 

Yes, that would be safer (but in the same time, that would make discovering possible residual bugs more difficult...).

**Comment by herbelin** [comment] 2020-11-03 07:32
I finally could reproduce and fix (no care was taken about free de Bruijn variables but primitive projections were expecting the terms to have the free variables bound in their exact context). Its observability depended on the name of module. By renaming the module `bij.v` to `A.v`, I could force `bijK` to be searched first (thus interrupting the rest of the search). Since stdlib has capital library names and I was searching elementary names such as `nat`, module `bij` was searched after and I could not observe the problem.

Fixed in #13301. Thanks a lot for the report.

**Comment by herbelin** [comment] 2020-11-03 10:20
> Since stdlib has capital library names

By the way, @chdoc, as a user of MathComp, do you understand the reasons why MathComp seems to tend to use syntactic/naming conventions which seem to diverge so much of standard usages in Coq. This does not seem to help different kinds of users to better understand themselves?

**Comment by chdoc** [comment] 2020-11-03 11:08
> By the way, @chdoc, as a user of MathComp, do you understand the reasons why MathComp seems to tend to use syntactic/naming conventions which seem to diverge so much of standard usages in Coq?

@herbelin I don't feel qualified to comment on this. Maybe you should ask someone who has been involved in mathcomp from the beginning, when those conventions emerged.

**Comment by herbelin** [comment] 2020-11-03 11:26
> I don't feel qualified to comment on this.

No worry about it. I'm asking to an outsider like you because, when asked, MathComp developers generally don't answer.

**Comment by CohenCyril** [comment] 2020-11-03 11:59
> No worry about it. I'm asking to an outsider like you because, when asked, MathComp developers generally don't answer.

This is a self-full-filling prophecy

**Comment by herbelin** [comment] 2020-11-03 12:01
Just invalidate this prophecy then...

**Comment by CohenCyril** [comment] 2020-11-03 12:17
My answer will be the same as @chdoc, I was not there either.

**Comment by herbelin** [comment] 2020-11-03 12:24
>  I was not there either.

Then we agree...

But how to make progresses on the communication between the different communities. Should we go back to the source?

**Comment by ppedrot** [comment] 2020-11-03 12:43
I know this is a bait, but:

> standard usages in Coq

as the plural surreptitiously implies, *at least* mathcomp has a consistent naming strategy.

**Comment by SkySkimmer** [comment] 2020-11-03 12:45
Please take the discussion to zulip, it doesn't belong on a random PR.

**Comment by CohenCyril** [comment] 2020-11-03 14:09
> Then we agree...

No I don't, please **do not speak on my behalf**, and let's get away from this PR.

**Comment by herbelin** [comment] 2020-11-03 14:27
> No I don't, please **do not speak on my behalf**

My apologies. I didn't want to speak on your behalf. I just sincerely thought that you were thinking the same as I was, and I'm sorry if I was mistaken. Let me then rephrase my sentence as follows: that you say that you "were not there either" clarify (to me) the difficulties I see in proposing to the community a unified consensual view at libraries.

> Please take the discussion to zulip.

Let me rather propose a verbal (online) discussion. The remark of @ppedrot lets me think that we are several to have more to say on this topic and that would be a pity that we don't share what we have to say. Moreover, I tend to think that we are close to be able to make a factual description of what are the library problems the Coq community is facing, and I consider that such a factual description is necessary to move forward and converge, as a community.

@ppedrot, @CohenCyril: would you be ok to participate to such a video-discussion?

**Comment by SkySkimmer** [comment] 2020-11-03 15:33
>Let me rather propose a verbal (online) discussion

Propose it on zulip, not here.

**Closed** 2020-11-05 15:10 UTC
Labels: hijacked
