### ISSUE TITLE
Ltac eval unfold,  error message refers to wrong file

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#12255] opened 2020-05-05 13:34 UTC
#### Description of the problem

File a.v:
```
Ltac can_unfold x :=
 let b := eval cbv delta [x] in x in idtac.
```
File b.v:
```
Require Import a.
Definition i := O.
Goal False.
can_unfold i.
can_unfold (i>0).
```
No error message when compiling` coqc a.v`.
Error message when compiling `coqc b.v`:
```
File "./a.v", line 2, characters 26-27:
Error: Ltac variable x is bound to i > 0 which cannot be coerced to an evaluable reference.
```

**This is the wrong error message.**  When compiling b.v, the error should not refer to some line of a.v.  Perhaps more appropriate would be, `File "./b.v", line 5,  Error: ...`
But I think best of all would be no error message, just tactic failure.

By the way, I can work around this problem by writing 
```
Ltac can_unfold x :=
 tryif (let b := eval cbv delta [x] in x in idtac) then idtac else fail.
```

**Comment by ppedrot** [comment] 2020-05-05 14:03
Isn't this addressed by #12223?

**Comment by andrew-appel** [comment] 2020-05-05 14:33
Very possibly.  If so, my apologies for not trying it in 8.11.2.

**Comment by herbelin** [comment] 2020-05-05 21:59
The cause is probably the same as what caused #12152, but apparently #12223 is not strong enough to fix the current instance.

**Comment by herbelin** [comment] 2020-05-06 09:00
I refined #12223 so that it locates again this error in `b.v`. The message is a bit different though. Before the message was relying on the trace, so it was writing:
```
File "./b.v", line 5, characters 0-10:
Error:
Ltac call to "can_unfold" failed.
Ltac variable x is bound to i > 0 which cannot be coerced to
an evaluable reference.
```
With #12223 as it is now, it prints:
```
File "./b.v", line 5, characters 0-16:
Error: Ltac variable x is bound to i > 0 which cannot be coerced to
an evaluable reference.
```
which is a bit more enigmatic because nothing says which `x` we are talking about. I could probably tweak the message to be `In call to "can_unfold", variable x is bound to i > 0 which cannot be coerced to an evaluable reference`, or, alternatively, to `Unable to coerce  i > 0 to an evaluable reference`. I'm however a bit afraid that changes made here will disturb the trace reporting mechanism and that a more general reflection on what kind of error reporting we expect shall be needed.

**Closed** 2020-05-12 19:09 UTC
