### ISSUE TITLE
rewrite in * does less than rewrite in H

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#8635] opened 2018-10-02 18:59 UTC
#### Version

8.8.1

#### Operating system

Fedora 28

#### Description of the problem

Here's an example where `rewrite in *` does nothing, while `rewrite in H` does the rewrite I want it to do. Also, `autorewrite` behaves the same, and there, it's even more annyoing because it prevents me from using `autorewrite`.

```
Class MapFunctions(K V: Type) := mkMap {
  map: Type;

  empty_map: map;
  get: map -> K -> option V;
  put: map -> K -> V -> map;

  get_put_same: forall (m: map) (k: K) (v: V), get (put m k v) k = Some v;
  get_put_diff: forall (m: map) (k1 k2: K) (v: V),
      k1 <> k2 -> get (put m k1 v) k2 = get m k2;
}.

Arguments map _ _ {_}.

Class Decidable (P : Prop) := dec : {P} + {~P}.
Arguments dec _%type_scope {_}.
Notation DecidableEq T := (forall (x y: T), Decidable (x = y)).

Section Lemmas.

  Context {K V: Type}.
  Context {key_eq_dec: DecidableEq K}.
  Context {Map: MapFunctions K V}.

  Lemma get_put: forall m x y v,
    get (put m x v) y = if dec (x = y) then Some v else get m y.
  Proof.
    intros. destruct (dec (x = y)).
    - subst. rewrite get_put_same. reflexivity.
    - rewrite get_put_diff by assumption. reflexivity.
  Qed.

End Lemmas.

Hint Rewrite @get_put : foo.

Section MoreLemmas.

  Context {K V: Type}.
  Context {key_eq_dec: DecidableEq K}.
  Context {Map: MapFunctions K V}.

  Lemma get_put_empty_map: forall k1 k2 v,
      get (put empty_map k1 v) k2 = Some v ->
      k1 = k2.
  Proof.
    intros.
    Fail rewrite get_put in *.
    Fail progress autorewrite with foo in *.
    rewrite get_put in H.
```

The expected behavior is that the two commands marked with `Fail` would not fail.

I also tried using `rewrite_strat`, but it leaves an open evar, which is not so nice either.

```
    Require Import Coq.Setoids.Setoid.
    generalize H.
    unshelve rewrite_strat (repeat topdown hints foo).
```

**Comment by ppedrot** [comment] 2018-10-03 11:42
Probably a duplicate of #3051.

**Comment by Blaisorblade** [comment] 2019-08-25 16:34
During a discussion, @benzrf found another example of this, minimized to https://gist.github.com/benzrf/0793b9233b95ce6785b2227a2f74e109.

**Comment by benzrf** [comment] 2019-08-25 16:59
I can confirm that this is a duplicate of #3051; an evar is being created for the maximally inserted instance argument. I'm pretty sure that the discrepancy with `Check` is because of [`Check` immediately performing extra constraint solving](https://github.com/coq/coq/blob/9e1f8009141345f3232947c1d356b5def4ca7263/vernac/vernacentries.ml#L1856) that `rewrite` doesn't at first.

**Comment by ppedrot** [comment] 2021-12-23 22:18
Duplicate of #3051

**Closed by ppedrot** 2021-12-23 22:18 UTC
Labels: part: rewriting tactics
