### ISSUE TITLE
lia does not like Set Mangle Names.

### ISSUE THREAD

**Issue by jonleivent** [coq/coq#13672] opened 2020-12-24 19:15 UTC
In v8.12.1:
```Coq
Require Import Lia.

Set Mangle Names.
Goal 1 + 1 = 2.
  Fail lia.
  Unset Mangle Names.
  lia.
Qed.
```
`Fail lia` output is:
```
The command has indeed failed with message:
The variable __ff was not found in the current environment.
```

**Comment by jashug** [comment] 2020-12-24 19:53
Duplicate of #12907, fixed for Coq 8.13 in #12913.

**Closed by jashug** 2020-12-24 19:53 UTC
Labels: resolved: duplicate(d), resolved: fixed in newer version
