### ISSUE TITLE
Rewrite creates universe levels that are not properly cleaned up during backtracking

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#14116] opened 2021-04-15 07:40 UTC
#### Description of the problem

```
Lemma t (A : Type) (h : Type = A) :
forall X : Type,
eq_rect_r (fun X : Type => X)
          (eq_rect Type (fun X : Type => X) X A h) h
= X.
(rewrite <- h; fail) ||
(rewrite <- h).
(* Conversion test raised an anomaly:
Anomaly
"Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/. *)
```
Note that on Coq versions before #13726, the error is:
```
Conversion test raised an anomaly:
Anomaly "Universe Test7.9 undefined."
Please report at http://coq.inria.fr/bugs/.
```
It seems that during the first rewrite a new universe is created and something is not cleaned up during backtrakcking.

#### Coq Version
master

**Comment by ppedrot** [comment] 2021-04-15 09:44
Probably a duplicate of #3608.

**Comment by SkySkimmer** [comment] 2021-04-15 09:45
Probably duplicate of https://github.com/coq/coq/issues/13834

**Comment by ppedrot** [comment] 2021-04-15 09:47
Nah, I insist, it's a problem with tactic backtracking rather than side-effects handling in declarations.

**Comment by SkySkimmer** [comment] 2021-04-15 10:13
Aren't they all the same bug?

**Comment by ppedrot** [comment] 2021-04-15 11:01
I don't think so. #3608 is due to a mismatch between the global imperative environment and the pure local used in the proof, whereas #13834 seems to be a problem with cleaning the set of side-effects after subproof closing. Fixing one may impact the other in some fancy way but I don't think it would solve it.

**Comment by SkySkimmer** [comment] 2021-04-15 11:13
#13834 is also about backtracking, looking at the example
~~~coq 
Inductive myeq (A : Type) (x : A) : A -> Prop :=
| myeq_refl : myeq A x x.

Arguments myeq [A].
Arguments myeq_refl {A} {x}.

Definition myeqss (A : Type) (a b : A) (H : myeq (Some a) (Some b)) : myeq a b.
  pose (Some b) as Someb.
  rewrite (myeq_refl : myeq (Some b) Someb) in *.
  rewrite (myeq_refl : myeq b (match Someb with None => a | Some b_ => b_ end)).
  destruct H.
  reflexivity.
Qed.
~~~
if you change the `rewrite in *` to `rewrite in H` there is no error, and if you then add `try rewrite in a` before  it you get the error again.

**Comment by SkySkimmer** [comment] 2021-06-10 12:56
Anyway the point is that this is a duplicate of some mentioned bug.

**Closed by SkySkimmer** 2021-06-10 12:56 UTC
Labels: resolved: duplicate(d)
