### ISSUE TITLE
subst substitutes but does not clear equation

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#12139] opened 2020-04-20 23:29 UTC
I was assuming that when `subst x` substitutes `x`, the equation used to substitute `x` is cleared.

Other Coq users seem to make this assumption too, because otherwise [this Ltac code](https://github.com/achlipala/frap/blob/69de20dec86597534052615349203477b3612bc3/MessagesAndRefinement.v#L14-L17) can loop infinitely, as shown in this standalone example:

```coq
Axiom proc : Type.
Axiom mkproc : nat -> nat -> proc.

Section WithParams.
  Context (input aggregatorIn : nat).

  Definition MapReduceImpl : proc := mkproc input aggregatorIn.

  Inductive R: proc -> proc -> Prop :=
  | BuildR : forall pr1 pr2,
      pr1 = MapReduceImpl ->
      pr2 = MapReduceImpl ->
      R pr1 pr2.

  Goal forall pr1 pr2,
      input = aggregatorIn ->
      R pr1 pr2 /\ aggregatorIn = input.
  Proof.
    intros.
    subst input. (* Bad: makes progress but does not clear H *)
    (* Bad: loops forever *)
    repeat match goal with
           | x: _ |- _ => subst x
           end.
```

Related to https://github.com/coq/coq/issues/10812:

```coq
  Goal forall pr1 pr2,
      input = aggregatorIn ->
      R pr1 pr2.
  Proof.
    intros.
    Fail subst.
    (* Error: Found no subterm matching "input" in the current goal. *)
    (* Bad: "subst" without arguments should never fail *)
  Abort.
```

Coq version: 8.11.0

This occurred while designing a problem set for our [FRAP class](http://adam.chlipala.net/frap/).

**Comment by herbelin** [comment] 2020-05-02 06:49
@jasongross raised good questions about the intended of `subst` in [#12146](https://github.com/coq/coq/pull/12146#pullrequestreview-401135761). In particular, there is a nice "reversible" view about `subst` which is to see it as a converse of `remember` and `set`.

1. If we adopt this view, `subst x` should not clear the equality over a section variable which has indirect depencencies: by not being able to rewrite inside these internal dependencies, clearing the equality would loose information.

   Then, we could either fail, or do a rewriting w/o clearing as it is now.

   1. Doing a rewriting implies that the ping-pong game involving 2 equal section variables with indirect dependencies as described in this PR is not a bug.

   2. We could alternatively fail (thus fixing the issue), but I'm afraid of incompatibilities.

2. If we don't insist to defend the view of `subst` as converse of `remember` and `set`, then we could solve the current issue by using the equality to replace the visible occurrences of the section variable and clear the equality afterwards, as #12145 is doing (thus losing information). This would solve the issue to the price of a few incompatibilities.

Personally, I'm quite tempted by the "reversible" view, which means either the status quo (and this issue is not a bug), or moving to a failure. I don't know the opinion of others though.

**Comment by JasonGross** [comment] 2020-05-02 15:08
I would say do 1.ii.  I'm a big fan of subst being reversible.  Most incompatibilities should be fixable in a backwards-compatible way by first doing `generalize dependent; intros` to turn the variable into not-a-section-variable

**Comment by samuelgruetter** [comment] 2020-05-03 03:23
1.ii. makes most sense to me as well.

**Comment by herbelin** [comment] 2020-05-03 20:02
> We could alternatively fail (thus fixing the issue), but I'm afraid of incompatibilities.

> 1.ii. makes most sense to me as well.

Let's then go in this direction. There are incompatibilites in four packages tested in CI. I started to evaluate if the required changes are reasonable. Most of the time, this is solved by first clearing a (useless) hypothesis indirectly depending on the section variable and blocking the `subst`. It even revealed a case of artificial dependencies of a lemma in section hypotheses apparently induced by such now-rejected `subst`.

**Comment by SkySkimmer** [comment] 2022-02-01 14:50
Fixed by https://github.com/coq/coq/pull/12146

**Closed by SkySkimmer** 2022-02-01 14:50 UTC
Labels: part: ltac, kind: bug
