### ISSUE TITLE
Impossible to define mutual induction-induction types

### ISSUE THREAD

**Issue by tobiasBora** [coq/coq#19200] opened 2024-06-12 12:11 UTC
### Is your feature request related to a problem?

I wanted to define types that depend on each others like:
```
Inductive typeA : Type :=
| Foo : nat -> typeB-> typeA
with typeB : typeA -> typeA -> Type :=
| Bar : forall (x : typeA), b x x
.
```
but it gives an error `Error: The reference typeA was not found in the current environment.`. After discussing in [zulip](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Mutually.20recursive.20indexed.20inductive.20definition/near/444109052), it turns out that induction-induction types are not supported in Coq (but they might in Agda?).

### Alternative solutions

Luckily I could rewrite my definitions to avoid this dependency… But it may not always be the case.

**Comment by Alizter** [comment] 2024-06-12 12:18
Duplicate of https://github.com/coq/coq/issues/4654

There was an attempt to add these a while back but it never took off: https://github.com/coq/coq/pull/12464

**Closed by Alizter** 2024-06-12 12:18 UTC
Labels: needs: triage, kind: wish
