### ISSUE TITLE
Universe coercion error when module is not called "option" [regression from 8.7]

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#7595] opened 2018-05-24 11:31 UTC
#### Version

8.8.0

#### Operating system
Linux

#### Description of the problem

This needs two files to reproduce, the error goes away on inlining:

File `base2.v`:
```
From Coq Require Export Morphisms RelationClasses List Bool Utf8 Setoid.
Set Default Proof Using "Type".
Export ListNotations.
From Coq.Program Require Export Basics Syntax.
Global Generalizable All Variables.

(** * Type classes *)
(** ** Decidable propositions *)
(** This type class by (Spitters/van der Weegen, 2011) collects decidable
propositions. *)
Class Decision (P : Prop) := decide : {P} + {¬P}.
Hint Mode Decision ! : typeclass_instances.
Arguments decide _ {_} : simpl never, assert.

(** ** Proof irrelevant types *)
(** This type class collects types that are proof irrelevant. That means, all
elements of the type are equal. We use this notion only used for propositions,
but by universe polymorphism we can generalize it. *)
Class ProofIrrel (A : Type) : Prop := proof_irrel (x y : A) : x = y.
Hint Mode ProofIrrel ! : typeclass_instances.

Class MGuard (M : Type → Type) :=
  mguard: ∀ P {dec : Decision P} {A}, (P → M A) → M A.
Arguments mguard _ _ _ !_ _ _ / : assert.
Notation "'guard' P ; z" := (mguard P (λ _, z))
  (at level 20, z at level 200, only parsing, right associativity) .
Notation "'guard' P 'as' H ; z" := (mguard P (λ H, z))
  (at level 20, z at level 200, only parsing, right associativity) .
```

File `option.v`:
```
Require Import base2.

Lemma dec_stable `{Decision P} : ¬¬P → P.
Proof. firstorder. Qed.

(** The tactic [destruct_decide] destructs a sumbool [dec]. If one of the
components is double negated, it will try to remove the double negation. *)
Tactic Notation "destruct_decide" constr(dec) "as" ident(H) :=
  destruct dec as [H|H];
  try match type of H with
  | ¬¬_ => apply dec_stable in H
  end.
Tactic Notation "destruct_decide" constr(dec) :=
  let H := fresh in destruct_decide dec as H.


(** * Monadic operations *)
Instance option_guard: MGuard option := λ P dec A f,
  match dec with left H => f H | _ => None end.

(** * Tactics *)
Tactic Notation "case_option_guard" "as" ident(Hx) :=
  match goal with
  | H : context C [@mguard option _ ?P ?dec] |- _ =>
    change (@mguard option _ P dec) with (λ A (f : P → option A),
      match @decide P dec with left H' => f H' | _ => None end) in *;
    destruct_decide (@decide P dec) as Hx
  | |- context C [@mguard option _ ?P ?dec] =>
    change (@mguard option _ P dec) with (λ A (f : P → option A),
      match @decide P dec with left H' => f H' | _ => None end) in *;
    destruct_decide (@decide P dec) as Hx
  end.
Tactic Notation "case_option_guard" :=
  let H := fresh in case_option_guard as H.

Lemma option_guard_True {A} P `{Decision P} (mx : option A) :
  P → (guard P; mx) = mx.
Proof. intros. case_option_guard. reflexivity. contradiction. Qed.
```

Both files compile fine when running `coqc`, but the last `Qed` fails when running `coqtop` or running interactively in emacs:
```
Error: Illegal application: 
The term "option" of type "Type → Type"
cannot be applied to the term
 "A" : "Type"
This term has type "Type@{Top.95}" which should be coercible to
 "Type@{Coq.Init.Datatypes.13}".
```

**Comment by ppedrot** [comment] 2018-05-24 11:40
Have you properly set the `-top` flag?

**Comment by RalfJung** [comment] 2018-05-24 11:51
I... what? On the console I ran something like `coqtop < theories/option.v`. But I am getting the same error in emacs which sets `-emacs` or so.

**Comment by ejgallego** [comment] 2018-05-24 11:53
That's weird, `sertop` doesn't show a problem. Umm...

**Comment by ejgallego** [comment] 2018-05-24 11:53
First thing I'd to is to check your loadpath, etc...

**Comment by RalfJung** [comment] 2018-05-24 11:54
> Have you properly set the -top flag?

Ah, but this works:
```
coqtop -top option < option.v
```
?!?? Why should the module name matter?

**Comment by ppedrot** [comment] 2018-05-24 11:55
@RalfJung It's probably resolving the name in a wrong way.

**Comment by ejgallego** [comment] 2018-05-24 11:55
I don't set the module name in sertop and it still works, so some weird bug is going on.

**Comment by RalfJung** [comment] 2018-05-24 11:56
> First thing I'd to is to check your loadpath, etc...

What is there to check? There's nothing else called `base2` anywhere else on my machine, and also when I remove the `base2.vo` the import stops working so I'm as sure as I can get that it loads the right thing.

**Comment by RalfJung** [comment] 2018-05-24 11:58
*lol* after `mv option.v FOO.v`, even `coqc FOO` fails. Amazing.

**Comment by ejgallego** [comment] 2018-05-24 12:00
yeah I can reproduce, but hard to say what's going on as if I am not messing anything `sertop` does work.

**Comment by ejgallego** [comment] 2018-05-24 12:02
Umm, the main difference is how `sertop` sets the path; let me try something.

**Comment by RalfJung** [comment] 2018-05-24 12:11
Oh, also, the same thing still worked with 8.7.

**Comment by ejgallego** [comment] 2018-05-24 12:11
No clue what's going on... but sertop works so it is still very weird....

**Comment by ejgallego** [comment] 2018-05-24 12:11
Maybe we are gonna need a bisect I'm afraid.

**Comment by ppedrot** [comment] 2018-05-24 12:38
@RalfJung I cannot reproduce. What is the exact setting you're in, i.e. `pwd` and flags passed to `coqtop` / `coqc`?

**Comment by RalfJung** [comment] 2018-05-24 12:39
I'm just doing `coqc base2.v && coqc FOO.v`, in a directory that does not contain any other `*.v*` files.

Bisect is ongoing.

**Comment by ejgallego** [comment] 2018-05-24 12:42
What do you folks have on `user-contrib` ? Maybe that makes a difference.

**Comment by RalfJung** [comment] 2018-05-24 12:46
@ejgallego I reproduced this with a `./configure -local` build, where would `user-contrib` even be?

**Comment by ppedrot** [comment] 2018-05-24 12:46
@RalfJung In the folder where Coq is compiled.

**Comment by RalfJung** [comment] 2018-05-24 12:47
Which one?
```
$ find -name user-contrib
./test-suite/coq-makefile/uninstall2/_test/tmp/doc/user-contrib
./test-suite/coq-makefile/uninstall2/_test/tmp/user-contrib
./test-suite/coq-makefile/coqdoc1/_test/tmp/doc/user-contrib
./test-suite/coq-makefile/coqdoc1/_test/tmp/user-contrib
./test-suite/coq-makefile/multiroot/_test/tmp/doc/user-contrib
./test-suite/coq-makefile/multiroot/_test/tmp/user-contrib
./test-suite/coq-makefile/mlpack2/_test/tmp/user-contrib
./test-suite/coq-makefile/mlpack1/_test/tmp/user-contrib
./test-suite/coq-makefile/coqdoc2/_test/tmp/doc/user-contrib
./test-suite/coq-makefile/coqdoc2/_test/tmp/user-contrib
./test-suite/coq-makefile/plugin1/_test/tmp/user-contrib
./test-suite/coq-makefile/plugin2/_test/tmp/user-contrib
./test-suite/coq-makefile/uninstall1/_test/tmp/doc/user-contrib
./test-suite/coq-makefile/uninstall1/_test/tmp/user-contrib
./test-suite/coq-makefile/plugin3/_test/tmp/user-contrib
```

**Comment by ppedrot** [comment] 2018-05-24 12:48
@RalfJung None. It would be at the root, together with `theories` and the ML subfolders.

**Comment by RalfJung** [comment] 2018-05-24 12:49
@ppedrot  Okay. I never created such a folder.

**Comment by ejgallego** [comment] 2018-05-24 12:53
It is strange that @ppedrot cannot reproduce. I can. But not when using my own toplevel; weird.... as 8.8/8.9 is in fact very close to my toplevel :S only difference is that in `sertop` you need to add the `.` path manually, but I modified coq not to do it and still the problem persists.

**Comment by ppedrot** [comment] 2018-05-24 14:03
Sorry, I was using the wrong Coq version, master instead of 8.8. So it means that this bug has been solved in the meantime...

**Comment by RalfJung** [comment] 2018-05-24 14:39
> Sorry, I was using the wrong Coq version, master instead of 8.8. So it means that this bug has been solved in the meantime...

Ah! Can you do a "reverse bisect" to find the fix? ;)

**Comment by ppedrot** [comment] 2018-05-24 14:41
I'm not sure I have much time for that. Don't you want to do that on your side?

(I wouldn't be suprised that it is some heuristic-changing commit though, so not really informative.)

**Comment by RalfJung** [comment] 2018-05-24 14:43
Maybe next week, already lost enough time on this today.

A testcase would also be nice to avoid future regressions, I guess.

**Comment by RalfJung** [comment] 2018-06-07 08:40
I did a bisect to figure out when this got fixed:
```
f53890d1629ea7aaff86ea92e5ac27ab027b2e8d is the first bad commit
commit f53890d1629ea7aaff86ea92e5ac27ab027b2e8d
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Fri Mar 2 13:37:07 2018 +0100

    universe normalisation: put equivalence class partition in UGraph
    
    ie don't go through having Eq constraints but directly to the unionfind.

:040000 040000 eecec09f78c07f6917f8a8e2e8741f4d96c6cfae f4349222746a21f7b93f14d571df463d707e1631 M	engine
:040000 040000 de30ac5e15707fa882be4c4ffedf3caf423515b0 3dc74298c4e3f6668279dda7685aa551ff0277f2 M	kernel
```
("bad" is "good" here)

**Comment by SkySkimmer** [comment] 2018-06-07 21:22
>2e30531 is the first bad commit

Removing the `subst` and using `us` instead around https://github.com/coq/coq/commit/2e30531e78519a5b9c3773c2524e4fd4759cc5c8#diff-143dbfaa98e46ffc64d4561fcca413e2R1017 is the only change in that commit where I can't trivially say it only has an impact with cumulative inductive types (which don't appear in the bug).

**Closed** 2018-08-23 08:02 UTC
Labels: kind: regression, part: universes
