### ISSUE TITLE
'Anomaly "Uncaught exception Not_found."' in an Inductive definition

### ISSUE THREAD

**Issue by roboguy13** [coq/coq#13835] opened 2021-02-07 20:54 UTC
#### Description of the problem

I am getting the error `Anomaly "Uncaught exception Not_found."` when I try to step to the last `Inductive` definition.

Maybe this is related to #13824?

```coq
Definition optionS (n : option nat) : option nat :=
  match n with
  | None => Some O
  | Some n => Some (n+1)
  end.

Inductive Env' : option nat -> Type :=
| Env_Empty : Env' None
| Env_Cons : forall n, bool -> Env' n -> Env' (optionS n).

Definition Env x := Env' (Some x).

Definition optionPred (n : nat) : option nat :=
  match n with
  | O => None
  | S n' => Some n'
  end.

Lemma optionS_optionPred : forall x, optionS (optionPred x) = Some x.
Proof.
  induction x. simpl. reflexivity.
  assert (A : x + 1 = S x).
  { rewrite <-plus_n_Sm,<-plus_n_O;reflexivity. }
  simpl. rewrite A. reflexivity.
Defined.

Definition rewr' {A : Type} {P : A -> Type} {x y} (prf : x = y) : P x -> P y.
Proof. subst. easy. Defined.

Definition rewr_' {A : Type} {P : A -> Type} {x y} (prf : x = y) : P y -> P x.
Proof. subst. easy. Defined.

Inductive Lookup : forall x y, (y <= S x) -> Env (S x) -> bool -> Prop :=
| Lookup_Here : forall x (prf : S x <= S x) e b, Lookup x (S x) prf (rewr_' (optionS_optionPred _) (Env_Cons (optionPred x) b e)) b.
```

If I replace `(optionS_optionPred _)` in the first argument of `rewr_'` in the last line with `_`, I instead get the following inference error: 

```
Cannot infer this placeholder of type "Some (S x) = optionS (optionPred x)"
in
environment:
Lookup : forall x y : nat, y <= S x -> Env (S x) -> bool -> Prop
x : nat
prf : S x <= S x
e : Env' (optionPred x)
b : bool
```

If, instead of using `rewr_'` at all, I use a call to this in its place:

```
Definition optionS_optionPred_thm {x} : Env' (optionS (optionPred x)) -> Env' (Some x).
Proof.
  intros. rewrite <- optionS_optionPred. assumption.
Defined.
```

I get (I believe) the correct type error:

```
In environment
Lookup : forall x y : nat, y <= S x -> Env (S x) -> bool -> Prop
x : nat
prf : S x <= S x
e : Env' (optionPred x)
b : bool
The term "optionS_optionPred_thm (Env_Cons (optionPred x) b e)" has type "Env' (Some x)"
while it is expected to have type "Env (S x)".
```

#### Coq Version

I am running CoqIDE with Coq 8.13.0 on Windows 10.

**Comment by SkySkimmer** [comment] 2021-02-08 11:56
On 8.11.2 I get `In env ... Unable to unify "Env' (optionS (optionPred x))" with "?P (Some ?x)".`

**Comment by herbelin** [comment] 2021-02-09 21:49
@roboguy13: Thanks for the report!

The bug is related to the second-order unification heuristic, #7819 (1c9e1a39652b). In 8.11, it was not called, in 8.13 it is called (I don't know when it exactly changed).

To devs: as far as I could reconstruct the technical issue is the following one.

Let `Γ ⊢ ?x@{a1:=arg1;...;an:=argn} == phi(argi₀,...,argiᵤ)` be a 2nd order unification problem where the `argiⱼ` denote specific occurrences of the `argi` in `phi`). The algorithm creates for each occurrence of an argument an evar `?yⱼ` in context `ctxt` and generates the solution `phi(?yⱼ@{ctx:=ctx})`, with two candidates for instantiations: either that `?yⱼ` is instantiated by `t` (an imitation of the original term) or by `aiⱼ` (a projection of the corresponding argument of `?x`).

The problem is that `t` is not necessarily directly imitable: it needs to be closed in the context of `?x` and cannot contain free variables which are not among the `args`. The cause of the failure is precisely that: here, `t` is the de Bruijn indice 4 which is not closed. The error is eventually triggered by `solve_unconstrained_evars_with_candidates` which tries to retype this unbound de Bruijn index 4.

A simple workaround would be to check that `t` is closed. A more challenging algorithm would be to continue unification on `t` so that `t` itself is virtually abstracted over the `argi`. It might be a bit trickier but probably feasible.

@mattam82 (and @maximedenes, as co-author of unifall): what do you think?

**Comment by herbelin** [comment] 2021-02-09 21:53
> Maybe this is related to #13824?

The trace obtained with `-debug` are the same, thus it is most probably the same.

**Comment by SkySkimmer** [comment] 2021-12-07 19:56
Current master gets
~~~
Unable to unify "Env' (optionS (optionPred x))" with
 "(fun _ : option nat => Env' (Some (S x))) (Some ?x)" (cannot unify "optionS (optionPred x)" and
"Some (S x)").
~~~

**Comment by ppedrot** [comment] 2022-02-25 16:12
At least we don't get an anomaly, I think that this bug can be closed. Tweaking the unification is a completely different thing.

**Closed by ppedrot** 2022-02-25 16:12 UTC
Labels: kind: regression, kind: anomaly, part: unification
