### ISSUE TITLE
Internal error related to Require in section

### ISSUE THREAD

**Issue by bcip** [coq/coq#12000] opened 2020-04-02 07:53 UTC
#### Description of the problem
1. Clone VST from https://github.com/PrincetonUniversity/VST
2. `make floyd` in VST root
3. unzip [bug.zip](https://github.com/coq/coq/files/4419518/bug.zip) in VST root
4. `make rotate.vo bug.vo`

`bug.v` looks like
```
Require Import VST.floyd.proofauto.

Section verif_rotate.

Require Import rotate.

Definition rotate_spec :=
 DECLARE _rotate
  WITH tt : unit
  PRE []
     PROP()
     LOCAL ()
     SEP ()
  POST [ tvoid ]
     PROP()
     LOCAL()
     SEP ().

End verif_rotate.
```
Coq reports on the last line of `bug.v`
```
Anomaly "File "clib/int.ml", line 46, characters 14-20: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

It works without error if putting Require outside of section, like
```
Require Import VST.floyd.proofauto.
Require Import rotate.

Section verif_rotate.
...
```

#### Coq Version

The Coq Proof Assistant, version 8.11.0 (March 2020)
compiled on Mar 24 2020 12:42:57 with OCaml 4.06.0

OS: MacOS
Coq is installed from OPAM.

#### Related Issue
https://github.com/coq/coq/issues/11783

**Comment by SkySkimmer** [comment] 2020-04-02 08:15
Duplicate of #11783

**Closed by SkySkimmer** 2020-04-02 08:15 UTC
