### ISSUE TITLE
Ltac2 array notation is not reparsable

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#11085] opened 2019-11-08 22:11 UTC
#### Description of the problem

The last line of the code bellow errors out:

```coq
Require Import Ltac2.Ltac2.

Ltac2 Eval (Ltac2.Array.make 1 0).
(* - : int array = [| 0 |] *)

Fail Ltac2 Eval ([| 0 |]).
(* Syntax error: [tactic:tac2expr level 5] expected after '[' (in [tactic:tac2expr]). *)
```

This makes it impossible to have array constants, which would be convenient.

#### Coq Version

8.9.1

**Comment by ppedrot** [comment] 2019-11-08 22:34
Yep, definitely a TODO.

**Comment by ppedrot** [comment] 2021-04-22 22:01
Duplicate of #13976

**Closed by ppedrot** 2021-04-22 22:01 UTC
Labels: kind: enhancement, part: ltac2
