### ISSUE TITLE
Anomaly after compiling and using file

### ISSUE THREAD

**Issue by JonasOberhauser** [coq/coq#9724] opened 2019-03-08 13:36 UTC
#### Description of the problem

In CoqIde I just got the following:

```
Anomaly
"Uncaught exception Library.Faulty("[...]/core.vo")."
Please report at http://coq.inria.fr/bugs/.
```
I just compiled a file after changing something that I had the impression should have broken some parts of the proof, but the proof checker went through (this could mean that the effect of the change would only be visible in the next file).
When using the compiled file in the next file, I got this error.

[orderpaper18.zip](https://github.com/coq/coq/files/2945994/orderpaper18.zip)

However, I only got the error after completely checking the second file, which definitely shouldn't have worked. The error came at the end of the section in which I imported the compiled file.

EDIT: 
After recompiling the file, the second file correctly detected that the proof breaks.

#### Coq Version

8.9 on windows 10

**Comment by Alizter** [comment] 2021-07-07 15:00
I am unable to reproduce this. I am closing this issue. If you are still able to reproduce this bug, let us know and I will reopen.

**Closed by Alizter** 2021-07-07 15:00 UTC
