### ISSUE TITLE
Uncaught exception library

### ISSUE THREAD

**Issue by yunoJ** [coq/coq#9940] opened 2019-04-10 06:06 UTC
Hi, I'm new to coq (8.9.0) and studying with Software Foundations. I've tried compiling the first file (Basic.v) and 

File "./IndProp.v", line 4, characters 0-29:
Anomaly:
Uncaught exception Library.Faulty("Path_to_archive").

./IndProp.v", line 4, characters 0-29: is "From LF Require Export Logic."

popped up. IndProp.v is another source file in the same folder but I haven't touched it and Basic.v  is not directly linked with IndProp.v.

My question is why is IndProp.v causing error even though I compiled Basic.v?
--coqide told me to report this problem here

thanks in advance

**Comment by Zimmi48** [comment] 2019-04-10 06:41
You did well but you didn't provide enough information so that we can reproduce your problem. What is your setup exactly? What OS? How did you install Coq? How did you try to compile SF? Did you do something else?

**Comment by yunoJ** [comment] 2019-04-10 08:38
Sorry for not mentioning the details. Coq is installed using opam and running on ubuntu. I used "compile buffer" in coqide to compile SF. I haven't touched much except for solving the examples listed in Basic.v. I did rewrite my _coqproject file but restored it after seeing that nothing much changed from my modification.

**Comment by yunoJ** [comment] 2019-04-10 08:42
I just compiled Basic.v and the problem disappeared.... But can you still explain the cause of the problem?

**Comment by Zimmi48** [comment] 2019-04-10 09:11
If you mean that you can't reproduce the problem anymore, this is likely going to be very hard to debug it.

**Comment by yunoJ** [comment] 2019-04-10 12:51
Oh....maybe there was a temporary problem with my machine. I just compiled the file without any modification after couple hours and it worked. Thanks for the reply.

**Comment by ejgallego** [comment] 2019-04-10 13:03
That could be caused by a truncated file or by the user hitting Ctrl-C in the exact vo save moment. Closing as there is little we can do.

**Closed by ejgallego** 2019-04-10 13:03 UTC
