### ISSUE TITLE
Appveyor is too unreliable

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#9164] opened 2018-12-07 10:35 UTC
Appveyor times out frequently enough that I just assume appveyor failures are spurious. This means it provides negative value. Shall we remove it?

**Comment by Zimmi48** [comment] 2018-12-07 12:43
Isn't this kind of a duplicate of #8078? Well, except that I was not so radical. If moving the test-suite on Windows to GitLab CI (or Azure, or Travis) is considered too hard, we could stop running AppVeyor on PRs and only on branches. This way, we would still catch errors, but later.

**Closed** 2018-12-12 12:54 UTC
