### ISSUE TITLE
Conversion test raised an anomaly: "conversion was given ill-typed terms (FProd)."

### ISSUE THREAD

**Issue by akr** [coq/coq#9186] opened 2018-12-11 06:13 UTC
#### Version

```
% coqtop -v
The Coq Proof Assistant, version 8.8.2 (October 2018)
compiled on Oct 7 2018 20:17:55 with OCaml 4.07.0
```

#### Operating system

```
% lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch
% uname -mrsv
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64
```

#### Description of the problem

I found an anomaly as follows.

```
Fixpoint arrow_type (Ts : list Set) (Tr : Set) :=
  match Ts with
  | nil => Tr
  | cons T Ts' => T -> arrow_type Ts' Tr
  end.

Fixpoint forall_type (Ts : list Set)
    (f : unit -> Set) : Set :=
  match Ts as Ts return (unit -> Set) -> Set with
  | nil => fun f => f tt
  | cons T Ts' => fun f => T -> forall_type Ts' f
  end f.

Definition test_func (Ts : list Set) (Tv : Set)
    (f : arrow_type Ts Tv) := tt.

Definition test_type (Ts : list Set) (Tr : Set) : Set :=
  forall_type Ts (fun (dummy : unit) => True -> Tr).

Definition test (Ts : list Set) (Tr : Set)
    (f : test_type Ts Tr) :=
    test_func Ts (True -> Tr) f.
(*
Conversion test raised an anomaly:
Anomaly "conversion was given ill-typed terms (FProd)."
Please report at http://coq.inria.fr/bugs/.
*)
```

**Comment by ejgallego** [comment] 2018-12-11 09:12
Backtrace on master:
```
Error: Conversion test raised an anomaly:
Anomaly "conversion was given ill-typed terms (FProd)."
Please report at http://coq.inria.fr/bugs/.
frame @ file "toplevel/coqloop.ml", line 396, characters 19-59
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 604, characters 33-68
raise @ file "stdlib.ml", line 33, characters 17-33
frame @ file "stm/stm.ml", line 2695, characters 4-60
frame @ file "stm/stm.ml", line 2556, characters 4-105
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 939, characters 6-10
frame @ file "stm/stm.ml", line 2420, characters 16-43
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 1093, characters 12-91
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/vernacentries.ml", line 2440, characters 4-36
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/vernacentries.ml", line 2411, characters 8-451
frame @ file "vernac/vernacentries.ml", line 2413, characters 15-58
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
frame @ file "vernac/comDefinition.ml", line 95, characters 4-62
frame @ file "vernac/comDefinition.ml", line 60, characters 31-76
frame @ file "interp/constrintern.ml", line 2326, characters 17-58
frame @ file "pretyping/pretyping.ml", line 1101, characters 20-71
frame @ file "pretyping/pretyping.ml", line 1059, characters 21-77
frame @ file "pretyping/pretyping.ml", line 686, characters 22-60
frame @ file "pretyping/pretyping.ml", line 471, characters 16-37
raise @ unknown
frame @ file "pretyping/coercion.ml", line 526, characters 6-82
raise @ unknown
frame @ file "pretyping/coercion.ml", line 490, characters 7-34
frame @ file "pretyping/evarconv.ml", line 1404, characters 8-42
raise @ unknown
frame @ file "pretyping/evarconv.ml", line 382, characters 16-87
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/cErrors.ml", line 65, characters 8-11
raise @ file "lib/cErrors.ml", line 116, characters 9-24
```

**Comment by ppedrot** [comment] 2018-12-11 18:59
This is due to the fact that the inferred term is ill-typed but untyped conversion tries to apply η-expansion on it, leading to the anomaly.

Duplicate of #5466

**Closed by ppedrot** 2018-12-11 19:00 UTC
Labels: kind: anomaly
