### ISSUE TITLE
Warning attributes on notations do not apply when they are imported

### ISSUE THREAD

**Issue by tchajed** [coq/coq#19536] opened 2024-09-12 13:22 UTC
### Description of the problem

If I want to suppress a warning on a notation, using `#[warning="-..."]` appears to work, but then when the notation is imported the warning attribute isn't used. In this case I want to disable "notation-incompatible-prefix" which seems to have false positives (it says two notations are incompatible but they do both work).

If it's feasible to implement I'd like to see the attribute also used on import. If this isn't implemented, the alternative is to globally disable the warning, which is a lot less nice (for one thing, all users of a library will also have to disable the warning).

I imagine that a similar limitation applies to other items on import, where their warning attributes aren't used, but don't have any examples.

### Small Coq file to reproduce the bug

```coq
Module notations.
Reserved Notation "{[ x ]}" (at level 0).
#[warning="-notation-incompatible-prefix"]
Reserved Notation "{[ x | P ]}"
  (at level 0, x at level 200 as pattern, format "{[  x  |  P  ]}").
End notations.

Import notations.
```

### Version of Coq where this bug occurs

8.20

**Comment by SkySkimmer** [comment] 2024-09-13 12:57
Duplicate of https://github.com/coq/coq/issues/17925

**Closed by SkySkimmer** 2024-09-13 12:57 UTC
Labels: kind: bug, needs: triage
