### ISSUE TITLE
Nested notations break bound scopes

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10803] opened 2019-10-01 00:43 UTC
#### Description of the problem

The last of these should not fail, I think.

```coq
Inductive Foo := foo.
Delimit Scope foo_scope with foo.
Bind Scope foo_scope with Foo.
Notation "'!'" := foo : foo_scope.
Definition of_foo {x : nat} {y : nat} (f : Foo) := f.
Notation a := (@of_foo O).
Notation b := (@a).
Check a !.
Check @a O !.
Check @b O.
Check @b O !. (* Error: Unknown interpretation for notation "!". *)
```

See Also #8126

cc @herbelin 

#### Coq Version

8.9.0, also master post v8.10 (59079a232d2157c0c4bea4cb1a3cd68c9410e880)

**Comment by herbelin** [comment] 2020-09-01 11:48
The effect was different but the cause is the same as #9403. Both are fixed by #12960.

**Closed** 2020-09-22 17:42 UTC
