### ISSUE TITLE
CoqMakefile.in missing from the install repository

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#14187] opened 2021-04-27 18:03 UTC
The dune makefile wrapper does not copy the `CoqMakefile.in` file to a place where `coq_makefile` can find it. This happens even after a `make world`.

This leads to weird errors when compiling external developments, the source of which is hidden by the scripts. The root cause can be observed by simply calling `coq_makefile`, which prints `Error: cannot find CoqMakefile.in`.

cc @ejgallego

**Comment by ejgallego** [comment] 2021-04-27 18:49
Can you provide the exact set of steps you use to build / configure Coq? [This works for me in both my setups]

There are still some cases not covered by CI, tho if we manage to make progress on some of the related PRs, locations of stuff will be canonical soon.

**Comment by ppedrot** [comment] 2021-04-28 10:17
I can't reproduce with `make tools` on #14185. I might have generated coq_makefile with a rule that messed up the state. I am closing this issue then.

**Comment by ppedrot** [comment] 2021-04-28 10:23
Actually, `coq_makefile` doesn't print the warning anymore, but the generated makefile is still empty. So, let's reopen.

A reproducible test for me on a clean #14185:
```
pm@ouranos:~/sources/coq$ env | grep COQ
COQLIB=/home/pm/sources/coq/_build_vo/default/
COQBIN=/home/pm/sources/coq/_build/install/default/bin/

pm@ouranos:~/sources/coq$ ./configure -profile devel
You have OCaml 4.07.1. Good!
You have OCamlfind 1.8.1. Good!
You have native-code compilation. Good!
You have the Zarith library 1.12 installed. Good!
LablGtk3 and LablGtkSourceView3 found (3.1.1), with native threads:
=> native CoqIde will be built.

  Architecture                : Linux
  Sys.os_type                 : Unix
  Coq VM bytecode link flags  : -dllib -lcoqrun -dllpath "/home/pm/sources/coq/kernel/byterun"
  Other bytecode link flags   : 
  OCaml version               : 4.07.1
  OCaml binaries in           : /home/pm/.opam/4.07.1+fp/bin/
  OCaml library in            : /home/pm/.opam/4.07.1+fp/lib/ocaml
  OCaml flambda flags         : 
  Native dynamic link support : true
  Lablgtk3 library in         : /home/pm/.opam/4.07.1+fp/lib/lablgtk3-sourceview3
  CoqIde                      : opt
  Documentation               : None
  Web browser                 : firefox -remote "OpenURL(%s,new-tab)" || firefox %s &
  Coq web site                : http://coq.inria.fr/
  Bytecode VM enabled         : true
  Native Compiler enabled     : ondemand

  Local build, no installation...

If anything is wrong above, please restart './configure'.

*Warning* To compile the system for a new architecture
          don't forget to do a 'make clean' before './configure'.

pm@ouranos:~/sources/coq$ make -j -l4 tools
[...]

pm@ouranos:~/sources/coq$ $COQBIN/coq_makefile foo.v
Warning: Omitting -o is deprecated
```
Note the empty output. I passed a dummy argument to it but for real world _CoqProject I have the same issue.

**Comment by ejgallego** [comment] 2021-04-28 17:15
I see an error, "cannot find CoqMakefile.in", but indeed there are two bugs here:

- provide a working setup which is a subset of the `world` target
- improve the code handling the location of stuff cc #14059 

In fact, with your current reproduction setup coq_makefile won't even be able to find COQLIB as Prelude won't be get built by `tools`.

Gonna address this bug with a PR doing 1 for now.

**Comment by ejgallego** [comment] 2021-04-28 18:31
Actually I am tempted to close this as you latest case indeed is not expected to copy that file to the install layout, tho it could.

But `make world` does copy everything to the right place.

What do you think @ppedrot ? We could add `CoqMakefile.in` to the `tools` target but this still won't produce a fully working env.

**Comment by ppedrot** [comment] 2021-04-28 22:00
What's missing if we add CoqMakefile.in? More generally I believe that we should have a target that makes any Coq binary usable without having to rely on shell hacks. Maybe it goes against the dune ideology, but this looks like a clear case of reality-inconsistent stance. I am not asking for crazy dynamic rules or whatnot, I just want a build system to build the thing I asked for...

**Closed** 2021-05-04 09:58 UTC
Labels: kind: bug, part: build
