### ISSUE TITLE
build failure due to missing csig.ml?

### ISSUE THREAD

**Issue by madroach** [coq/coq#10404] opened 2019-06-19 23:31 UTC
#### Description of the problem
build failure:
```
gmake[1]: Entering directory '/usr/obj/pobj/coq-8.9.1/coq-8.9.1'
CAMLP5O   plugins/derive/g_derive.ml4
Error while loading "/usr/local/lib/ocaml/camlp5/pr_dump.cmo": The module `Pr_dump' is already loaded (either by the main program or a previously-dynlinked library).
CAMLP5O   ide/coqide_main.ml4
Error while loading "/usr/local/lib/ocaml/camlp5/pr_dump.cmo": The module `Pr_dump' is already loaded (either by the main program or a previously-dynlinked library).
OCAMLC    clib/cMap.mli
File "clib/cMap.mli", line 30, characters 10-19:
30 |   include CSig.MapS
               ^^^^^^^^^
Error: Unbound module CSig
gmake[1]: *** [Makefile.build:696: clib/cMap.cmi] Error 2
gmake[1]: Leaving directory '/usr/obj/pobj/coq-8.9.1/coq-8.9.1'
gmake: *** [Makefile:166: submake] Error 2
```
Help appreciated.

#### Coq Version
Coq 8.9.1
camlp5 https://github.com/camlp5/camlp5/pull/37
OCaml 4.08.0
OpenBSD 6.5-current

**Comment by glondu** [comment] 2019-08-09 23:53
I see the same error in Debian unstable with ocaml 4.08.0, camlp5 7.08 and coq 8.9.0.

**Comment by SkySkimmer** [comment] 2019-11-04 15:16
Probably fixed by https://github.com/coq/coq/pull/10650 like #10403

**Comment by SkySkimmer** [comment] 2019-11-04 15:17
(ie duplicate of #10403)

**Closed by SkySkimmer** 2019-11-04 15:16 UTC
