### ISSUE TITLE
Error: Anomaly "variable H unbound." Please report at http://coq.inria.fr/bugs/. on autorewrite using a cleared section variable

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12486] opened 2020-06-09 02:56 UTC
#### Description of the problem

```coq
Section A.
  Context (x y : nat)
          (H : x = y).
  Hint Rewrite H : foo.
  Lemma f : x = y.
  Proof. clear H. autorewrite with foo.
         (* Error: Anomaly "variable H unbound." Please report at http://coq.inria.fr/bugs/. *)
```

#### Coq Version

8.11.1

**Comment by ppedrot** [comment] 2020-06-16 13:40
Duplicate of #12486

**Closed by ppedrot** 2020-06-16 13:40 UTC
Labels: kind: anomaly, part: rewriting tactics
