### ISSUE TITLE
rewrite_strat build_signature: no constraint can apply on a dependent argument

### ISSUE THREAD

**Issue by jad-hamza** [coq/coq#7838] opened 2018-06-16 11:17 UTC
#### Version

opam coq (dev)

#### Operating system

Debian

#### Description of the problem

Maybe a duplicate of https://github.com/coq/coq/issues/4175?

```coq
Require Import Coq.Bool.Bool.
Require Import Setoid.
Hint Rewrite eqb_true_iff: libBool.

Goal forall (b: {b : bool | eqb b true = true}), b = b.
Proof.
  intros.
  rewrite_strat repeat topdown (hints libBool).
(* Error:
Ltac call to "rewrite_strat (debug_flag) (rewstrategy)" failed.
build_signature: no constraint can apply on a dependent argument *)
```

**Comment by JasonGross** [comment] 2018-06-18 13:32
What behavior do you expect?  Do you expect `eqb_true_iff` to apply, or do you expect `rewrite_strat` to be a no-op in this case?

**Comment by jad-hamza** [comment] 2018-06-18 15:07
Not sure, I'd be ok with either here. Ideally I could give options or a custom strategy to say whether I want rewriting to happen under local bindings.

I cannot try right now so I'm not sure, but I believe that currently this example will crash even if there is another instance that can be rewritten (e.g. replacing "b = b" with "eqb b true = true")

**Comment by jad-hamza** [comment] 2018-06-18 18:47
```coq
Require Import Coq.Bool.Bool.
Require Import Setoid.
Hint Rewrite eqb_true_iff: libBool.

Goal forall (b: {b : bool | eqb b true = true}), eqb (proj1_sig b) true = true.
Proof.
  intros.
  rewrite_strat repeat topdown (hints libBool).
(* Error:
Ltac call to "rewrite_strat (rewstrategy)" failed.
build_signature: no constraint can apply on a dependent argument *)
```

`autorewrite with libBool` here correctly rewrites `eqb (proj1_sig b) true = true`

**Comment by JasonGross** [comment] 2018-06-18 18:52
Duplicate of #4175

**Closed by JasonGross** 2018-06-18 18:52 UTC
