### ISSUE TITLE
Opening Nat.v in freshly installed CoqIDE gives Safe_typing.import fatal error

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12079] opened 2020-04-12 04:27 UTC
I wanted to step through a sample proof, so I thought I'd use something from the Coq library.  I get this dialog when I open "Nat.v".  If I click "Reset", the same dialog returns in a second.

To reproduce:
- do a fresh install (just to start from a known state, probably not necessary)
- start CoqIde
- from the menu, open Nat.v from the theories/Init directory (e.g. C:\Coq8.11.0C\lib\coq\theories\Init)
- boom!

This seems pretty user-hostile and perhaps something a beginner might encounter.  Or someone curious about the libraries.

The log file shows "Error: in Safe_typing.import: Cannot load a library with the same name as the current one."  (log file attached below).

#### Coq Version 8.11.0 on Windows 10.

![image](https://user-images.githubusercontent.com/1253341/79060270-027d4b80-7c38-11ea-8cb1-ed33e443629a.png)

[coqide_5049c9.log](https://github.com/coq/coq/files/4465844/coqide_5049c9.log)

**Comment by ppedrot** [comment] 2020-04-12 10:08
Duplicate of #10872

**Closed by ppedrot** 2020-04-12 10:08 UTC
Labels: kind: bug
