### ISSUE TITLE
`Warning: The following expression should have type unit. [not-unit,ltac]` should include a following expression and name its type

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14013] opened 2021-03-26 13:42 UTC
```coq
Require Import Ltac2.Ltac2.
Ltac2 foo (f : constr -> constr) (x : constr array) := Array.iteri (fun i z => Array.set x i (f z)); ().
(* Warning: The following expression should have type unit. [not-unit,ltac] *)
```
It should actually print the expression (`Array.iteri (fun i z => Array.set x i (f z))`) and its type.

**Comment by ppedrot** [comment] 2021-03-26 14:46
What interface are you using? With CoqIDE I get the right expression highlighted. Also it's quickly going to become intractable if you print random snippets of code. I know Coq does it for Gallina, but it's most of the time useless because the printed term is not informative enough (the *types* do matter a lot though).

**Comment by JasonGross** [comment] 2021-03-26 14:55
ProofGeneral.  But also `coqc` on the command line.  Location information is correct, which is why it's highlighted in CoqIDE.

I find the error messages including Gallina quite useful, though there is a very steep learning curve.  I agree that when the IDE highlights the corresponding input, additionally printing out the term is useless noise.  So perhaps we should always print the type, and print the term only on the command line and in emacs mode, and not for CoqIDE?

**Comment by ppedrot** [comment] 2021-03-26 14:58
I agree the message should be made more informative. I don't really know if there is a proper infrastructure to display richer information in batch / emacs mode though.

**Comment by ppedrot** [comment] 2021-04-17 18:13
By the way:

Duplicate of #11683

**Closed by ppedrot** 2021-04-17 18:13 UTC
Labels: kind: user messages, part: ltac2
