### ISSUE TITLE
 Nat.log2_up_le_pow2 Anomaly Uncaught exception.

### ISSUE THREAD

**Issue by Isomorph70** [coq/coq#12859] opened 2020-08-19 16:14 UTC
#### Description of the problem
Get following error message.

Anomaly
"Uncaught exception Pp_diff.Diff_Failure("string mismatch, shouldn't happen")."
Please report at http://coq.inria.fr/bugs/.

Here is the example.
----
Require Coq.derive.Derive.
Require Import Coq.Numbers.Natural.Peano.NPeano.
Section P.
Variables (v:nat).
Derive l SuchThat (le v (pow 2 l)) As h.

Search (_ <= (pow _ _)).
(* // # apply (not_lt (pow 2 l)  v). *)

apply <- Nat.log2_up_le_pow2.

#### Coq Version

8.9.1

os: gentoo linux.

**Comment by JasonGross** [comment] 2020-08-19 16:22
I cannot reproduce this, not with 8.9.1 nor 8.10.0 nor 8.11.0 nor 8.12.0 nor master, nor with CoqIDE on 8.10.0 on Windows.  Please provide more information about how to reproduce the error, including what IDE you're using and what commands you're issuing to it.  If you can run it with `-debug` and get a backtrace for the anomaly, that would also be useful.

**Comment by JasonGross** [comment] 2020-08-19 16:27
Okay, I was able to reproduce something like this in 8.9.1 by running `coqtop -q -diffs on <<<` followed by the text of your example, but I got
```coq
Warning: Diff failure: string mismatch, shouldn't happen
Showing results without diff highlighting
mismatch: expected 'l' but got '.'
```
rather than an anomaly.

However, the warning does not occur in 8.10.0, so I suspect this bug has already been fixed, and I'm going to close this.  Please comment and/or reopen if the problem persists after upgrading Coq to a newer version.

**Closed by JasonGross** 2020-08-19 16:27 UTC

**Comment by Isomorph70** [comment] 2020-08-19 19:10
Okey I have tested it again. I only get the exception using coqide.
