### ISSUE TITLE
`Print Assumptions foobar` triggers an Anomaly

### ISSUE THREAD

**Issue by vsiles** [coq/coq#8861] opened 2018-10-30 09:06 UTC
#### Version
```
$ opam list | grep coq
coq                 8.8.1             pinned to version 8.8.1
coqide              8.8.1             IDE of the Coq formal proof management system.

$ coqtop -v
The Coq Proof Assistant, version 8.8.1 (October 2018)
compiled on Oct 9 2018 17:40:59 with OCaml 4.02.3
```

#### Operating system
MacOS High Sierra 10.13.6

#### Description of the problem

I was trying to rebuild my contribution PTSATR on my new setup, and I got the following error:
```
$ make
COQDEP VFILES
COQC final_result.v
File "./final_result.v", line 276, characters 0-33:
Error:
Anomaly
"File "vernac/assumptions.ml", line 74, characters 19-25: Assertion failed."
Please report at http://coq.inria.fr/bugs/.

make[1]: *** [final_result.vo] Error 129
make: *** [all] Error 2
```

(Note: I got a couple other errors prior to that one, but they were easily fixed)

The relevant statement is `Print Assumptions PTS_equiv_PTSe.`

**Comment by vsiles** [comment] 2018-10-30 09:36
Hi ! I used my old archive from http://www.lix.polytechnique.fr/~vsiles/coq/PTSATR.html
Can you point me to the ''new'' (I just saw that coq was on github a couple weeks ago...) contrib repository, so I provide a revision to reproduce it ?

**Comment by vsiles** [comment] 2018-10-30 09:47
Ok, then I'll move to 8.8.2 sooner than planned :D I'll check coq-community, thanks !

**Comment by herbelin** [comment] 2018-10-30 09:48
Duplicate of #8532

**Closed by herbelin** 2018-10-30 09:48 UTC
