### ISSUE TITLE
CoqIDE: wrong highlighting of error msgs?

### ISSUE THREAD

**Issue by orilahav** [coq/coq#13064] opened 2020-09-22 06:49 UTC
#### Description of the problem

"No applicable tactic" highlights an applicable tactic (a later non-applicable tactic exists).

![Screen Shot 2020-09-22 at 9 45 04](https://user-images.githubusercontent.com/14070781/93851387-b2131b00-fcb8-11ea-8375-3a689a34ab39.png)
![Screen Shot 2020-09-22 at 9 45 24](https://user-images.githubusercontent.com/14070781/93851392-b3444800-fcb8-11ea-9719-b00ae0ea6257.png)

#### Coq Version

8.12.0

**Comment by corwin-of-amber** [comment] 2020-09-22 14:46
I tested with `coqtop` (8.12.0) and I also see `simpl` as the error location.
```
Coq < Lemma aaa : 1 + 1 = 2.
1 subgoal

  ============================
  1 + 1 = 2

aaa < simpl; discriminate.
Toplevel input, characters 0-5:
> simpl; discriminate.
> ^^^^^
Error: Tactic failure: No applicable tactic.

aaa <
```

**Comment by ejgallego** [comment] 2020-09-22 15:34
Fixed in 8.12.1 , duplicate of #12773

**Closed by ejgallego** 2020-09-22 15:34 UTC
Labels: resolved: fixed in newer version
