### ISSUE TITLE
with Ltac Debug print function not found for a value interpreted as tauto_flags.

### ISSUE THREAD

**Issue by jmikedupont2** [coq/coq#18658] opened 2024-02-11 12:32 UTC
#### Description of the problem

Anomaly "print function not found for \
a value interpreted as tauto_flags."

Compiling code 

https://github.com/meta-introspector/metacoq/pull/2

#### Coq Version

The Coq Proof Assistant, version 8.20+alpha
compiled with OCaml 4.12.1

**Comment by JasonGross** [comment] 2024-02-11 18:32
Can we get a smaller example?
@coqbot minimize coq.8.16
```bash
git clone git@github.com:meta-introspector/metacoq.git --branch=feature/ltac_debug
cd metacoq
git checkout 1bc110910d49e2bcf3f3eb111527d4be0d4ad0c7
opam install --deps-only coq-metacoq
make
```

**Comment by JasonGross** [comment] 2024-02-11 18:33
Oops, I guess I'm using the wrong Coq version here
@coqbot minimize coq.dev
```bash
git clone git@github.com:meta-introspector/metacoq.git --branch=feature/ltac_debug
cd metacoq
git checkout 1bc110910d49e2bcf3f3eb111527d4be0d4ad0c7
opam install --deps-only coq-metacoq
make
```

**Comment by JasonGross** [comment] 2024-02-11 20:54
Should actually work this time
@coqbot minimize coq.dev
```bash
git clone https://github.com/meta-introspector/metacoq.git --branch=feature/ltac_debug
cd metacoq
git checkout 1bc110910d49e2bcf3f3eb111527d4be0d4ad0c7
opam install -y --deps-only coq-metacoq-utils
./configure.sh local
make
```

**Comment by SkySkimmer** [comment] 2024-03-13 14:55
Duplicate of https://github.com/coq/coq/issues/18660

**Closed by SkySkimmer** 2024-03-13 14:55 UTC
