### ISSUE TITLE
Extraction improperly erases Prop and proofs, incompatible with Module functors

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#10367] opened 2019-06-12 18:39 UTC
#### Description of the problem

Extraction of proofs and Prop sometimes completely erases the proof, rather than replacing it with a unit value.  Unfortunately this is incompatible with the module system.  The result is that Extraction can produce ill-typed ML programs.

For example, 
```
Inductive pos : Type :=  B: forall i:nat, lt 0 i -> pos.
```
is extracted to ML type `nat` rather than `(nat*unit)`.

Now I will show a test case that confuses the extractor:

```
Module A.
Inductive pos : Type :=
 B: forall i:nat, lt 0 i -> pos.

Definition inc (x: pos) : nat :=
 match x with B i p => i end.
Definition p := lt 0.
Theorem ok: forall i, lt 0 i -> p i.
Proof. intros; auto. Qed.
End A.

Module Type C.
Parameter p : nat -> Type.
Axiom ok: forall i:nat, lt 0 i -> p i.
Inductive pos : Type :=
 B: forall i:nat, p i -> pos.
Parameter inc : pos -> nat.
End C.

Module D (X: C).
Definition b : X.pos.
 refine (X.B 3 _). apply X.ok. compute. auto.
Defined.
End D.

Module E := D A.

Require Import Extraction.
Recursive Extraction E.
```

The resulting ML code is,
```
type __ = Obj.t
let __ = let rec f _ = Obj.repr f in Obj.repr f

type nat =
| O
| S of nat

module A =
 struct
  type pos = nat
    (* singleton inductive, whose constructor was B *)

  (** val pos_rect : (nat -> __ -> 'a1) -> pos -> 'a1 **)

  let pos_rect f p0 =
    f p0 __

  (** val pos_rec : (nat -> __ -> 'a1) -> pos -> 'a1 **)

  let pos_rec f p0 =
    f p0 __

  (** val inc : pos -> nat **)

  let inc x =
    x
 end

module type C =
 sig
  type p

  val ok : nat -> p

  type pos =
  | B of nat * p

  val pos_rect : (nat -> p -> 'a1) -> pos -> 'a1

  val pos_rec : (nat -> p -> 'a1) -> pos -> 'a1

  val inc : pos -> nat
 end

module D =
 functor (X:C) ->
 struct
  (** val b : X.pos **)

  let b =
    X.B ((S (S (S O))), (X.ok (S (S (S O)))))
 end

module E = D(A)
```

about which OCaml complains,

```                       
module E = D(A)
             ^
Error: Signature mismatch:
       ...
       The value `ok' is required but not provided
       The type `p' is required but not provided
```

**Comment by mattam82** [comment] 2019-06-12 18:47
This is a variant of the usual `Prop <= Type` problem, only made worse by the ability to do subtyping of inductive types.

**Comment by cstolze** [comment] 2019-06-19 12:51
Interestingly enough, one could expect the problem to be solved if you explicitly state that A : C, but then there is still a bug. Here is the minimal version I have:
```
Module Type C.
  Parameter p : Type.
  Axiom ok: nat -> p.
End C.

Module A : C.
  Definition p := True.
  Theorem ok: nat -> True.
  Proof. auto. Qed.
End A.

Module D (X : C).
End D.

Module E := D A. (* forces A to have type C *)

Require Import Extraction.
Recursive Extraction E.
```

Here, both p and ok are created:
```
type __ = Obj.t
let __ = let rec f _ = Obj.repr f in Obj.repr f

type nat =
| O
| S of nat

module type C =
 sig
  type p

  val ok : nat -> p
 end

module A =
 struct
  type p = __

  (** val ok : __ **)

  let ok =
    __
 end

module D =
 functor (X:C) ->
 struct
 end

module E = D(A)
```
But OCaml still complains:
```
Error: Signature mismatch:
       Modules do not match:
         sig type p = __ val ok : Obj.t end
       is not included in
         C
       Values do not match:
         val ok : Obj.t
       is not included in
         val ok : nat -> p
```

**Comment by pi8027** [comment] 2019-08-02 15:30
Duplicate of #5795

**Closed** 2019-08-08 17:12 UTC
Labels: part: extraction, resolved: duplicate(d)
