### ISSUE TITLE
Unused Context variables create floating universe variables

### ISSUE THREAD

**Issue by jdchristensen** [coq/coq#18200] opened 2023-10-23 16:12 UTC
#### Description of the problem

If an unused `Context` variable involves a fresh universe variable, then definitions in the `Section` depend on that universe variable, even when they don't depend on the `Context` variable.

```coq
Global Set Universe Polymorphism.

Section Foo.
Context (A B : Type).
Definition bar := A.
End Foo.
Set Printing Universes.
Print bar.
(*
bar@{univ2.9 univ2.10} =
fun A : Type@{univ2.9} => A
     : forall _ : Type@{univ2.9}, Type@{univ2.9}
*)
```

I would expect `bar` to depend on only one universe variable.

(This came up in a discussion a while back, but I can't remember where.)

#### Coq Version

8.18.0

**Comment by SkySkimmer** [comment] 2023-10-23 16:29
Duplicate of https://github.com/coq/coq/issues/10513

**Closed by SkySkimmer** 2023-10-23 16:29 UTC

**Comment by jdchristensen** [comment] 2023-10-23 20:22
Thanks for pointing out that this is a duplicate.  I did search the open issues, but my keywords didn't match that one.
