### ISSUE TITLE
`eval unfold x in x` does other reduction than unfolding x

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9634] opened 2019-02-23 02:53 UTC
#### Description of the problem

```coq
Definition x := 0.
Definition g := let x := x+x in x.
Definition f :=
  let x := x+x in let x := x+x in let x := x+x in
  let x := x+x in let x := x+x in let x := x+x in
  let x := x+x in let x := x+x in let x := x+x in
  let x := x+x in let x := x+x in let x := x+x in
  let x := x+x in let x := x+x in let x := x+x in
  let x := x+x in let x := x+x in let x := x+x in
  let x := x+x in let x := x+x in let x := x+x in
  let x := x+x in let x := x+x in let x := x+x in x.
Goal True.
  let t := eval unfold g in g in idtac t. (* (x + x) *)
  Timeout 1 let t := eval unfold f in f in idtac t. (* Timeout! *)
  exact I.
Qed.
```

#### Coq Version

8.9.0

@JasonGross has this always been the case?

**Comment by JasonGross** [comment] 2019-02-23 05:37
Yeah, I think this has been the case since at least 8.4.  Use `eval cbv delta [x] in x` to not do other reduction.

**Comment by Blaisorblade** [comment] 2019-11-21 20:03
@robbertkrebbers [suggested reporting](https://gitlab.mpi-sws.org/iris/stdpp/merge_requests/106#note_42140) the same behavior for the `unfold` tactic itself, but I expect it's the same issue. His testcase:
```
Lemma foo :
  let x := 10 in id x = x.
Proof.
  unfold id.
  (* BUG: goal is [10 = 10] instead of [id 10 = 10] *) 
```

**Comment by Blaisorblade** [comment] 2019-11-21 20:05
But FWIW, if this is intended, maybe it should be closed as "won't fix" or such?

**Comment by SkySkimmer** [comment] 2019-11-21 20:05
>  `(* BUG: goal is [10 = 10] instead of [id 10 = 10] *)`
You mean `instead of [let x := 10 in x = x]` right?

**Comment by Blaisorblade** [comment] 2019-11-21 20:14
@SkySkimmer Right, fixed above.

**Comment by SkySkimmer** [comment] 2019-11-21 20:17
I'm pretty sure this is intended, I made https://github.com/coq/coq/pull/11159 to clarify the doc.

**Comment by robbertkrebbers** [comment] 2019-11-21 22:05
> I'm pretty sure this is intended, I made #11159 to clarify the doc.

Why is this intended behavior? I don't see why the current behavior makes sense.

**Comment by ppedrot** [comment] 2019-11-22 07:32
@robbertkrebbers usually terms resulting from βι are deemed more *natural*, you don't get nasty trivial cuts. So I do believe this is the right behaviour for `unfold`. (Using ζ is a bit stranger though, although it's probably for historical reasons.)

**Comment by robbertkrebbers** [comment] 2019-11-22 07:37
Since one often uses `unfold f` when `f` is a function that is applied to some arguments, it makes sense to perform β. However, I don't understand why ζ makes sense.

**Comment by ppedrot** [comment] 2019-11-22 07:39
We can try to change it for βι alone if desired. I don't know how many developments this will affect though...

**Comment by robbertkrebbers** [comment] 2019-11-22 07:40
Maybe let me first ask another question, is there some other way to unfold a definition without normalizing the rest of the goal? (Apart from writing an explicit change by hand).

**Comment by robbertkrebbers** [comment] 2019-11-22 07:41
Oh, I should read this thread, @JasonGross gave the answer in https://github.com/coq/coq/issues/9634#issuecomment-466619154

**Comment by robbertkrebbers** [comment] 2019-11-22 08:41
Looking more carefully at this, there is quite a difference between the two examples in this issue:

1. In [@andres-erbsen's example](https://github.com/coq/coq/issues/9634#issue-413647424), `unfold x` reduces lets in the body of the unfolded `x`.
2. in [@Blaisorblade's example](https://github.com/coq/coq/issues/9634#issuecomment-557249708), `unfold x` reduces lets at totally different places in the goal.

For the first example, it is not so clear to me whether that is a good idea or not (changing the behavior will probably affect many existing developments, though). The behavior in the second example is much more weird, and I don't think it's desired. Basically, it shows that `unfold x` will affect the goal the arbitrary places that do not even involve `x`.

**Comment by gares** [comment] 2019-11-22 09:12
A way around overreduction is to focus a tactic using patterns.
```coq
rewrite [id]/id.
(*
1 subgoal
  
  ============================
  let x := 10 in x = x
*)
```
(you can localize also `/=`, FTR).

**Comment by robbertkrebbers** [comment] 2019-11-22 09:23
Thanks @gares I always forget about the focus patterns in the ssreflect rewrite.

**Closed** 2019-11-25 12:30 UTC
Labels: part: tactics
