### ISSUE TITLE
Problem with extraction of Decimal.v (the type int is redefined and masks OCaml's one)

### ISSUE THREAD

**Issue by SimonBoulier** [coq/coq#7017] opened 2018-03-19 13:19 UTC
#### Version

version 8.8+alpha (February 2018), c921825

#### Description of the problem

When I run the following:
```
Require Import Extraction BinPos.
Require Import ExtrOcamlNatInt.

Recursive Extraction Library BinPos.
```
And then I try:
```
ocamlbuild BinPos.cmo
```

It fails with `This expression has type int but an expression was expected of type Decimal.int`.

The problem is that `Decimal.v` redefines a type `int` and then the `open Decimal` masks the OCaml type `int`.

Should `int` be renamed as something like `coq_int`?

**Comment by maximedenes** [comment] 2018-04-11 17:38
@Zimmi48 is the milestone reflecting @letouzey's schedule on this? or why was it added?

**Comment by Zimmi48** [comment] 2018-04-11 20:09
I added the 8.8.0 milestone because this is a 8.8-regression / compatibility issue. Given that this file `Decimal.v` was added in 8.8, it would be very unfortunate to not address this before the 8.8.0 release. I had forgotten about it but I'll try to ask @letouzey to have a look at it tomorrow.

**Comment by maximedenes** [comment] 2018-04-12 15:58
@Zimmi48 what did @letouzey say about his schedule?

**Comment by Zimmi48** [comment] 2018-04-12 17:28
Unfortunately I didn't manage to see him and I had to leave early.

**Comment by maximedenes** [comment] 2018-04-16 06:53
I'll remove the milestone. @letouzey please put back one that reflects your schedule. Thanks!

**Comment by Zimmi48** [comment] 2018-06-09 15:09
We have a fix for this for 8.9. It doesn't seem that anyone is working on a backportable fix. So this issue should probably be re-targeted.

**Comment by maximedenes** [comment] 2018-06-09 19:01
> We have a fix for this for 8.9

Who is we?

**Comment by Zimmi48** [comment] 2018-06-09 22:11
You

**Comment by maximedenes** [comment] 2018-06-10 07:32
Ok, I was asking in case you had heard of another fix by Pierre. My "fix" breaks CompCert, so I need to figure out what to do.

**Comment by Zimmi48** [comment] 2018-06-17 11:41
Postponing.

**Comment by vzaliva** [comment] 2018-10-09 06:40
Because of this problem I was forced to downgrade to 8.7.2 to be able to use OCaml extraction. This is unfortunate as it has other problems such as https://github.com/coq/coq/issues/6614.

I think it is an important bug to address ASAP, not waiting for 8.9.

**Comment by maximedenes** [comment] 2018-10-09 06:42
I can look again at https://github.com/coq/coq/pull/7625 and try to make it mergeable.

**Comment by SkySkimmer** [comment] 2018-10-09 07:33
Why don't we just rename `Decimal.int` to something else? That can be done regardless of extraction becoming smarter about this sort of issue.

**Comment by vbgl** [comment] 2018-10-09 10:10
This can be seen as a bug in `ExtrOcamlNatInt.v`. It contains free variables: unqualified references to the type `int`, many operators like `( / )`, `( mod )` etc.

Unfortunately, this is not immediate to fix: the OCaml standard library does not provide unambiguous names to refer to these built-ins (see related issue https://github.com/ocaml/ocaml/pull/2011).

Suggestion: the extraction could generate (when needed) a support module that exports the OCaml built-ins under a qualified names.

**Comment by vzaliva** [comment] 2018-10-09 15:56
What about some facility which allows renaming types during extraction? So we can specify
to export Decimal.int as Decimal.coq_int.

**Comment by SkySkimmer** [comment] 2018-11-28 15:12
So what do we do with this?

**Comment by JasonGross** [comment] 2019-03-11 04:19
@SkySkimmer I just made a proposal at https://github.com/coq/coq/pull/7625#issuecomment-471399136 which might satisfy the relevant constraints:
> What about adding a command that lets users extend the blacklist? (Or using making the blacklist a setting so that users can `Set Extraction Blacklist Append ...` or whatever) Then the specific `ExtrOcaml*` files can add the types and functions they use in extraction to the blacklist, and since CompCert does not use ExtrOcamlNatInt, it will not be impacted by this change.

**Comment by mattam82** [comment] 2019-07-24 21:51
@JasonGross that would be nice indeed. I think an extension of Blacklist will have to come.

**Comment by liyishuai** [comment] 2019-10-17 04:26
`bool` is also affected. I can't afford doing the same to `bool` as QuickChick/QuickChick@dadabe5971ed87d78c6653c5abe3d3a20a8f1c35 any more.
```coq
From Coq Require Import ExtrOcamlString.
Extraction TestCompile Ascii.N_of_ascii.
```
```
Error: This expression has type bool/2 but an expression was expected of type
         bool/1
       File "/tmp/testextraction79735d.ml", line 2, characters 0-26:
         Definition of type bool/1
       File "_none_", line 1:
         Definition of type bool/2
Error: Compilation of file /tmp/testextraction79735d.ml failed with exit code 2
```

**Comment by vbgl** [comment] 2019-10-17 06:21
As a workaround, if you target OCaml ≥ 4.08, you can add that command before your extraction command:

~~~
Extract Inductive bool => "Bool.t" [ "false" "true" ].
~~~

**Comment by pochinha** [comment] 2020-09-21 10:31
> @vzaliva, there is a workaround found by @liyishuai in [QuickChick/QuickChick@dadabe5](https://github.com/QuickChick/QuickChick/commit/dadabe5971ed87d78c6653c5abe3d3a20a8f1c35).
> 
> Simply add the following line before the command Extraction:
> 
> `Extract Inductive Decimal.int => unit [ "(fun _ -> ())" "(fun _ -> ())" ] "(fun _ _ _ -> assert false)".`

But this only works if you don't actually use Decimal.int in your code, right? If you do, is there any proposed solution?

**Closed** 2021-12-01 09:59 UTC
Labels: part: standard library, part: extraction, kind: regression, wellknown: the int clash extraction problem
