### ISSUE TITLE
`constr_eq Prop Set` succeeds

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#7310] opened 2018-04-19 15:51 UTC
#### Version

~~~
The Coq Proof Assistant, version 8.8.0 (April 2018)
compiled on Apr 18 2018 14:30:24 with OCaml 4.06.0
~~~

#### Operating system

Arch Linux, up to date as of yesterday.

#### Description of the problem

Ltac `constr_eq` seems to be identifying `Prop` with `Set`, making it not a subrelation of convertibility. I would expect the first `constr_eq` below to fail because the next two lines should fail, and I would expect the second `constr_eq` to fail as long as the next two lines fail.

~~~~~~~~~~
Set Printing Universes.
Goal False.
  constr_eq Prop Set.
  Fail unify Prop Set.
  Fail assert (Prop = Set) by reflexivity.

  constr_eq Prop Type.
  Fail unify Prop Type.
  Fail assert (Prop = Type) by reflexivity.
~~~~~~~~~~~

**Comment by SkySkimmer** [comment] 2018-05-04 08:58
Duplicate of  #7421.

**Closed by SkySkimmer** 2018-05-04 08:58 UTC
Labels: kind: regression, part: universes
