### ISSUE TITLE
The refman does not mention `string(...)` for `Tactic Notation`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#11207] opened 2019-11-28 15:12 UTC
#### Description of the problem

at https://github.com/coq/coq/blob/master/doc/sphinx/user-extensions/syntax-extensions.rst#tactic-notations

```rst
.. productionlist:: coq
   tacn                 : Tactic Notation [`tactic_level`] [`prod_item` … `prod_item`] := `tactic`.
   prod_item            : `string` | `tactic_argument_type`(`ident`)
   tactic_level         : (at level `num`)
   tactic_argument_type : ident | simple_intropattern | reference
                        : hyp | hyp_list | ne_hyp_list
                        : constr | uconstr | constr_list | ne_constr_list
                        : integer | integer_list | ne_integer_list
                        : int_or_var | int_or_var_list | ne_int_or_var_list
                        : tactic | tactic0 | tactic1 | tactic2 | tactic3
                        : tactic4 | tactic5
```

This is missing `string` under `tactic_argument_type`.  Probably also `string_list` and `ne_string_list`.

#### Coq Version

master (https://github.com/coq/coq/commit/b4eca882b6692b6374dfff8517f9f5a5cc4970f5)

**Comment by ppedrot** [comment] 2020-02-03 15:55
Duplicate of #3081

**Closed by ppedrot** 2020-02-03 15:55 UTC
Labels: good first issue, kind: documentation
