### ISSUE TITLE
What does time for discussion mean?

### ISSUE THREAD

**Issue by herbelin** [coq/coq#7042] opened 2018-03-22 11:28 UTC
I'm opening this issue to centralize a discussion started at #7023 and which has no reason to be continued there.

Summary: in the last few years, it has been made clear at various occasions that communication targetting the whole development team was expected so that the opinions, suggestions, needs of everyone in the team could be taken into account whenever wanted. (*)

In the period when @maximedenes was merging PRs, it has been made clear (e.g. #5986) that both predictability of when a PR is merged was important and that a more "agile" merging which a single person is not able to give was necessary.

With the new merging process, we have an opportunity to improve on both issues: being more agile by distributing the process, being more structured in the protocol we use. And we have actually no choice than being more structured so that every "merger" knows clearly how to proceed in a way which is consensual.

To satisfy the need for a clear communication (*), which, again, various events show in the past that this is required for everyone in the team to feel his words and needs respected, the option that I'm proposing is to put some temporal guidelines to frame our discussions, as it is common to do in many collective processes (see also Robert which @silene mentioned at some time).

I'm not saying that we need to have a heavy frame and the lighter it shall be, the best it shall be. I'm only saying that we need to give time and space to enough discussions so that anyone can feel that his/her opinion is admissible if there is one, as several of us already asked in the past.

For instance, a light way to proceed in situations like #7023 would be that running the merging script starts a daemon that shall merge the PR after 24h and add a comment of the following form to the PR discussion: "Merging will be processed in 24h. If you see anything wrong with this PR and want to add something, it shall be more convenient that you do it in the next hours than later on" (or any other formulation which everyone would feel comfortable with). 

Let me now answer to some comments posted at #7023:

From @maximedenes:
> > the question of minimal/maximal time has been asked several times and we shall not escape to eventually address it
> 
> It has been addressed many times in working groups after you raised it, and the answer was, as I understood it, "no fixed minimal delay".

You are not answering to my question. My question is: "where do you leave explicit time for discussion", a time for discussion which you were among those to ask several times in the past regarding my own PRs, even for bug fixes.

From @maximedenes:
> That's too heavy for a daily merging process. Like @ejgallego said, we are already at the limit with the current process that asks all concerned maintainers for approval. Please don't make it even heavier.

I'm not trying to make it heavier (see e.g above a proposition). I'm trying to improve the way we interact in the team (and maybe I'm failing too, but then, I'd be happy to have your help to improve my own way of expressing what I have to say). As for making things lighter on other directions than the one I'm talking here, I let you do propositions.

> You say yourself that there was no problem here, so why exactly are you complaining?

I'm not complaining on the PR, which again, I find relevant. I'm trying to find a model on which we all agree, and this was the first PR to be committed along the new scheme, so the first PR to discuss about the process and about how to implement the expression "discussion converge" which I proposed and which you agreed.

> I have a strange feeling that this has been said many times already. Could we move on and invest our energy in more productive ways?

Noone is asking you to put your energy in this issue if you don't want to. As far as I'm concerned, I don't think that a good solution has been given yet and I try to find one. Is the kind of courtesy I'm asking for really supernatural?

From @Zimmi48:
> But honestly, I feel that you should first give a few days or a few weeks so that we see how the process is going and we can judge better whether the amendment is a good idea.

We all know that giving space and time for interaction is important, there were enough situations in the team where it mattered, and we can easily observe that it matters in all kinds of social interaction, not only in the team. We can spend time about whether there was enough space for potential discussions in #7023 or not, but this is not my point. The past has shown, in particular wrt my own PRs, that thinking that everything seems in order from one's point of view does not mean that everything is in order for everyone, and we have to take this into account. I would not like to go the other way round myself, as I believe that this would be a pity for the team that, on the name of agility, I start again to commit things, even bug fixes, without enquiring about the opinion of others.

**Comment by ejgallego** [comment] 2018-03-22 13:42
My point of view is that a change can be discussed 1 minute after it is submitted or 10 years after it is merge, discussion somehow doesn't seem to me so strongly coupled with merging.

I guess we have now:
a) discussion time until the maintainer of the current subsystem agrees to merge. This will range from close to 0 [straightforward fixes] to many months in the case of complex changes.
b) discussion time after the maintainer has merged [or the PR has been closed]. In this case discussion can happen anytime.

**Comment by herbelin** [comment] 2018-03-22 14:16
@ejgallego: I have a vague feeling that your position changes according to the circumstances. You were one of the most ardent defenders at some time that even simple bug fixes are by default reviewed and commented by anyone is wishing to do so (which means allocating a time span for that). Are you e.g. not anymore interested in having the time to look at the PRs I would merge before I merge them? 

You were one of those who were [asking](#5986) for more predictability about "if [a] PR will be merged and when". With my proposal, there is an announcement, say 24h in advance, of the time of merge, so that you can organize your schedule in function of this announced time. Are you not anymore interested in such improved predictability?

**Comment by ejgallego** [comment] 2018-03-22 14:24
@herbelin your feeling is wrong, but indeed my confusion about what you do mean is actually monotonically increasing. I think the problem maybe is that I think this assumption:

> which means allocating a time span for that

in indeed inconsistent. Things can be reviewed instantly [trivial bug fix], so no, you don't need to allocate a time span for reviews.

In my model "review != time span". So I say review, yes, time span, I think it is **difficult** to come up with a time span. 24h seems a bit arbitrary to me. I guess common sense should be enough here, even tho I agree with your general idea of making sure we arrive to a good consensus over merges.

**Comment by ejgallego** [comment] 2018-03-22 14:32
> Are you e.g. not anymore interested in having the time to look at the PRs I would merge before I merge them?

Every PR should get a review, but that's a kind of a hard precondition. Of course, if some other developer does a review consensus can be reached without my participation. Distributed consensus is hard and I have the feeling that such a simple rule is not gonna change things a lot.

But let's go back to you concrete case. Someone submits a PR, you review it, and you think it is OK, and merge. Common sense would mean that as maintainer, you would leave more time for more complex PRs, and even ping / wait for other people who could be interested in having a look. In that sense, as a maintainer, you have become a **coordinator** too.

But let's continue, imagine you get a PR, you review it, you consider than my input is not necessary, and you merge. That seems pretty fine to me. I will still see the PR later or sooner, and I have some comment I'll open an issue or as in the PR itself. Maybe I realize too late, that's life, we can't be perfect.

But I don't see a problem with that as I think all maintainers have a sufficient understanding of their system as to take the correct decisions.

> I have a vague feeling that your position changes according to the circumstances.

As Alejandro Jodorowsky wrote "Una persona inteligente se permite contradecirse." so obviously dumber ones as myself have undoubtedly that right.

More seriously, my position on this is not static, and what I may think today is a good idea it may turn out that tomorrow reveals itself as pretty bad. Here we are talking about social and development dynamics and that's a big unsolved question.

**Comment by herbelin** [comment] 2018-03-22 15:47
> Things can be reviewed instantly [trivial bug fix], so no, you don't need to allocate a time span for reviews.

Well... This morning, I don't know if it should be considered a trivial bug fix or not but I reviewed #7016. In about 2-5 minutes, I started to understand what was the point and I started to write a comment, betting on the responsiveness of @skyskimmer to answer my question quicker than what I would require myself to fully understand the PR. While he was answering, I could not stop my brain to continue thinking at the PR, and at whether my understanding was fully correct (it was not, there were 2 key lines: the move of the test to `Flags` from one point to another, as @gares has said in a former high-level comment). Altogether, it took me maybe 15 minutes thinking at this PR and such 15mns start to have some thickness in a day.

About dispatching the work and trusting each other, it seems that I'm one who is spontaneously trusting the most easily, or, at least, I received comments telling that I was trusting too much. On the other side, I appreciate having an extra look at PRs before merging, so as to quickly have an overview of whether everything is going well, in technical or even simply in human-level terms, and I need time allocated for that.

But ok, let's go in the direction of giving priority to fast merging and to consider that dispatching responsibilities is more important than ensuring a collective discussion. Now, how do you implement the case of a disagrement after a merge. In the past, I received capital letters, I received aggressive comments from various persons. Do you think our team is now mature enough so that people who see a merge they disagree with are able to express their disagreement in courteous and constructive terms? I'm not convinced about it, and I prefer that we anticipate and let time for discussion in advance.

Another argument for letting time for last checks before merging is that intervening after a merge is more demanding than before a merge. If I see a typo, say a missing "s" somewhere, I may probably not add the burden of a new PR just for a typo. While if I see it before a merge, I would worry less about mentioning the typo.

Well, we could discuss for long... I'm not saying that I have an absolute answer to what should be done, but based on the past experiences, I'm more enclined to think now that if we could combine swiftness with a collective breathing time between a ready-to-merge-from-the-assignee-point-of-view and an effective merge, even for bug fixes, that would be better than only swiftness.

> Here we are talking about social and development dynamics and that's a big unsolved question.

Yes, it is difficult question...

**Comment by ejgallego** [comment] 2018-03-22 16:04
> This morning, I don't know if it should be considered a trivial bug fix or not but I reviewed #7016.

Umm, IMVVHO this is distant from a "trivial bug fix". I'd classify it as "quite tricky stuff".

But I think you make a good point, but on the other hand I get the feeling that you may be overthinking the process a bit. Maybe I have an easier time as I assume there will never be a perfect process so errors will be made, so I am more interested in fact to increase the tolerance/recovery for errors than in preventing them.

> About dispatching the work and trusting each other, it seems that I'm one who is spontaneously trusting the most easily, or, at least, I received comments telling that I was trusting too much.

Sure, there is a delicate balance in reviews, but here it is a personal criteria. I was also criticized by approving PRs such as #873 , but I found that criticism quite misguided, I had a look to it, computed my tradeoff, and said "it looks OK to me". There was problem? Fine, but not a big deal, the problem is either fixed or the change is rolled back. 

> But ok, let's go in the direction of giving priority to fast merging and to consider that dispatching responsibilities is more important than ensuring a collective discussion.

I think nobody is proposing to "give priority to fast merging", but more on the lines of "fast merging should be possible".

Note the difference between the two statements. I agree with the spirit of your proposal "every PRs should receive the **right** amount of discussion", however I am not so sure:
- we have a problem here in the first place: it seems to me that the large majority of PRs are receiving a fair amount of discussion,
- that some kind of "formal time system" is the right tool for that. I'd rather trust the person in charge of the subsystem to determine when the amount of required discussion has been reached.

> Now, **how do you implement the case of a disagreement after a merge**. ...

I guess that's fairly easy, you would just open an issue or add a comment in the PR expressing your concerns. Whether a patch has been merged or not doesn't seem very relevant to me in this context.

**Comment by Zimmi48** [comment] 2018-03-22 21:50
Hugo, I can see a **fundamental flaw** in your reasoning, a **huge confusion** in most examples you give in this thread: Your examples are ones when you committed fixes without asking anyone. You still have a vivid memory of the rude way in which this was received. But this practice is definitely banned. No one can merge their own PR. No one can commit to master directly.

When a maintainer merges a PR according to the new process, however fast it may be, it is a PR someone else has opened. Thus there is agreement of at least two people (and not just any two persons, one of them at least is a maintainer). There is a review! It's not comparable at all with the examples you have where there wasn't any review.

Thus while you may be right about expressing a need for letting discussions happen, I can't follow the reasons you give. They do not illustrate the concern at all. Please come back with a real example of something which didn't work while following the merging process.

**Comment by maximedenes** [comment] 2018-03-22 21:52
> at least two people

More than that, maintainers of all impacted components have to agree.

**Comment by Zimmi48** [comment] 2018-03-22 22:05
I wonder whether your confusion in the case of the PR of @maximedenes that was merged by @gares comes from the fact that these two developers are located at the same place and thus you tend to see them as the same person. So it seems to you like this change was merged without discussion, similarly to the case where one merges their own PR. But they are indeed two distinct developers who can disagree from time to time even if they are close.

**Comment by ejgallego** [comment] 2018-03-22 22:12
Well Hugo has a point in the sense that we tend to overreact we also get burnt out from time to time :)

> More than that, maintainers of all impacted components have to agree.

So I wonder what's the role of the RM here? In a sense, the RM should be a bit special here with larger-scale commits?

**Comment by herbelin** [comment] 2018-03-23 09:38
> Hugo, I can see a fundamental flaw in your reasoning, a huge confusion in most examples you give in this thread: Your examples are ones when you committed fixes without asking anyone. You still have a vivid memory of the rude way in which this was received. But this practice is definitely banned. No one can merge their own PR. No one can commit to master directly.

Vivid memory certainly but fundamental flaw and huge confusion seem to me a bit strong :)

First, I do not see anything wrong _per se_ in what I was doing. It is wrong only from the moment that some people are interested in discussing what I'm doing. It is not wrong as long as there is an agreement that this is a normal way to proceed. For instance, many improvements of the code architecture have been made by @ppedrot using the protocol which we used at that time and it is not clear that he could be able to do it as easily with the current procedures.

Second, the example of #7016, as you say, is pretty much in the category of "without asking anyone" besides that it concerns not one but two people used to work together (and the sentence "maintainers of all impacted components have to agree" that @maximedenes added does not change anything to the case of #7016, since, even with this latter sentence, it is still two people used to work together).

Third, I do not see anything wrong per se in "No one can merge their own PR. No one can commit to master directly.". This is just a convention and other development teams don't see it as a necessary rule (including in some companies developing very high quality softwares, as far as I've been told). And I don't see why "No one can merge their own PR. No one can commit to master directly." would be better than "No one can merge their own PR but everyone can merge the PR of his/her roommate. No one can commit to master directly but everyone can have his code committed directly to master by his/her roommate.".

> So it seems to you like this change was merged without discussion, similarly to the case where one merges their own PR. But they are indeed two distinct developers who can disagree from time to time even if they are close.

First, my demand was not about #7016 in particular, it was about the concrete implementation of "discussion converge". And in the case of #7016, I did not say that it was merged without discussion. I said that it was merged without asking whether there were further comments about it. Imagine that I discuss with @mattam82, that we decide to prepare a fix for something, that he submits the fix as a PR, that I click the approve button and that I commit the fix in the next few hours without asking anything to anyone else? Is that the model that you want to justify? It is coming back to the model we had before, where, 1. at the technical level, we were discussing a posteriori when some of us was seeing a problem 2. at the human level, people easily tended to feel excluded. If this is what you are advocating for, I'm ok to come back to this model, but I'm not sure that this is really what we want, collectively.

> Please come back with a real example of something which didn't work while following the merging process.

If I felt as saying "didn't work", then I withdraw what I said. What I meant is that I'd like that we clarify as early as now what discussion mean in the context of the group. You're saying that I was committing without asking anyone in the past. Then, I take it first degree and ask that asking everyone is clearly part of the protocol.

The optimism and enthousiasm of @ejgallego almost convinced me that the general state of mind was now that we can trust each other, that we can commit PRs of officemates without having to inquire that someone else has comments to do, without having to fear that someone feels excluded, and, in case of comments to do after the merge, that this shall be treated courteously. Do you confirm that this is the new state of mind? If so, even it seems to me to be a regression, I'm ready to follow it.

Now, let me tell also the following. @maximedenes and you are making a lot of efforts to define rules which you think are good for the group and my vague impression is that you feel that I'm ungratefully making a lot of efforts to always being unsatisfied with the rules that you are trying to put. If it is so, then, this means that we shall have to discuss much more than what we are currently doing. It is probably true that I'm someone who is spontaneously inclined to always question and go beyond what seems nevertheless assured (and I believe that it is a normal attitude in a scientific context). But I'm also ok with rules which help a group to work together. So, some form of agreement should certainly be reachable at some time, no?

**Comment by maximedenes** [comment] 2018-03-23 09:54
> Second, the example of #7016, as you say, is pretty much in the category of "without asking anyone" besides that it concerns not one but two people used to work together (and the sentence "maintainers of all impacted components have to agree" that @maximedenes added does not change anything to the case of #7016, since, even with this latter sentence, it is still two people used to work together).

What are you talking about? There are 4 code owners assigned for #7016.

**Comment by Zimmi48** [comment] 2018-03-23 09:55
I think @herbelin was referring to the wrong PR and FTR I am writing a more complete answer.

**Comment by maximedenes** [comment] 2018-03-23 09:56
Ok, very good, I can go back to actual work then :)

**Comment by Zimmi48** [comment] 2018-03-23 10:11
For a logician the following sentence surprises me a lot:

> You're saying that I was committing without asking anyone in the past. Then, I take it first degree and ask that asking everyone is clearly part of the protocol.

The negation of "not asking anyone before committing" is not "asking everyone before committing".

-----

That being said, **I feel very good** when reading your answer because **I was spot on** with https://github.com/coq/coq/issues/7042#issuecomment-375472806 and **your answer to this now dissipates a big confusion**.

Indeed, it was clear to you but unclear to everyone else why you compared the time when you pushed commits on your own with the way this PR (#7023, not #7016) was merged. The reason was indeed that it seemed to you like the change was not discussed because it was proposed and merged by two people who are very close in location and very often work together. So it looked indeed to you like a change that wasn't properly reviewed and discussed.

> The optimism and enthousiasm of @ejgallego almost convinced me that the general state of mind was now that we can trust each other, that we can commit PRs of officemates without having to inquire that someone else has comments to do [...] Do you confirm that this is the new state of mind? If so, even it seems to me to be a regression, I'm ready to follow it.

No, I don't.

> So, some form of agreement should certainly be reachable at some time, no?

I fully agree: we have to reach some form of agreement on what's the right process.

**So I propose that we amend the merging doc**, not to talk about delays (for now, it doesn't seem necessary to me) but to explicitly say that when a fix was prepared together with another person, this should be mentioned and this other person should not be the one to merge a PR (similarly to a case where you and I would prepare a fix together then I would submit it: I would need to make clear that it was prepared with you and you should not be the one to merge it).

Would this amendment to the doc look like a good first step to you? And does it look acceptable to @maximedenes?

PS: in the case of the incriminated PR, my personal understanding is that it was indeed not specifically discussed offline by @gares and @maximedenes and thus it was not going against this new rule that I propose to add.

**Comment by maximedenes** [comment] 2018-03-23 10:27
A few remarks:
- it is hard for me to prove I'm not the same person as @gares. On the other hand, it's easy to show we can disagree (which is what matters I guess). For example, @gares likes French coffee, I hate it.
- I'm not sure what problem we are trying to solve here. @gares and I didn't make the fix in #7023 together. I made the fix alone, after a discussion involving other developers.
- asking to add one more bureaucratic rule to get three levels of review when people do pair programming seems a bit beyond the resources we have. Why not instead let the authors choose if they feel they need a third pair of eyes?

Again, what is the problem we are trying to solve? The discussion started with #7023 and finished with a proposal that would not even apply to it...

**Comment by Zimmi48** [comment] 2018-03-23 11:03
> asking to add one more bureaucratic rule to get three levels of review when people do pair programming seems a bit beyond the resources we have. Why not instead let the authors choose if they feel they need a third pair of eyes?

My feeling about this is that this is in the same category as "Maintainers MUST NOT merge their own patches". Pair programming means that there are two authors, even if one of them only submits the PR. The reviews must always be done by someone else to ensure some kind of distance with the patch (it's hard to review one's own patch).

I don't think it would add so much "bureaucracy" because it is not a very frequent occurrence. However, I feel it would dissipate any misunderstanding and claims for lack of discussions. But of course, I would also need Hugo to confirm that this clarification would satisfy him. (I'm looking for a "fix" to this "issue" that is consensual.)

**Comment by ejgallego** [comment] 2018-03-23 12:56
Going back to the original topic of this issue, my view is that:
- discussion time should be determined by the merger / shepherd and be reasonable as to ensure everyone that should have a look does. I don't think a formal rule can be done, but I am in favor of adding this step as a merge "checkpoint".
- there is nothing bad in trying to be eager sometimes, but of course we should all have common sense as it boils down to a personal interpretation.
- requirement that all "owners" approve a PR is in many cases too strong, so it should be the assignee who decides which owners have to approve a particular PR.

> I do not see anything wrong per se in "No one can merge their own PR. No one can commit to master directly.". This is just a convention and other development teams don't see it as a necessary rule (including in some companies developing very high quality softwares, as far as I've been told). And I don't see why "No one can merge their own PR. No one can commit to master directly." would be better than "No one can merge their own PR but everyone can merge the PR of his/her roommate. No one can commit to master directly but everyone can have his code committed directly to master by his/her roommate.".

> Imagine that I discuss with @mattam82, that we decide to prepare a fix for something, that he submits the fix as a PR, that I click the approve button and that I commit the fix in the next few hours without asking anything to anyone else? Is that the model that you want to justify?

I think you are missing the point here and being too literal of rules that are not mathematical rules, but "directives". The idea indeed of having all changes go through a review phase CI phase was suggested in the spirit to avoid the codebase to become stale such that regular users would not be able to use the master branch.

You can keep that spirit by merging your own PRs, or you can be totally unfaithful to that spirit even by following the rules to the millimeter. The idea here is to put usability and stability above personal development strategies.

Regarding complaints of the past, I guess you were unlucky that your patch broke the CI, bad luck I guess, such is life XD

**Comment by gares** [comment] 2018-03-23 20:18
For once I agree with Emilio more than Maxime does. It counts way more than the French coffee urban legend... Good we fellas!

**Comment by maximedenes** [comment] 2018-03-23 21:00
@gares I think it is obvious that you are trying to show you can disagree with me here :D

Unluckily, I also agree with @ejgallego.

**Comment by ejgallego** [comment] 2018-03-23 22:05
Agreement changes depending on the circumstances so of course it is not transitive thus all that we have is, have all a nice weekend!

**Comment by herbelin** [comment] 2018-03-24 19:38
I (also) basically feel in agreement with @ejgallego, in the sense that I prefer simplicity to bureaucracy and cheerfulness to uncourteous words (even if I still feel guilty for a memorable big anger I had in winter 2015 at a period of time where I was unable to find the right words to express what I felt).

On the other side, I'm unsure that it is fully fair to identify direct commits to the archive with "personal development strategies". The time we were committing directly to the archive was a time where we cared about the usability of master as much as we do now, even if the tools were not as sophisticated as CI is. Contrastingly, we also know that CI is not absolute in preventing to merge commits breaking the tests and we also know that "relecture"/"re-reading" is not an absolute guarantee that we are not committing bugs (I'm using "relecture" to distinguish from "evaluation", which is the way the word "review" is thought in general in academy I think, while it seems that in the context of GitHub, "review" should rather be thought as "relecture" - surveying in English?). But, well, it seems that we missed to understand the constructive contents of some of the messages that some of us were trying to convey as the constructive part of these messages was sometimes, and I hope nobody will be angry that I'm saying that, obfuscated and hidden beyond a use of confrontational or reproaching words.

Now, about the real questions:

> I'm not sure what problem we are trying to solve here.

The discussion was about the need for discussion. It turns out that it goes into two parts, a human one and a technical one.

On the human side, the question is how we want to address situations of the form "What! you committed that and you did not inform me. I disagree with that, the good approach was this one". Do we want to try to anticipate this? The same way as we use CI to prevent the risk of buggy commits, are there simple procedures which would allow to anticipate and protect against misunderstanding coming from a lack of discussion?

On the technical side, the question is how we want to address situations of the form "Ah, I was just going to read this and I saw that there is a mistake here, but it was merged before I had time to say anything. That's a pity". The same way as we use reviews to catch more mistakes in advance, can we catch more potential problems by giving a time structure for receiving comments. Compare to the "Robert" procedure, compare to public benefit inquiries when a public project is ongoing, etc.

> asking to add one more bureaucratic rule to get three levels of review when people do pair programming seems a bit beyond the resources we have. Why not instead let the authors choose if they feel they need a third pair of eyes?

I also feel that we are at the limit of the resources that we have and that we should avoid more bureaucracy than what we already have. I had a simple proposal above which is that the merge script is automatically introducing a delay standing for a "publication of banns" (at least for regular merges, since there are also administrative merges which may require acting quickly).

Another proposal, which goes in the direction of less bureaucy than now is the following. First, we make a difference between PRs from core developers and PRs from occasional contributors. For the latter, we proceed as now. For the former, we do the following: on one side we let the author/s explain/s what kind of review she/he/they expect/s, what parts of his/her/their code she/he/they would like to be quickly checked and which parts she/he/they would like to be thouroughly checked; on the other side, anyone willing to do either a quick check or a thorough review (or anything inbetween) is also free to do, independently of the will of the author.

And finally, about the logical puzzle:

> The negation of "not asking anyone before committing" is not "asking everyone before committing".

Indeed... I intended an interpretation of "not asking anyone" as "not asking the group" more than as "not asking at least one person". And I guess that you intended roughly the same... Well, we should now define what "group" means... (but I'm exhausted now).

PS: why are GitHub's basic smileys (e.g. :smile: or :tired_face:) so "ugly" (compared e.g. to Skype's ones).

**Comment by ejgallego** [comment] 2018-03-25 00:21
Hugo (@herbelin) thanks for your comments. Indeed, I do fully agree with "the spirit" of both your proposals and comments, however I am not sure I fully understand the implementation details you propose.

I don't think I can add a lot more, other than that my personal view is indeed an "optimistic" one. Even if as of today there still is some work to do in order to be sure we are all in the same "wave", I am totally positive about the fact that we will reach synchrony pretty soon, of course after doing some more experimental tries.

As the number of contributors and styles grows, a fruitful challenge of convergence appears, but that seems an interesting scenario to be involved with.

**Comment by ejgallego** [comment] 2018-04-29 23:42
I also feel here that this discussion has come to a kind of satisfactory end; with the new system in place discussion seems to be quite fluent and problems with specific subsystems should be deferred to their own issue.

Thus, I propose to close.

**Comment by ejgallego** [comment] 2018-06-02 20:21
One month is enough IMO.

**Closed by ejgallego** 2018-06-02 20:21 UTC
Labels: kind: meta

**Comment by herbelin** [comment] 2018-07-15 09:38
To avoid repeating situations like #7920 where the merging decision of an obviously delicate PR has been done in an anticipated way with a notice of only 75 minutes, I consider that a notice of at least one working day should preventively be the default rule, and immediacy be only the exception. Moreover, I'm pretty sure that this preventive delay shall be mostly neglictable compared to the average merging time of a PR, which is one more reason not be afraid of ensuring such a delay.

**Comment by ejgallego** [comment] 2018-07-15 12:10
Indeed the merge of #7920 was not done in proper procedure and that situation should not happen again, indeed in a soccer match that would be a "yellow card".

But so far that case seems to be an exceptional situation, IMHO the new merging process is working reasonably well, and if anything we are leaving far too much time for people to discuss due to lack of assignee manpower.

**Comment by maximedenes** [comment] 2018-07-15 12:43
> Indeed the merge of #7920 was not done in proper procedure and that situation should not happen again, indeed in a soccer match that would be a "yellow card".

What is this claim based on?

Quoting you on the corresponding PR:

"I think we made it clear that the PR can be merged now and no need to put a deadline or whatever."

**Comment by ejgallego** [comment] 2018-07-15 13:18
OK maybe you both have a point. Certainly we were not communicating very well in that mess.

I mean the yellow card as a world cup joke but now reading again I can see the bad meaning so I take it back. Indeed both interpretations are possible.

Back to the point of this issue, I am not sure I feel we have enough ground to reopen it, but we can see.

**Comment by Zimmi48** [comment] 2018-07-15 21:52
Reacting to both Hugo and Emilio's comments: as @mattam82 and I already told Hugo, the merge was done in respect of the procedure: the PR had received 4 approved reviews and no request for changes. It may have been wiser to give a 24-hour notice of the merge, but given that @maximedenes had tried for more than a week to get a clear answer on whether to merge or not, and thought he had got one, I can understand his action. In the future, it would be wiser that the people who don't want a PR to be merged use either the "request for changes" feature or the "needs: discussion" label, and that the person who is planning to merge a PR where a lot of discussion / debate has happened give a 24-hour notice.

**Comment by maximedenes** [comment] 2018-07-15 21:58
> and that the person who is planning to merge a PR where a lot of discussion / debate has happened give a 24-hour notice.

Sounds good, maybe even a working day.

**Comment by Zimmi48** [comment] 2018-07-15 22:40
Should we write this advice in the merging doc?
