### ISSUE TITLE
Assertion failure on => tactical after 'match goal'

### ISSUE THREAD

**Issue by hanazuki** [coq/coq#6716] opened 2018-02-08 05:35 UTC
#### Version

version 8.7.1

#### Operating system

macOS 10.13

#### Description of the problem

Coq stops when using `match goal with ... end => ...` tactic from ssreflect.

example.v:
```coq
Require Import ssreflect.

Goal True.
match goal with _ => idtac end => //.
Qed.
```

```console
% coqc example.v
File "./example.v", line 4, characters 0-37:
Error:
Anomaly
"File "plugins/ltac/tacinterp.ml", line 1157, characters 35-41: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

**Comment by hanazuki** [comment] 2018-02-08 08:02
Other ssreflect tacticals with match also fails on the same assertion.

```coq
by match goal with _ => idtac end.
do !match goal with _ => idtac end.
match goal with _ => idtac end; first idtac.
```

**Comment by cmangin** [comment] 2018-02-08 08:34
This is a duplicate of #2800, and not specific to Ssreflect.

**Comment by ppedrot** [comment] 2018-02-12 19:11
Closing this bug then.

**Closed by ppedrot** 2018-02-12 19:11 UTC
