### ISSUE TITLE
Porting coq-plugin-lib from coq 8.9 to coq 8.10

### ISSUE THREAD

**Issue by agrarpan** [coq/coq#17895] opened 2023-07-27 18:21 UTC
I want some help trying to port this plugin. Here's a [draft PR](https://github.com/agrarpan/coq-plugin-lib/pull/1) with most of the type errors fixed.

**Comment by tlringer** [comment] 2023-07-27 18:30
Thanks for posting this! A bit more context:

- This is the library used in both PUMPKIN PATCH and PUMPKIN Pi, which are also stuck on 8.9 right now.
- Last time we tried to port from 8.9 to a later version, unification changed in a way that broke the other plugins, even after we fixed all of the type errors. We were not able to resolve this. So we should think carefully about everything involving unification, universes, and so on.

**Comment by tlringer** [comment] 2023-07-27 18:31
@agrarpan where are your remaining type errors?

**Comment by SkySkimmer** [comment] 2023-07-27 18:57
>This is the first port in a series; we'd like to get this up to the latest Coq eventually.

I wonder if this is the better approach or if it would be better to port directly to latest. Porting release by release means less changes to deal with at a time (probably), but may also mean having to deal with 1 API going through multiple changes in the different releases such that doing it all at once would be easier. We may also hope that newer Coq versions have nicer APIs making porting easier.

**Comment by tlringer** [comment] 2023-07-27 18:59
@agrarpan I think tried that and gave up, not sure if he has more to add there

**Comment by agrarpan** [comment] 2023-07-27 18:59
@SkySkimmer I was hoping to do that at first, but ran into too many issues at once. @ejgallego suggested it would be easier to ask for help if I had a working build for 8.9 and tried to port one version at a time.

**Comment by agrarpan** [comment] 2023-07-27 19:30
The main issues that are still remaining are the type change of Declarations.universes (the removal of cumulative) (constutils.ml and indutils.ml are impacted) and the changes to hook_declarations (defutils.ml is impacted)

**Comment by SkySkimmer** [comment] 2023-08-02 11:38
>Last time we tried to port from 8.9 to a later version, unification changed in a way that broke the other plugins, even after we fixed all of the type errors.

That sounds like we need a way to validate the patch, does it mean we need to simultaneously port the dependents or is there a test suite somewhere?

**Comment by tlringer** [comment] 2023-10-03 09:51
Hi all, we are currently having trouble with `SProp` eliminators showing up in unexpected places in our code, and may need some more help if we can't figure it out ourselves.

**Comment by SkySkimmer** [comment] 2023-10-04 07:37
What does "unexpected places" mean?

**Comment by tlringer** [comment] 2023-10-04 07:40
I think we figured this out. Mostly it is inconsistencies in 8.10 with respect to handling of `SProp` by different API calls, but they are resolved in 8.11. But @agrarpan found a way around this for now, and I think we are almost done.

**Comment by tlringer** [comment] 2023-10-04 07:56
OK we solved this particular issue. We now get undefined universe errors which are always really hard to debug. It could be related to `evar_map` handling. It could also be unification-related; last time we tried to update to a newer version of Coq, we gave up because the behavior of unification had changed in a way that we couldn't find a workaround for.

**Comment by SkySkimmer** [comment] 2023-10-04 08:02
If you say how to reproduce them I can have a look

**Comment by tlringer** [comment] 2023-10-04 08:03
Sounds good, we are going to try it ourselves first and then we will let you know if we are struggling still and need that help

**Comment by agrarpan** [comment] 2023-10-05 11:48
We're currently getting this error in our code:

Error: Conversion test raised an anomaly:
Anomaly "Universe Intro.17 undefined."

On further debugging, it turns out that a call to Typing.type_of is where this error comes from. The term we are trying to type check is the same for both Coq 8.9 (working version) and Coq 8.10 (currently trying to port the library to this). This makes me suspect that the evar_map is different in the two cases and potentially the source of the error.

Is there a way to print the evar_map for debugging or are there other ways to track all the places where the evar_map gets updated?

Thanks!

**Comment by SkySkimmer** [comment] 2023-10-05 12:19
You can use `Termops.pr_evar_universe_context  (Evd.evar_universe_context sigma)` to print the universe data (same output as Show Universes except it won't print the "normalized constraints" part)

**Comment by SkySkimmer** [comment] 2023-10-05 12:20
It's also possible that there are more checks that all universes are known in 8.10

**Comment by agrarpan** [comment] 2023-10-06 04:57
Thanks, that was very helpful!

**Comment by SkySkimmer** [comment] 2024-06-25 11:56
Not sure keeping this issue open is useful

**Closed by SkySkimmer** 2024-06-25 11:56 UTC
