### ISSUE TITLE
CoqIDE cannot build imported files

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#18044] opened 2023-09-14 11:56 UTC
#### Description of the problem

It is very common for Coq projects to be spread across multiple files. Even for teaching, the definitions I use in my class become big enough that one doesn't want to have them all in the same file any more. Sadly, the moment a Coq development is spread across multiple files, CoqIDE becomes very cumbersome to use: if B imports A, then every time A is changed, one needs to remember to build it (either using the "compile buffer" menu item or via some external tool such as `make`), and only then one can go on editing in B. As dependency chains grow, "compile buffer" ceases to be even remotely practical.

I don't know of any other programming language that would make multi-file projects so difficult to work with. Generally, when I save one file and then switch to another, I can use the changes in the first file without having to do some manual work on the terminal. I spoke with people using Isabelle and they were quite surprised by this; the Isabelle IDE supports multi-file projects just fine and everything builds automatically. (I don't know the state of Lean.)

Overcoming this CoqIDE limitation is the biggest hurdle I encountered so far in using Coq for teaching. Commonly people use `make` in a terminal to fill this gap, but that's not a very portable solution (Windows doesn't ship with `make`) and it is very inefficient (`make` will build much more than needed).

**Comment by ejgallego** [comment] 2023-09-14 14:49
Duplicate of #14110

**Closed by ejgallego** 2023-09-14 14:49 UTC

**Comment by RalfJung** [comment] 2023-09-14 15:39
> This is not something really related to Coq as a programming language, but more to editor support. 

Sure. But Coq comes with an official IDE, like e.g. Isabelle. This is a CoqIDE bug, I didn't mean to imply that it is a Coq bug. It still becomes a problem for the language, in terms of how it gets perceived ("Coq is immature, their IDE doesn't even support multi-file projects").

**Comment by ejgallego** [comment] 2023-09-14 15:45
Yes, the IDE situation for Coq is not the best (yet ;))
