### ISSUE TITLE
lia performance regression 

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#11436] opened 2020-01-21 20:41 UTC
#### Description of the problem

On 0c86e644 built on shared runner 5, bedrock2 GoFlatToRiscv takes less than 1min [here](https://gitlab.com/coq/coq/-/jobs/406176323#L1637).  
On the next commit, merging #11362 as 55ded808 the same file takes > *15min* ([different runner](https://gitlab.com/coq/coq/-/jobs/407023732#L2236)).
Shortly thereafter (commit 1f3ad4f8), shared runner 5 reports ~ 13min for the same file [here](https://gitlab.com/coq/coq/-/jobs/407271712#L1635).

So I am guessing this is a plain regression in running time, by more than 10x. I will try to find the slow line now.

**Comment by andres-erbsen** [comment] 2020-01-21 21:42
https://github.com/mit-plv/bedrock2/blob/wip-bbv2/compiler/src/compiler/GoFlatToRiscv.v#L590, second case.

```coq
Require Import ZArith Lia.
Local Open Scope Z_scope.

Goal forall
(a : Z)
(H : 0 <= a < 2 ^ 64)
(q r r1 : Z)
(H0 : 4 <> 0 -> r1 = 4 * q + r)
(H1 : 0 < 4 -> 0 <= r < 4)
(H2 : 4 < 0 -> 4 < r <= 0)
(H3 : 4 = 0 -> q = 0)
(H4 : 4 = 0 -> r = 0)
(q0 r0 : Z)
(H5 : 4 <> 0 -> a = 4 * q0 + r0)
(H6 : 0 < 4 -> 0 <= r0 < 4)
(H7 : 4 < 0 -> 4 < r0 <= 0)
(H8 : 4 = 0 -> q0 = 0)
(H9 : 4 = 0 -> r0 = 0)
(q1 : Z)
(H10 : 2 ^ 64 <> 0 -> a + 4 = 2 ^ 64 * q1 + r1)
(H11 : 0 < 2 ^ 64 -> 0 <= r1 < 2 ^ 64)
(H12 : 2 ^ 64 < 0 -> 2 ^ 64 < r1 <= 0)
(H13 : 2 ^ 64 = 0 -> q1 = 0)
(H14 : 2 ^ 64 = 0 -> r1 = 0),
r = r0.
intros.
  Time lia.
Abort.
```

**Comment by samuelgruetter** [comment] 2020-01-23 21:39
Slightly smaller example:

```coq
Require Import ZArith Lia.
Local Open Scope Z_scope.

Goal forall a q q0 q1 r r0 r1: Z,
    0 <= a < 2 ^ 64 ->
    r1 = 4 * q + r ->
    0 <= r < 4 ->
    a = 4 * q0 + r0 ->
    0 <= r0 < 4 ->
    a + 4 = 2 ^ 64 * q1 + r1 ->
    0 <= r1 < 2 ^ 64 ->
    r = r0.
Proof.
  intros.
  (* subst. *)
  Time lia.
```

This takes forever, but used to work fast before https://github.com/coq/coq/pull/11362.
Interestingly, if I do `subst` before, it becomes fast again.
/cc @fajb

**Comment by andres-erbsen** [comment] 2020-01-23 21:50
Forever or >10min?

**Comment by samuelgruetter** [comment] 2020-01-23 22:11
It took 674.022 secs on my machine, to be precise

**Comment by fajb** [comment] 2020-01-24 09:04
Are your sure this is due to #11362 ? 
I have a version with and a version without and both are slow...

My guess that the fact that `subst` makes it fast is just luck. 
I had a look at the linear constraints after preprocessing and there are no equations 
but maybe `r` was kept instead of `r1`.

I see this is again a modulo arithmetics problem. Maybe there is something to investigate there to find a good strategy.
Maybe `Unset Simplex` works actually better for this.

**Comment by andres-erbsen** [comment] 2020-01-24 14:20
I believe the minimized examples were tested on latest release vs master, but I pointed at #11362 based on coq CI runs which I linked above (I fixed one of the links just now).

Div/mod is indeed common in our work (more than 50% of problems?) and I have had decent success with following https://github.com/coq/coq/pull/8062 but not 100% reliably.

**Comment by samuelgruetter** [comment] 2020-01-25 00:11
We think it's due to https://github.com/coq/coq/pull/11362 because a `lia` call in bedrock2's `GoFlatToRiscv.v` was fast before https://github.com/coq/coq/pull/11362 was merged, and slow after it was merged.
Also, in the example I posted above, if I do

```coq
  change (2 ^ 64) with (4 * 2 ^ 62) in *. remember (2 ^ 62) as W. clear HeqW.
```

before `Time lia`, it becomes fast (0.2 secs), so it looks like it's related to `Z.pow`.

Along the way, I got confused by some seemingly irreproducible behaviors. But then I deleted `.lia.cache` and also put `Unset Lia Cache.` at the beginning of the file and the behavior became consistent :sweat_smile:

**Closed** 2020-02-04 09:14 UTC
Labels: kind: performance, kind: regression, part: micromega
