### ISSUE TITLE
CoqIDE frequently loses keyboard focus in 8.15

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#15675] opened 2022-02-14 10:11 UTC
#### Description of the problem

Since Coq 8.15.0 CoqIDE frequently loses keyboard focus - at least on MacOS. One way to reproduce it is to create a new Window with `CMD+N`. Typing is then lost until one clicks into the Window. There are many other cases in which CoqIDE loses keyboard focus temporarily, that is after certain editing operations a few key strokes are lost, frequently the first one, but this is harder to reproduce. Still I have this at least 10x a per hour of CoqIDE usage. The described `Cmd+N` issue is 100% reproducible, though, in Coq 8.15 and does not exist in Coq 8.14.

I compared the Coq Platform 2022.01 versions of Coq 8.14 and 8.15.

I don't think that this is a Mac specific issue since 8.14 works fine, but can't exclude this. If there are doubts, I can test on other systems.

#### Coq Version

Broken:
```
coqtop -v
The Coq Proof Assistant, version 8.15.0
compiled with OCaml 4.10.2
```

Fine:
```
coqtop -v
The Coq Proof Assistant, version 8.14.1
compiled with OCaml 4.10.2
```

**Comment by Alizter** [comment] 2022-02-14 10:20
Do you have autocomplete enabled? I have been observing similar defects but haven't been able to reproduce them reliably.

**Comment by MSoegtropIMC** [comment] 2022-02-14 10:39
No, I don't have autocomplete enabled - maybe I should ...

> I have been observing similar defects but haven't been able to reproduce them reliably. 

Except for the `Cmd+N` thing it is the same for me - I frequently loose keys after some editing operations, but I couldn't figure out the details as yes.

> The only major change in CoqIDE for 8.15 that I am aware of is the debugger, but I haven't been able to make sure.

If you suspect the debugger, I can try the preview of the debugger for 8.14 (it is available in Coq Platform 2021.09).

@jfehrle : have you seen such effects?

**Comment by jfehrle** [comment] 2022-02-14 18:06
I've not noticed the specific case you mention (Ctrl+N, then drops characters) on my system (Ubuntu on WSL).  I vaguely recall cases in which the focus didn't seem to get set correctly, but that was a good while ago.

I'll take a closer look later today.

Are you using the debugger when you see this issue?
What other editing operations show the problem?
Can you reproduce this faster by repeatedly using `Cmd+N`?
What are your settings in Editor/Preferences/Editor (screen shot)?

Perhaps you could run coqide with `-debug` in the command line and redirect output to a file?  The file should include messages for each keystroke in the script panel, like this:

```
got key 'd' (100, MOD2)
[DEBUG] begin_action_cb
[DEBUG] prev_insert moved
[DEBUG] insert_cb 2
[DEBUG] target deleted
[DEBUG] target moved
[DEBUG] end_action_cb
```

When the problem occurs, see whether the missing keystrokes appear in the output file.  FYI: each time you open a new window, you'll see a message a bit like this:

```
(Spawn  ,7797) EXEC: /home/proj/coq/_build/default/dev/shim/../../../install/default/bin/coqidetop.opt -main-channel stdfds --xml_format=Ppcmds -async-proofs on -I /home/proj/coq/_build/default/dev/shim/../../../install/default/lib -coqlib /home/proj/coq/_build/default/dev/shim/../..
```

PS "loose" is the wrong word, you surely meant "lose"

**Comment by MSoegtropIMC** [comment] 2022-02-14 18:22
> Are you using the debugger when you see this issue?

No. It was just suspected that it has to do with the debugger, because there were no other significant changes from 8.14 to 8.15 in CoqIDE and it works fine in 8.14.

> What other editing operations show the problem?

I can't say as yet. I guess I would need a screen / keyboard recorder (will try your suggestion with -debug)

> Can you reproduce this faster by repeatedly using Cmd+N?

As mentioned the `Cmd+N` thing is 100% reproducible at first press - only other effects are not.

> What are your settings in Editor/Preferences/Editor (screen shot)?

attached

![Screenshot 2022-02-14 at 19 20 42](https://user-images.githubusercontent.com/7895506/153923405-c9bab7af-99e5-4e5a-8cb2-3934648e61b1.png)

**Comment by jfehrle** [comment] 2022-02-14 19:22
> As mentioned the `Cmd+N` thing is 100% reproducible at first press - only other effects are not.

What do you mean by "100% reproducible at first press"?  You had said "frequently" (i.e. not 100%) in the original description.  "at first press" means when you start CoqIDE or ??

**Comment by jfehrle** [comment] 2022-02-14 19:26
You see it _every time_ you use `Cmd+N`?

**Comment by Alizter** [comment] 2022-02-14 23:14
I suspect that CoqIDE is missing keystrokes when it is busy. Here is a test case for CoqIDE (remember Ctrl-Home restarts Coq):
```coq
Fixpoint many_things_type (n : nat) : Type :=
  match n with
  | 0 => Set
  | S m => forall (x : nat), many_things_type m
  end.


Definition just_too_many_things_to_print : Type :=
  Eval cbv in many_things_type 10000.

Print just_too_many_things_to_print.

(** Now try typing, CoqIDE struggles *)
(** For instance I can only type "a" *)
```

**Comment by SkySkimmer** [comment] 2022-02-14 23:27
>I suspect that CoqIDE is missing keystrokes when it is busy. Here is a test case for CoqIDE

reproduces for me on master but not 8.11 (linux)

**Comment by jfehrle** [comment] 2022-02-14 23:28
CoqIDE does see the keystrokes on master with your example, but they don't get added to the buffer:

```
got key 'x' (120, MOD2)
got key 'x' (120, MOD2)
got key 'x' (120, MOD2)
got key 'x' (120, MOD2)
```

**Comment by ppedrot** [comment] 2022-02-14 23:31
@Alizter this doesn't look like the same issue though. CoqIDE is not losing window focus, it's just discarding the buffer input operations for some reason.

**Comment by jfehrle** [comment] 2022-02-15 05:45
This isn't too mysterious.  The debugger added code to make the script window not editable at all (dropping keystrokes) while Coq is processing an XML protocol request.  Similar to what happens if you enter Ctrl-down while Coq is busy (it's dropped).  When you create a new buffer or open a file, the script panel briefly becomes not editable while Init and Setoptions messages are processed.  (I thought some about having CoqIDE beep when it drops keystrokes, but I haven't found any audio API.)

In the previous version, any change to the buffer before the command/tactic that's running immediately aborted the script, which I thought would be too easy to trigger by mistake while using the debugger.  Another aspect is that the offsets used to highlight code then become incorrect absent a bunch more code specifically to map Coq-returned offsets to new buffer offsets.  Also, editability without aborting the debugger session would tend to lead users to think they can modify Ltac tactics while in mid-execution, which won't be supported anytime soon, if ever.

I later learned about a read-only character attribute that might be used to prohibit changes in the first part of the script while allowing them in the latter part.  Maybe the debugger could open a "Quit debugging?" dialog if the user modifies the first part of a script being debugged.

These are initial thoughts.

**Comment by jfehrle** [comment] 2022-02-17 23:34
@SkySkimmer I'd like to get a simple fix for this into 8.15.1.  Probably just a day to code/test that.  When will 8.15.1 freeze?

**Comment by jfehrle** [comment] 2022-02-18 04:27
Examining 8.13, it appears the CoqIDE has inconsistent behavior when you modify the buffer above the last-processed line while Coq is processing.  If the multiple worker code kicks in, modifying above the last-processed line usually stops Coq and clears the green "completed" highlight up to the point of the modification.  However, if I run a much shorter script and the multiple worker code doesn't kick in, then I can modify the green section without CoqIDE clearing any of the green highlight--clearly incorrect behavior.  This latter behavior is what I intended to prevent by making the script uneditable while the Coq is busy.

Note the shorter script takes several seconds to run, so this defect usually wouldn't be apparent in many cases though occasionally it may trip up users.

**Comment by jfehrle** [comment] 2022-02-18 07:00
@gares The issue I mention in the previous comment arises from this code.  If a coq operation is in progress, then `try_grab` does nothing and the character is inserted in the buffer in processed code without invalidating anything.  The simpler solution is to ignore insertions in processed code when Coq is busy.  The other, a bit more complex, is to stop the computation: send an interrupt, maybe hide the "User interrupt" message, then clear highlights and go back to an earlier Stm state.  Both could lead to some user surprise.  Let me know if you have a strong opinion.  I'll ponder this overnight.

Also, I'm not sure what the point is for the `fallback` function and "(* If Coq is busy due to the current action, we don't cancel *)".

```ocaml
  let insert_cb it s = if String.length s = 0 then () else begin
      :
    else if it#has_tag Tags.Script.processed then
      call_coq_or_cancel_action (coqops#go_to_mark (`MARK text_mark))

  let call_coq_or_cancel_action f =
    :
    ignore @@ Coq.try_grab coqtop action fallback in
```

**Comment by SkySkimmer** [comment] 2022-02-18 12:02
>@SkySkimmer I'd like to get a simple fix for this into 8.15.1. Probably just a day to code/test that. When will 8.15.1 freeze?

I'm waiting for https://github.com/coq/coq/pull/15594

**Comment by gares** [comment] 2022-02-21 11:14
> The other, a bit more complex, is to stop the computation: send an interrupt, maybe hide the "User interrupt" message, then clear highlights and go back to an earlier Stm state.

This one is very unreliable, so please do the other one.

**Comment by MSoegtropIMC** [comment] 2022-02-22 13:53
@jfehrle : One more case I can 100% reproduce on macOS:

- select a word in accepted (proof checked) text by double clicking in the text
- type something which should overwrite the selected text
- the first typed character is always lost

CoqIDE 8.14 does not show this effect.

**Comment by Alizter** [comment] 2022-02-22 14:15
@MSoegtropIMC I can also reproduce that on linux.

**Comment by Alizter** [comment] 2022-02-22 14:16
Also same issue happening in: https://github.com/coq/coq/issues/15725

**Closed** 2022-03-03 00:19 UTC
Labels: part: IDE, kind: regression
