### ISSUE TITLE
Import -(coercions) uses huge amount of memory and hangs

### ISSUE THREAD

**Issue by joscoh** [coq/coq#18838] opened 2024-03-24 02:53 UTC
### Description of the problem

In the following example, using `Import -(coercions)` results in `coqc` using huge amounts of memory (at least 8 GB on my machine) and hanging. I have to manually kill the process. Removing the `-(coercions)` made everything proceed as usual.
I am running Coq 8.18 on Linux Mint 20.

### Small Coq file to reproduce the bug

```coq
From stdpp Require pmap.
Import -(coercions) pmap. (*hangs*)

From stdpp Require Import pmap. (*works normally*)
```

### Version of Coq where this bug occurs

8.18.0

**Comment by SkySkimmer** [comment] 2024-03-24 09:21
Duplicate of https://github.com/coq/coq/issues/18697 ? Can you test on master?

**Comment by ppedrot** [comment] 2024-03-24 12:42
I cannot reproduce on master, so closing.

**Closed by ppedrot** 2024-03-24 12:42 UTC
Labels: kind: bug, needs: triage
