### ISSUE TITLE
setoid_rewrite: Anomaly: Uncaught exception Invalid_argument("decomp_pointwise").

### ISSUE THREAD

**Issue by ichung** [coq/coq#8204] opened 2018-08-02 20:09 UTC
Version 8.8.1

[This file](https://gist.github.com/ichung/937da4dda111447dcbd6fbdc9b7ef869) produces an anomaly on the last line:
```
Error:
Ltac call to "setoid_rewrite (orient) (glob_constr_with_bindings)" failed.
Anomaly "Uncaught exception Invalid_argument("decomp_pointwise")."
Please report at http://coq.inria.fr/bugs/.
```

**Comment by ppedrot** [comment] 2018-08-04 09:02
Duplicate of #4617.

**Closed** 2018-08-04 09:02 UTC
