### ISSUE TITLE
CoqIDE FAQ is installed to the wrong place

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14467] opened 2021-06-08 22:22 UTC
[PR #14434] is incorrect, as it installs `/usr/doc/coqide/FAQ`, but `/usr/doc` is not a thing. It should be installing to `/usr/share/doc/coqide/FAQ`. See also https://launchpadlibrarian.net/542891987/buildlog_ubuntu-groovy-amd64.coq_8.master~git~202106082017+22408-0~daily357-b541ac00b5~ubuntu20.10.1_BUILDING.txt.gz

_Originally posted by @JasonGross in https://github.com/coq/coq/pull/14434#pullrequestreview-679054124_

**Comment by JasonGross** [comment] 2021-06-08 22:22
cc @ejgallego

**Comment by ejgallego** [comment] 2021-06-09 19:00
This doesn't look like a bug in Coq, but in your dune setup, which seems to be incorrectly configured.

**Comment by JasonGross** [comment] 2021-06-09 22:52
This is the standard system dune on Ubuntu from the apt packages, how do I check if it's properly configured?

**Comment by ejgallego** [comment] 2021-07-07 16:19
Duplicate of #14232

**Closed by ejgallego** 2021-07-07 16:19 UTC
Labels: kind: bug, kind: regression, part: IDE, part: installation, priority: blocker
