### ISSUE TITLE
doc:dune takes longer than expected

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#10694] opened 2019-08-23 16:21 UTC
https://github.com/coq/coq/pull/10686#issuecomment-524374510 @Zimmi48 
>This makes me realize that there is something wrong with the "doc:refman:dune" and the "doc:stdlib:dune" jobs taking both 17 minutes to run (I checked and this is indeed the same in master) when they are said to depend on the Dune build job.

**Comment by ejgallego** [comment] 2019-08-23 17:39
What does `_build/log` say?

**Comment by Zimmi48** [comment] 2019-08-23 18:43
Unfortunately we don't keep this artifact for these builds.

**Comment by ejgallego** [comment] 2019-08-23 18:46
Yeah, I'm running a modified test in my gitlab instance, with debugging enabled. It seems that something is causing a full rebuild, so some env variable the build depends or some other issue could be the culprit.

I seem to recall that originally this target was working, but indeed I have seen too many rebuilds on Dune lately, so we must be tracking too many deps [I originally thought that `coq_config` could be the culprit but that seems to be properly preserved].

Anyways keeping the build log seems like good practice so I'll tweak the template.

**Comment by ejgallego** [comment] 2019-08-23 19:44
I'm trying to see if this is a problem of the Dune 1.6 -> Dune 1.10 update in Docker, but Gitlab's web interface timeouts when trying to grab such old jobs.

**Comment by ejgallego** [comment] 2019-08-23 19:45
The sooner I speak the sooner it works, already a problem with Dune 1.6.2 https://gitlab.com/coq/coq/-/jobs/236459151

**Comment by ejgallego** [comment] 2019-08-23 20:06
The problem is with all dune builds with artifacts, for some reason a full rebuild happens, so `odoc` target is also affected. A full rebuild is happening so that's indeed bizarre; at that level things are only invalidated when the compiler hash or something like that changes.

**Comment by ejgallego** [comment] 2019-08-23 20:42
Absolutely no idea what is going on.

**Comment by ejgallego** [comment] 2019-08-27 13:37
I have been looking into this, and still no idea; I'll have to patch Dune to output some debug info.

@rgrinberg do you have any idea on what could the problem be here? Summarizing, we have the following setup:
- identical docker images are booted, including the OCaml compiler and all the required opam packages,
- job A does build Coq, packs the whole of `_build` and saves it as an artifact.
- job B downloads the artifact and places it correctly into `_build`, however a full rebuild is performed, instead of an incremental one.

**Comment by rgrinberg** [comment] 2019-08-27 16:03
No idea what could be the issue but it should be possible to debug if you can give us some steps to reproduce using docker. Perhaps @aalekseyev knows?

I do think that we need some better tools in dune to debug these issue however. For example an `--explain-cache` mode that will output why a particular target was marked as out of date.

**Comment by aalekseyev** [comment] 2019-08-27 16:22
Do the build artifacts themselves actually change?
What would be helpful is to pick a specific artifact that you're sure shouldn't be re-built and look in detail at the rule for that artifact and its dependencies.

A command like this could tell you about the rule and its dependencies:

```
dune rules _build/default/bin/main.exe
```

**Comment by ejgallego** [comment] 2019-08-27 16:48
> Do the build artifacts themselves actually change?

Hard to check as the targets deps are kinda complex, in this case `@refman-html` and `@odoc`, logs show that everything is being rebuilt tho, so it must be some very basic dependency. Note that the envs are almost identical [except for the CI variables, but indeed I could try to unset them and see if this happens with identical envs]

Unfortunately `dune rules` doesn't provide a lot of info here, indeed explaining the cache misses would be super useful in some contexts.

**Comment by SkySkimmer** [comment] 2019-08-27 16:55
We could run a test branch where we upload all _build as artifact, then we could diff the one from build:dune and the one from refman:dune

**Comment by aalekseyev** [comment] 2019-08-27 17:24
By the way, if you run `dune --verbose` then it prints the actions it decided to re-run. If you look at the first action dune re-runs, that can narrow it down a lot. The same information goes into `_build/log`, I think, so it would be nice to look at that file.

**Comment by ejgallego** [comment] 2019-12-08 20:26
I'm still having a hard time understanding what's going on here, instrumenting the dune used in the build but even so I don't understand the reason things get rebuilt....

Example log: https://gitlab.com/coq/coq/-/jobs/372897053 

The log starts after the
`dune exec --build-dir=_build_boot ./tools/coq_dune.exe _build_boot/default/.vfiles.d`
line, and for some reason dune rebuilds the whole of Coq, despite the DB is the same.

I'm gonna run with even deeper debugging [printing all digests] to see if I can figure out the problem.

**Comment by ejgallego** [comment] 2019-12-08 21:31
There is indeed something very strange with the artifact, with more debug info we see:
```
digest changed for tactics/abstract.mli [931d6135cab1190ffce2d51e6b4fe5db/931d6135cab1190ffce2d51e6b4fe5db]
[d]file: tactics/abstract.mli | 931d6135cab1190ffce2d51e6b4fe5db 
digest changed for _build/default/tactics/abstract.mli [931d6135cab1190ffce2d51e6b4fe5db/216e2c22debf9c5440ba2cb65635f855]
```
So the old digest in the database was correct, however the file installed by the artifact doesn't have the same digest! A similar problem exists for object files.

Trying with different debug information.

**Comment by ejgallego** [comment] 2019-12-08 22:34
Aha, the problem is the executable bit:
```
$ ls -l _build/default/clib/exninfo.mli clib/exninfo.mli
-rwxrwxrwx. 1 root root 1425 Dec  8 22:10 _build/default/clib/exninfo.mli
-rw-rw-rw-. 1 root root 1425 Dec  8 22:18 clib/exninfo.mli
```
why is not gitlab properly preserving the execution bit of the artifact?

**Comment by ejgallego** [comment] 2019-12-08 22:40
Indeed the artifact storage format changed to zip some time ago:
https://gitlab.com/gitlab-org/gitlab-foss/issues/34771

**Closed** 2019-12-16 10:45 UTC
Labels: kind: infrastructure

**Comment by gasche** [comment] 2021-01-26 12:03
I was pointed to this issue by @ejgallego (thanks!) after banging my head in an apparent dune-build-caching issue that turned out to be exactly the same. I wrote an [upstream bug report](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27496) where a Gitlab developer suggested a workaround that does not require changing the archive format: just enable `FF_USE_FASTZIP: "true"` in the variables of the affected jobs (or globally). This might improve Coq's CI times by not having to .tar.gz an archive that is later zipped. But this probably not the bottleneck in your CI, and controlling the archiving strategy means that you are more robust against similar bugs in the future.
