### ISSUE TITLE
What commit from 3rd party developments should CI test?

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#6724] opened 2018-02-09 12:54 UTC
Currently we test some branch, usually master, occasionally some 8.8 specific branch. This regularly causes CI failures when Coq master and the 3rd party branch have moved on but CI is on some branch with an older base (mostly these failures are in Equations).
It also means that if I look at some old commit I can't reproducibly run CI on it because the 3rd party branch has moved on from what it was at the time of the commit.
What can we do about this?

**Comment by Zimmi48** [comment] 2018-02-09 14:04
I think that the conclusion that was reached on Gitter was:
- we should always test specific hashes of the external developments instead of testing a branch
- we should periodically update these hashes (probably a bot can be programmed to do that by opening a PR updating the hashes every week or every two weeks and using CI to confirm that the PR can be merged).

This approach has many advantages:
- as you say it means that testing again an older commit won't fail because the external development has received backward-incompatible fixes
- if CircleCI is testing a feature branch that is not up-to-date with master, it won't yield unwanted failures
- our CI won't break when external developers mess up
- it will provide a pretty good way of dealing with dependencies between external developments (in particular it should help with the stdpp -> iris -> lambda-rust dependency chain and with #6639 - VST not rebuilding CompCert)

I was considering implementing this using GitHub feature of being able to get an archive for a given commit hash. Example: https://github.com/mattam82/Coq-Equations/archive/7e507d5.tar.gz. It would be much more efficient than non-shallow cloning, which would be the other option.
Notice that in this specific example I used the a commit hash that is in a PR that is not merged yet (at the time of writing). This GitHub (mis-)feature could come in handy in our case to manage "overlays".
The same feature exists with GitLab. Example (using once again a commit from an unmerged PR): https://gitlab.mpi-sws.org/FP/iris-coq/repository/d0253c0/archive.tar.gz
This feature even exists on gforge. Example: https://scm.gforge.inria.fr/anonscm/gitweb?p=coquelicot/coquelicot.git;a=snapshot;h=0e01746;sf=tgz. But of course, in this case there are no PRs.

If no one is opposed to this approach, I'm ready to volunteer to implement it (unless someone else wants to do it).

**Comment by ejgallego** [comment] 2018-02-09 20:05
Hi Théo, I'm not sure that the motivation to modify this aspect of the
CI is strong enough.

IMHO, the current "continuous" approach has worked very well with
_near to zero_ problems, and the benefits IMHO again have been great
at a very reasonable cost. Ensuring that everything is "in sync" is a
great asset and having a low delta to face when problems arise is very
good.

Indeed, software in general is moving to a truly continuous release
process and I think that doing a step backwards would not be the best
for Coq's CI.

Also, if it ain't broke, don't fix it!

I am also concerned wrt to having to maintain a custom a bot; this is
complex and how conflict resolution is going to proceed seems not
clear to me.

One thing I like of the current model is that it requires very low
mental effort to figure out how the system works, and what the steps
to fix things are. I'm not sure we want to mix testing with curation.

Also, let me point out that compatiblity experiences with other
languages don't seem very extrapolable to Coq, we are in a different
league wrt Rust for example due to unification, TC, etc... See for
example the recent problem at:

I suggest we discuss more in the WG. A few more comments:

> as you say it means that testing again an older commit won't fail because the external development has received backward-incompatible fixes

This is indeed the main problem today; however, I am not sure how much
is this a problem if we have good testing and why we cannot use a
different solution [like a smart bisect script]

> if CircleCI is testing a feature branch that is not up-to-date with master, it won't yield unwanted failures

CircleCI could be modified to merge with `master` if possible, anyways Circle's future doesn't look too bright unless it gets way more capacity.

> our CI won't break when external developers mess up

The whole point of the CI is to have people who test against `master`
too. Instead, they will ignore the commit and the coq-contribs
situation will be reproduced, mainly due to lacking the manpower to
resolve delayed conflicts.

Indeed, this brings us again to the topic of rolling/continuous
releases. It turns out that the cost of resynchronizing a repository
is likely **exponential** on the number of changes you lag behind. Now
the lag is close to 0 [and that has been working well], which is close
to optimal.

> it will provide a pretty good way of dealing with dependencies between external developments (in particular it should help with the stdpp -> iris -> lambda-rust dependency chain and with #6639 - VST not rebuilding CompCert)

IMHO that's orthogonal to the change you propose.

**Comment by SkySkimmer** [comment] 2018-02-09 20:08
>See for example the recent problem at:

??

**Comment by ejgallego** [comment] 2018-02-09 20:24
At https://github.com/antalsz/hs-to-coq/issues/68 , fixed.

Anyways, the short answer to the question is that we should test whatever branch / commit upstream suggests. But then it'd be their business to see if they are not in sync.

**Comment by RalfJung** [comment] 2018-04-25 11:39
I think the problem that you cannot even reproduce old tests is a fairly serious one. Coq's CI essentially relies on implicit global state and does not even record in a systematic way what the state was at the time of testing a commit.

> Indeed, software in general is moving to a truly continuous release process and I think that doing a step backwards would not be the best for Coq's CI.

I fully disagree. Yes, software is moving towards more continuous processes, but it is my impression that it is also moving towards *less* implicit global state and *more* reproducability in the build process.  Examples for this are Docker and NixOS; even [Debian nowadays records](https://buildinfo.debian.net/) the exact versions of all dependencies that were used to build a binary package, in a machine-readable format. This proposal is a step forwards into these directions.

I also don't understand why you consider this proposal a "step backwards" from a continuous release process. A continuous process needs good CI to ensure some level of consistency, and the current approach seems to be "well it's consistent with whatever happened to be the latest thing at the time", which makes it (a) prone to break as independent actors move forward on their own projects in their own pace, and (b) really hard to figure out *what* actually was consistent with what at any given point in the past.

So, I fully agree with @Zimmi48. CI should not be susceptible to changes in downstream projects, and CI should be reproducible. It should only ever check out other git repositories at fixed SHAs. This provides a very clear answer to the question which version was consistent with what at any given point in the past. You argued for megarepos on gitter the other day, and reproducible CI is one of the nice things you get from a megarepo. Recording git SHAs of dependencies is essentially going a bit towards a megarepo without actually forcing all Coq developers to share one repo, which obviously would not be practical. I honestly do not understand how you can argue both for megarepos and against pinning dependencies.

And I think it's not just CI: Both Rust and other systems like npm have the notion of a "lock file", which records exactly the version of all transitive dependencies that are used for a project. This results in reproducible builds, so e.g. I know I will always be able to [build the current version of ripgrep with the given version of its dependencies](https://github.com/BurntSushi/ripgrep/blob/ab64da73ab3f73f50192459dfc1e49c6cabd9de8/Cargo.lock), and if I use the same compiler I should even get the same binary. Having debugged issues (e.g. in Python) that arose from updating dependencies without any good way to control or even record what is happening, I can attest that this is extremely useful -- it's an example of making the previously implicit state "just use the latest version of everything" explicit, and unsurprisingly more explicit state tracking makes everything more predictable and easier to manage.

**Comment by ejgallego** [comment] 2018-04-25 12:06
> does not even record in a systematic way what the state was at the time of testing a commit.

This is incorrect, the build log contains the hashes of everything that is tested. It is not recorded to a file as we don't have the setup to persist artifacts, but apart from that the system does keep logs. And such logs have been used in the past to reproduce issues [with a bit of script hackery].

Likely due to the difficulty of online chat it seems you think I "argue" for mega repos. No, I just mention that they do have many advantages, and it seems not very optimal to split packages when you are not willing to maintain an stable interface in the base ones.

I am sorry but `npm` won't be our model XDD now seriously, again, it is my impression that the current setup has worked very well, and the fact I like most is how simple it is. Simplicity is underrated, and IMHO so far we have little incentive to introduce more complicated features to fix problems that are not here.

**Comment by Zimmi48** [comment] 2018-04-25 12:40
I think our CI is way too often red for no good reason and we should address that. Using fixed commits will be a step forward, but that's not the only one needed. Another one is fixing all these non-deterministic failures, see https://github.com/coq/coq/projects/9.

**Comment by ejgallego** [comment] 2018-04-25 13:26
> That's not systematic (as in, machine-readable).

It is systematic, it is generated by a script, and it is machine readable....

**Comment by ejgallego** [comment] 2018-04-25 13:28
> For plugins (I mean equations) it's not uncommon for a commit to change a ML API incompatibly so that when equations is fixed it breaks all PRs that where branched before that commit.

And indeed the simplest solution is to put equations in the main repository. Otherwise, you quickly run into very complex scenarios that amount to basically everyone having to provide an overlay.

**Comment by Zimmi48** [comment] 2018-04-25 13:38
I strongly disagree with this position. Development of a plugin outside of the main repository is a very good practice: it allows for a quicker development as the same level of quality is not expected. Equations can join the main repository whenever it is ready.

**Comment by ejgallego** [comment] 2018-04-25 13:51
> it allows for a quicker development as the same level of quality is not expected

None of the above concerns is related to whether the code is stored in or out tree.

**Comment by Zimmi48** [comment] 2018-04-25 14:25
It is. Because we don't allow maintainers to push commits directly for instance.

**Comment by ejgallego** [comment] 2018-04-25 14:30
That's a social rule. But equations could be well developed as a branch of the main Coq repos and then be merged back, as most people do in other projects. We gain some things, we lose others.

But indeed, I do miss BitKeeper notion of submodule, that worked so well.

**Comment by gares** [comment] 2018-04-27 08:57
> If no one is opposed to this approach, I'm ready to volunteer to implement it (unless someone else wants to do it).

I'm in favor of this but I fail to understand some details (or better I'll guess and you tell if they are right):
- the hashes are in a file if the git repo of Coq, so a PR is always tested against the hashes it branches from
- if you rebase a PR you also get updated hashes
- hashes are updated automatically every day?week? by picking the tip of the branches we use today (if they build)

Did I get it?

**Comment by RalfJung** [comment] 2018-04-27 09:05
> hashes are updated automatically every day?week? by picking the tip of the branches we use today (if they build)

In particular, this would be a PR on its own, testing on CI that everything still works after moving to the latest versions of the dependencies. This way one can distinguish failures due to changes on the other side from failures due to changes in Coq -- only one ever changes in  any given PR.

**Comment by gares** [comment] 2018-04-27 09:07
I see. I've a scenario in mind (with my "merger" hat):
- I've a PR with all green lights
- before I manage to merge it, CI gets updated

Should I rebase the PR (or ask the author to do it) in order to test it on the new snapshot before merging?

**Comment by gares** [comment] 2018-04-27 09:08
Oh, now I realize we already have this "bug", so it won't make things worse.

**Comment by RalfJung** [comment] 2018-04-27 09:13
> Should I rebase the PR (or ask the author to do it) in order to test it on the new snapshot before merging?
(if so we must also find a way to detect this in the merge-pr script).

That's the usual problem of "racing merges" -- and it is why Rust has a [queue](https://buildbot2.rust-lang.org/homu/queue/rust) for the final CI that runs before merging (and then immediately automatically performs the merge). This ensures that `master` is only ever advanced to a new SHA after *that exact commit* has been tested on CI, avoiding these races. It also sequentializes the CI for merging.

**Comment by RalfJung** [comment] 2018-04-27 09:34
> Wow, science fiction!

**Comment by RalfJung** [comment] 2018-04-27 09:35
> Wow, science fiction!

And [you can use it, too](https://github.com/barosl/homu) :D

**Comment by Zimmi48** [comment] 2018-04-27 14:58
> We had this model in the past, it was called "coq-contribs", it failed big time to keep track of upstream, as when someone decided to update, the compatibility diff was too long for anybody to figure out.

No, the proposed model is quite different here, as every time we need to fix a development we are actually submitting PRs upstream. Anyways, it looks to me that you are the only one here not fully understanding what is proposed here: we should talk a bit together IRL (I won't be in Paris before Wednesday though).

On the other hand, @gares and @RalfJung understood it perfectly ;-)

**Comment by mattam82** [comment] 2018-04-27 15:54
I think I get it too and I believe it solves a real problem without adding
too many complications. What happens though if people do force pushes on
their development branch rewriting history?
— Matthieu
Le ven. 27 avr. 2018 à 16:58, Théo Zimmermann <notifications@github.com> a
écrit :

**Comment by gares** [comment] 2018-04-27 16:25
> We had this model in the past, it was called "coq-contribs"

The problem with contrib is that it was testing 99% abandonware, and that of the 3 active projects being tests only 1 (ssreflect) had a maintainer with write access to the repo, so the other two (CompCert and CoRN) were, as you say, out of sync.

I don't think this proposal has anything to do with the problems above. First, the plan is to update the snapshot automatically. Maybe we should the timeframe more precisely to make you happy. Every week? (note that for the contribs the timeframe was +oo, or NaN depending on the color of the snake).
Second the fact that a PR, unless rebased, continues to be tested against the same *consistent* snapshot is a feature (the main point of this proposal I would say).

**Comment by ejgallego** [comment] 2018-04-27 18:30
I am still not understanding what problem you are trying to solve here, and I am not sure I understand who's going to update the commit data for all the large amount of contribs; if that's to be done automatically, this is exactly what we have in place now; it is just that we record the information in the logs; I'm OK with recording somewhere [not in the Coq repos]

But as I understood Ralf, he proposed a manual update to the Coq repos. I won't approve that, first, because the coq repository is the wrong place for it, and second, because such information will quickly go stale creating the same problems we had in the past. We don't even have the manpower to merge trivial commits and you are trying to convince me that someone is gonna take care of running on their own a multi hour computation update every a few days? Let me lol.

**Comment by gares** [comment] 2018-04-27 18:39
> someone is gonna take care of running on their own a multi hour

It has been said many times that the update is a PR, hence the CI will do this. It could be 1 more PR per week. Is it too much?

> I'm OK with recording somewhere [not in the Coq repos]

We record the git URLs of the repos CI tests... what is the difference between `URL` and `URL#hash`?

You don't like this proposal? Fine, but stop climbing mirrors.

**Comment by ejgallego** [comment] 2018-04-27 18:49
> It has been said many times that the update is a PR, hence the CI will do this. It could be 1 more PR per week. Is it too much?

It has bad latency properties wrt detecting consistency problems, I much prefer to have as low as possible latency, in particular because consistency problems are well known to incur into exponential costs in the length of the diverging path.

> We record the git URLs of the repos CI tests... what is the difference between URL and URL#hash?

The difference is that in the first case we don't need to maintain the hash but instead the maintainer does it and we try to approximate a zero latency solution.

> You don't like this proposal? Fine, but stop climbing mirrors.

I am not arguing that black is white, but instead I do argue that there are multiple problems with some of the arguments here [including for example "regular CI breakage" that IMHO it is very far from that], some fallacious arguments "the CI doesn't record the hashes" while it **does**.

I remain very way of relying on someone to update the hashes, but indeed I do agree that we should have a better system for reproducible CI builds, but just adding the hashes is going to create way more serious problems than what it solves.

As I said I tried to write such a tool [that indeed can even do inter-project bisect for example] but still far from it, so any improvement is OK in that sense, waiting for the PR; but it is easy to talk but for example we don't even have a sad S3 service where we can persist travis stuff, not to say the health of our relation with the Travis organization.

**Comment by ejgallego** [comment] 2018-04-27 22:04
> I'll see if I can come out with a concrete PR in the next few weeks.

Sounds good, feel free to chat more [IRL is OK too] or even publish a RFC of the concrete implementation if you want some feedback.

**Comment by ejgallego** [comment] 2018-04-27 22:09
My current thinking of the problem is indeed quite influenced by the view that I believe Yaron Minsky mentioned in a blog post: I see this issue as a consistency problem, and he mentioned the CAP theorem.

So in that sense, it is not possible "to support the proposal": whatever path you take, you are gonna give away something; still my view is that we want to optimize reconciliation latency.

**Comment by Zimmi48** [comment] 2018-07-01 08:39
Here are ways to get an archive of a specific commit on GitHub, GitLab and BitBucket. As can be seen, only the base URL are different, so they could be included in an ARCHIVEURL variable meant to replace the current GITURL.

https://github.com/coq/coq/archive/033c32a32fedcf2160bb38a3fed55efa9d1c2b77.tar.gz
https://gitlab.com/coq/coq/-/archive/033c32a32fedcf2160bb38a3fed55efa9d1c2b77.tar.gz
https://bitbucket.org/coqpide/pidetop/get/bfdd6668ab5ae4c0968083cdb32e327a7e1188b4.tar.gz

**Comment by Zimmi48** [comment] 2018-12-02 22:50
Coming back to this issue, I will try to summarize my current view of the situation and the possible solutions.

What has become clearer and clearer is that there are two very different kinds of 3rd party projects that we test in our CI: the ones that use the ML API and the ones that do not. For the second kind, the current situation is OK because virtually all fixes are backward compatible and thus we just need to wait for overlays to be merged before we can merge the corresponding PR. The situation that is far from perfect is for the first kind (a.k.a plugins).

For plugins, it has also become clearer and clearer that there is no hope to provide a stable API. We prefer the "Linux" model of "*the API is not stable but we will fix your plugins*" (communication about this policy is improving but we should do more to ensure that all plugin writers are aware that they are encouraged to join Coq's CI; in particular, there could be a "writing a plugin" chapter in the reference manual).

**Given this policy, there is a strong need of synchronization between the code of plugins and the code of Coq.** The problems with the current setup are:

1. the usual development cycle is too long: modify Coq, commit and push, CI tells which plugins need overlays, fix them, prepare overlays, submit PRs (this is already becoming better with recently introduced tooling (dune, #8978 and #9018);
2. the need to merge simultaneously a PR on Coq and its overlays on plugins (ideas to improve this were recently discussed in #9022, in particular involving @coqbot);
3. the fact that even if the previous problem is fixed, there will still be PRs whose CI will fail because their build started just before the PR was merged.

All of these issues seem to push to adopt a monorepo approach (i.e. plugins should all be developed in the main Coq repository) but... monorepos are better suited for single organizations that share common policies. It wouldn't feel right if plugin developers were forced to adopt Coq's strict policies (no pushing to main branches, all PRs should come from forks, no PR merged by PR author or without an approved review...).

A second solution is a monotree approach (a.k.a. the Linux way), a distributed variation of the monorepo approach. Everyone works on the same tree but in multiple repositories which may have distinct merge policies, bug trackers, owners and teams, etc. Synchronization happens later on, when repository owners pull changes from various sources. I recently read a [blog post](https://blog.ffwll.ch/2017/08/github-why-cant-host-the-kernel.html) explaining why Linux developers prefer pull requests through e-mail. E-mails are more flexible as they support PR discussion spanning multiple repositories (or rather the mailing lists associated to multiple repositories).

However, a full monotree approach does not seem right either: it is more complex, and thus harder to learn, and it would be weird for a plugin repository to have the full code of Coq with the actual code of the plugin lost in a sub-directory somewhere, and a README that is intended for the Coq repository and not for the plugin repository).

Nonetheless, we can consider a solution that would be closer to a monotree. The Coq repository could indeed include the code of external plugins in sub-directories, which would make it simpler for developers to fix plugins even before pushing to remote branches and opening a PR. This wouldn't even require changing anything to the build system files thanks to dune's build compositionality. (In fact, this compositionality would also allow plugin developers using dune as a primary build system to include a copy of Coq in a sub-directory of their repository if they wished to.)

The synchronization would entirely be the role of @coqbot:
- When a PR is opened or synchronized and includes changes in a plugin, it extracts these changes, and opens (or synchronizes) a PR on the corresponding plugin repository. It refers to the upstream PR for context and urges plugin authors to make any comments they may have directly on the PR upstream (all plugin authors can be easily added to the "Contributors" team of the Coq organization, which would allow them to do "Request for changes" on Coq's PRs).
- When a PR is merged in Coq, @coqbot also merges the PR on the plugin repository if it was given write access, or else comments on the PR thread to signal plugin authors that they may proceed with the merge. Note that even if the plugin authors do not react very fast, this is not a problem as Coq will contain an updated copy.
- When a change is pushed on a plugin repository, @coqbot updates Coq's copy immediately (probably without going through a PR, trusting plugin authors to use CI systematically before pushing to branches that are synchronized in the Coq repository -- this would then become risk-free when Coq's merging process becomes bors-like).

This solution (let's call it solution A) solves (AFAICT) all three problems mentioned above and all the required tooling is within @coqbot. It could also seriously simplify the creation of install bundles and bring internal and external plugins much closer. It would also be possible to apply this methodology to non-plugins that we still want to keep tightly synchronized with Coq (e.g. stdlib2).

The only other solution that I can see to the three problems mentioned above is to emulate this near-monotree approach but without actually including a copy of external plugins in the Coq repository. In this case, instead of storing a copy of the plugins, we would simply make `*_CI_REF` variables (from `ci-basic-overlays.sh`) contain commit hashes instead of branches (as was proposed initially in this thread). We would have tooling that would clone the repositories of the plugins inside the developer's local Coq clone (we would probably add these paths to `.gitignore`). Thanks to dune, it would be easy to fix the plugins (even before pushing). Then we would have more tooling to create and submit overlays (stub already exists with Emilio's scripts from #9018). This solution (let's call it solution B) also works but the required tooling is now in the hands of the developers (and thus it makes the process more complex for them as you cannot just commit and push). This is why, at this point of my thinking, I'm now more favorable to solution A.

**Comment by vbgl** [comment] 2019-02-14 10:04
What’s the status of this? Are you Théo willing to try one of the solutions you described above?

**Comment by Zimmi48** [comment] 2019-02-18 13:28
@vbgl I'm still interested to work on it. However, I really want to take advantage of the build compositionality offered by Dune, so this is pending on ocaml/dune#1555.

**Comment by ejgallego** [comment] 2019-04-01 14:37
> @vbgl I'm still interested to work on it. However, I really want to take advantage of the build compositionality offered by Dune, so this is pending on [ocaml/dune#1555](https://github.com/ocaml/dune/pull/1555).

Can you detail what you are missing @Zimmi48 ? I will submit the PR enabling the composition of Coq libraries soon and will bump the dune coq lang to 1.0, but it'd be good to know what more we could do for you.

**Comment by Zimmi48** [comment] 2019-04-01 15:05
I think that at this point, all the required bricks will be there.

**Comment by MSoegtropIMC** [comment] 2019-07-02 08:22
@Zimmi48 : I just started to follow this discussion - @RalfJung linked it in a coq-dev discussion.

One question: couldn't we have forks - owned by the Coq group - of all plugins which need tight synchronization and build from these forks? Coqbot could then create PRs to the upstream repos from these forks and possibly also keep the forks in sync. One could even switch easily between using the upstream repo and the fork on a as needed basis.

**Comment by Zimmi48** [comment] 2019-07-02 09:01
@MSoegtropIMC I fail to see what having forks would bring beyond what we have today: it would not solve the synchronization problem, contrarily to the monorepo approach, so I'm not sure what problem it would aim to solve. We do not really suffer at the current time of the lack of responsiveness from upstream authors that would make it necessary to maintain our own forks.

---

*Just FWIW the lack of progress on this front and on the Coq platform front more generally is not because I am not satisfied by the solutions I sketched, but because I just have no time for this right now, as I'm writing my thesis, but this is one of the things I intend to work on soon after I wrap it up.*

**Comment by MSoegtropIMC** [comment] 2019-07-02 09:22
@Zimmi48 : To make my suggestion clear: instead of copying the plugin code into the Coq source tree (which is my interpretation of what you mean with monotree) Coq has forks of all plugin coqbot can write to. If someone makes a synchronized pull request to the Coq tree and a plugin (by referencing her/his own fork of a plugin in some CI control file) coqbot can make both merges and change the reference in the CI file to coqbots fork of the plugin and run CI on this. This ensures that we have a copy of the code we used for CI under our control. At the same time coqbot can create an upstream PR for the plugin. And if this upstream PR gets merged, coqbot could even change the CI reference to the corresponding  hash of the upstream. This would make it easier to switch to a different upstream hash later (without worrying if things are merged properly between the coqbot fork and upstream). If someone makes another synced PR, (s)he would start from the current CI hash.

**Comment by ejgallego** [comment] 2019-07-02 11:07
This is basically how things work today @MSoegtropIMC , with some automation missing, but we will add it soon.

**Comment by Zimmi48** [comment] 2019-07-02 12:07
@ejgallego We are discussing details here, and when looking close, there are significant differences between this proposal (or any other proposal in this thread) and how this works today.

@MSoegtropIMC Thanks for the detailed description, but could you clarify the advantages you see to this solution compared to the solution where the source code of the plugins is copied in the Coq repository? It seems to me that it is not going to make the implementation any simpler, nor is it going to be easier to manage for developers, but maybe I'm missing something.

**Comment by MSoegtropIMC** [comment] 2019-07-02 12:56
@ejgallego : except that currently we have everything tied to master rather than tags. For linking tags in CI this kind of automation is required.

@Zimmi48 : if you actually copy the code you need to handle the connection between the upstream repos and the copies in some manual way (unless I miss something). As far as I can see doing it with forks allows more automation and better history linking between the two. The plugins are fully handled as a separate GIT repo with automated CI and merge integration into Coq.

This is btw. also how we handle this for large modem or automotive projects.

**Comment by ejgallego** [comment] 2019-07-02 13:00
> @ejgallego : except that currently we have everything tied to master rather than tags. For linking tags in CI this kind of automation is required.

Actually the CI overlay infrastructure does support arbitrary pinning and we use it regularly for overlays, it even nicely composes with Dune for a full composed build; I have some extra tooling that allows to manage all repositories, but need to polish it off before I submit it here.

The main difference tho is that clones of the repositories do live in the user space on github, by default when doing any overlay tags/branches will go into the clone of `ejgallego/repos.git`. So far I only support rebase of overlays against the upstream master branch, but that could be made more flexible, dunno about the utility of merges tho.

**Comment by gares** [comment] 2019-07-02 14:48
> Actually the CI overlay infrastructure does support arbitrary pinning and we use it regularly for overlays

Yes, in addition to writing "master" or "coq-master" we can also write "HASH" or "TAG" or "GITREF" in basic-overlay (as we do in PRs overlay where we typically write a feature branch).

What this issue was about is *changing the policy* to never write "master" and always write a TAG or a HASH. What is missing in order to make this approach feasible is some automation to advance the hashes/tags in a semi automatic way.

> This ensures that we have a copy of the code we used for CI

IMO the schema you propose is quite convoluted. Can't CI just save the tarball corresponding to the HASH/TAG as an artifact (later to be included in the "open source archive")?
I guess I'm missing why we need a full fork, and I only the synchronization problems it generates.

**Comment by ejgallego** [comment] 2019-07-02 14:56
First the premise of this issues "This regularly causes CI failures" seems like too strong to me. I don't think we are seeing regular failures.

The CI already records which tag the CI is run against, so that's a matter of the tooling reading that info.

> What is missing in order to make this approach feasible is some automation to advance the hashes/tags in a semi automatic way.

My point is that in a sense we have such system now, and while is not pain-free, at least avoids problems of running stale CI, etc...

**Comment by Zimmi48** [comment] 2019-07-02 15:23
@ejgallego When I start working on this, I'll need to make sure I synchronize with you to not redo some work that you may already have done.
Regarding the “regular CI failures”, you just stopped noticing them, but indeed, we see CI failures in plugins on PRs right after a PR with plugin overlays was merged, and it is sometimes confusing to external contributors. But anyway, I don't really want to have this debate again right now.

@MSoegtropIMC You are indeed missing something: as you can read above, the idea of the single tree was to have a fully automatic synchronization process, and I seriously think that it will be less work to implement it that way, than with the forks that you proposed. But this remains to be seen when the actual implementation work is done. In any case, your solution is closer to the solution initially proposed (and reminded by @gares above) which is just to pin hashes using the current infrastructure, and develop tooling to update them automatically.

**Comment by ejgallego** [comment] 2019-07-02 15:29
> we see CI failures in plugins on PRs right after a PR with plugin overlays was merged

a fix for this doesn't have to necessary involved stop tracking `master`, in fact, that would only make the situation worse. What we need here is that the tooling that merges the PRs in reaction to a Coq merge does rebase the rest of the overlays open. I have something that does that [manually] in my `overlay` script. I though I had posted some info about it in some other issue but I can't locate that now.

@Zimmi48 I'll flush all my current in-flight work before the fall so we should hopefully get in sync. But basically I'm working on the tooling to manage overlays manually.

**Comment by ejgallego** [comment] 2019-07-02 15:35
For the record, I am strongly convinced that the answer to the main question here:

> What commit from 3rd party developments should CI test?

is that we should test whatever commit the 3rd party developers want. **It is not our job** to update the tag, ref, etc... but theirs. We chose ` master` because it is a reasonable default for many devs, but already some devs are not tracked for `master` [tho a few that didn't chose this approach switched to it as it quite practical]

**Comment by MSoegtropIMC** [comment] 2019-07-02 15:56
@ejgallego : one advantage of using only tags/refs is that this way we could test in CI what we (plan to) release. I think it is agreed that a release must only use tags/refs and never branches because otherwise a release build would not be reproducible with I think would be unacceptable.

**Comment by MSoegtropIMC** [comment] 2019-07-02 16:00
@Zimmi48 :
> But this remains to be seen when the actual implementation work is done.
Indeed I don't see how local copies with their own history would be easier to manage than using just one (distributed and forked) git repo.

**Comment by ejgallego** [comment] 2019-07-02 16:09
> I think it is agreed that a release must only use tags/refs and never branches because otherwise a release build would not be reproducible with I think would be unacceptable.

Even if you use branches it doesn't imply that a release build is not reproducible, the actual ref used in a build are kept so you can reproduce the build.

**Comment by ejgallego** [comment] 2019-07-02 16:09
But indeed I agree that tagged builds are a bit special, most of my comments do apply to the context of regular PR testing.

**Comment by RalfJung** [comment] 2019-07-02 16:12
> My point is that in a sense we have such system now, and while is not pain-free, at least avoids problems of running stale CI, etc...

The key difference between the current *implicit* updating of tested developments and a more *explicit* variant lies in all the usual benefits of making state more explicit: updating the development that is tested becomes a commit one can talk about, a commit that is subject to CI (which currently those updates are not!), a commit that can be reverted, and so on.

**Comment by MSoegtropIMC** [comment] 2019-07-02 16:17
> Even if you use branches it doesn't imply that a release build is not reproducible, the actual ref used in a build are kept so you can reproduce the build.

Assuming one has a mechanism which actually takes care of this and documents this properly - which I believe we don't have. I think the documentation on what a release really contains should be a document in GIT and not some CI artifact.

**Comment by ejgallego** [comment] 2019-07-02 22:46
> the current _implicit_ updating of tested developments and a more _explicit_ variant lies in

@RalfJung note that upstream authors are free to choose what to test, so indeed "current" is wrong here as at least one development do pin the version they test on the CI.

> easier/better reproducibility than having to extract the exact hashes from some online database and then having to convince the local scripts to actually use them.

I have to digress, the current CI setup is pretty simple and IMHO that's a key point of its success, specially with the manpower we have; it is much easier to develop such script than to take care of updating what potentially could be hundredths of refs in the upcoming years. That simply doesn't scale.

Anyways I think we are talking about different things: packing for a release and running CI. IMO, for the first part, the Coq repos shouldn't become also a packaging point; a different team of packages should use their own repos to manage packing [and I guess they'll end with something similar to Nix]

Regarding CI, and this issue. IMO we should close it with the following outcome:

- What commit to test: the one upstream authors indicate.
- What to do to reproduce CI builds? I'm unsure about what value would have to reproduce a CI build with the same data; care to explain @SkySkimmer ? I should fail again. One the contrary retrying builds with different data does save a few full builds every once in while. To reproduce a CI build _locallly_ is of course very useful and for that we should have a script that fetches the data.

**Comment by gares** [comment] 2019-07-03 06:46
> we should have a script that fetches the data

You mean a script that scrapes the logs of CI? How long to these last? Is there an API to fetch them all?

> the one upstream authors indicate.

That is exactly the point. We have no control a priori, we can just see a posteriori that the CI green light is about an old version. Assuming the script above exists, we can probably fetch the last working version, but just using the metadata in our repo would not help.

**Closed** 2023-05-25 10:20 UTC
Labels: kind: infrastructure, food for thought, part: CI

**Comment by ejgallego** [comment] 2023-06-20 17:41
I did read the discussion carefully again, I'm sorry we didn't manage to make more progress on the core issue and have a more efficient discussion.

I also think that the problematics outlined by @Zimmi48 are still present, so I'm unsure we should consider this fully solved. (I won't reopen it but I can understand other doing so)

Apart from reproducibility issues, there are caching issues ( see for example https://github.com/ejgallego/coq-lsp/issues/472 ) , and indeed pinning deps in a multi-repos setup is required in many scenarios.

However my original fear is still a big problem, latency poses a large risk, in particular as it requires a lot of manual intervention in case of conflict. I'm unsure how to manage that while retaining good properties. The current tradeoff has been working but it is far from satisfactory.

@Alizter and I have been doing quite a few experiments on this kind of setup with https://github.com/ejgallego/coq-universe/

The hypothesis of coq-universe is actually pretty close to Théo views (as I understand them): it is possible to simulate a "monorepos" setup using some advanced tooling and lots of computing infrastructure.

So maybe a way forward with this problem is to continue experiementation on coq-universes and its tooling, and transfer some of the tech there to Coq's CI when we feel it is ready.

**Comment by Alizter** [comment] 2023-06-20 19:13
I should note that there is on-going work on package management in Dune which will make building CI projects much easier all within Dune. Regardless of whether or not those projects use Dune as a build system.
