### ISSUE TITLE
Impossible to `Require` files in 8.11

### ISSUE THREAD

**Issue by silene** [coq/coq#11057] opened 2019-11-06 14:57 UTC
I must do something terribly wrong, but just typing

    From Flocq Require Import Zaux.

causes a failure in coqtop and coqide:

    Error: Unable to locate library Zaux with prefix Flocq. (While searching for a .vos file.)

If it is now mandatory to install `.vos` files before doing an interactive proof, it should certainly be mentioned in the changelog.

Obviously related to #8642.

**Comment by ejgallego** [comment] 2019-11-06 15:10
This is IMO a bug in the `vos` implementation; there are more things that need to be solved with `vos` IMO before the 8.11 beta.

**Comment by maximedenes** [comment] 2019-11-06 16:03
@charguer What was the intended behavior in this scenario?

**Comment by charguer** [comment] 2019-11-06 18:04
The behavior I had in mind is that the compilation of a library creates vo and empty vos files. These vos files are installed by coq makefile. We forgot to write in the change logs that library authors using custom makefiles should export these Vos files. 

I know the empty Vos file is not ideal, but after lengthy discussions we had not found a simpler solution to achieving our goals.

**Comment by silene** [comment] 2019-11-06 22:04
What I don't understand is the difference between an empty file and a nonexisting file. What is the semantics?

**Comment by charguer** [comment] 2019-11-07 09:03
When using coqide, or coqc -vos, or coqc -vok, à require is interpreted as loading a Vos file. If the vos file is missing,you get an error. If it is empty, the system attempts to load the vo file.

The idea of this policy is to not rely on rules such as "load the most recent of vo and Vos" or "load one if  the other is missing" as these policy may cause loading not up to date files.

**Comment by silene** [comment] 2019-11-07 10:11
I don't understand how having an empty `.vos` file guarantees to Coqide that the `.vo` file is up-to-date.

**Comment by charguer** [comment] 2019-11-07 10:30
> I don't understand how having an empty .vos file guarantees to Coqide that the .vo file is up-to-date.

I am not sure that I fully understand the question.

If you have an empty `.vos` file, and CoqIDE loads the `.vo` file, it will check (as usual) using the magic number that this library is not out-of-date compared with the other required libraries.

It is true that at the moment there is no formal guarantee that the empty `.vos` file was produced at the same time as the `.vo file. Someone recently suggested (see the PR thread) including a magic number inside the currently-empty `.vos` file in order to ensure that it was produced together with the `.vo` file. Would that address your concern?

**Comment by silene** [comment] 2019-11-07 11:44
I don't see how a `.vos` file with a checksum brings more information that a `.vos` file with a checksum. Again, my question is: what information does Coqide gain from such a `.vos` file? (And the corollary question is: if this information is deemed so important, why is Coqc perfectly happy without any `.vos` file.)

I am already getting user bug reports about "quelques soucis avec les *.vos de Flocq et Coquelicot". That is a real pain.

**Comment by charguer** [comment] 2019-11-08 09:29
The current rule for interpreting a `Require` from `coqc -vos`
or from `coqc -vok` or from `coqide` is:
   - if there is a nonempty `.vos`, take it
   - if there is an empty `.vos`, search for the `.vo`
   - else error.

@silene suggests modifying the rule to:
   - if there is a nonempty `.vos`, take it
   - if there is an empty `.vos` or no `.vos` file, search for the `.vo`

This would help with installed library, which wouldn't need to export .vos
files, and help with backward compatibility of makefiles.

Additionnaly, I realized that in addition to `coqc foo.v` producing
`foo.vo` and an empty `foo.vos`, it makes sense to also produce an
empty `foo.vok` to indicate that the proofs are up to date.
(Recall that `.vok` files are always empty files.)


Let me recap the overall policy and its properties, so that we can all check that it makes sense.

**Policy 1**: the production of a `.vo` creates an empty `.vos`.

**Policy 2**: a `Require` from `coqc -vos` or from `coqc -vok` or from `coqide`
first searches for a nonempty `.vos`, and as fallback searches for a `.vo`.

**Property 1**: a command `make foo.vos` or `make foo.vok` never modifies any `.vo` file.

**Property 2**: one can produce `.vo` files and interactively edit `.v` files (provided
the `.vo` of the dependencies exist) without depending on the existence of any `.vos` file.

**Property 3**: no matter the initial state of the system, one is able to interactively
edit `foo.v` after invoking any of the following commands:
- `make foo.vo`
- `make foo.required_vo` (compiles only the dependencies of `foo.v`)
- `make foo.vos`
- `make foo.required_vos` (compiles only the statements in the dependencies of `foo.v`).

**Property 4**: following a `make` command that produces a file `foo.vo`, there is
no subsequent `make` command that will process `foo.v` again, in particular
`coqc -vos foo.v` and `coqc -vok foo.v` won't be called.

**Property 5**: the production of a file `foo.vos` does not depend on the production
or existence of any `.vo` file (nor any `.vok` file).


**Remark**: an installed library may export only `.vo` files, and no empty `.vos` files,
because `coqdep` does not create dependencies on installed library files. Thus, a
user can create a local `.vos` file, and the `Require` it contains will be interpreted
by loading the `.vo` files from the library.

**Comment by ejgallego** [comment] 2019-11-08 09:44
> Additionnaly, I realized that in addition to `coqc foo.v` producing
> `foo.vo` and an empty `foo.vos`, it makes sense to also produce an
> empty `foo.vok` to indicate that the proofs are up to date.
> (Recall that `.vok` files are always empty files.)

All this use of empty files as "markers" makes little sense to me from a build perspective, and it is not going to work with build systems that try to work on a digest-based way. You cannot escape calculating the transitive dependencies anyways so I'm not sure the whole "marker" thing is very useful.

Proofs being "up to date" should be a property of the dependencies of the proofs, whatever the method [last modif, digest, some quotient] is used.

**Comment by proux01** [comment] 2019-11-08 09:49
May I suggest the following way to proceed:
1. @charguer fix the "no .vos found" bug ASAP in a simple PR (by looking for the .vo when no .vos is found as you suggest), this is painful for everybody and probably very easy to fix
2. go on with the discussion on marker files that seem non trivial and may take a bit more time to reach a conclusion

**Comment by charguer** [comment] 2019-11-08 10:14
>  it makes sense to also produce an empty foo.vok to indicate that the proofs are up to date.

Let me reformulate: an empty foo.vok file indicates that the proof of the files could be successfully compiled. 

There are two ways to handle the markers: 
- either the makefile (or dune) does a `touch foo.vos && touch foo.vok` as part of the rule that says that `coqc foo.v` is  the command for producing `foo.vo`. (@ejgallego: is this what you have in mind for Makefile users?)
- or `coqc` is touching these files by itself. 

What would be very ackward is to leave Coq in a state where `coqc` touches the `.vos` file but not the `.vok` file.


btw, I'm working on the PR atm.

**Comment by gares** [comment] 2019-11-08 10:15
> I don't see how a `.vos` file with a checksum brings more information than an empty `.vos` file

This was proposed to help the following

> it is not going to work with build systems that try to work on a digest-based way.

Because dune does not look at the time stamp (that changes if you touch a file) but rather its checksum (that does not). If we put in the .vos file something like the checksum of the corresponding vo then I believe dune can make sense of it.

Anyway this is orthogonal to the top priority which is to make Coqide & co work if there is no vos around. One way to to fallback of vo is not present. Another, discussed during the Coq call, is to make Coqide look for vos only if we pass to it -vos, eg changing the line
  https://github.com/coq/coq/blob/64ddd9ac0c34e560a0640297e2e23b6aaf074810/toplevel/coqtop.ml#L275
from an hardcoded value to a command line option. I prefer this latter option, with default being off.

**Comment by gares** [comment] 2019-11-08 10:17
> What would be very ackward is to leave Coq in a state where `coqc` touches the `.vos` file but not the `.vok` file.

I agree

**Comment by charguer** [comment] 2019-11-08 10:24
@gares : I also considered the option of adding a flag to CoqIDE for loading vos files. But discussing yesterday with @silene, I see at this point three motivations against this approach:
- this flag does not really solve the issue of editing a file that depends both on local files compiled as .vos and on library files compiled as .vo only. (in other words, it still forces libraries to export .vos files, whereas my proposal does not).
- other interfaces (emacs, vscode) will also need to implement the extra flag.
- the user has to care about opening CoqIDE with different flags depending on whether he is working with .vos or .vo (possibly alternating between the two); moreover, one would need visual feedback in CoqIDE (and other interfaces) to display the state of the flag.

**Comment by SkySkimmer** [comment] 2019-11-08 10:27
I think it makes sense to allow loading vos by default unless compiling to vo. The issue is failing when the vos is missing, and to a lesser extent the proliferation of empty files.

**Comment by charguer** [comment] 2019-11-08 10:52
Ok, it's there: https://github.com/coq/coq/pull/11075
I've tested it on TLC/CFML2. 
Please check that it solves your problems.

**Closed** 2019-11-21 10:06 UTC
Labels: priority: blocker
