### ISSUE TITLE
azure macos broken

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#10544] opened 2019-07-21 20:38 UTC
https://dev.azure.com/coq/coq/_build/results?buildId=4211 "fatal: reference is not a tree: 944a5b7d83e4b81c749d93831b514607bdd2b6a1"
cf https://github.com/coq/coq/pull/10509

**Comment by ejgallego** [comment] 2019-07-21 21:03
Yup it seems that homebrew is not very solid in terms of reproducible packages, nor it does seem to support package pinning?

Maybe we should use macports or Nix?

**Comment by ejgallego** [comment] 2019-07-21 22:52
cc #10505 #10505

**Comment by Zimmi48** [comment] 2019-07-22 09:33
Unfortunately using Nix on macOS amounts to almost not testing macOS, I'm afraid.
I suggest trying the alternative pinning strategy from #8526 (although this would mean pinning each package separately) because GitHub is going to be more robust than homebrew w.r.t. data persistence: e.g. https://raw.githubusercontent.com/Homebrew/homebrew-core/944a5b7d83e4b81c749d93831b514607bdd2b6a1/Formula/opam.rb still exists.

**Comment by ejgallego** [comment] 2019-07-23 16:56
This seems fixed now; how did it happen? Maybe the failures were due to a github problem?

**Comment by SkySkimmer** [comment] 2019-07-23 20:10
Failed here https://dev.azure.com/coq/coq/_build/results?buildId=4249&view=logs

**Comment by ejgallego** [comment] 2019-07-23 21:16
Yet here succeeded ? https://github.com/coq/coq/pull/10549/checks?check_run_id=175468075

What is going on?

**Comment by SkySkimmer** [comment] 2019-07-23 21:19
Maybe something weird with the fetch
for instance we fetch -since the date of the commit we want, but maybe sometimes we get a machine in a time zone such that the commit is on the previous day
or some other bs
It may be more stable to rm -rf * and get the tarball for the commit instead

**Comment by ejgallego** [comment] 2019-07-23 21:34
Oh, indeed the `fetch --since` may be the problem here.

**Comment by Zimmi48** [comment] 2019-07-29 14:06
I saw it again today: https://dev.azure.com/coq/coq/_build/results?buildId=4315. May I insist in suggesting the alternative pinning method that had been tested in #8526, and that had been successful? @vbgl?

**Comment by vbgl** [comment] 2019-07-29 14:16
I’ll give it a try.

**Comment by ejgallego** [comment] 2019-07-29 14:27
We could also remove the `--since` and use some other number.

**Comment by vbgl** [comment] 2019-07-29 14:38
We could use `git fetch --unshallow`; but that repository is a bit large: do we care?

**Closed** 2019-07-30 16:44 UTC
Labels: kind: ci-failure, kind: infrastructure
