### ISSUE TITLE
Non-standard installation paths

### ISSUE THREAD

**Issue by silene** [coq/coq#14833] opened 2021-09-01 15:43 UTC
When executing the following
```shell
./configure -prefix foo
make
make install
```
some files get installed to `foo/doc` instead of `foo/share/doc`. This is both non-standard and unexpected. This is especially improper when `foo` happens to be `/usr` (for package managers) or `/usr/local` (for users).

This happens both with an Opam-based Dune (the recommended way of installing Dune) and a manually compiled one (using `make release` in the Dune repository, as documented).

This is a regression with respect to 8.13. This is possibly redundant with #14232 and #14468, but put as a separate issue so as to focus on the blocking part.

**Comment by Zimmi48** [comment] 2021-09-06 13:33
@silene Could #14844 be considered enough to close this? I.e., if users are installing Dune through opam, then they should get Dune >= 2.9. Otherwise, they should skip the `make install` step and run `opam-installer` with the right options instead. AFAIU, there is no problem with the default doc install location when using an older Dune version if it was packaged as a Debian / Ubuntu package or such, because it is then configured differently (this would need to be confirmed).

**Comment by silene** [comment] 2021-09-06 14:09
> Could #14844 be considered enough to close this?

I need to find some time to actually test it.

> there is no problem with the default doc install location when using an older Dune version if it was packaged as a Debian / Ubuntu package or such, because it is then configured differently (this would need to be confirmed).

I just tried with Dune 2.7.0, as shipped in Ubuntu (and Debian). Files still get installed in the wrong place. And this is not specific to Coq. Even the Debian packaging rules of Dune have to manually remove wrongly installed documentation files from the Dune package itself. (They do not even bother moving them to the correct place, they just blindly remove them, which is fine, I guess.)

> run `opam-installer` with the right options instead

I have no idea how to run `opam-installer` on Coq. Is that documented somewhere? In particular, how does one get Dune to produce the `coq.install` file that `opam-installer` waits for?

**Comment by Zimmi48** [comment] 2021-09-06 14:26
> I just tried with Dune 2.7.0, as shipped in Ubuntu (and Debian). Files still get installed in the wrong place. And this is not specific to Coq. Even the Debian packaging rules of Dune have to manually remove wrongly installed documentation files from the Dune package itself. (They do not even bother moving them to the correct place, they just blindly remove them, which is fine, I guess.)

OK, thanks for checking.

> I have no idea how to run `opam-installer` on Coq. Is that documented somewhere? In particular, how does one get Dune to produce the `coq.install` file that `opam-installer` waits for?

I think it does by default when you run `dune -p`. See https://github.com/coq/coq/pull/14844/files#diff-3ec5f4f9e74d58e12516b2c5468376f03445f2eeb4b1ced448fcda344d841c86R132-R134.

**Comment by ejgallego** [comment] 2021-09-06 14:42
> I just tried with Dune 2.7.0, as shipped in Ubuntu (and Debian). Files still get installed in the wrong place. And this is not specific to Coq. Even the Debian packaging rules of Dune have to manually remove wrongly installed documentation files from the Dune package itself.

Indeed, there are quite a few bugs in the packaging still present in Debian; as for Dune, they should apply this patch to 2.7.1:
```
diff --git a/src/dune_rules/install.ml b/src/dune_rules/install.ml
index afa2acdad..9fd7e6779 100644
--- a/src/dune_rules/install.ml
+++ b/src/dune_rules/install.ml
@@ -209,7 +209,7 @@ module Section = struct
       let libexec_root = libdir in
       let share_root = Path.relative destdir "share" in
       let etc_root = Path.relative destdir "etc" in
-      let doc_root = Path.relative destdir "doc" in
+      let doc_root = Path.relative share_root "doc" in
       { lib_root
       ; libexec_root
       ; share_root
```

**Comment by ejgallego** [comment] 2021-09-06 14:43
Note that indeed this is a Dune + Debian bug, which just happens to be inherited by Coq.

**Comment by silene** [comment] 2021-09-07 06:22
> Note that indeed this is a Dune + Debian bug, which just happens to be inherited by Coq.

There is nothing specific to Debian in that issue. It also happens for RPM-based distributions. Indeed, they do `rm -fr %{buildroot}%{_prefix}/doc` to manually remove the files Dune has installed in the wrong directory.

- Fedora: https://src.fedoraproject.org/rpms/ocaml-dune/blob/rawhide/f/ocaml-dune.spec
- Debian: https://salsa.debian.org/ocaml-team/ocaml-dune/-/blob/master/debian/rules

**Comment by Zimmi48** [comment] 2021-09-07 06:39
One stricter way to fix this issue would be for configure to detect whether Dune 2.9+ is available, and if it is not, to *require* `opam-installer` (and use that in the `make install` phase instead). In this case, we would always be able to fix the doc install directory, even with an unpatched Dune.

**Comment by silene** [comment] 2021-09-07 08:09
I am leaning toward a simpler solution: Just release as-is and put in front of the release notes the following blob:

"Note to distribution packagers: Regardless of the setting of `configure -docdir`, Coq incorrectly installs some files to `%prefix%/doc` (e.g., `/usr/doc`). These files can and should be removed from user systems. Sorry for the inconvenience."

**Comment by Zimmi48** [comment] 2021-09-07 08:26
Sounds good, but you mean without even including the changes in #14844? If they are included, we can amend this warning to say "when using Dune < 2.9".

**Comment by Alizter** [comment] 2021-09-07 08:30
Why don't we just bump to dune 2.9?

**Comment by ejgallego** [comment] 2021-09-07 08:35
The problem with fedora is also a bug in the fedora package. Distributions should package dune so that the default install directories are correct.

Regarding 8.14, both PRs targeting configure fixes must be merged.

**Comment by silene** [comment] 2021-09-07 08:43
> Sounds good, but you mean without even including the changes in #14844?

Yes, I am fed up of waiting. Let us just release.

**Comment by ejgallego** [comment] 2021-09-07 08:52
Please don't release broken software, in particular when a fix exists.

**Comment by silene** [comment] 2021-09-07 10:44
This is not a suitable fix, as far as I am concerned, since it changes the meaning of a `configure` option. For example, the file `coq.8.14.dev/opam` is not compatible with this change, as far as I understand. So, I will not include it in the final release of 8.14.

**Comment by ejgallego** [comment] 2021-09-07 19:14
Closed by  #14844

**Closed by ejgallego** 2021-09-07 19:14 UTC
Labels: priority: blocker

**Comment by ejgallego** [comment] 2021-09-07 19:20
> For example, the file `coq.8.14.dev/opam` is not compatible with this change, as far as I understand.

I tried to understand that, but according to opam documentation, #14844 made the file actually more correct, as it uses `"-docdir" doc` which IIANM refers to a switch variable.

**Comment by ejgallego** [comment] 2021-09-08 09:07
Indeed, I have actually confirmed it, the Coq opam packages are buggy, including the 8.14 one, as they set -docdir incorrectly. So it turns out that [by chance] #14844 fixes it.
