### ISSUE TITLE
coqide is very slow with many shelved goals (XML protocol?)

### ISSUE THREAD

**Issue by andres-erbsen-sifive** [coq/coq#10623] opened 2019-08-05 17:57 UTC
#### Description of the problem

```coq
Goal True.
  do 1000 (assert True by admit); clear.
  idtac.
Abort.
```

takes .5s in `coqc`, .5s in ProofGeneral, and ~10s in coqide. Even stepping back into that proof is very slow. This is forcing me to switch back to ProofGeneral for now.

#### Coq Version

8.9.1

coqtail has the same issue (https://github.com/whonore/Coqtail/issues/55), so I would expect other clients that use the new interaction protocol to be similarly impaired.

**Comment by ppedrot** [comment] 2019-08-05 20:44
Yes, that's a feature that was introduced despite my warnings that it would create slowness. The reason is that coq unconditionally sends all the goals to the GUI, including the shelved ones. It used to be the case that you had to ask explicitly for this data. IIRC this was introduced by @ejgallego.

**Comment by ejgallego** [comment] 2019-08-05 22:36
I don't have any memory of ever working in that area @ppedrot, in fact I advocate a very different model of interaction. Do you have a commit that I could look into?

**Comment by ppedrot** [comment] 2019-08-06 08:20
I did a little bit of archaeology, and indeed @ejgallego is innocent. This feature was introduced quite a long time ago between 8.4 and 8.5 together with the new tactic engine, probably by @aspiwack. But I do remember complaining at the time.

I guess we can fix it by extending the XML goal query with parameters to specify the subset of the data to be sent.

**Comment by gares** [comment] 2019-08-06 08:30
note that `admit` generates a given_up goal, not a shelved one. Was it a guess or you did profile?

**Comment by gares** [comment] 2019-08-06 08:31
Also, @andres-erbsen-sifive am I right assuming you open that file and you "jump to the end" and then wait until all is green? Is that what takes 10 seconds?

**Comment by andres-erbsen-sifive** [comment] 2019-08-06 16:53
I put the cursor after `idtac.`, press Ctrl + rightarrow, and wait until I see "Coq is ready" in the bottom right corner.

**Comment by aspiwack** [comment] 2019-08-06 18:22
For the records, I don't think that I have anything to do with this. My interaction with the XML protocol was, a best, very superficial. But attribution doesn't really matter, aside from curiosity :slightly_smiling_face: .

**Comment by ppedrot** [comment] 2019-08-06 20:38
@gares both shelved and given up goals are sent. Sorry for not using the right terminology.

**Comment by ppedrot** [comment] 2019-08-06 20:51
@aspiwack I know we should forgive our neighbour and whatnot, but well, git wrath will forever remember c9504af26647ab745dc22811a2db8058e0b66632 and fb1c2f25fb0ca5f422c69e14b6b434ad1d8f01a9 :zap:

**Comment by aspiwack** [comment] 2019-08-07 05:28
That doesn't look like the change in logic that you were mentioning though: if I'm reading correctly, all the goals were already sent, and I just added the shelved and given up goals to the mix.

Maybe looking at where `bg_goals` was introduced will blame me for a change in the logic though. Who knows?

But trying to move forward, is the following

```coq
Goal True.
  do 1000 (assert True by admit); clear.
  trivial.
```

also very slow in coqtop/proof general? (does proof general display the given up goals at all? it certainly prints the shelved ones)

At any rate, if the amount of data sent is the issue, then there is no real way out except:
> I guess we can fix it by extending the XML goal query with parameters to specify the subset of the data to be sent.

**Comment by JasonGross** [comment] 2019-08-07 05:34
> it certainly prints the shelved ones

It does not print the context of shelved goals, though, so the growth is not quadratic

**Comment by jfehrle** [comment] 2020-10-25 04:54
The CoqIDE debug output and an examination of the code tell a different story.

Whenever CoqIDE fetches the Goals, it follows up with a call to get the Evars.  The size of the output grows as the square of the do count; here is one of the 1000 evars that are returned by the Evars call:

```
[?Goal6 : [H : True
          H0 : True
          H1 : True
          H2 : True
          H3 : True
          H4 : True
          H5 : True |- True]]
```

AFAIK, CoqIDE doesn't display the Evars at all.  It appears it's used only in `Wg_Proofview.display` to generate messages such as "No more subgoals, but there are non-instantiated existential variables:\n\n".

`display` is only called from `proof_view#refresh`, which is a workaround for a GUI problem.  The comment on `#refresh` is:

```
(* We need to block updates here due to the following race:
         insertion of messages may create a vertical scrollbar, this
         will trigger a width change, calling refresh again and
         going into an infinite loop. *)
```

I can't figure out how to reproduce this, nor do I see the messages from `display`.  That code is mainly from df1d4dc9c3808a811111e4cd9eeda328b51f20de.  Perhaps @ejgallego can remember what this was about and whether it's still needed.

`display` prints all the non-instantiated existential variables, if it's ever called.

If `#refresh` is no longer needed, this can be fixed by just deleting code.  If the user should be able to see all the non-instantiated evars, we should consider ways to do that better. 
 Please advise.

**Comment by jfehrle** [comment] 2021-01-26 06:59
The server-side call to Idetop.goals takes 62 seconds, generating a 70MB message that takes .8 seconds to read and 2.4 seconds to parse.

**Comment by ppedrot** [comment] 2022-02-05 13:09
Working on this one, almost have a full patch ready that I will submit soon.

**Closed** 2022-02-08 16:34 UTC
Labels: kind: performance, part: IDE
