### ISSUE TITLE
"Nat.add not found" even though "(1 + 2)" notation relying on Nat.add works fine.

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#19468] opened 2024-08-21 03:08 UTC
### Description of the problem

I don't see why `Nat.add` is not accepted on line 5.  Seems like a bug.  Is it?

![image](https://github.com/user-attachments/assets/610825cc-af2e-443a-8891-c92eaa21b4af)

### Small Coq file to reproduce the bug

```coq
Require Import Nat.

Goal (Nat.add 1 2) = 3.
let x := (1+2) in idtac x.  (* 1 + 2 *)
let x := (Nat.add 1 2) in idtac x.  (* Nat.add not found in the current environment *)
```

### Version of Coq where this bug occurs

8.21 alpha

**Comment by Janno** [comment] 2024-08-21 13:01
I have long thought there was something weird with ltac sometimes parsing constrs automatically and sometimes not. This example makes me think I am not imagining this. I never tried to minimize it because I wasn't sure a term without `constr:()` or something similar around it shouldn't be parseable at all in Ltac.

In your example you can add the quotation to make it work: `let x := constr:(Nat.add 1 2) in idtac x.` I agree that the inconsistency here is really confusing.

**Comment by ppedrot** [comment] 2024-08-22 20:11
This is not a bug, this is a Ltac *feature*. Ltac "arguments" are parsed as constrs as a last resort, but have a more precise grammar for some hardcoded cases. In particular `reference list(arguments)` is parsed as an Ltac1 expression, not a constr. The error thus means that Nat.add is not a defined Ltac reference in the environment.

As is usual for Ltac1 quirks, this is a clear WONTFIX.

**Closed by ppedrot** 2024-08-22 20:11 UTC
Labels: kind: bug, needs: triage
