### ISSUE TITLE
Anomaly "grounding a non evar-free term"

### ISSUE THREAD

**Issue by zeldovich** [coq/coq#8155] opened 2018-07-25 18:43 UTC
#### Version

The Coq Proof Assistant, version 8.9+alpha (July 2018)
compiled on Jul 24 2018 0:32:36 with OCaml 4.05.0

Git commit 32415df7e24d4d79a00fae95a5f619980b006c61

#### Operating system

Linux

#### Description of the problem

```
Axiom x : Type -> Type.
Fixpoint f (a : x _) := tt.
```

gives:

```
Error: Anomaly "grounding a non evar-free term"
Please report at http://coq.inria.fr/bugs/.
```

**Comment by tchajed** [comment] 2018-08-07 18:44
This is probably a duplicate of #7538 for what it's worth.

**Comment by ejgallego** [comment] 2018-10-28 13:51
Confirmed duplicate of #7538

**Closed by ejgallego** 2018-10-28 13:51 UTC
