### ISSUE TITLE
cumulativity for records

### ISSUE THREAD

**Issue by DanGrayson** [coq/coq#9793] opened 2019-03-17 15:13 UTC
I wonder whether there is any possibility of getting this sort of cumulativity to work in the future.  I'm referring to the "Fail" command below, using Coq 8.9.0 or the latest on the master branch.
```coq
Set Universe Polymorphism.
Set Primitive Projections.
Set Polymorphic Inductive Cumulativity.
Set Printing All.
Set Printing Universes.

Inductive paths@{i} {A:Type@{i}} (a:A) : A -> Type@{i}
  := idpath : paths a a.

Inductive nat : Type :=
| O : nat
| S : nat -> nat.

Record total2@{i} (T : Type@{i}) (P : T -> Type@{i}) : Type@{i}
  := tpair { pr1 : T; pr2 : P pr1 }.

Definition iscontr@{i} (T:Type@{i}) : Type@{i}
  := total2 T (fun cntr => forall t:T, paths t cntr).

Fixpoint isofhlevel@{i} (n : nat) (X : Type@{i}) : Type@{i}
  := match n with
     | O => iscontr X
     | S m => forall x : X, forall x' : X, (isofhlevel m (paths x x'))
     end.

Definition isaprop@{i} := isofhlevel@{i} (S O).

Definition isaset@{i} := isofhlevel@{i} (S (S O)).

Definition hSet@{i i'} : Type@{i'} := @total2@{i'} Type@{i} isaset@{i}.

Definition hSetpair@{i i'} (X : Type@{i}) (i : isaset@{i} X)
  := tpair@{i'} Type@{i} isaset@{i} X i : hSet@{i i'}.

Definition checkEta (X : hSet) : paths X (tpair Type isaset (pr1 _ _ X) (pr2 _ _ X)).
Proof.
  reflexivity.
Defined.

Definition change_hSet@{i i' j j' | i < j, i < i', j < j'} : hSet@{i i'} -> hSet@{j j'}.
Proof.
  intros X. lazy. lazy in X.
  Fail exact X.                 (* fails with universe inconsistency *)
  exact (tpair _ isaset@{j} (pr1 _ _ X) (pr2 _ _ X)).
Defined.
```

**Comment by DanGrayson** [comment] 2019-03-17 15:14
@mattam82 -- this may be in your area of expertise.

**Comment by SkySkimmer** [comment] 2019-03-17 17:34
Duplicate of https://github.com/coq/coq/issues/3353

**Closed by SkySkimmer** 2019-03-17 17:34 UTC
