### ISSUE TITLE
Error: Anomaly "Uncaught exception Failure("action op")."

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#18436] opened 2023-12-23 00:01 UTC
#### Description of the problem

```bash
$ printf 'Set Ltac Debug. Ltac foo := idtac; idtac "bar"; idtac "baz". Goal True. foo.\nr "bar"\n' | coqtop
Welcome to Coq 8.18.0

Coq <
foo is defined

1 goal

  ============================
  True

Goal:

  ============================
   True


Going to execute:
foo

TcDebug (0) > Executed expressions: 0

Executed expressions: 1

Executed expressions: 2

Executed expressions: 3

bar
Toplevel input, characters 72-76:
> Set Ltac Debug. Ltac foo := idtac; idtac "bar"; idtac "baz". Goal True. foo.
>                                                                         ^^^^
Error: Anomaly "Uncaught exception Failure("action op")."
Please report at http://coq.inria.fr/bugs/.

Unnamed_thm <
```

cc @jfehrle 

#### Coq Version

8.18.0

**Comment by ejgallego** [comment] 2023-12-23 00:39
cc @jfehrle

**Comment by jfehrle** [comment] 2023-12-23 03:43
Thanks for the report.  This is a duplicate of #18067, which is fixed by #18068 in 8.19.

**Closed by jfehrle** 2023-12-23 03:43 UTC
Labels: kind: anomaly, part: ltac debugger

**Comment by JasonGross** [comment] 2023-12-23 03:52
Neat, thanks!  Sorry I missed that
