### ISSUE TITLE
Performance suggestion: Investigate the impact of the `best-fit` allocator, new in OCaml 4.10

### ISSUE THREAD

**Issue by gasche** [coq/coq#11277] opened 2019-12-11 09:09 UTC
(This is an enhancement suggestion rather than a bug.)

OCaml 4.10 should be released within a few months. The main feature of the new release (besides breaking internals-using C code) is a new `best-fit` allocator for the OCaml major heap, who appears to do wonders on memory-constrained programs by reducing fragmentation in the major heap. Benchmarks have shown that, in some cases, enabling it (it is not currently the default) can lead to programs that are both faster and use less memory.

*If* your workload results in major-heap fragmentation, which may or may be the case of Coq proofs, we've observed 30%-or-more reductions in memory usage, some of which can be traded back into reductions of the GC time of the program. (What's a typical proportion of Gc time for a large Coq development?)
(One reason why Coq proof may *not* suffer from major-heap fragmentation is that hashconsing may result in fairly different liveness patterns from usual programs. Another is that the Coq term representation may result in few larger blocks on the heap -- except in native-compute scenarios, are there Coq terms with arrays of size above 16? It's hard to tell without an experiment.)

I'm creating this issue to encourage Coq maintainers to experiment with the `best-fit` allocator, once they have a version of Coq that is compatible with OCaml 4.10, and track the effectiveness (or not) of this experiment.

No change to the build system is required, you just have to run your OCaml program under the `OCAMLRUNPARAM="a=2"` environment setting. It may also be beneficial to increase the `space_overhead` setting of the GC (this will reduce GC time at the cost of increased memory usage; this may let you convert some of the space reduction into a time reduction), for example `OCAMLRUNPARAM="a=2,o=100"` (or `120`, etc.; this is a memory overhead in percentage of the live heap size, the default is `80`).

For slightly more details on the `best-fit` memory allocator, see the [gc.mli documentation](https://github.com/ocaml/ocaml/blob/4.10/stdlib/gc.mli), in particular the `allocation_policy` field.

**Comment by ejgallego** [comment] 2019-12-11 14:42
Thanks for the pointer @gasche , this was already on my roadmap, however we must first solve the problems with 4.10 and thus merge #11131 ; then we could use the bench suite to see some macro scale numbers easily.

**Comment by ppedrot** [comment] 2019-12-11 14:48
I am willing to run a bench with those two PRs merged first though, it cannot hurt to give a rough idea...

**Comment by ejgallego** [comment] 2019-12-11 15:00
> I am willing to run a bench with those two PRs merged first though, it cannot hurt to give a rough idea...

Can we set the allocator from OCaml code, or do we need to set the env variable manually?

If the last case, we may need to update the bench script so it allows us to set this.

**Comment by ejgallego** [comment] 2019-12-11 15:43
@ppedrot in #11131 you have a version where the merge conflict is solved.

**Comment by gasche** [comment] 2019-12-11 16:10
> Can we set the allocator from OCaml code

Yes! I believe the right invocation is

```ocaml
let () =
  Gc.(set { (get ()) with allocation_policy = 2; space_overhead = ...; }
```

Note that [the Gc documentation](https://github.com/ocaml/ocaml/blob/4.10/stdlib/gc.mli) says:

> Note: changing the allocation policy at run-time forces a heap compaction, which is a lengthy operation unless the heap is small (e.g. at the start of the program).

**Comment by ppedrot** [comment] 2019-12-11 16:12
We already do this in the Coq code, actually, it's only a matter of tweaking one line.

P.S.: for some reason opam fails at installing the 4.10.0+trunk OCaml version claiming it's not a solvable request, any idea why this happens?

**Comment by gasche** [comment] 2019-12-11 16:14
Did you install the opam repository for ocaml beta versions? See https://github.com/ocaml/ocaml-beta-repository .

**Comment by ejgallego** [comment] 2019-12-11 16:14
@ppedrot see https://github.com/ocaml/ocaml-beta-repository

**Comment by ejgallego** [comment] 2019-12-12 14:14
@gasche @ppedrot preliminary results are not very promising (large slowdown), I'm afraid. I am about to launch a bench in our bench infra tho, let's see how that fares as indeed different Coq setups do have very different memory usage patterns.

**Comment by ejgallego** [comment] 2019-12-12 14:19
Bench will eventually appear here: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/820/

**Comment by gasche** [comment] 2019-12-12 20:49
Can you show the code that you are testing? (I'm interested in looking at the Gc parameters you had set before and the ones you have now.)

Observing a large slowdown is surprising, because we are not currently aware of large slowdowns on any program that the new allocator was tried before. It is more likely to be a problem in the setup, but if you really have a large slowdown, the authors are going to be very interested -- for reproduction and fixing.

**Comment by ppedrot** [comment] 2019-12-12 20:54
In @ejgallego's patch (05e7667438e837b273a3e9de1b077b45a6d965c8) the code is the following:
```ocaml
    Gc.set { (Gc.get ()) with
             Gc.allocation_policy = 2;      (* best-fit *)
             Gc.minor_heap_size = 33554432; (* 4M *)
             Gc.space_overhead = 120}
```

**Comment by gasche** [comment] 2019-12-12 21:01
If the patch is the whole GC-related change, you haven't changed the `space_overhead` value from the Coq defaults. You may need to increase this value to reduce the amount of GC work and get back the same performance. This is explained in the [gc.mli documentation](https://github.com/ocaml/ocaml/blob/4.10/stdlib/gc.mli).

(If think it would make sense to try on a smallish benchmark first, to find what's the right `space_overhead` tuning for compacting policies, and only then use that value on the whole benchmark suite.)

**Comment by ejgallego** [comment] 2019-12-12 21:15
@gasche I'm gonna try with a larger space_overhead, as you recommended 120 I left the default value. 

By "large-slowdown" I mean a 12% percent hit, this is quite large in my book.

**Comment by maximedenes** [comment] 2019-12-12 22:25
> Bench will eventually appear here: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/820/

This is a 404, it seems.

**Comment by ejgallego** [comment] 2019-12-12 22:27
> This is a 404, it seems.

That's the usual jenkins behavior, the bench page is not created until the previous ones have finished.

**Comment by gasche** [comment] 2019-12-13 05:46
Note: the "slowdown" version should in theory exhibit smaller memory usage than with the default allocator. Were you able to observe this?

**Comment by ejgallego** [comment] 2019-12-14 14:02
Some bench results are in and indeed they don't reproduce the slowdown I've observed locally, except in a very particular case:

- o=120 https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/820/console
- o=200 https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/821/console

In fact in some developments it seems that the new allocator does indeed provide an advantage.

I think tho the bench as-is is not a bench where the new allocator should shine a lot, as the `coqc` processes used in compilation are not very long-lived and their memory allocation patterns are kind of "linear"; it would be much more interesting to see how a long-lived interactive proof session performs here, and I'd guess indeed we'd see a big memory reduction in that case.

**Comment by ejgallego** [comment] 2019-12-14 14:05
We should also do a bench on 32bit mode before setting this to be the default if ocaml version >= 4.10 , unfortunately the 4.10.0+32bit variant is still not enabled.

**Comment by gasche** [comment] 2019-12-14 14:46
What we expected from the benchmark results is the following:
- Keeping `space_overhead` the same (o=120) should decrease memory usage (possibly by large amounts), but may hurt performance due to a more active GC.
- increasing `space_overhead` (o=200) should regain performance due to extra GC activity, but may increase memory usage

(I'm going to not consider `coq-performance-tests` in my results above, whose behavior I don't understand and doesn't follow at all the trends of the other benchmark. Separate discussion at the end.)

From the benchmark results, two of those expected outcomes are very clear:

- keeping `space_overhead` the same does decrease memory usage. There are a few outliers (coq-verdi +1.58%, coq-mathcomp-solvable +1.90%, coq-hott +3.22%), but they tend to be benchmarks that are on the "small" side of memory usage among all benchmarks. (all benchmarks are above 420Mio of resident memory, coq-hott goes 580Mio -> 607Mio), many benchmarks with a modest <4% reduction, and a few large wins, especially on memory-hungry benchs. Listing all above-1Gio benches is eloquent:

> coq-veri-raft: 1.8Gio (unchanged)
> coq-geocoq 1.37Gio (unchanged)
> coq-fiat-parsers (2.84Gio -> 2.58 Gio, -9.37%),
> coq-color (1.56Gio -> 1.42Gio, -9.14%)
> coq-unimath (1.13Gio -> 9.81Gio, -13.5%)
> coq-lambda-rust (1.24Gio -> 1.10Gio, -11.0%), 
> coq-fiat-crypto-legacy (2.37Gio -> 2.22Gio, -6.65%)
> coq-fiat-crypo (2.16Gio -> 2.12Gio, -1.79%)
> coq-mathcomp-odd-order (1.29Gio -> 1.20Gio, -7.08%)
> coq-bedrock2 (3.16Gio -> 3.10Gio, -2.11%)

- bumping `space_overhead` to 200 does result in large memory usage increases for some of the programs. The most memory-hungry program, coq-bedrock2, goes +14% (on 3Gio, that's a 400Mio bump!).

On the other hand, the prediction that runtime would increase a bit with `o=120` and decrease with `o=200` are not verified by the benchmark data.
- with `o=120` (should be slower), the time changes are between -1.64% and +1.45%; no real difference.
- with `o=200` (should be faster), there are a few performance improvements, but very minor (11 benchmarks over 21 do better than -1%, with -3.16% in the best case).

My conclusion from this data is that best-fit with o=120 is better than the current state or o=200, and should be made the default (for workloads similar to those benchmarks, at least). With best-fit and no space_overhead bump, there is no noticeable time increase, and there are noticeable memory-consumption reductions (from -7% to -13%) in several memory-hungry cases (there are a few memory-consumption regressions, by they are fairly small (+3.22% at worst).

My impression is that Coq users are often memory-constrained in their usage of the proof assistant, so that memory-consumption reductions on large proofs could have a positive impact.

**Comment by gasche** [comment] 2019-12-14 15:08
`coq-performance-tests` is an outlier in the benchmark results: it gets slower and uses more memory with either settings. Its runtime is very small (11s), so I'm not sure the +4.5% and +3.2% bumps are significant. Its memory usage is 425Mio with the current settings, 462Mio (+8.6%) with best-fit o=120, and 440Mio (+3.7%) with best-fit o=200.

These results make little sense to me: I don't understand how best-fit could result in higher memory usage, and I don't see how increasing space_overhead could reduce memory consumption (it should be the other way around).

The [benchmark sources](https://github.com/coq-community/coq-performance-tests/blob/master/pattern.v) suggest that it is an extremely specific microbenchmark. It seems reasonable to assume that other Coq programs will not behave in the same way, but this may still interest `best-fit` implementors. I wonder if the problem comes from the use of the `time` tactic, which is heavily used in this benchmark (I wonder how it is implemented).

**Comment by ejgallego** [comment] 2019-12-14 15:38
> My impression is that Coq users are often memory-constrained in their usage of the proof assistant, so that memory-consumption reductions on large proofs could have a positive impact.

As of today I don't think most Coq users are really suffering for memory; those who need it can get 64GiB of RAM pretty easily; this may change in the future tho with more parallel checking.

The dominant issue for users as of today are long checking times.

**Comment by gasche** [comment] 2019-12-14 16:08
Expert users working on very large developments are indeed able to buy more RAM to solve their memory-consumption problems. However, for each of those there are dozens of non-expert users or expert beginners that don't have a very strong machine *yet* and are hitting RAM limitations on their machines.

It would be a difficult choice if you could reliably decrease memory at the cost of of a time regression -- you would need to balance one against the other. But the numbers show that memory decreases (by up to 13%) without notable regressions in time, so it sounds like an easy win to me.

**Comment by JasonGross** [comment] 2019-12-14 16:19
@gasche I can make coq-performance-tests take longer if you'd like, simply by running the tests 6x more?  (Note that we already run each of the tactics 9x.)  It is just checking the performance of `pattern` in the number of binders in the term, which is indeed a microbenchmark.  Do you have the build log available somewhere, to inspect the times of the individual calls?

> As of today I don't think most Coq users are really suffering for memory; those who need it can get 64GiB of RAM pretty easily; this may change in the future tho with more parallel checking.
>
> The dominant issue for users as of today are long checking times.

Indeed, the ordering of concerns for me is build time > .vo size > RAM usage.  I've only ever hit RAM issues under the following conditions:
- A single invocation of coqc wants more than 60 GB of RAM (I think `simpl` is probably the easiest tactic to hit this with, but I've also seen unification eat memory like this)
- Coq's CI OOMs when trying to build fiat-crypto with multiple threads
- bedrock (not bedrock2) has a file which needs ~11GB of RAM, which therefore cannot be built in parallel with many other processes demanding similar amounts of RAM

On the other hand, every single Coq project I've worked on would benefit from being faster.


> coq-unimath (1.13Gio -> 9.81Gio, -13.5%)

Something here is wrong.  Perhaps 9.81 is really 0.981?  Or does the usage really increase 9x?

**Comment by gasche** [comment] 2019-12-14 16:25
I fixed the unimath numbers, thanks. (It was 0.98.)

**Comment by jhjourdan** [comment] 2019-12-15 17:03
> As of today I don't think most Coq users are really suffering for memory; those who need it can get 64GiB of RAM pretty easily; this may change in the future tho with more parallel checking.

I blatantly disagree with this statement. I spent my whole PhD thesis fighting against memory usage problem in Verasco. Sure I may have bought a machine with more RAM, but:
   - it cost money, which not PhD students have in large amount
   - it is not easily available on relatively small laptops
   - a verified software or a verified formal development which would need 64GB of RAM is essentially not distributable to other users, and artifact reviewers would usually not be able to review it.

I am very much willing to trade 15% or more time for 15% of memory!

**Comment by ejgallego** [comment] 2020-09-16 20:12
This can be of help for those willing to play with best-fit
https://blog.janestreet.com/memory-allocator-showdown/

Indeed Coq numbers are better with best fit, but unfortunately the regressions on >= 4.08.0 make them not worth it , will post some data.

**Comment by ejgallego** [comment] 2020-09-21 14:54
See new results in #13040 , it looks like we will make it the default.

**Closed** 2020-11-16 16:52 UTC
Labels: kind: infrastructure, kind: performance
