### ISSUE TITLE
Can't run coqtop shim built with master on Windows

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#16615] opened 2022-10-06 06:31 UTC
`coqtop-prelude` fails, but the executable appears to be OK (last line below).
I can use -coqlib as a workaround, but this should be fixed.

```
$ dune clean

$ make world
dune build  --root . theories_dune ltac2_dune
*** Warning: cannot open ..\..\plugins\.merlin
*** Warning: cannot open ..\plugins\.merlin
touch .dune-stamp
cp -a _build/default/theories_dune theories/dune && chmod +w theories/dune
cp -a _build/default/ltac2_dune user-contrib/Ltac2/dune && chmod +w user-contrib/Ltac2/dune
dune build  coq-core.install coq-stdlib.install coqide-server.install coqide.install coq.install
File "_none_", line 1:
Warning 58 [no-cmx-file]: no cmx file was found in path for module Zarith_version, and its interface was not compiled with -opaque

$ dune exec -- dev/shim/coqtop-prelude

create_process(C:\proj\coq2\_build/default/dev/shim/coqtop-prelude): Exec format error

$ _build/install/default/bin/coqtop.exe -coqlib _build/default
(works)
```

**Comment by ejgallego** [comment] 2022-10-06 06:39
This is the 3rd (at least) time the same bug is submitted. The shim is a bash script so it can't be directly executed by windows.

**Comment by Zimmi48** [comment] 2022-10-06 12:41
Once you have done `dune build dev/shim/coqtop-prelude`, are you sure that you cannot just run `_build/install/default/bin/coqtop.exe` (no `-coqlib` option) or even `dune exec coqtop`? At least on my side (not on Windows, so without the `.exe` ending), it seems to work.

**Comment by ejgallego** [comment] 2022-10-06 12:43
Maybe a shortcut to `bash dev/shim/coqtop-prelude` would be practical.

**Comment by SkySkimmer** [comment] 2022-10-06 12:45
>Once you have done dune build dev/shim/coqtop-prelude, are you sure that you cannot just run _build/install/default/bin/coqtop.exe (no -coqlib option) or even dune exec coqtop? At least on my side (not on Windows, so without the .exe ending), it seems to work.

Did you test from a clean state? dune build stdlib.install populates _build/install with symlinks and they don't get removed when outdated.

**Comment by jfehrle** [comment] 2022-10-06 15:41
> The shim is a bash script so it can't be directly executed by windows.

How about replacing the script with a short OCaml program?  Then it could work identically on Linux and Windows.

> are you sure that you cannot just run `_build/install/default/bin/coqtop.exe` (no `-coqlib` option) or even `dune exec coqtop`? 

```
$ _build/install/default/bin/coqtop.exe
cannot guess a path for Coq libraries; please use -coqlib option or ensure you have installed the package containing Coq's stdlib (coq-stdlib in OPAM) If you intend to use Coq without a standard library, the -boot -noinit options must be used.
$ dune exec coqtop
cannot guess a path for Coq libraries; please use -coqlib option or ensure you have installed the package containing Coq's stdlib (coq-stdlib in OPAM) If you intend to use Coq without a standard library, the -boot -noinit options must be used.
```

> dune build stdlib.install populates _build/install with symlinks and they don't get removed when outdated.

```
$ dune build stdlib.install
Error: Don't know how to build stdlib.install
```

**Comment by ejgallego** [comment] 2022-10-06 15:54
> How about replacing the script with a short OCaml program? Then it could work identically on Linux and Windows.

That's a good idea indeed; we were hoping it would be replace by `dune coq top`, which works pretty well, but we went on a different path.

**Comment by Zimmi48** [comment] 2022-10-06 15:56
It's `dune build coq-stdlib.install`, but this is included in `make world`. So if you do `make world` once, then do not clean, you should have the symlinks I suppose.

**Comment by ejgallego** [comment] 2023-06-30 17:32
Duplicate of #14547

**Closed by ejgallego** 2023-06-30 17:32 UTC
Labels: part: build, kind: bug
