### ISSUE TITLE
Regression in notation printing

### ISSUE THREAD

**Issue by gares** [coq/coq#6777] opened 2018-02-17 09:57 UTC
From mathcomp, `fingroup/quotient.v`:
```
Variables (gT : finGroupType) (Q A : {set gT}).
Notation H := <<A>>.
Check <<A>>.
(*
@generated gT A
     : @set_of (FinGroup.arg_finType (FinGroup.base gT))
         (Phant (Finite.sort (FinGroup.arg_finType (FinGroup.base gT))))
*)
Check H.
(*
@generated gT A
     : @set_of (FinGroup.arg_finType (FinGroup.base gT))
         (Phant (Finite.sort (FinGroup.arg_finType (FinGroup.base gT))))
*)
```
In both cases, the system prints `<<A>>` and not `H`.

I don't know when the regression took place.

**Comment by gares** [comment] 2018-02-17 12:52
I tested current master, but I've no clue when the regression did happen. This specific file has not been touched for years (and the bug is in printing, so the file compiles just fine). I spot it because I'm tracking down a (unrelated) regression in #6700 and I did see the goal looked weird compared to the names given to hyps (`nBH` is not a reasonable name for `B  <|  <<A>>`, so I did look around and saw the broken notation).

I think we should try to minimize and bisect, unless it rings a bell to someone.

**Comment by gares** [comment] 2018-02-17 12:53
What is very odd is that the term `@generated gT A` is very simple.

**Comment by gares** [comment] 2018-02-17 13:24
This may be the commit (I did not try, but the commit message seems clear):

```
commit e4a09fc480f512f54d5e7ba05d7e408dc5817a46
Author: Hugo Herbelin <Hugo.Herbelin@inria.fr>
Date:   Sat Jul 8 17:12:59 2017 +0200

    Selecting which notation to print based on current stack of scope.
    
    See discussion on coq-club starting on 23 August 2016.
    
    An open question: what priority to give to "abbreviations"?
```
@herbelin ?

**Comment by gares** [comment] 2018-02-17 13:26
FTR `Notation H := <<A>>` is an abbreviation and used to have precedence over `<< _ >>`.

**Comment by Zimmi48** [comment] 2018-02-17 14:33
The corresponding PR is https://github.com/coq/coq/pull/873 and you can see over there the recent comments by @JasonGross asking to make this feature optional. I suppose this is the way to go, possibly deactivating this feature by default.

**Comment by JasonGross** [comment] 2018-02-17 16:08
Yes, this is https://github.com/coq/coq/pull/873#issuecomment-351909163 ; abbreviations are considered to have lower precedence than notations since this PR.  Previously, the selected notation was the most recently declared.  My suggestions are
1. Make this feature optional and
2. Allow scopes for abbreviations for the purposes of printing precedence and
3. Fix the algorithmic issue in the notation selection (this one not relevant to this issue)

**Comment by ppedrot** [comment] 2018-02-19 10:50
Rewriting #873 to fix the performance bug would likely require rewriting the algorithm from scratch, so it'd probably better to try to fix this bug and #6416 at once.

**Comment by maximedenes** [comment] 2018-02-23 14:57
@herbelin Do you plan to push a fix to both bugs mentioned by @ppedrot ?

**Comment by herbelin** [comment] 2018-02-23 16:22
@maximedenes: @ppedrot's issues, namely points 2 and 3 (referring to @JasonGross's list) are expected. Point 2 is relatively easy. It just need time to be allocated. Point 3 is probably not difficult, but I did not think at yet. If someone is willing to help, it would be with pleasure. If @ppedrot knows how to fix the efficiency problem, I'd be happy if he can do it.

Regarding point 1 of @JasonGross's list, it would also be easy (restoring the old code). I'm not fully convinced that it is mandatory, so if third voices have something to say about that, that would be good.

So, to strictly answer your question, I have no precise scheduled plans for improving the PR, (especially considering that there are many various important things to do for 8.8), but something has to be done, definitively.

**Comment by maximedenes** [comment] 2018-02-27 13:24
WG discussion: will be fixed by reverting #873

**Comment by herbelin** [comment] 2018-02-27 22:54
@ppedrot: I was unsure whether you were interested in fixing the performance issue. I was not taking part to the WG discussion but I guess I should infer that the answer to my wondering is that you have no time (which I would understand!)?

**Comment by maximedenes** [comment] 2018-02-27 22:56
Sorry I didn't write more because we were discussing at the same time, but we decided to revert for the purpose of the 8.8 release. Once the two issues (performance and priority of aliases) are fixed, we can merge it again in view of 8.9.

**Comment by herbelin** [comment] 2018-02-27 23:09
So maybe can you indeed write more? Were there proposals to do better than #873 or is it the question of performance and priority of aliases which was discussed, in which case, what said the discussion about the idea to simply fix the two issues?

**Comment by maximedenes** [comment] 2018-02-27 23:15
Unfortunately no, it wasn't discussed. We only concluded quickly that we wouldn't have time for 8.8. I think @ppedrot had some ideas about the performance part, though.

**Comment by herbelin** [comment] 2018-02-27 23:32
Ah, I see, so, how to proceed then? (I mean, as far as I'm concerned, I'm not opposed a priori to implement a binding of scopes to abbreviations, and as far as the performance is concerned - which I did not think at all about yet - if @ppedrot has some ideas, that seems to be good.) What I'm wondering is whether the comment [above](https://github.com/coq/coq/issues/6777#issuecomment-366451193) by @JasonGross roughly reflects the general opinion on #873 or if there are other (better?) ideas around?

**Comment by maximedenes** [comment] 2018-02-27 23:41
I personally don't know why abbreviations don't belong to a scope, so I can't make informed comments. I'm not sure it is desirable to have yet another a flag that changes the notation resolution, so if the other problems are resolved, I wonder if we could not just turn on that feature.

**Comment by herbelin** [comment] 2018-03-10 13:37
@maximedenes: No objection if I reopen this by adopting the point of view that the real problem (which is the treatment of abbreviations in #873) is not addressed by #6949. However, with #6952, we have the following:
```coq
Parameter n : nat.
Notation "<< n >>"  := (S n) : nat_scope.
Notation H := <<n>>.
Check <<n>>.
(* H : nat *)
Check H.
(* H : nat *)
```
which seems to be the expected behavior.

**Comment by silene** [comment] 2018-10-23 20:34
This issue is marked as a blocker for 8.9 but there is no assignee, so what is the status?

**Comment by gares** [comment] 2018-10-23 21:46
The issue was closed by a revert of the commit that introduced it.
@herbelin has reopened it since, but I'm afraid he should have opened a new issue, AFAICT.

**Comment by Zimmi48** [comment] 2018-10-24 09:05
Or at the very least not put any milestone on it.

**Comment by herbelin** [comment] 2018-10-24 09:34
>  @herbelin has reopened it since, but I'm afraid he should have opened a new issue, AFAICT.

Yes, that would have been an alternative.

> Or at the very least not put any milestone on it.

+1

**Closed** 2018-12-04 14:43 UTC
