### ISSUE TITLE
Can't install coqide using opam due to problems with gnome-icon-theme

### ISSUE THREAD

**Issue by mvanier** [coq/coq#13229] opened 2020-10-20 21:00 UTC
#### Description of the problem

I'm trying to install coqide using opam on MacOS (something I've done many times successfully in the past).  It is failing because of a dependency on `conf-gnome-icon-theme3`, which is apparently deprecated in favor of `conf-adwaita-icon-theme`, which installs fine.  Here is the error output:
```
[ERROR] The compilation of conf-gnome-icon-theme3 failed at "/Users/mvanier/.opam/opam-init/hooks/sandbox.sh build
        pkg-config --short-errors --print-errors gnome-icon-theme".

#=== ERROR while compiling conf-gnome-icon-theme3.0 ===========================#
# context     2.0.7 | macos/x86_64 | ocaml-base-compiler.4.11.1 | https://opam.ocaml.org#ead61a76
# path        ~/.opam/4.11.1/.opam-switch/build/conf-gnome-icon-theme3.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build pkg-config --short-errors --print-errors gnome-icon-theme
# exit-code   1
# env-file    ~/.opam/log/conf-gnome-icon-theme3-4137-ffb3fd.env
# output-file ~/.opam/log/conf-gnome-icon-theme3-4137-ffb3fd.out
### output ###
# No package 'gnome-icon-theme' found
```

I've installed `gnome-icon-theme` using Homebrew with no issues, but what that does is install adwaita-icon-theme anyway.  Seems like there is a configuration that needs to be updated.

#### Coq Version

8.12

**Comment by mvanier** [comment] 2020-10-20 21:13
Wow, it's weird posting a bug report and then finding a fix within minutes, but that's what happened.  I edited the opam file for coqide.8.12.0 to use "conf-adwaita-icon-theme" instead of "conf-gnome-icon-theme3", deleted the opam cache at ~/.opam/repo/state.cache, and then coqide installed fine.  I'm going to leave this open for now.

**Comment by herbelin** [comment] 2020-10-21 10:42
This seems to be known from @MSoegtropIMC who made a dependency of [coqide](https://opam.ocaml.org/packages/coqide/coqide.8.12.0-1/) 8.12.0-1 on conf-adwaita-icon-theme. Coqide from 8.10 to 8.12.0 (no "-1") depend on conf-gnome-icon-theme3 though.

I'm not so much expert with opam, would it support a disjunctive dependency of the form say `[conf-gnome-icon-theme3|conf-adwaita-icon-theme]`? Or should the dependency in conf-gnome-icon-theme3 be replaced by a dependency in 
conf-adwaita-icon-theme in all existing coqide packages (the deprecation seems from 2016 already)? Or should a "-1" package be submitted for 8.11 (which I guess is the version that you are installing).

@mvanier: could you fill an issue on https://github.com/coq/opam-coq-archive with a link to here?

**Comment by MSoegtropIMC** [comment] 2020-10-21 12:02
This is a transitional issue. The adwaita icon theme opam package is new and the CoqIDE package has not yet been adjusted to it while the hack on MacOS to install the adwaita icon theme in the gnome icon theme package has already been removed. I will do a PR on the CoqIDE package today. The problem is that CoqIDE and the icon theme live in different opam repos and need different PRs and doing this transitionally safe requires a lot of extra PRs and time.

Please note that there is a multi platform script to install Coq via opam which has a local opam patch repo where both patches can be done together. This is the new recommended method to install Coq.

(https://github.com/coq/platform/tree/v8.12)

**Comment by MSoegtropIMC** [comment] 2020-10-22 09:28
I created this opam repo PR to fix this https://github.com/ocaml/opam-repository/pull/17463.

**Comment by mvanier** [comment] 2020-10-22 09:37
@herbelin I opened an issue on https://github.com/coq/opam-coq-archive as you requested.

**Comment by MSoegtropIMC** [comment] 2020-10-22 12:43
This should be fixed for all release packages of CoqIDE with (https://github.com/ocaml/opam-repository/pull/17463) which was just merged. So I will close this PR.

**Closed by MSoegtropIMC** 2020-10-22 12:43 UTC
Labels: needs: merge of dependency, part: IDE, part: installation, platform: macOS
