### ISSUE TITLE
Ltac should parse notations that do not denote a reference as constrs

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10131] opened 2019-05-09 21:07 UTC
#### Description of the problem

```coq
Definition foo1 := (prod Set Set).
Notation foo2 := (prod Set Set).

Ltac bar x := pose x.

Ltac bar0 := bar (prod Set Set). (* success *)
Ltac bar1 := bar foo1. (* success *)
Fail Ltac bar2 := bar foo2. (* Should not need [Fail] *) (* Error: foo2 is bound to a notation that does not denote a reference. *)
Fail Ltac bar2_p := bar (foo2). (* Should not need [Fail] *) (* Error: foo2 is bound to a notation that does not denote a reference. *)
Ltac bar2' := bar (@foo2). (* success *)
Ltac bar2'' := bar ((fun x => x) foo2). (* success *)
```

cc @ppedrot 

#### Coq Version

8.9.0

**Comment by ppedrot** [comment] 2019-05-09 21:09
Duplicate of #2582

**Closed by ppedrot** 2019-05-09 21:09 UTC
Labels: part: ltac
