### ISSUE TITLE
Instructions for 8.14 compilation

### ISSUE THREAD

**Issue by herbelin** [coq/coq#14553] opened 2021-06-24 20:53 UTC
#### Description of the problem

If the intended way to compile Coq is with Dune, shouldn't `Makefile.dune` be now called by default?

It is quite natural to call `make` w/o a `-f Makefile.dune` by default, which asks to call `configure`. Then, a `_build_vo`, and a `bin/coqc`, etc. are created,  and neither `bin/coqc` nor _build/install/default/bin` succeed to find the right library.

So, if I understood the idea correctly, shouldn't the `Please run ./configure first` message when running `make` replaced by something of the form `The recommended way to build Coq is using dune, use "dune build world" to build and "dune build @install" to install. For more targets use "make -f Makefile.build help".`, or whatever is relevant.

In the same vein, shouldn't the paragraph `Build and Installation Procedure` in `INSTALL.md` be more affirmative and ask to use `Dune` exclusively since it is now using `make` which requires special tricks?

#### Coq Version

pre-8.14

**Comment by ppedrot** [comment] 2021-06-24 21:07
See also #14034.

**Comment by Columbus240** [comment] 2021-06-25 06:14
While we're at it, the debugging manual still uses `make byte` and it isn't clear to me from reading the docs, how to "correctly" build coq with debugging-info using dune. I did `./configure; make byte` and got an adequate result, but don't think that this should be the recommended way of doing it.

**Comment by herbelin** [comment] 2021-06-25 07:53
> See also #14034.

Interesting, based on the observation that  `make` does not work anymore the way it was working before, I thought that #14034 was merged and that it was on purpose that `make`-based compilation stopped letting executables in `bin` to correctly find the coq library root.

If the intended situation is that `make` continues to work the way it was working before, something has clearly to be fixed (which maybe is just a trivial fix!).

Cc @coq/build-maintainers, @coq/legacy-build-maintainers, @mattam82, @silene.

**Comment by herbelin** [comment] 2021-06-25 09:16
> While we're at it, the debugging manual still uses `make byte` and it isn't clear to me from reading the docs, how to "correctly" build coq with debugging-info using dune. I did `./configure; make byte` and got an adequate result, but don't think that this should be the recommended way of doing it.

If you're talking about using ocamldebug, it works by default.

Under emacs, there is even a very convenient `coqdev-ocamldebug` command which open a debugger windows and compiles all dependencies for you.

**Comment by ejgallego** [comment] 2021-06-25 11:36
Hi @herbelin, I am not sure I understand the problem you refer, do you refer to compilation by users, or compilation by devs?

If there is a case where coqlib is not found, that is a bug, please submit instructions to reproduce, tho I need to find a minute to finish some pending PRs, in particular #14059

**Comment by herbelin** [comment] 2021-06-25 13:26
@ejgallego:
> If there is a case where coqlib is not found, that is a bug

No bug found, it was apparently only my confusion (and probably a mixed dune/make not clean archive at some time which disturbed me). In particular, both `./configure -profile devel; make -j5; bin/coqtop` and `./configure -prefix /foo; make -j5; make install; /foo/bin/coqtop` find the coq library correctly.

After more carefully reading the paragraph `Build and Installation Procedure` of the `INSTALL.md` file, I conclude that there are actually three build possibilities:
- build driven my `make`, relying under the hood on `dune` for ml dependencies and `make` for v dependencies
  - use `configure` with  either `-profile devel` (local installation) or with specific installation paths
  - `make -j4`
  - either `bin/coqtop` (local installation) or `make install` and call the installed `coqtop`
- build driven my `make` relying under the hood on `dune` for ml and vo dependencies:
  - for developers only, with local installation only?
  - read `dev/doc/build-system.dune.md`; in particular, don't do `configure`, just `make -f Makefile.dune world`
  - run with either `dune exec coqtop` or `_build/install/default/bin/coqtop`
- build fully driven by `dune`:
  - for developers only, with local installation only?
  - `dune build coq-core.install coq-stdlib.install coqide-server.install coqide.install`
  - `dune exec coqtop`

If that is a correct way to look at thing, shouldn't the `Build and Installation Procedure` section of the `INSTALL.md` clarifies the two roles of `make`, as e.g. in:
```
Please see [INSTALL.make.md](dev/doc/INSTALL.make.md) for
build and installation instructions.

Note that under the hood, Coq uses Dune to build all the OCaml 
parts and a makefile-based build system [similar to `coq_makefile`]
for `.vo` files. There is also an alternative experimental
[Dune](https://github.com/ocaml/dune)-based system to build `.vo` 
files. If you wish to use it, see the
[dune guide for developers](dev/doc/build-system.dune.md).
```

**Comment by ejgallego** [comment] 2021-06-25 13:32
Thanks a lot for the detailed write up @herbelin , I'd say that methods 2 and 3 are really the same, we provide the makefile targets for documentation and convenience. Indeed, build methods 2/3 is only recommended for developers because a) it is in general faster and allows sound incremental bisect, caching, etc... b) it doesn't fully cover stuff such as the current coq-native setup, thus not suitable for users yet.

Note that running configure when in 2/3 is optional, but users can run it if they wish, for example to set a prefix or to change the vm / native defaults.

**Comment by herbelin** [comment] 2021-06-25 13:52
I agree that 2/3 are essentially the same under the hood, but it is pretty confusing from a "naive" point of view by what I mean that when you type `make` you naively think that your usage pertains to `make`, not to `dune`. I'm afraid that some users might be confused by that (as I did at some time).

I'm not fully sure that the dune change is fully transparent to users still. For instance, standard settings of `COQLIB` or `COQBIN` may not work the same when compiling plugins. I'm continuing investigating why I stumbled on problems at some times.

**Comment by ejgallego** [comment] 2021-06-25 21:23
> For instance, standard settings of `COQLIB` or `COQBIN` may not work the same when compiling plugins.

They should.

I agree that having both forms of make is a bit confusing, still unsure what the best way to do this is, other than at some point consolidating.

**Comment by Zimmi48** [comment] 2021-06-26 07:24
> I agree that 2/3 are essentially the same under the hood, but it is pretty confusing from a "naive" point of view by what I mean that when you type `make` you naively think that your usage pertains to `make`, not to `dune`. I'm afraid that some users might be confused by that (as I did at some time).

It's still very common for OCaml projects using Dune as a build system to still provide a small `make` wrapper though. Clearly, the particular situation in Coq makes the whole thing more confusing. But this `Makefile.dune` wrapper is very useful (in particular its `world` target is more suited to most use cases than calling `dune build` without arguments---something that we should really fix BTW).

**Comment by Zimmi48** [comment] 2021-07-19 08:56
#14659 includes an update to the message `please run configure first` to also suggest using `Makefile.dune`.

For `INSTALL.md`, I'll propose an update to more specifically encourage the use of Dune for developers.

Is there anything more that needs to be addressed to close this issue?

**Comment by herbelin** [comment] 2021-07-19 10:24
> Is there anything more that needs to be addressed to close this issue?

I feel that the difference between make as a build system and as a capsule to call dune is still not very clear.

**Comment by Zimmi48** [comment] 2021-07-19 11:52
In `INSTALL.md` or elsewhere?

**Comment by herbelin** [comment] 2021-07-19 14:47
I meant in `INSTALL.md`, section `Build and Installation Procedure` (which no PR is addressing yet iiam).

**Comment by Zimmi48** [comment] 2021-07-20 07:04
> I meant in `INSTALL.md`, section `Build and Installation Procedure` (which no PR is addressing yet iiam).

Modifying this section was the main reason why I opened #14677. The only thing in this section I didn't change in this PR is the introduction:

>Coq will build all the OCaml parts using Dune; for `.vo` files, Coq offers the choice of two build systems: an experimental one based on [Dune](https://github.com/ocaml/dune), and a makefile-based one [similar to `coq_makefile`].

Is this what you would like to see adjusted?

**Comment by herbelin** [comment] 2021-07-20 08:06
> Is this what you would like to see adjusted?

Yes, this is where I got confused at some time. What remains non clear in #14677 is that it is not really the choice between two build systems but the choice between two ways to mix `dune` and `make` to build coq. In both cases, `make` is the wrapper. In both cases, `dune` is used under the hood for OCaml files and the like. In both cases, `make` is used for the test-suite (or did it change?). The observable differences seem rather in how configuring is done, and in where vo are stored.

**Comment by Zimmi48** [comment] 2021-07-20 09:23
> In both cases, `make` is used for the test-suite (or did it change?).

It didn't.

The above sentence already says that in all cases Dune is used to build Coq. And it already says that the choice is for building vo files. It just doesn't mention the `make` wrapper (though in the case of Dune you can actually do without if you want) and the test-suite. I don't know how to improve it further without making it overly long and complicated...

**Closed** 2021-07-28 20:07 UTC
Labels: part: installation, priority: high
