### ISSUE TITLE
Can't supply explicit proof term when Unset Silent is used

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#8229] opened 2018-08-09 19:11 UTC
#### Version

Coq 8.8.1

#### Operating system

macOS 10.13.6

#### Description of the problem

Adding `Unset Silent.` between `Lemma` and `Proof <term>` results in an error, but should not:

```
$ coqtop
Welcome to Coq 8.8.1 (July 2018)

Coq < Lemma foo A : A -> A.
1 subgoal

  A : Type
  ============================
  A -> A

foo < Unset Silent.

foo < Proof fun x => x.
Toplevel input, characters 0-17:
> Proof fun x => x.
> ^^^^^^^^^^^^^^^^^
Error: Attempt to save an incomplete proof (in proof foo)
```

For instance, this works as expected:
```
$ coqtop
Welcome to Coq 8.8.1 (July 2018)

Coq < Lemma foo A : A -> A.
1 subgoal

  A : Type
  ============================
  A -> A

foo < Proof fun x => x.
foo is defined
```

It seems that this issue is the cause of [this PG issue #377](https://github.com/ProofGeneral/PG/issues/377).

**Comment by ejgallego** [comment] 2018-08-09 19:26
The `Proof` command is broken, my advice is to avoid it. [I proposed to document this fact in a `KNOWN_ISSUES` file but it was rejected :S ]

**Comment by ejgallego** [comment] 2018-08-09 19:28
On a different note, PG should really stop sending Coq all those `Set Silent.`

**Comment by anton-trunov** [comment] 2018-08-09 19:31
Oh, I see. Thanks!

> On a different note, PG should really stop sending Coq all those Set Silent.

It looks like you already reported it here: https://github.com/ProofGeneral/PG/issues/212

**Comment by Zimmi48** [comment] 2018-08-14 08:19
Should this be a won't fix?

**Comment by erikmd** [comment] 2020-06-03 21:43
Duplicate of #12444

**Closed by erikmd** 2020-06-03 21:43 UTC
Labels: kind: bug, resolved: duplicate(d)
