### ISSUE TITLE
Module Include on a file containing inductive types can break validity of extracted OCaml code

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#11462] opened 2020-01-27 19:30 UTC
#### Description of the problem

```
$ cat VectorDef.v 
```
```coq
Inductive t A : nat -> Type := nil : t A 0 | cons : A -> forall {n}, t A n -> t A (S n).
```
```
$ cat Vector.v
```
```coq
Require Foo.VectorDef.
Include VectorDef.
```
```
$ cat foo.v
```
```coq
Require Import Coq.extraction.Extraction Coq.extraction.ExtrOcamlBasic.
Require Foo.Vector Foo.VectorDef.

Definition id {A n} (x : VectorDef.t A n)
  := match x with
     | @VectorDef.nil _ => @Vector.nil _
     | @VectorDef.cons _ x n x0 => @Vector.cons _ x n x0
     end.
Definition main : unit := tt.
Extraction Language OCaml.
Unset Extraction Optimize.
Extraction "foo.ml" id main.
```
```
$ coqc -v
The Coq Proof Assistant, version 8.10.0 (January 2020)
compiled on Jan 24 2020 13:21:12 with OCaml 4.06.1
```
```
$ for i in VectorDef Vector foo; do coqc -q -Q . Foo $i.v; done
```
```
$ cat foo.ml
```
```ocaml

type nat =
| O
| S of nat

type 'a t =
| Nil
| Cons of 'a * nat * 'a t

type 'a t0 =
| Nil0
| Cons0 of 'a * nat * 'a t0

(** val id : nat -> 'a1 t -> 'a1 t0 **)

let id _ = function
| Nil -> Nil0
| Cons (x0, n, x1) -> Cons0 (x0, n, x1)

(** val main : unit **)

let main =
  ()
```
```
$ ocamlc -v
The OCaml compiler, version 4.06.1
Standard library directory: /home/jgross/.opam/4.06.1+fp/lib/ocaml
$ ocamlc -o foo foo.ml
File "foo.ml", line 18, characters 36-38:
Error: This expression has type 'a t but an expression was expected of type
         'a t0
```

Note that if you put the inductive types in modules, then things work fine, because it seems that extraction only inlines file-modules (and OCaml considers two inductive types defined in different modules but with the same names and constructor names and type signatures to be the same), but does not inline modules defined in files.  Perhaps there should be an option (on by default) for not inlining file modules (except the currently open one)?

Found by @joonwonc in the course of working on Kami / ssith (where some files `Import Vectors.VectorDef.VectorNotations` rather than `Import Vectors.Vector.VectorNotations`)

#### Coq Version

8.10.0

**Comment by ppedrot** [comment] 2020-01-28 10:07
Nice one!

**Comment by ppedrot** [comment] 2020-02-09 15:56
Duplicate of #9011

**Closed by ppedrot** 2020-02-09 15:56 UTC
Labels: part: extraction
