### ISSUE TITLE
Problem with VST and universes:

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6913] opened 2018-03-04 21:40 UTC
So as we have noted in the CI infrastructure, VST is faling to compile on `master`, however it works fine in 8.7.2. Problem in `master`:

```
File "./floyd/library.v", line 78, characters 3-472:
Error:
The term "(compspecs * type)%type" has type
 "Type@{max(Set,compcert.lib.Maps.71,compcert.cfrontend.Ctypes.24)}"
while it is expected to have type "Type@{VST.veric.SeparationLogic.231}"
(universe inconsistency).
```

Hard to say what's the significance of this bug, a bisect should be attempted.

**Comment by ejgallego** [comment] 2018-03-04 21:53
It happened quite recently so any of the merges in the last 10 days would be a good candidate.

**Comment by ejgallego** [comment] 2018-03-05 05:46
And the Oscar goes to:
```
commit d9530632321c0b470ece6337cda2cf54d02d61eb
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Mon Jul 17 12:57:43 2017 +0200

    Removing template polymorphism for definitions.
    
    The use of template polymorphism in constants was quite limited, as it
    only applied to definitions that were exactly inductive types without any
    parameter whatsoever. Furthermore, it seems that following the introduction
    of polymorphic definitions, the code path enforced regular polymorphism as
    soon as the type of a definition was given, which was in practice almost
    always.
    
    Removing this feature had no observable effect neither on the test-suite,
    nor on any development that we monitor on Travis. I believe it is safe to
    assume it was nowadays useless.
```

**Comment by SkySkimmer** [comment] 2018-03-05 08:54
I would call this WONTFIX.

**Comment by mattam82** [comment] 2018-03-05 09:22
Can the dev be fixed or is it a regression ?
Le lun. 5 mars 2018 à 09:54, Gaëtan Gilbert <notifications@github.com> a
écrit :

**Comment by maximedenes** [comment] 2018-03-05 09:24
Probably both.

**Comment by SkySkimmer** [comment] 2018-03-05 09:24
I don't understand what you mean.
See VST side issue is https://github.com/PrincetonUniversity/VST/issues/153#issuecomment-370278778 btw.
```
Instead of putting it in a code block, I have done this:

    In the latest commit (115e814), floyd/library.v uses a simpler parameterization that probably does not trigger the universe bug in the Coq 8.8 master branch (can you confirm this?).
    In that commit, there's a new file, floyd/bug_coq88dev.v, that demonstrates the bug (since it's derived directly from the old floyd/library.v). I suggest that the Coq team ensures that their travis-ci makefile builds this file ("make" might do it), so you can use this as a regression test.

This simpler parameterization (not triggering the bug) is what we want anyway in VST,
so this Coq bug is not high priority for us.
```

**Comment by ejgallego** [comment] 2018-03-05 09:42
Umm, I started the bisect around the time of Andrew's commit, let me check if the bug is still there.

**Comment by ejgallego** [comment] 2018-03-05 10:41
The build failure is still there even after @andrew-appel 's latest commit.

**Comment by SkySkimmer** [comment] 2018-03-05 10:43
>The build failure is still there even after @andrew-appel 's latest commit.

Probably you checked but just in case you didn't: is the failure just their new reproduction file bug_coq88dev.v ? Since that's expected to fail.

**Comment by ejgallego** [comment] 2018-03-05 10:48
Indeed it fails in `bug_coq88dev.v`, sorry my mistake. I don't understand why this file is build by default.

**Comment by ejgallego** [comment] 2018-03-05 10:48
See my comment in the VST issue:
```

**Comment by andrew-appel** [comment] 2018-03-05 13:01
If this is deprecated -- if it is "official" that bug_coq88dev.v is not expected to build in future versions of Coq -- then I will remove that file from VST.  Please let me know.

**Comment by maximedenes** [comment] 2018-03-05 13:03
The problem is that "constant template polymorphism" didn't go through a deprecation phase AFAIK, it was directly removed. Was there a story for compatibility that failed on this particular example? @ppedrot ?

**Comment by SkySkimmer** [comment] 2018-03-05 13:07
How would we deprecate it, given that template polymorphism happens automatically even when it's not useful?

**Comment by mattam82** [comment] 2018-03-05 13:08
A priori - I did not check, but I think - template polymorphic constants
did not go through module interfaces so replacing such constants by
abbreviation notations could provide a compatibility solution, maybe.

**Comment by maximedenes** [comment] 2018-03-05 13:09
> How would we deprecate it, given that template polymorphism happens automatically even when it's not useful?

Indeed, not easy. I imagine that you could detect when it is actually relied on and emit a warning, but that's going to be costly.

So maybe just make sure we mention it clearly as an incompatible change, both in `CHANGES` and in the release material.

**Comment by ejgallego** [comment] 2018-03-05 13:52
Yeah the funny part here is that VST passed the CI test at the PR merging time, but then got incompatible later.

With the hopefully upcoming AWS on-demand CI infrastructure we could provide way more comprehensive and automatic CI to projects desiring it, that would help avoid this problem as such CI would indeed test `master` too.

**Comment by Zimmi48** [comment] 2018-03-05 14:09
Hum, VST wouldn't have needed any additional infrastructure to test Coq master and really all the projects that we include in our CI should do that.

**Comment by ejgallego** [comment] 2018-03-05 14:18
> Hum, VST wouldn't have needed any additional infrastructure to test Coq master and really all the projects that we include in our CI should do that.

Yes they should but we are not there yet on terms of stability I feel.

**Comment by andrew-appel** [comment] 2018-03-05 14:27
I don't think it's necessary to put a coq-master test into the VST travis-ci script.  In this case the system worked:  I committed to the VST master branch a build that succeeds in Coq 8.7, and the Coq travis-ci system detected that it fails in Coq 8.8; and it was quick and easy to understand what the problem was.  If this kind of thing happened every week, then you might want to make some infrastructure to detect it quicker, but actually it has been quite rare.

**Comment by maximedenes** [comment] 2018-03-07 08:44
> If this is deprecated -- if it is "official" that bug_coq88dev.v is not expected to build in future versions of Coq -- then I will remove that file from VST. Please let me know.

@andrew-appel Yes, it is official (we were aware of the incompatibility in some cases, when removing "template universe polymorphism for constants"). We are going to think about how to communicate clearly about this incompatibility, but I think the right step for VST is to remove the `bug_coq88dev.v` file.

**Comment by SkySkimmer** [comment] 2018-03-07 13:12
See PrincetonUniversity/VST@fcda4ec6e6ec52a10ac85dbaabdcbd68c91a8fb6.

**Closed by SkySkimmer** 2018-03-07 13:12 UTC
Labels: kind: regression
