### ISSUE TITLE
Line numbers in 'Error' tab in coqide wrong after upgrade

### ISSUE THREAD

**Issue by chrisd1977** [coq/coq#15531] opened 2022-01-24 05:40 UTC
After upgrading from coq 8.14.1 to 8.15 using the package manager of
my linux distribution (pacman and archlinux) the line numbers in the
'Error' tab are wrong. An example file is here: http://chrisdams.nl/euclid.v
Opening this in coqide and going to the end of the file by pressing the
down button 'Run to end' yields an error. The 'Errors' tab contains the line
number 533 and the error message 'Tactic failure: tauto failed.'. However,
the line number 533 is wrong. The actual error occurs on line 303. Also,
double clicking on the error in the 'Errors' tab brings us to line 533 which
is not where the error is.

cc: @jfehrle

**Comment by jfehrle** [comment] 2022-01-24 07:26
OK, I can reproduce this, thanks.

Oddly, FWIW, when I run your script using 8.13 there are no errors at all.

**Comment by Alizter** [comment] 2022-01-24 07:32
Also broken in 8.16.

**Comment by jfehrle** [comment] 2022-01-24 08:03
I wouldn't refer to 8.16 until that tag is set.  I'd just say "on master".

**Comment by jfehrle** [comment] 2022-01-24 08:04
Fixed by #15532.

**Comment by Zimmi48** [comment] 2022-01-24 08:40
> I wouldn't refer to 8.16 until that tag is set. I'd just say "on master".

FWIW, 8.16+alpha is the version that `coqtop` / `CoqIDE` report on `master`.

**Comment by Alizter** [comment] 2022-01-24 08:48
Also mentioning `master` has a tendency of aging poorly. In the future, one might look back upon `master` and have to corss-reference the date with the version. Mentioning 8.16, even though it hasn't been released yet, gives future readers a clearer idea of what we are on about.

**Closed** 2022-01-25 07:17 UTC
Labels: kind: user messages, part: IDE, kind: bug

**Comment by jfehrle** [comment] 2022-02-07 04:02
"8.16" is not good terminology because there will eventually be an 8.16 version that means a precise commit.  This could be particularly confusing around the time when the 8.16 release is being prepared.  "post-8.15" would capture your idea while avoiding such confusion.

**Comment by jfehrle** [comment] 2022-02-07 04:14
A partial workaround: clicking on the red bits of the ribbon at the bottom will take you to the correct error locations.

![image](https://user-images.githubusercontent.com/1253341/152723443-5e2d31cd-b8ea-4dbe-aeb5-22dd41456e7e.png)

**Comment by Zimmi48** [comment] 2022-02-07 10:01
> "8.16" is not good terminology because there will eventually be an 8.16 version that means a precise commit. This could be particularly confusing around the time when the 8.16 release is being prepared. "post-8.15" would capture your idea while avoiding such confusion.
>
>"8.16+alpha" is not so great, either, because it represents something that's not based on the future 8.16 version. "Post-8.15" or "8.15+alpha" (since it's based on 8.15) would make a lot more sense.

If you want to be specific, you should use `git describe`. This is the conclusion of a discussion that the Coq developers had a long time ago already, and this is why we put the `+alpha` tags.

For instance, if I run `git describe` on the tip of `master` today, it means: `V8.16+alpha-752-g7c608fe3e9`.

**Comment by SkySkimmer** [comment] 2022-02-07 10:31
You can also say master (current hash), anyone who wants to know more can use git describe or lookup the commit on github.

**Comment by Alizter** [comment] 2022-02-07 13:14
@Zimmi48 I've submitted a patch that displays SHA1: https://github.com/coq/coq/pull/15639
