### ISSUE TITLE
Fails to typecheck with notations, but succeeds with inlined terms.

### ISSUE THREAD

**Issue by joonwonc** [coq/coq#7512] opened 2018-05-14 17:14 UTC
#### Version

8.8.0

#### Operating system

macOS 10.13.4

#### Description of the problem

Hi, when I try to define a domain-specific language in Coq and to use some notations for it. I just found a bug where Coq fails to typecheck with notations, but succeeds with inlined terms. It looks like a bug, since Coq's notation mechanism is supposed not to provide any further information or restrictions.

I minimized the code which still has the bug; I would appreciate if someone take a look at it!
- https://gist.github.com/joonwonc/c2d9f7807df5415b27e745be43d255fa

Thanks!

**Comment by JasonGross** [comment] 2018-05-15 05:59
This is a duplicate of https://github.com/coq/coq/issues/4728 ; `Notation`s with tactics in terms parse their arguments as `constr`s.

Here is a smaller example:
```coq
Notation foo x := (ltac:(let y := open_constr:(x) in exact y)).
Goal True.
  let e := open_constr:(foo _) in
  pose e. (* Error: Cannot infer an internal placeholder of type "Type". *)
```

**Comment by JasonGross** [comment] 2018-05-15 06:00
Duplicate of #4728

**Closed by JasonGross** 2018-05-15 05:59 UTC
