### ISSUE TITLE
Limitation of the guard condition

### ISSUE THREAD

**Issue by silene** [coq/coq#18963] opened 2024-04-22 11:45 UTC
### Description of the problem

While it is well-known that the guard condition has several limitations, I was a bit surprised by the following one, since `x'` is an obvious subterm of `x`. At the very least, the error message should be improved to point to the real issue.

### Small Coq file to reproduce the bug

```coq
Inductive foo := Foo : option foo -> foo.

Fixpoint f (x : option foo) :=
  match x with
  | Some (Foo x') => f x'
  | None => false
  end.

(*
Recursive definition of f is ill-formed.
In environment
f : option foo -> bool
x : option foo
f0 : foo
x' : option foo
Recursive call to f has principal argument equal to "x'" instead of
a subterm of "x".
Recursive definition is:
"fun x : option foo => match x with
                       | Some (Foo x') => f x'
                       | None => false
                       end".
*)
```

### Version of Coq where this bug occurs

8.19.1

**Comment by SkySkimmer** [comment] 2024-04-22 12:01
Duplicate of https://github.com/coq/coq/issues/12781 (and others linked in https://github.com/coq/coq/pull/17950)

**Closed by SkySkimmer** 2024-04-22 12:01 UTC
Labels: kind: bug, needs: triage

**Comment by DmxLarchey** [comment] 2024-07-01 09:16
This one works:

```coq
Inductive foo := Foo : option foo -> foo.

Fixpoint f (x : foo) :=
  match x with
  | Foo (Some x') => f x'
  | Foo None => false
  end.
```
