### ISSUE TITLE
-noinit anomaly in Definition := Eval cbv in.

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#8240] opened 2018-08-12 15:12 UTC
~~~~~
The Coq Proof Assistant, version 8.8.1 (July 2018)
compiled on Jul 5 2018 7:25:50 with OCaml 4.06.0
~~~~~

~~~~~
(* -noinit *)
Example simple_cbn := Eval cbn in (fun x:Set => x).
(* Error:
Anomaly "Uncaught exception Invalid_argument("Lexer: location function")."
Please report at http://coq.inria.fr/bugs/. *)
Example simple_cbv := Eval cbv in (fun x:Set => x).
Example simple_vm_compute := Eval vm_compute in (fun x:Set => x).
~~~~~

Works fine without `-noinit`. I am looking for a way to create big terms without loading the prelude to make less flaky memory usage benchmarks.

**Comment by herbelin** [comment] 2018-08-21 12:17
There should be a error `"entry [Tactic.red_expr] is empty"` and this is because `cbn`, `cbv`, `vm_compute` and cie are defined only in the ltac plugin which is not loaded with `-noinit`.

I don't understand why the above error (generated by camlp5) does not display as another parsing error would display (presumably, camlp5 is calling the `tok_fun` method on a wrong argument at some time?).

What to do about the report is unclear. I guess that one question is also whether the reduction functions are considered part of the ltac plugin or part of the core of Coq (since after all, there are part of the syntax of `Definition`).

**Comment by herbelin** [comment] 2018-08-21 13:41
> They should probably part of the core syntax. 

OK. Then, how to organize? Do you have time to do it, or do you prefer I do it?

**Comment by herbelin** [comment] 2020-02-24 14:15
I'm looking at how to fix this, but the duplication between the vernac syntax `Eval red_expr in lconstr` and the tactic syntax `red_expr clause_dft_concl` is painful. There are many auxiliary subgrammars such as `occs`, `nums_occs`, etc. which are not really worth to be exported and which would have to be exported.

Somehow, the problem is a parsing problem. One should be able to write a `red_expr clause_dft_concl` clause in tactics w/o having to expand/inline the whole of the grammar of `red_expr`.

My proposal would be to duplicate all auxiliary subgrammar, until gramlib is able to accept that we write `red_expr clause_dft_concl` w/o inlining. Then, at this time, we will remove the duplication. Any objection to this strategy?

**Comment by herbelin** [comment] 2020-02-24 14:56
@ppedrot:

> They should probably part of the core syntax. 

Is it correct to assume that you have no time to do it and that you are ok that I work on it, and that e.g. I move `interp_redexpr` to a file `vernac/redinterp.ml`, parameterized by a record of interpretation functions to be instantiated differently in `vernacentries.ml` and in `tacinterp.ml`?

**Comment by herbelin** [comment] 2020-02-24 15:31
@ppedrot: and is it ok if I also move the interpretation functions for `constr` and `pattern` in a new file `vernac/constrinterp.ml` even though these functions have the trace in their code of the dynamic typing overloading `[x]` as either a singleton list or a binding of `x` to a list?

**Comment by herbelin** [comment] 2020-02-24 15:34
Or maybe directly in `constrintern.ml`?

**Comment by Zimmi48** [comment] 2020-02-24 15:54
@herbelin Do you mind explaining where you put the limit between the `red_expr` which should be part of the core language and the ones which shouldn't?

**Comment by herbelin** [comment] 2020-02-24 15:56
> Do you mind explaining where you put the limit between the red_expr which should be part of the core language and the ones which shouldn't?

I don't know if `Eval` has to be part of the core language. I see it more as a convenience than as a "logical" thing.

**Comment by herbelin** [comment] 2020-02-24 16:05
Already explaining the semantics of `cbn`, `cbv`, `lazy`, `simpl`, etc. would be difficult (even more than they could be explained better, e.g. by reducing fixpoints differently, by having `cbn` and `cbv` be canonically associated to the positive vs negative encoding of lambda-calculus, ...).

Maybe `compute` is the simplest to explain (up to fix body expansion): it produces normal forms.

**Comment by SkySkimmer** [comment] 2020-02-24 16:06
>Maybe compute is the simplest to explain (up to fix body expansion): it produces normal forms up to blocking some constants.

Also true of cbv and lazy no?

**Comment by herbelin** [comment] 2020-02-24 16:23
> Also true of cbv and lazy no?

Without flags yes. But with a selection of flags, it is probably hard to give a clear semantics.

**Comment by Zimmi48** [comment] 2020-02-24 16:30
Which reduction machines are in the kernel? It seems to me that the `Eval ... in ...` command should be part of the core language for those.

**Comment by herbelin** [comment] 2020-02-24 16:42
If you consider the CIC, it only needs a function to put in weak-head normal form. This function is `CClosure.whd_stack`.

Additionally, the lazy machine in the kernel is customizable so that it implements all variants of the `lazy` reduction machine (this is function `CClosure.clos_norm_flags`), even though these variants are not needed to define the CIC.

Maybe could you ask @mattam82 and the Nantes people who are working on a verified kernel how they define the kernel.

On the other side, as part of the pedagogy is concerned, it is probably enough to explain the things in a way which is easy to explain.

PS: note that, in theory, the reduction functions are user-extensible. Thus, `Eval red in` works in theory for any reduction function provided by a third-party.

**Comment by JasonGross** [comment] 2020-02-24 17:10
> PS: note that, in theory, the reduction functions are user-extensible. Thus, Eval red in works in theory for any reduction function provided by a third-party.

In practice too.  I've used [`Declare Reduction`](https://coq.inria.fr/refman/proof-engine/vernacular-commands.html#coq:cmd.declare-reduction) in fiat-crypto

**Comment by JasonGross** [comment] 2020-02-24 17:24
> I don't know if Eval has to be part of the core language. I see it more as a convenience than as a "logical" thing.

I think Eval (and all of the reduction expressions for it) should be as much a part of the core language as notations and simpl modifiers.

**Comment by Zimmi48** [comment] 2020-02-24 17:56
@JasonGross Right. Although in this case, I was asking about the kernel language.

**Comment by ppedrot** [comment] 2020-08-25 14:23
FTR, the anomaly has disappeared as of master (af5e7d44a2a685fe72a65df3daae577938eaa989) and has been replaced by the proper syntax error. I think we should close this bug and reopen one for the feature of being able to call Eval without the Ltac hook.

**Comment by ppedrot** [comment] 2020-08-30 11:42
Bug transferred to #12948.

**Closed by ppedrot** 2020-08-30 11:42 UTC
