### ISSUE TITLE
PR #6844 adds code that depends on "Unsafe" features without providing an alternative roadmap.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7145] opened 2018-04-01 15:30 UTC
PR #6844 was merged adding some likely useful tactics. However, these tactics are implemented using a so-tagged `Unsafe` API of the proof engine, and no hint is in place as to how the situation should be resolved.

IMO we can't allow code like this to creep in the codebase as it is creating non-trivial technical debt, for example, such code may make hard or impossible to provide a better API for `engine` in the future, due to the assumptions the code does on the low-level details of the implementation.

It is not clear the code as is would be compatible with some of the alternatives discussed in coq/ceps#33 including the recent LICS paper about proof refinement.

So IMHO a plan should be provided as how to "promote" the "`Unsafe`" API towards a more principled status, or the PR should be reverted. Or well, we could keep the PR in place as it is not a big deal really [and the feature is of course OK], but we should raise the awareness about the use of "Unsafe" by an order of magnitude.

Think you are a plugin writer meaning to implement this feature, what would you think when you have to `open Unsafe`

**Comment by ejgallego** [comment] 2018-04-01 15:35
By the way don't interpret this issue in an "alarming" or "complaining" way that's not my intention, quite the contrary; however I do believe we have a bit of problem with the way the API is organized and we have to pay utmost attention to it.

**Comment by ppedrot** [comment] 2018-04-01 15:38
My take on that is that *unsafe* is a bit of an overstatement. Such primitives are also exported on Ltac2 side for instance, because you need them to be semantically complete w.r.t. the engine. I think a trivial solution would be to move them to another module called `LowLevel` or something, that is here for completeness but that are not expected to be used by end-users except if they want to reimplement some intricate tactic.

**Comment by ejgallego** [comment] 2018-04-01 15:49
> My take on that is that unsafe is a bit of an overstatement.

Well, they are certainly unsafe in the sense that once you get down there, you are walking on a very thin line wrt the `evar_map`.

Also, they assume that goals are list however it seems to me that usually they tend to look more like a tree. So I dunno, maybe we would put a bit fat warning in the code. Recall that the way plugin writers work is cut&paste from the Coq codebase, so we ought to be careful.

**Comment by gares** [comment] 2018-04-01 16:03
I think that `Unsafe` was badly chosen, and this naming issue should be fixed once and for all.

The proper name for most of these API is `Internal` and at some point in the stack of ML modules there should be no more need to use these API (i.e. become really internal). If the system was a single file, they should not be in the corresponding mli. Since the software is made of many files, I think `Internal` is reasonable. We should probably ensure that the "range" of `Internal` APIs is inside a single component.

Plugins writes must not need to use these APIs (in principle at least).

`Unsafe` is *standard* OCaml slang for "things that break the language safety", i.e. `SIGSEGV`.

**Comment by maximedenes** [comment] 2018-04-01 16:10
I think the issue is a bit more serious than one wrong name chosen. It is rather that *the same* name was chosen to indicate a potential safety breakage (but users were still provided no other way), but also to denote things that were not to be used (like `unsafe_type_of`, and possibly `EConstr.Unsafe.to_constr`).

It is high priority to identify which is which IMHO.

**Comment by maximedenes** [comment] 2018-04-01 16:11
> Plugins writers must not need to use these APIs (in principle at least).

Why wouldn't a plugin writers be expected to write the tactics in #6844 ?

**Comment by ejgallego** [comment] 2018-04-01 16:20
> Why wouldn't a plugin writer be expected to write the tactics in #6844 ?

Because we couldn't provide a decent API to do so (yet).

**Comment by SkySkimmer** [comment] 2018-04-01 16:28
Did #6844 really have to use Unsafe? See https://github.com/coq/coq/pull/6844/files#r178462770

**Comment by SkySkimmer** [comment] 2021-10-04 20:17
Unsafe is not deprecated, there is nothing wrong with using it.

**Closed by SkySkimmer** 2021-10-04 20:17 UTC
Labels: priority: nice to have

**Comment by ejgallego** [comment] 2021-10-05 14:32
IMO the bug still stands, but indeed we can close it as "the proof engine needs rewriting". As showcased by the code of refine, in my opinion the API is not usable.
