### ISSUE TITLE
Anomaly in `specialize H with bindings_list` when the type contains let binders followed by foralls

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#11253] opened 2019-12-07 03:50 UTC
I'm a big fan of the `with bindings_list` variant of the `specialize` tactic.
I use it a lot in the code I commit, but even more in the code I don't commit, for debugging why my `eapply P` doesn't work (then I specialize `P` until I see why it doesn't match).
This feature increases my productivity quite a bit :smiley: 

Today however, I encountered an anomaly with it, which occurs in [all Coq versions we test](https://github.com/mit-plv/bedrock2/runs/337729772), that is, [in Coq 8.9](https://travis-ci.com/mit-plv/bedrock2/jobs/264277675#L2195), [in Coq 8.10](https://travis-ci.com/mit-plv/bedrock2/jobs/264277674#L2195), as well as [in Coq master](https://travis-ci.com/mit-plv/bedrock2/jobs/264277673#L2150).

A very quick attempt at minimizing it didn't succeed, but maybe @Matafou, who seems to be the author of this feature and the [assertion which failed](https://github.com/coq/coq/commit/d767261f0057d8e846bab65a882254d8e4f4c283#diff-b9438b9295c1e6e7d6860d5e55350125R3017) has some hint on what the problem could be and how to mimize it?

**Comment by JasonGross** [comment] 2019-12-07 04:00
Note that my bug minimizer can minimize anomalies.

But here is a small example, which I made by looking at the name of the function you point at and guessing:
```coq
Goal forall (P : let x := 1 in forall n : x = x, n = n), True.
  intro P.
  specialize P with (n := eq_refl).
  (* Error:
Anomaly
"File "tactics/tactics.ml", line 3009, characters 18-24: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
*)
```
This one is 8.10.0, https://github.com/coq/coq/blob/V8.10.0/tactics/tactics.ml#L3009

**Comment by JasonGross** [comment] 2019-12-07 04:02
Therefore, the appropriate workaround is to run `cbv zeta in H` before you run `specialize H with bindings_list`

**Comment by ppedrot** [comment] 2019-12-07 10:23
It looks very simple to fix, I'll come up with a patch quickly.

**Comment by ppedrot** [comment] 2019-12-07 10:54
The code is more horrible than I thought, it may be more efficient to rewrite it properly than fix it locally.

**Comment by Matafou** [comment] 2019-12-07 13:34
I will have a look. Thanks for reporting (and for minimizing!).
Part of the « horrible » thing is because one wants to re-quantify things that were not solved by unification.

**Comment by ppedrot** [comment] 2019-12-07 14:03
Indeed, it resembles the pattern feature from ssreflect, and the code there is also fairly contrived. Maybe we should try to make it simpler and unique...

**Comment by samuelgruetter** [comment] 2019-12-08 01:20
Oh my memory is so bad :see_no_evil: I already reported this a few months ago: https://github.com/coq/coq/issues/9893

**Comment by ppedrot** [comment] 2019-12-08 09:17
Let's close then.

Duplicate of #9893

**Closed by ppedrot** 2019-12-08 09:17 UTC
Labels: kind: anomaly, part: tactics
