### ISSUE TITLE
build:quick doesn't build .vos

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#11195] opened 2019-11-27 10:29 UTC
ie `coqc -quick foo.v` then `coqc -schedule-vio2vo foo.vio` produces foo.vo and no foo.vos.
You can see this by looking at the log from any `build:quick` job in CI, eg https://gitlab.com/coq/coq/-/jobs/362460292#L2828
cc @charguer

**Comment by charguer** [comment] 2019-11-27 13:01
Good point.

The original intention was to not pay attention to `.vio` because eventually they would be deprecated, and that in the meantime people would not use `.vio` in conjunction with `.vos` files. But I agree with you that this assumption has not been written down.

It could easily be fixed that the production of a `.vo` via ` -schedule-vio2vo` would touch the `.vos`.
It is not clear what `-quick` should do, because `.vos` and `.vio` are not meant to coexist well; the most conservative thing would be to touch the `.vos` as well, I suppose.

Also, I realize that there is an issue, because the current policy makes it impossible from CoqIDE to load a `.vio` on a `Require Import`, unlike previously. (`loadpath.ml`, function `select_vo_file`). 

A backward-compatible policy would be: if `!Flags.load_vos_libraries` is true, then attempt loading `.vos`, if not found attempt to load most recent between `.vo` and `.vio`.

On the one hand, if the user does not create any `vio`, she would get the expected behavior w.r.t. `vos`. On the other hand, if the user uses only `vio`, the past behaviors would presumably still be working.

Let's discuss at the Coq meeting today what is the best fix. One question in particular is whether the `.vio` stuff should simply be marked as deprecated.

**Comment by Zimmi48** [comment] 2019-11-27 13:40
Is there actually a call today? It hasn't been announced by @mattam82 and it turns out there is an event at the same time in our lab.

**Comment by gares** [comment] 2019-11-27 17:17
My impression is that .vio and .vos could share the same extension. After all they are the same thing and their compilation is, IIRC, the same in terms of dependencies and a .vos is a .vio where the tasks were pruned.

This would impose to be uniform in the behavior of CoqIDE & co, that is probably a plus.

Then `make vio2vo` and `make vok` could again be the same, they are both fully parallel (the former has a scheduler written in ML, but this seems to be a detail to me). If the tasks are empty, you restart from the .v file, as vok do, while if the tasks are there you complete them as we do in vio2vo.

This would not be a 5 minutes fix, but it may be worth thinking about it, since it simplifies the story for our users quite a bit.

**Comment by charguer** [comment] 2019-11-27 19:52
> Then `make vio2vo` and `make vok` could again be the same.

There is a little catch though: with `make vio2vo` you need `foo.vio/vos` to build `foo.vok/vo`, whereas with `make vok` you produce `foo.vok` without needing `foo.vos`.

I don't think it would be such a good idea to have a same extension for files with possibly different contents (suspended proofs vs none), it seems to just makes much life harder for build systems. 

If the goal is to preserve the `vio` stuff (i.e. not deprecate the feature) and make it more uniform with the `vos` mechanism, here would be my suggestion:
- `coqc -vio foo.v` would process the definitions and produce dump both `foo.vos` (compiled statement only, lightweight file, efficient for loading) and `foo.vio` (suspended proofs, to save some time for later producing `foo.vo`, with the potential caveat of having huge files).
- `coqc -vok foo.vio` would check the suspended proofs from `foo.vio` and touch an empty `foo.vok` in case of success. It does not produce a `.vo` file, because this extension should be reserved for proofs with verified universes.

I suspect these changes would be very straightforward to implement, if we wish to make these changes. 

Now, coming back to the original point of whether storing suspended proofs is worth the effort: the gain in compilation time of storing suspended proofs as opposed to reprocessing the entire file is in most case not very significant. The relative time difference would be signifiant only for files with many definitions and very few opaque proofs, yet those files tend to have a relatively small compilation time in absolute terms.

**Closed** 2020-01-13 13:02 UTC

**Comment by palmskog** [comment] 2020-01-15 14:55
@charguer:

> Now, coming back to the original point of whether storing suspended proofs is worth the effort: the gain in compilation time of storing suspended proofs as opposed to reprocessing the entire file is in most case not very significant. 

Do you have some new data on this? Recall that our [empirical study](http://users.ece.utexas.edu/~gligoric/papers/PalmskogETAL18piCoq.pdf) on several large project revision histories suggests that, in the sequential case, reproving suspended proofs is usually twice as a fast as reprocessing entire files (table on p. 9,  `p·icoq-LO` mode vs. `f·file-LO` mode for jobs=1).

**Comment by charguer** [comment] 2020-01-17 10:40
Let me make my claim more precise. The relevant comparison is between:

- (1) `time coqc -vos foo.v` (skip proofs), plus (2) `time coqc foo.v` (check proofs, possibly using `-vok` for the later to save the need to dump the proofs)
- vs (3) `time coqc -vio foo.v` (alias `-quick` generate a big vio file), plus (4) `time coqc -vio2vo foo.vio` (load big vio file and play suspended proofs).

In the very worst case of a file containing only definitions, and ignoring the cost of writing to disk, we have `(2) = (1) = (3)` and `(4) = 0`. Then, the vio approach is twice faster. But the vast majority of useful libraries do contain a fair amount of proofs.

Instead, consider the typical case where proofs account for at least half of the compilation time. Now, here is my analysis.

- To fix things, consider a file that takes 1 second to compile in the standard way, i.e. (2) is 1 second.
- Observe that going through `vio` cannot beat a direct proof, thus `(3) + (4) >= (2)`.
- In fact, a file that takes 1-second to compile typically generates a 50Mb `vio` file.
- Take into account that a typical SSD drive writes 500Mb per second, this means that `(3) + (4) >= 1.1`.
- What (1) does with `-vos` is like what (3) does with `-vio`, except that is saves the time to dump. Thus `(1) <= (3)`, but let's ignore the difference and say `(1) = (3)`.
- We assume that skipping proofs like in (1) and (3) speeds up compilation by at least 2x compared with full compilation (2), though often it does so by a factor 10x, or more. Thus, we have `(1) = (3) <= 0.5`. 

Let's do the maths.
- `((3) + (4)) / ((1) + (2)) >= `1.1 / (0.5 + 1)` = 0.73.

This shows that, even for a file whose proofs account for only half of the compilation time, the gain of using the `vio` route is never more than 27%. The gain decreases when the ratio of proof increases. Eventually, when statements become complex enough, `vio` files can become big enough that the `vio` route becomes less interesting than recompilation from scratch using the `vos` route.

I speculate that, on a single-file compilation, you never measure then SSD cost due to the disk cache, however, in the case of a parallel build with 8 cores, reading and writing dozens of `vio` files at the same time can put a lot of pressure on the disk.

**Comment by palmskog** [comment] 2020-01-17 15:02
@charguer thanks for detailed breakdown (and performance model). Unless I am mistaken though, I think our perspectives differ here since the problem my collaborators and I consider is how to best find failing proofs in CI when Coq project developers make a small edit to an existing file, which may result in only needing to reprove 3 proofs out of say 150 in the file, and thus never calling `vio2vo`.

If detailed historical proof checking time data is available per file and per proof, it seems to me one could find a nice tradeoff when using `coqc -vos foo.v && coqc -vok foo.v` is preferable vs. `coqc -vio foo.v && coq -schedule-vio-tasks [task list] foo.vio`

cc: @ejgallego
