### ISSUE TITLE
CoqIDE 8.10beta1 fails to open filenames with dots

### ISSUE THREAD

**Issue by charguer** [coq/coq#10286] opened 2019-06-03 12:50 UTC
#### Description of the problem

CoqIDE 8.10 fails to handle file with dot in the name.

```
coqide foo.bar.v
Error: Invalid character '.' in identifier "foo.bar".
```

If the file already exists, CoqIDE can even silently hang on load.

#### Coq Version

coq-8.10beta1

**Comment by maximedenes** [comment] 2019-06-04 19:43
@charguer Can you clarify what behavior you were expecting?

**Comment by charguer** [comment] 2019-06-04 20:42
Like it used to be, that is:
- if `foo.bar.v` exists, then `coqide foo.bar.v` should open the file named `foo.bar.v`
- otherwise, it should open a blank file named `foo.bar.v`, with an "unsaved" status.

The existence of a dot in the middle of a filename is perfectly valid, as far as I know.
I haven't tried the presence of spaces, but one could argue that they should be supported as well (i.e. `coqide "foo bar.v"`).

**Comment by SkySkimmer** [comment] 2019-06-04 20:45
I don't know what you mean by valid, you certainly can't compile them.

**Comment by maximedenes** [comment] 2019-06-04 20:59
> The existence of a dot in the middle of a filename is perfectly valid

I doubt it, since the filename should be a valid identifier, shouldn't it?

**Comment by Zimmi48** [comment] 2019-06-04 21:02
The silent hanging is problematic though.

**Comment by maximedenes** [comment] 2019-06-04 21:06
> The silent hanging is problematic though.

Indeed, it is strange that we don't get the same error regardless of whether the file exists.

**Comment by SkySkimmer** [comment] 2019-06-04 21:07
coqide should be able to deal with init time errors without hanging I guess

**Comment by charguer** [comment] 2019-06-04 21:15
I just realized that indeed, there is a restriction in the filenames due to the fact that the same names serve as module names, and that "dot" is reserved for parsing qualified names.

Interestingly,  Ocaml accepts to compile a file with a dot in the name. It simply seems not possible to refer to the corresponding module from another file.

Thus, let me take back what I wrote previously. I suggest to simply document somewhere that dot in filenames are disallowed. And to raise a clean error wherever possible.

Thanks

**Comment by Zimmi48** [comment] 2019-07-21 12:38
The hanging is really problematic and should not be left in a final release. This shouldn't even be hard to fix!

**Comment by MSoegtropIMC** [comment] 2019-07-22 10:05
Who is taking care of this? I think it should be fixed in the way suggested by @charguer, that the user gets an error when using a filename which is not a module name already when saving a file (which btw. does work without errors - only reopening such a file fails).

I feel responsible for Windows specific bugs but not for bugs which also appear on Linux.

**Comment by Zimmi48** [comment] 2019-07-22 10:54
Maybe one of the CoqIDE maintainers (@gares @herbelin @ppedrot)?

**Comment by herbelin** [comment] 2019-07-22 12:03
OK, I'll have a look by tomorrow.

**Comment by silene** [comment] 2019-07-22 12:22
Please don't make it an error to save a file with a name that is not a module name. I happen to do it quite often. (Not all `.v` files are meant to be compiled to `.vo` files using `coqc`. Some files, e.g., tests, are just used with `coqtop`.)

**Comment by MSoegtropIMC** [comment] 2019-07-22 13:09
> Please don't make it an error to save a file with a name that is not a module name. I happen to do it quite often. (Not all `.v` files are meant to be compiled to `.vo` files using `coqc`. Some files, e.g., tests, are just used with `coqtop`.)

I actually do the same (otherwise I wouldn't have hit the issue), but I think users should be at least warned about it, since it is not so obvious.

But I concluded that it wouldn't hurt me to use underscores instead of hyphens in file names either.

**Comment by herbelin** [comment] 2019-07-22 19:27
@silene, @MSoegtropIMC: The name of the file given to Coqide is used to evaluate the file as if given with `coqtop`'s option `-top`/`-topfile`. This is what allows for instance to do `coqide theories/Init/Logic.v` and have the evaluation of the file referring to constants of the file `Logic.v` itself (e.g. `eq` for rewriting). [I'm not saying this kind of self reference is a good methodology or not. I'm just saying how, currently, the name of the file is used, even if the file is not intended to be compiled.]

So, @silene, @charguer, I'd be tempted to follow @MSoegtropIMC's suggestion and to make it a (non-freezing) error. The alternative would otherwise be to warn that the filename is not valid and to renounce in this case to call `coqtop` with option `-topfile`. But I feel that a warning would be as intrusive as an error, and, eventually, users would eventually get the habit in all cases to avoid invalid names??

**Comment by Zimmi48** [comment] 2019-07-23 17:41
Indeed, your explanation on the new behavior makes perfect sense. I personally support making this an error.

**Comment by herbelin** [comment] 2019-07-23 19:57
Actually, that's not so easy to fix in an optimal way.

First, for the record: the change was motivated by fixing #8989.

The reason it hangs is that `coqide` command line arguments are processed this way:
- `coqide` calls `coqidetop` to check that the command line arguments are valid. The errors are turned into a popup message w/o hanging. At the same time, `coqidetop` returns the list of non-options arguments, making the assumption that these are the files to open.
- `coqide` calls `coqtop` with option `-topfile` on each of the files. This call is assumed not to raise an error at command line interpretation and this is why it hangs (only errors received from the xml protocol are treated) but the communication is here via the command line.

None of the options I see to address the problem are fully satisfactory:
1. we could protect the interpretation of the command line argument as was done in the first call to `coqide` but this seems a bit overkill since only `-topfile` seems the cause for a possible new failure.
2. checking the validity of option `-topfile` in coqide would require exporting a function from `coqtop` which is not supposed to be exported (`dirpath_of_file`).
3. a warning at the interpretation of `-topfile` would look strange. If a warning, it should be governed by `coqide` itself. In itself, option `-topfile` is not supposed to be discarded when invalid.

I opted in #10557 for roughly copy-pasting the check of validity of the file in coqide (i.e. a weak ad hoc form of 2).

**Comment by maximedenes** [comment] 2019-07-23 21:04
> Please don't make it an error to save a file with a name that is not a module name. I happen to do it quite often.

This seems to be adding complexity. Can you give a motivation? What prevents changing these file names to valid module names?

**Comment by gares** [comment] 2019-07-23 21:04
We could also say that coqtop never fails if a `-topfile f` is passed with a file name `f` that cannot be turned into a module name, eg coqtop could replac all offending characters with `_`. So if you use `-topfile` with a "valid" file name, you get the module name you expect. If you pass junk you get something that is still sensible.

**Comment by MSoegtropIMC** [comment] 2019-07-24 09:21
> coqtop could replac all offending characters with _

This is a very sensible suggestion: have a documented translation from arbitrary file names to module names. In case one doesn't care what the module name is as in top level test files, this doesn't make a difference.

**Comment by charguer** [comment] 2019-07-24 12:42
The issue with a translation from arbitrary files names to modules is that you'll inevitably end up with module name clashes for distinct files. That would be incomprehensible to the user. E.g. if `foo_.v` and `foo'.v` were both considered by `Import foo_\`. Plus, your translation table will never be rich enough, given how fancy characters a file system might accept.

I thus advise against a translation.

**Comment by ejgallego** [comment] 2019-07-24 12:54
Indeed the translation seems to add little; Coq itself should not save `.vo` files with invalid module names, on the other hand I don't see a reason to restrict what `coqide` can save, however warning should be given as the user won't be able to run that file anymore, as `coqtop` should refuse to start on it.

**Comment by MSoegtropIMC** [comment] 2019-07-24 13:15
> on the other hand I don't see a reason to restrict what `coqide` can save

As @herbelin explained, it is not that easy to support opening files with arbitrary names - either one has to translate them or one has to throw an error or one has to have some non standard handling for such files. I would be happy with either, throwing an error or translation, but I am not so happy with introducing a number of "if filename is special", because this would not be tested much and likely break every other release.

@charguer : the translation is intended for cases where one never want's to load the file as module (top level test cases). I don't follow the incompleteness argument. The syntax of module names should be well defined and any character not supported by this syntax is replaced by _.

The current situation is that one can save files with arbitrary names, but if one tries to open them, CoqIDE gives a "coqtop dies badly".

**Comment by ejgallego** [comment] 2019-07-24 13:25
> As @herbelin explained, it is not that easy to support opening files with arbitrary names

What I mean is that you can save the files however you won't be able to check them.

**Comment by MSoegtropIMC** [comment] 2019-07-24 13:36
> What I mean is that you can save the files however you won't be able to check them.

The issue is that you can't even open them in CoqIDE again. This is not terribly helpful. Opening files with non module names would require special handling in CoqIDE.

**Comment by ejgallego** [comment] 2019-07-24 13:38
You can open them, however coqtop will fail to initialize; this error can happen for many reasons already so it should not be too complicated.

**Comment by gares** [comment] 2019-07-24 14:16
> You can open them, however coqtop will fail to initialize; this error can happen for many reasons already so it should not be too complicated.

You also want to play the file, not just open it, this is why I suggest to have coqtop not fail to initialize but pick a module name, any actually would do, and eventually, as you suggest, emit a warning.

> The issue with a translation from arbitrary files names to modules is that you'll inevitably end up with module name clashes for distinct files. 

I agree but...

> That would be incomprehensible to the user. E.g. if `foo_.v` and `foo'.v` were both considered by `Import foo_\`.

what I suggest it to have "coqidetop" do the mangling, coqc would just fail generating the .vo and hence there would be no Require or Import of these (top level) modules.

**Comment by gares** [comment] 2019-07-24 14:19
>  Can you give a motivation? What prevents changing these file names to valid module names?

I don't know you but I end up having `#foo.v#`, `foo.v.coqidecrash`, `foo.v.bak`, `foo.v~` around.
Doing the `mv foo.v foo.v.stash; mv foo.v.bak foo.v; coqide foo.v; ...` is not very handy.

**Comment by gares** [comment] 2019-07-24 14:30
Discussing with @maximedenes I realized that one can refer to the top module name, so even "renaming" `foo.v` in `bar.v` can break its meaning (eg if you have a line `Check Foo.x`). Similarly picking any module name for the sake of being able to process the file is equally wrong in terms of semantics.

So maybe we should just give an error that explains all that to the user, and eventually think about a file format Isabelle style, where there is a mandatory header telling the top module name (and its dependencies).

**Comment by Zimmi48** [comment] 2019-07-25 08:28
>mandatory header telling the top module name

That actually sound very reasonable and it is also very common in various programming languages (e.g. Haskell, Elm, what else...?)

**Comment by Zimmi48** [comment] 2019-07-25 08:29
(But that isn't a short time solution.)

**Closed** 2019-08-06 07:58 UTC
Labels: kind: documentation, kind: user messages, part: IDE, priority: high
