### ISSUE TITLE
A bug about section variable.

### ISSUE THREAD

**Issue by QinxiangCao** [coq/coq#11729] opened 2020-03-01 19:16 UTC
#### Description of the problem

I find "induction" may eliminate section variables (claimed by Variable or context) and reuse the same name.
However, an in-section theorem about section variables can be applied on those new variables (which seems to be the original section variable).
Qed can find this problem but "apply" cannot find it. Here is an example.

```coq
Inductive rt_clos {A: Type}: (A -> A -> Prop) -> A -> A -> Prop :=
| rt_refl: forall R x, rt_clos R x x
| rt_step: forall (R: A -> A -> Prop) x y z, R x y -> rt_clos R y z -> rt_clos R x z.

(* Using this bad definition is intentional. A better definition is:

Inductive rt_clos {A: Type} (R: A -> A -> Prop): A -> A -> Prop :=
| rt_refl: forall x, rt_clos R x x
| rt_step: forall x y z, R x y -> rt_clos R y z -> rt_clos R x z.
*)

Section TEST.

Context {A: Type} {R: A -> A -> Prop}.

(* Again, we intentionally put R here so that we can demonstrate a bug. *)

Lemma foo: forall x y, rt_clos R x y -> rt_clos R x y.
Proof. intros; auto. Qed.

Lemma rt_clos_trans: forall x y z, rt_clos R x y -> rt_clos R y z -> rt_clos R x z.
Proof.
  (* This is the current proof goal:
  A : Type
  R : A -> A -> Prop
  ============================*
  forall x y z : A, rt_clos R x y -> rt_clos R y z -> rt_clos R x z
  *)
  intros.
  induction H.
  + (* This is the current proof goal:
       A : Type
       z : A
       R : A -> A -> Prop
       x : A
       H0 : rt_clos R x z
       ============================*
       rt_clos R x z

       But I think it is better to be:
       A : Type
       z : A
       R : A -> A -> Prop
       R0 : A -> A -> Prop
       x : A
       H0 : rt_clos R0 x z
       ============================*
       rt_clos R0 x z
     *)
    apply foo, H0.
    (* In other words, "apply foo" should be denied here. *)
  + apply IHrt_clos in H0.
    apply rt_step with y; auto.
Qed.
```

#### Coq Version

The Coq Proof Assistant, version 8.10.1 (October 2019)
compiled on Oct 28 2019 20:20:52 with OCaml 4.09.0

MacOS / CoqIDE on Windows

**Comment by SkySkimmer** [comment] 2020-03-31 14:28
Duplicate of https://github.com/coq/coq/issues/11487 and probably others

**Closed by SkySkimmer** 2020-03-31 14:28 UTC
Labels: part: tactics
