### ISSUE TITLE
(ssr) Rewrite doesn't terminate, but succeeds iff interrupted

### ISSUE THREAD

**Issue by ana-borges** [coq/coq#13340] opened 2020-11-10 15:13 UTC
#### Description of the problem

I ran into this problem at the same time as I ran into #13338, but I guess they are unrelated. Here is the relevant code:

```
Require Import Int63 ZArith.
From mathcomp Require Import all_ssreflect.

Coercion nat_of_int (n : Int63.int) : nat :=
match Int63.to_Z n with
| Zpos p => nat_of_pos p
| Zneg p => nat_of_pos p
| Z0 => 0
end.

Lemma exposed_max_int : max_int %/ 1%int63 - 1%int63 %/ 1%int63 = max_int - 1.
Proof.
  rewrite divnn. (* Doesn't terminate but succeeds iff interrupted *)
  (*rewrite-> divnn.*) (* Doesn't terminate and fails if interrupted *)
  by rewrite divn1.
Qed.
```
So, to reiterate: if I go through this proof, it gets stuck at `rewrite divnn`. However, if I stop the computation at that point (eg with `C-c C-c`), then it succeeds and the following lines can be evaluated, including the `Qed`. This doesn't happen with `rewrite->`, which simply fails.

I'm not sure whether this is a Coq bug or a Proof General bug (I tried installing CoqIDE to test, but it was non-trivial and I gave up), so I'm sorry in advance if this is the wrong issue tracker.

#### Coq Version
8.12

**Comment by ana-borges** [comment] 2021-11-01 18:58
> I'm not sure whether this is a Coq bug or a Proof General bug

I just tried it in Coqtail and exactly the same thing happens.

**Comment by ppedrot** [comment] 2021-11-01 19:04
Probably some fancy interaction with the compatibility layer that catches a stray exception. Funny thing is that I am precisely making some progress on its removal in ssr right now...

**Comment by ppedrot** [comment] 2022-02-28 12:44
I can't reproduce on a recent master. It was probably fixed by the port to the new engine. Closing then.

**Closed by ppedrot** 2022-02-28 12:44 UTC
Labels: part: ssreflect
