### ISSUE TITLE
Error: Anomaly "grounding a non evar-free term" Please report at http://coq.inria.fr/bugs/. on failed type inference

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#9244] opened 2018-12-18 17:44 UTC
#### Version

8.9+beta1

#### Description of the problem

```coq
Fixpoint foo a : unit.
(* Error: Anomaly "grounding a non evar-free term" Please report at http://coq.inria.fr/bugs/. *)
Fixpoint bar {a} (x : a = a) (n : nat) {struct n} : unit.
(* Error: Anomaly "grounding a non evar-free term" Please report at http://coq.inria.fr/bugs/. *)
```
I expect to see an error message about failed type inference, not this anomaly.

**Comment by ppedrot** [comment] 2018-12-18 17:46
AFAICT this is a duplicate of #9163.

**Comment by ejgallego** [comment] 2019-03-04 03:32
Fixed on master.

**Closed by ejgallego** 2019-03-04 03:32 UTC
Labels: kind: anomaly
