### ISSUE TITLE
Coq 8.7.0 test-suite fails (when Coq not configured -local and not installed)

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#5975] opened 2017-10-18 14:59 UTC
I'm not sure what's up with `Error: cannot guess a path for Coq libraries; please use -coqlib option`.  See [this launchpad log](https://launchpadlibrarian.net/341301069/buildlog_ubuntu-precise-amd64.coq-8.7.0_8.7.0-1~precise~ppa79_BUILDING.txt.gz) for more details.
```
make[5]: Entering directory `/<<PKGBUILDDIR>>/test-suite'
Makefile:177: warning: undefined variable `TRAVIS'
logs/misc/printers.log
==========> TESTING misc/printers.sh <==========
Error during initialization: 
Error: cannot guess a path for Coq libraries; please use -coqlib option
0m0.000000s 0m0.000000s
0m0.050000s 0m0.000000s
==========> FAILURE <==========
    misc/printers.sh...Error!

logs/coq-makefile/uninstall1.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/uninstall1/run.sh...Error!

logs/coq-makefile/findlib-package.log
../template/init.sh: line 8: git: command not found
make[5]: Entering directory `/<<PKGBUILDDIR>>/test-suite/coq-makefile/findlib-package/findlib/foo'
make[5]: Leaving directory `/<<PKGBUILDDIR>>/test-suite/coq-makefile/findlib-package/findlib/foo'
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/findlib-package/run.sh...Error!

logs/coq-makefile/arg.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/arg/run.sh...Error!

logs/coq-makefile/extend-subdirs.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/extend-subdirs/run.sh...Error!

logs/coq-makefile/only.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/only/run.sh...Error!

logs/coq-makefile/coqdoc1.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/coqdoc1/run.sh...Error!

logs/coq-makefile/multiroot.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/multiroot/run.sh...Error!

logs/coq-makefile/latex1.log
/usr/bin/pdflatex
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/latex1/run.sh...Error!

logs/coq-makefile/mlpack1.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/mlpack1/run.sh...Error!

logs/coq-makefile/plugin3.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/plugin3/run.sh...Error!

logs/coq-makefile/merlin1.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/merlin1/run.sh...Error!

logs/coq-makefile/coqdoc2.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/coqdoc2/run.sh...Error!

logs/coq-makefile/uninstall2.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/uninstall2/run.sh...Error!

logs/coq-makefile/plugin2.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/plugin2/run.sh...Error!

logs/coq-makefile/plugin1.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/plugin1/run.sh...Error!

logs/coq-makefile/compat-subdirs.log
../template/init.sh: line 8: git: command not found
Warning: Subdirectories are deprecated.
Warning: Use double colon rules in Makefile.local.

Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/compat-subdirs/run.sh...Error!

logs/coq-makefile/mlpack2.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/mlpack2/run.sh...Error!

logs/coq-makefile/validate1.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/validate1/run.sh...Error!

logs/coq-makefile/timing.log
../template/init.sh: line 8: git: command not found
Error: cannot guess a path for Coq libraries; please use -coqlib option
==========> FAILURE <==========
    coq-makefile/timing/run.sh...Error!

FAILURES
    misc/printers.sh...Error!
    coq-makefile/arg/run.sh...Error!
    coq-makefile/compat-subdirs/run.sh...Error!
    coq-makefile/coqdoc1/run.sh...Error!
    coq-makefile/coqdoc2/run.sh...Error!
    coq-makefile/extend-subdirs/run.sh...Error!
    coq-makefile/findlib-package/run.sh...Error!
    coq-makefile/latex1/run.sh...Error!
    coq-makefile/merlin1/run.sh...Error!
    coq-makefile/mlpack1/run.sh...Error!
    coq-makefile/mlpack2/run.sh...Error!
    coq-makefile/multiroot/run.sh...Error!
    coq-makefile/only/run.sh...Error!
    coq-makefile/plugin1/run.sh...Error!
    coq-makefile/plugin2/run.sh...Error!
    coq-makefile/plugin3/run.sh...Error!
    coq-makefile/timing/run.sh...Error!
    coq-makefile/uninstall1/run.sh...Error!
    coq-makefile/uninstall2/run.sh...Error!
    coq-makefile/validate1/run.sh...Error!
make[5]: *** [report] Error 1
make[5]: Leaving directory `/<<PKGBUILDDIR>>/test-suite'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/<<PKGBUILDDIR>>/test-suite'
make[3]: *** [test-suite] Error 2
make[3]: Leaving directory `/<<PKGBUILDDIR>>'
make[2]: *** [submake] Error 2
make[2]: Leaving directory `/<<PKGBUILDDIR>>'
make[1]: *** [override_dh_auto_test] Error 2
make[1]: Leaving directory `/<<PKGBUILDDIR>>'
make: *** [build] Error 2
```

**Comment by Zimmi48** [comment] 2017-10-18 15:02
Isn't this a duplicate of #5725?

**Comment by JasonGross** [comment] 2017-10-18 15:08
I cannot tell what the cause of failure there is, but it's not clear to me that the cause of failure here is a lack of `git`.  In particular, all of the `../template/init.sh: line 8: git: command not found` lines are red herrings; the file contains `|| true` after the `git clean -dfx` command.  I don't know how Coq goes about trying to guess a path for coq libraries, and whether it special-cases the existence of `.git`.

**Comment by Zimmi48** [comment] 2017-10-18 15:12
Anyways, assigning this to @gares since he is the author of most of these tests.

**Comment by Zimmi48** [comment] 2017-11-08 15:22
`Error: cannot guess a path for Coq libraries; please use -coqlib option` appears when running `coqtop` as soon as it was not compiled with `./configure -local`. This was already the case in 8.6.1 but the only tests that fail because of this are new tests from 8.7.
What I don't understand though is that it should have been caught by GitLab CI (WDYT @SkySkimmer?). We should also make sure that at least one target of Travis does not rely on `./configure -local`.

**Comment by SkySkimmer** [comment] 2017-11-08 16:02
gitlab installs before running the test suite, so it finds the library in the expected -prefix path.

**Comment by SkySkimmer** [comment] 2017-11-19 21:19
This is a bit tricky, we're trying to test coq_makefile before installing Coq but the test of coq_makefile tests that it points Coq at the correct coqlib location.

**Comment by Zimmi48** [comment] 2017-11-30 16:09
@gares Do you intend to address this? I think the compile -> test -> install chain of action is at least as legitimate as compile -> install -> test and we should make sure that this is possible. At the very least we should disable these tests when Coq hasn't been installed yet (and was not compiled with `-local`).

**Comment by Zimmi48** [comment] 2017-12-06 13:57
@gares What's your take on this?

**Comment by Zimmi48** [comment] 2017-12-08 15:22
Are @JasonGross and I the only two persons annoyed by this situation?

**Comment by gares** [comment] 2017-12-12 16:50
I'm giving it a try now

**Comment by gares** [comment] 2017-12-12 19:43
The scripts fail because `coq_makefile` is configured to look for the coqlib in X (if `-prefix X` if given) but
it is not yet installed in there. The other tests work because we override the configure time path for coqlib by passing `-coqlib` to `coqtop`.

There is not easy fix:
- coq_makefile does not accept `-coqlib ../....`
- the `COQLIB` env variable does not exists (not used by envars)
and of course all tests about `coq_makfile` do call `coq_makefile` to create the `Makefile`...

**Comment by gares** [comment] 2017-12-12 19:46
For @JasonGross there are many ways to make the .deb package compile.
I think that `export DEB_BUILD_OPTIONS=nocheck` should do it, but I've no time to check it.

**Comment by Zimmi48** [comment] 2017-12-18 15:50
Are you envisioning a fix that would not be backportable? Otherwise, I'd rather have this fix in v8.7, so putting the 8.7.2 milestone.

**Comment by maximedenes** [comment] 2018-03-07 11:44
@gares please update the milestone to reflect your current schedule on this.

**Comment by Zimmi48** [comment] 2018-03-29 13:57
@ejgallego's comment https://github.com/coq/coq/pull/6809#issuecomment-377218945 makes me think that this problem should go away with Dune.

**Comment by ejgallego** [comment] 2018-03-29 14:04
Yup, Dune in a sense is a bit similar to "Nix-like" approaches, when running something from Dune   path is set up in such a way that it simulates the environment you'd get when installing the package. So in fact, if you depend on coqtop, coqtop is built and installed first

**Comment by ejgallego** [comment] 2018-03-29 14:04
I hit the wrong button because a bump in the bus, sorry.

**Comment by ejgallego** [comment] 2018-05-15 15:25
In my personal opinion this bug is a WONTFIX, "installing" should be a pre-requisite for running programs that depend on a working install, such as building the library or the test suite.

I write installing because that in practice means using a separate build dir that can be properly "brought into scope" by using PATH etc...

**Comment by ejgallego** [comment] 2018-05-15 15:27
By the way this is how Dune works and IMHO it is the right choice, if you depend on `coqtop` for example, it will be installed before use; you can also use build byproducts of course setting the build-tree path but what's not recommended is to have a conditional alias on the same thing depending on a configure flag.

**Comment by Zimmi48** [comment] 2018-05-15 15:30
Locally installing (how Dune works) could be fine but the current situation doesn't allow locally installing, then properly installing easily. So I strongly object to a "won't fix". But I get that Dune could make this problem go away.

**Comment by Zimmi48** [comment] 2018-05-16 12:28
Local install sounds to me more like part of the build process anyways. The actual install phase is just about copying files to their final destinations.

**Comment by ejgallego** [comment] 2018-07-12 16:05
Should this be closed BTW?

**Comment by Zimmi48** [comment] 2018-07-12 17:07
@JasonGross Does the solution proposed in #7977 satisfies your need?

**Comment by JasonGross** [comment] 2018-07-12 19:48
Yes, that should work fine for me

**Closed** 2018-07-12 19:56 UTC
Labels: priority: high
