### ISSUE TITLE
Unifying records with primitive projections requires universe polymorphism

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#13980] opened 2021-03-23 09:35 UTC
#### Version

Coq 8.12.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following proof only goes through
in the presence of universe polymorphism,
which is questionable.

```coq
From Coq Require Import Logic.StrictProp.

Module Mono.

Unset Universe Polymorphism.

Lemma eq_Ssig (A : Type) (P : A -> SProp)
  (a0 : A) (b0 : P a0) (a1 : A) (b1 : P a1)
  (e : a0 = a1) : Sexists P a0 b0 = Sexists P a1 b1.
Proof. apply Spr1_inj. auto. Qed.

End Mono.

Module Poly.

Set Universe Polymorphism.

Lemma eq_Ssig (A : Type) (P : A -> SProp)
  (a0 : A) (b0 : P a0) (a1 : A) (b1 : P a1)
  (e : a0 = a1) : Sexists P a0 b0 = Sexists P a1 b1.
Proof. apply Spr1_inj. auto. Qed.

End Poly.

Definition squish (x : unit) : SProp := Squash (x = tt).

Lemma unity (b0 b1 : squish tt) : Sexists squish tt b0 = Sexists squish tt b1.
Proof.
  Fail apply Mono.eq_Ssig.
  apply Poly.eq_Ssig.
  reflexivity.
Qed.
```

```
The command has indeed failed with message:
In environment
b0, b1 : squish tt
Unable to unify
 "@eq (@Ssig@{Mono.eq_Ssig.u0} ?M160 ?M161) (@Sexists@{Mono.eq_Ssig.u0} ?M160 ?M161 ?M162 ?M163)
    (@Sexists@{Mono.eq_Ssig.u0} ?M160 ?M161 ?M164 ?M165)"
with "@eq (@Ssig@{Set} unit squish) (@Sexists@{Set} unit squish tt b0) (@Sexists@{Set} unit squish tt b1)".
```

#### Notes

This is in conflict with #13979 and may be related to #13765.

**Comment by SkySkimmer** [comment] 2021-03-23 10:15
Duplicate of https://github.com/coq/coq/issues/6976

**Comment by SkySkimmer** [comment] 2021-03-23 10:16
BTW https://github.com/coq/coq/pull/12624 is enough to fix this example.

**Closed by SkySkimmer** 2021-03-23 10:15 UTC
