### ISSUE TITLE
Cast is using vm for type-checking, even when byte compiler is disabled.

### ISSUE THREAD

**Issue by corwin-of-amber** [coq/coq#9967] opened 2019-04-17 18:31 UTC
#### Description of the problem

The `<:` notation is translated to `VMcast`, and `vm_conv_gen` invokes the VM even if Coq was configured with `-bytecode-compiler no`. In `vm_conv_gen`, the flag `(typing_flags env).enable_VM` is tested, but this flag is set to `true` by default, unconditionally, since #8870.

#### Coq Version

8.10 (master)

**Comment by corwin-of-amber** [comment] 2019-04-19 08:23
@ejgallego have we decided that this is not a bug in Coq?

**Comment by ejgallego** [comment] 2019-04-19 08:30
IMO that's a bug [level: improvement] on the API for initializing the kernel; things should be structured in such a way that when new parameters appear [as in the case of #8870 compilation should fail.

As I mention @corwin-of-amber I have a tree fixing that particular problem which sadly I didn't finish yet; so feel free to close this and the PR if you want.

[And sorry for misleading you again]

**Comment by corwin-of-amber** [comment] 2019-04-19 08:32
Don't worry about it!

**Comment by Zimmi48** [comment] 2019-04-26 14:31
I don't understand why it was recommended to close this bug before the fix was merged. IIUC it was not even submitted as a PR yet.

**Comment by corwin-of-amber** [comment] 2019-04-26 16:45
There was in fact a PR (#9968) but then @ejgallego came to the conclusion that in fact the behavior is not defective, it's only that the kernel initialization internal API was a bit unintuitive. I don't understand all the details, perhaps this deserves another look.

**Comment by JasonGross** [comment] 2019-04-26 17:16
It seems like maybe the issue is that the configure flags don't do anything anymore and should thus be deprecated? (Is it true that they don't do anything anymore?)

**Comment by SkySkimmer** [comment] 2023-06-07 15:41
Should be fixed now

**Closed by SkySkimmer** 2023-06-07 15:41 UTC
Labels: part: kernel
