### ISSUE TITLE
`Print Ltac` should print implicit arguments in patterns if they are referred to

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#10967] opened 2019-10-25 20:20 UTC
#### Description of the problem

```coq
Axiom Inst: forall {K V: Type} (M: Type), Type.

Ltac foo :=
  lazymatch goal with
  | H: @Inst ?K ?V ?M |- _ => assert (forall k: K, k = k)
  end.

Goal forall M, @Inst nat nat M -> True.
  intros.
  foo.
  Print Ltac foo.
```

prints

```coq
Ltac foo := lazymatch goal with
            | H:Inst ?M |- _ => assert (forall k : K, k = k)
            end
```

Since `foo` takes no arguments, I'd assume I can copy paste the body printed by `Print Ltac` into my proof script and get the same effect as if I were running `foo`, but that's not true, because the implicit `?K` from the original source is not printed.

#### Desired behavior

`Print Ltac` should print implicit arguments in matches whenever they were mentioned explicitly in the original Ltac source.

#### Coq Version

8.9.0

**Comment by ejgallego** [comment] 2019-10-25 20:24
I am inclined to mark this as "not a bug". Or at most, it is likely a duplicate of some existing request regarding printing round-trip.

`Print` is for human use, so it is normal that in the default mode doesn't have the round-trip property. If you intend to cut and paste then it is not unreasonable to use `Set Printing All` before the print.

There are many heuristics we could use as such, but on the other hand would make printing quite expensive.

**Comment by JasonGross** [comment] 2019-10-25 20:30
Duplicate of #9715

**Closed by JasonGross** 2019-10-25 20:30 UTC

**Comment by JasonGross** [comment] 2019-10-25 20:32
I agree that `Set Printing All` is not unreasonable (though there are [other](https://github.com/coq/coq/issues/9716) [bugs](https://github.com/coq/coq/issues/6613) that mean that even with `Set Printing All`, `Print Ltac` does not round-trip).  However, I don't think the time overhead in `Print Ltac` is significant.  Even if it takes a full second to print my complicated tactic, that's fine, because `Print Ltac` is not a bottleneck in most compile-edit-debug cycles.  (Goal printing time, on the other hand, is absolutely a bottleneck in many cases.)
