### ISSUE TITLE
reproducibility: don't include compilation time in the binaries

### ISSUE THREAD

**Issue by treinen** [coq/coq#11265] opened 2019-12-09 21:16 UTC
#### Description of the problem

Please do not include the compilation time in the coq binaries. The problem with this is that it makes builds un-reproducible, that is different compilations  even on otherwise identical
environments do not produce byte-to-byte identical binaries. In Debian we apply for this reason [this patch](https://salsa.debian.org/ocaml-team/coq/blob/experimental/master/debian/patches/use-changelog-date).

If you think that you really need this to produce some welcome message then please at
least provide a configuartion option so that one can set the time displayed in the banner
without patching the source code.

#### Coq Version

8.10.2

**Comment by ppedrot** [comment] 2019-12-09 21:18
Hasn't that been just fixed by #11227?

**Comment by treinen** [comment] 2019-12-09 21:24
Wow that was fast ;-)

I haven't checked the master branch, my bug report was based on the latest released version.
Yes, if configure.ml does take the time from an environment variable that is fine with me.

Thanks -Ralf.

**Comment by ppedrot** [comment] 2019-12-09 21:26
Duplicate of #11037

**Closed by ppedrot** 2019-12-09 21:26 UTC

**Comment by ejgallego** [comment] 2019-12-10 11:58
Note @treinen that Coq still will fail on repro builds due to #11229

**Comment by treinen** [comment] 2019-12-10 12:20
On Tue, Dec 10, 2019 at 03:58:30AM -0800, Emilio Jesús Gallego Arias wrote:
> Note @treinen that Coq still will fail on repro builds due to #11229 

Yes I know there are other issues, but this is one that has to be
resolved if one wants to achieve reproduciability.
-  
Ralf Treinen
Institut de Recherche en Informatique Fondamentale
Équipe Preuves, Programmes et Systèmes
Université Paris Diderot, Paris, France.
http://www.irif.fr/~treinen/
