### ISSUE TITLE
Conversion was given ill-typed terms error

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#11771] opened 2020-03-07 18:46 UTC
This is the shortest script I could find to reproduce:
```coq
Variable P : (Prop -> Prop) -> Prop.

Definition g (_ : Prop) := forall (_ : Prop), True.

Goal P g -> True -> True.
intro.
Fail match goal with
| _ : _ ?y |- ?y => idtac
| _              => idtac
end.
(* The command has indeed failed with message:
Conversion test raised an anomaly: Anomaly "conversion was given ill-typed terms (FProd)."
Please report at http://coq.inria.fr/bugs/.*)
```
I have no idea what is going on here.

#### Coq Version
The Coq Proof Assistant, version 8.12+alpha (March 2020)

**Comment by ppedrot** [comment] 2020-03-07 23:15
Same problem as #5466, namely that conversion tries to apply to terms that have not a common supertype, and fails while performing η-expansion. I think this one can be closed as a duplicate.

**Comment by ppedrot** [comment] 2020-03-07 23:16
Duplicate of #5466

**Closed by ppedrot** 2020-03-07 23:15 UTC
