### ISSUE TITLE
Unfold evars hangs

### ISSUE THREAD

**Issue by rnrand** [coq/coq#6424] opened 2017-12-14 04:59 UTC
#### Version

Coq 8.6

#### Operating system

Mac OS

#### Description of the problem

I'm trying to create a matrix of evars using `evar (e : nat)`. Unfortunately, when I try to unfold the variables introduced by `evar` coq hangs. Note that if I unfold them manually, it works fine. I've included a simplified example using lists.
 
```
  Ltac evar_list_nat n :=
  match n with 
  | O => constr:(@nil nat)
  | S ?n' => let e := fresh "e" in
            let na := match goal with
                    | _ => evar ( e : nat )
                    end in
            let ls := evar_list_nat n' in 
            constr:(e :: ls)   
  end.

Lemma test : exists (l : list nat), l = l.
  let l := evar_list_nat 30 in exists l.
  repeat match goal with
         | [H : nat |- _ ] => idtac H; unfold H; clear H
  end.
```
(The idtac is just there so you can see Coq grinding to a halt).

A workaround would be appreciated, besides for fixing the problem.

**Comment by ejgallego** [comment] 2017-12-14 05:37
This is just `cbn` being very slow on your goal. Try to unfold it partially, then do `cbn` and you will see the problem. As to what is the solution, I'm afraid we will need some expert in the kernel to help.

**Comment by rnrand** [comment] 2017-12-14 05:42
Where is `cbn` being called?

I've replaced the line that hangs with:
```
repeat match goal with 
                              | [ |- context[?c :: _ ]] => unfold c; clear c
                              end.
```
and it works fine. (This isn't ideal, but it works for now.)

**Comment by ejgallego** [comment] 2017-12-14 05:42
A workaround for your particular example is to call `compute`, but indeed that may be useful in general.

**Comment by ejgallego** [comment] 2017-12-14 05:45
`unfold` calls `cbn` before trying to unfold IIUC. I am not so familiar with the semantics of LTAC's `context`, but if that restricts the scope of the goal so reduction has a smaller term it looks like a good solution.

**Comment by rnrand** [comment] 2017-12-14 05:48
It must be trying to call `cbn` when it matches a hypothesis, then? (A manual sequence of 30 `unfold`s will also run quickly.)

**Comment by ejgallego** [comment] 2017-12-14 05:53
`cbn` is called by unfold unconditionally. The behavior of `cbn` here depends on the shape of the term thus on the order of `unfolds` [only reverse order is slow].

**Comment by ejgallego** [comment] 2017-12-14 05:54
In fact my wild guess is that your new matching construct is just modifying the order so you are in the fast case then.

**Comment by ejgallego** [comment] 2017-12-14 05:54
Anyways this is a legitimate issue with `cbn` in my non-kernel-expert opinion.

**Comment by ejgallego** [comment] 2017-12-14 05:57
I'd swear I've seen @JasonGross complaining about similar issues not too long ago. Am I right?

**Comment by rnrand** [comment] 2017-12-14 05:57
I see, you're right. In which case, I don't love my solution, because it's just happening to choose the better order. (And, in context, I don't think I can call `cbv` without a lot of clever ssreflect-style locking.)

**Comment by maximedenes** [comment] 2017-12-14 07:31
> I'm afraid we will need some expert in the kernel to help.

Where is the kernel involved here?

**Comment by ppedrot** [comment] 2017-12-14 07:40
I don't think it has to do with `unfold` at all, on my machine Coq spends its time doing kernel reduction in the `check_and_clear_in_constr` function called by the `clear` tactic.

**Comment by ppedrot** [comment] 2017-12-14 07:51
That said, I wouldn't be surprised this is a non-bug. Experimentally, the code is exponential in the number of evars generated, and this is probably due to the fact that each evar body is mentioning all of the formerly generated ones. Because of that, the size of hypotheses is already quadractic, and unfolding in the wrong order results in a cascade of repeated unfoldings. If you replace `match goal` in your tactic by `match reverse goal` this is immediate because the unfolding is performed in the right order.

**Comment by rnrand** [comment] 2017-12-14 08:01
> each evar body is mentioning all of the formerly generated ones

What does this mean? All of the evars are independent of one another - is there some kind of internal dependency graph between them (so an evar created later can depend on one created earlier)?

**Comment by ppedrot** [comment] 2017-12-14 08:06
@rnrand Evars are essentially described by a type of the form `Γ ⊢ A`, where `Γ` is a context and `A` a type in that context. This is the very notion of evars, and having a type alone would give a broken system. When using an evar in a term, the user has to provide all arguments from the `Γ` context in what is called in Coq jargon an evar substitution. For reasons I believe to be bad, Coq hides this part to the user by default, although you can activate the printing e.g. setting the Print All option (there are more fine-grained options but I don't remember the name ATM).

In your example, all evars are created in a context that keeps growing, leading to the explosion you witness. Try setting the flag to see what I mean.

**Comment by maximedenes** [comment] 2017-12-14 08:11
> kernel reduction in the check_and_clear_in_constr

Just curious, where exactly does it call reduction?

**Comment by ejgallego** [comment] 2017-12-14 09:41
Oh, so if term is quadratic that does indeed explains why `cbn` takes so much time. I am surprised thou, I would have thought that Coq would use sharing to avoid this problem.

@rnrand : indeed evars are scoped by their possible instantiations, imagine a matrix:
```
| ?X1 | ?X2 |
|─────+─────|
| ?X4 | ?X3 |
```
so for example, should instantiating `?X2` by `f(?X1)` be allowed? If indeed would assume your evars are independent you could avoid this problem [in theory, I ignore if Coq can really suppor that].

Regarding the time spent, the main normalization culprit is called from `unfold`, not clear. Just a sequence of unfolds suffices to trigger the bug.

**Comment by ppedrot** [comment] 2017-12-14 10:09
> Regarding the time spent, the main normalization culprit is called from unfold, not clear. Just a sequence of unfolds suffices to trigger the bug.

Indeed, you're right, I was not completely awake while reading the backtraces. But that's not `cbn` still, that's `nf_betaiotazeta` which uses the kernel reduction. `cbn` is implemented using the Reductionops machinery.

>  I am surprised thou, I would have thought that Coq would use sharing to avoid this problem.

Well, to compute the reduced form you have to crawl the term anyway, so that sharing doesn't help.

**Comment by ejgallego** [comment] 2017-12-14 12:17
Oh indeed sorry, I meant `cbn` == kernel reduction.

> Well, to compute the reduced form you have to crawl the term anyway, so that sharing doesn't help.

Yeah this is tricky and I am not expert, but I was just assuming that `evar` contexts would be shared (by common prefix) and reduction would preserve them indeed to avoid a quadractic explosion otherwise"

**Comment by ppedrot** [comment] 2017-12-14 15:58
Anyways, I believe that this bug is invalid, and I'll close it.

**Closed** 2017-12-14 15:58 UTC
Labels: kind: performance

**Comment by rnrand** [comment] 2017-12-14 16:10
I would keep it open. 

This isn't quadratic time. The process literally doesn't run to completion - that's unfolding **30** evars! (And I can't see a justification for why this should be exponential.) This is going to be a recurring problem for any program that has more than a few evars in its scope.

Also, I tried `Set Printing All` and I still don't see the dependencies between evars.

**Comment by ppedrot** [comment] 2017-12-14 16:24
> This is going to be a recurring problem for any program that has more than a few evars in its scope.

I'm afraid this explosion is due to the very nature of evars. It's actually fairly strange how people complain in Coq about time explosions when their program is using a naive algorithm. You're not the first one, don't worry, even Coq gurus like @JasonGross complained about exponential behaviour while using unary integers...

> Also, I tried Set Printing All and I still don't see the dependencies between evars.

This is strange. What do you use to interact with Coq. PG, I guess?

**Comment by ppedrot** [comment] 2017-12-14 16:28
A quick fix for this particular case is reversing the order, but he probably has more principled examples in mind. I'd advise trying to understand the evar model to get why this blows up, but unluckily I'm not sure it is properly documented anywhere.

**Comment by ejgallego** [comment] 2017-12-14 16:41
Well this is clearly a bug in my book, the reduction machinery should be smarter and not normalize evar contexts that have been already normalized.

**Comment by ppedrot** [comment] 2017-12-14 16:46
I'm trying to come up with an example that does not involve evars so that @rnrand understands the problem. Morally, this is just that picking one unfolding order enforces a call-by-name reduction and the other one a call-by-value. So, I stand my ground, this is not a bug.

**Comment by herbelin** [comment] 2017-12-17 12:13
> > Also, I tried Set Printing All and I still don't see the dependencies between evars.
> 
> This is strange. What do you use to interact with Coq. PG, I guess?

The correct command here is `Set Printing Existential Instances". (Maybe should it be integrated to `Set Printing All`, at least to justify the `All`, I don't know...). In the present case, this gives (first lines shown):
```coq
1 subgoal
e := ?e : nat
e0 := ?e0@{e:=e} : nat
e1 := ?e1@{e:=e; e0:=e0} : nat
e2 := ?e2@{e:=e; e0:=e0; e1:=e1} : nat
e3 := ?e3@{e:=e; e0:=e0; e1:=e1; e2:=e2} : nat
e4 := ?e4@{e:=e; e0:=e0; e1:=e1; e2:=e2; e3:=e3} : nat
e5 := ?e5@{e:=e; e0:=e0; e1:=e1; e2:=e2; e3:=e3; e4:=e4} : nat
e6 := ?e6@{e:=e; e0:=e0; e1:=e1; e2:=e2; e3:=e3; e4:=e4; e5:=e5} : nat
```

I tried using an `instantiate (new_e := ltac:(clear previous_e; refine ?[?new_e]))` trick to modify your code so that each new `e` is cleared in the list `ls` of evars already posed, but the management of bindings is rather ad hoc in `ltac` and none of the two occurrences of `new_e` in
```coq
Ltac clear_previous_in_new previous_e neq_e := instantiate (new_e := ltac:(clear previous_e; refine ?[?new_e]))
```
are considered as binding `Ltac` variables so it fails.

We could modify `Ltac` so that the name in `instantiate` and the name in `?[n]`bind too, but writing code in a language primarily designed on a clear distinction of what binds what, as `Ltac2` is, could be a more robust way to go.

**Comment by Zimmi48** [comment] 2017-12-17 13:39
> The correct command here is Set Printing Existential Instances. (Maybe should it be integrated to Set Printing All, at least to justify the All, I don't know...). In the present case, this gives (first lines shown):

Yes, it probably should since it confused even @ppedrot.
Note that CoqIDE users can easily find this option in the CoqIDE view menu though. I expect something similar in PG/xml (@psteckler?) and in any "modern" Coq editor.

**Comment by herbelin** [comment] 2017-12-17 14:04
What is missing in `All` is also `Printing Universes` (and there is a menu in CoqIDE which does the three of them at the same time - bound to the `L` letter, e.g. `shift-alt-L` for me).

Don't know what would be the best interface, in either textual mode or graphical mode.

In textual mode, renaming the semantics of `All` into `Basic All` and adding `Printing Universes` and `Printing Existential Instances` to what the name `All` does?

In GUI mode, just have a side bar of checkboxes that can be freely mixed, with an additional button that deactivate all or activate all at the same time? (There was a discussion at some issue on how to additionally combine such an asynchronous model with the synchronous textual model.)


BTW, see also #5630.

**Comment by ejgallego** [comment] 2017-12-17 14:18
An interesting problem is that indeed the handling of flags in the printer has become a bit complicated after so many versions. It would be great if all the flags could be consolidated into a:
```ocaml
type coq_print_flag =
  | PrintO1 of ...
  | PrintOn of ...

module PrintFlagSet = Set.Make(struct t = coq_print_flag ... end)
```
such that printing functions would test for particular features using `PrintFlagSet.mem` etc...

After that, it would be interesting so tweak the set of flags in a systematic way. Also, IDEs could have a better reference as to what to set in the set.

**Comment by herbelin** [comment] 2017-12-17 14:31
@ejgallego: yes, your proposal looks good to me.

I opened a dedicated page at #6455 to centralize discussions on the topic (hoping that it would be easier to find again than the discussions here and there).

**Comment by JasonGross** [comment] 2017-12-17 15:06
I did indeed complain recently about exponential blowup in `refine` in evar creation, where I calculated that my single refine would run for about 2^99 seconds.

I expect sane behavior from `refine`, less so from `cbn`.

@rnrand I see three ways for you to work around this:
1. use `cbv [H]` instead of `unfold H`.  Or even `cbv delta [H]`.  I did not understand your comment about not being able to use `cbv` here.
2. Make the evars non-dependent.  Typically I do this with `instantiate (?e := ltac:(clear <other evars>))`, but you can also do it with a combination of `unshelve evar (e : ...)`, `clear `, and `shelve `.
3. Unfold your evars earlier: replace `constr:(e :: ls)   ` with `let e' := (eval unfold e in e) in let na := match goal with _ => clear e end in constr:(e' :: ls)

**Comment by ejgallego** [comment] 2017-12-17 15:07
I think this still looks like a bug to me. Reduction should be smarter, no reason it takes O(n^2) when it could it in O(n).

**Comment by JasonGross** [comment] 2017-12-17 15:16
A question for the coq devs: why does cbn touch evars?  My naive expectation is that it should treat uninstantiated evars as opaque, rather than running cbn in their instances (is that what the thing like `@{ x := ... }` is called?).  Barring that, it should cache terms that its seen in instances and only cbn each such term once (having an exponentially sized instance is what's causing the issue, right?  In one order, each evar is unfolded before all the evars that mention it, and this is fast, while in the other order, each evar is unfolded after all the evars that mention it, and so there are an exponential number of occurrences to unfold in?)

**Comment by JasonGross** [comment] 2017-12-17 15:25
Oh, wait, does replacing `unfold H` with `unfold H in *` also fix the speed issue?

**Comment by herbelin** [comment] 2017-12-17 15:50
> why does cbn touch evars

That's a good question. As noticed at the time of #6455, there was no evar normalization in `cbv`. One point is that it was wrong because there was even no correct substitution of the environment of the abstract machine in the evars, but as noticed in this [comment](https://github.com/coq/coq/pull/6025#issuecomment-339762379), evaluating in the evar was "consum[ing] massive amounts of memory".

So, that's probably worth trying to have strong normalization not traversing evars in `cbn` (in `reductionops.ml`)!

**Comment by ppedrot** [comment] 2017-12-17 16:33
@Zimmi48 Actually, it seems that the *print all low-level info* option of CoqIDE activates the evar substitution flag. I thought it was the same as the Coq `Printing All` option.

**Comment by ppedrot** [comment] 2017-12-17 16:35
> So, that's probably worth trying to have strong normalization not traversing evars in cbn

It's probably worth insisting: the blowup here comes from the **kernel** reduction, **not** `cbn`.

**Comment by herbelin** [comment] 2017-12-17 17:39
> the blowup here comes from the kernel reduction, not cbn.

Ah, sorry if I disregarded this. But anyway, the question of why `cbv` and `cbn` should behave differently wrt strong reduction traversing evars remain (i.e. a question about whether `strong` and `local_strong` in `Reductionops` shouldn't prevent to recur in the evar instances).

**Comment by JasonGross** [comment] 2017-12-17 18:00
I am still confused, though.  Even if I use `cbn`, I still cannot reproduce the time-complexity behavior of `unfold`:
```
Ltac evar_list_nat n :=
  match n with
  | O => constr:(@nil nat)
  | S ?n' => let e := fresh "e" in
             let na := match goal with
                       | _ => evar ( e : nat )
                       end in
             let ls := evar_list_nat n' in
             constr:((e :: ls)%list)
  end.

Lemma test : exists (l : list nat), l = l.
  (let l := evar_list_nat 15 in exists l).
  Time repeat match goal with
              | [H : nat |- _ ] => progress (cbv [H] in *; cbn [H] in * ); idtac H
              end. (* 0.104 s *)
Abort.
Lemma test : exists (l : list nat), l = l.
  (let l := evar_list_nat 15 in exists l).
  Time repeat match goal with
              | [H : nat |- _ ] => progress unfold H in *; idtac H
              end. (* 1.306 s *)
```

**Comment by ppedrot** [comment] 2017-12-18 06:44
@JasonGross In your first example, the goal evars are not unfolded by `cbn`, so obviously you will not see any blowup. This is probably related to the issue @herbelin was mentioning, i.e. that `Reductionops` functions do not perform anything on evar instances.
