### ISSUE TITLE
Ltac2 trivial antiquotations should work in match branches

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16408] opened 2022-08-26 09:05 UTC
#### Description of the problem

This works:
```coq
Require Import Ltac2.Ltac2.

Ltac2 test1 () :=
  lazy_match! goal with
  | [ |- @id unit _ = _ ] => ()
  end.
```
This should work:
```coq
Ltac2 test2 (v : constr) :=
  lazy_match! goal with
  | [ |- @id $v _ = _ ] => ()
  end. (* Error: Unbound value v *)
```

cc @ppedrot 

#### Coq Version

8.15

**Comment by ppedrot** [comment] 2022-08-26 10:00
Duplicate of #13962

**Closed** 2022-08-26 10:00 UTC
Labels: kind: enhancement, part: ltac2
