### ISSUE TITLE
Anomaly when applying Sort module functor to wrong module

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#11878] opened 2020-03-22 17:10 UTC
#### Description of the problem

The following snippet throws an internal exception. The code is wrong anyway, but there should be a proper error message.

```coq
From Coq Require Import Sorting Orders OrdersEx.

Module NOTF := OT_to_Full N_as_OT.
Module NSort := Sort NOTF.
```

```
Anomaly "File "clib/int.ml", line 46, characters 14-20: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

For the record, a correct version is:

```coq
From Coq Require Import Sorting Orders OrdersEx.

Module NOTF := OT_to_Full N_as_OT.
Module NTTLB := OTF_to_TTLB NOTF.
Module NSort := Sort NTTLB.
```

#### Coq Version

Coq 8.11

**Comment by JasonGross** [comment] 2020-03-22 17:21
In 8.10, this gives a proper error message:
```
Error: The field leb is missing in foo.NOTF.
```

**Comment by ppedrot** [comment] 2020-03-22 23:17
Probably a duplicate of #11845.

**Comment by JasonGross** [comment] 2020-03-22 23:32
Seems likely, given that in 8.9 both of these give a "field is missing" error, while in 8.10 both anomaly in the same file

**Comment by JasonGross** [comment] 2020-03-22 23:32
Duplicate of #11845

**Closed by JasonGross** 2020-03-22 23:32 UTC
Labels: kind: regression, part: modules
