### ISSUE TITLE
Unsetting universe checking with universe polymorphism makes type checking fail

### ISSUE THREAD

**Issue by ionathanch** [coq/coq#17952] opened 2023-08-11 04:16 UTC
#### Description of the problem

With universe polymorphism on, turning universe checking off causes a definition to fail type checking, whereas with universe checking on, it succeeds. (This is a chunk of Hurkens' paradox.)

```coq
Set Universe Polymorphism.

Inductive Empty.

Definition P (S : Type) : Type := S -> Type.

Definition U : Type := 
 forall (x : Type), ((P (P x)) -> x) -> (P (P x)).

Definition tau (t : P (P U)) : U :=
  fun x f p => t (fun s => p (f (s x f))).

Definition sigma (s : U) : P (P U) := s U tau.

Definition Delta (y : U) : Type :=
  (forall (p : P U), sigma y p -> p (tau (sigma y))) -> Empty.

(* Unexpected behaviour *)

Unset Universe Checking.

Fail Definition Omega : U :=
  tau (fun p => forall (x : U), sigma x p -> p x).

(* Expected behaviour *)

Set Universe Checking.

Definition Omega : U :=
  tau (fun p => forall (x : U), sigma x p -> p x).
```

The failure message is:

```
Unsatisfied constraints:
hurkens.158 < hurkens.159
hurkens.159 < hurkens.159
hurkens.164 < hurkens.159
hurkens.159 <= hurkens.159 (maybe a bugged tactic).
```

I would expect turning universe checking off to override all universe constraint checks, polymorphic or otherwise.

#### Coq Version

8.17.0

**Comment by SkySkimmer** [comment] 2023-08-11 07:30
Fixed in master
Probably duplicate of https://github.com/coq/coq/issues/17472

**Closed by SkySkimmer** 2023-08-11 07:30 UTC
