### ISSUE TITLE
Deprecation warnings with 4.09

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#10819] opened 2019-10-03 13:23 UTC
Although the build succeeds it still prints warnings for the occurences in https://github.com/coq/coq/pull/10768/commits/8562093a2337643164670d59d397771b1c881e5b, see eg https://gitlab.com/coq/coq/-/jobs/310033912

**Comment by ejgallego** [comment] 2019-10-06 18:59
Isn't this a duplicate of #10602 ?

**Closed** 2019-11-07 13:20 UTC
