### ISSUE TITLE
"There are pending proofs" message does not mention the file

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#9404] opened 2019-01-25 08:21 UTC
Compiling a file which contains:

```coq
Goal True.
```

with coqc produces the following error message:
```coq
Error: There are pending proofs: Unnamed_thm
```

which does not say which file the error comes from.

**Comment by Alizter** [comment] 2021-11-27 00:25
Looking at the code, the error messages where the filename is mentioned have an explicit location so it can be printed. This error message is a `fatal_error` in `ccompile.v`. It does however have access to the filename, but is this something that is really needed.

Since you can use coqc for only one file at a time, it seems a bit pointless to add this information. Though I would be interested to hear what other @coq/toplevel-maintainers think.

**Comment by Zimmi48** [comment] 2021-11-29 11:18
>Since you can use coqc for only one file at a time, it seems a bit pointless to add this information.

I think the issue is that when you are using `make` to build a large project and you get a failure, if the error message of `coqc` doesn't point you to the failing file, then you have a hard time knowing which one it is.

**Comment by SkySkimmer** [comment] 2021-11-29 11:29
The obligations message does mention the file:
~~~
Error: Unsolved obligations when closing file /tmp/foo.v:
bar has unsolved obligations.
~~~

**Closed** 2021-11-30 12:31 UTC
Labels: kind: user messages, part: toplevel
