### ISSUE TITLE
Weird Setoid behavior

### ISSUE THREAD

**Issue by JonasOberhauser** [coq/coq#9730] opened 2019-03-09 00:06 UTC
#### Description of the problem

The following according to my understanding should work:
```
Require Import Morphisms Setoid.



Set Typeclasses Debug.

Variable Z : forall ts, Proper
         ((pointwise_lifting iff ts)  ==> (pointwise_lifting iff ts) ==> (pointwise_lifting iff ts))
         (pointwise_extension or ts).
Variable R : forall ts,  Equivalence (pointwise_lifting iff ts).

Existing Instance Z.
Existing Instance R.

Lemma test2 f g h i : 
pointwise_lifting iff (Tcons nat Tnil) f g  ->
pointwise_lifting iff (Tcons nat Tnil) h i  ->
  pointwise_lifting iff (Tcons nat Tnil) (pointwise_extension or (Tcons nat Tnil) f h) (pointwise_extension or (Tcons nat Tnil) g i).
intros A B.
rewrite A.
```
This should also work:
```
Require Import Morphisms Setoid.



Set Typeclasses Debug.




Variable X : relation nat.
Variable Op : binary_operation nat.

Goal (binary_operation nat = nat -> nat -> nat). eauto. Qed.

Variable Z : Proper
         (X  ==> X ==> X) Op.
Variable R : Equivalence X.

Lemma test f g h i : 
X f g  ->
X h i  ->
  X (Op f h) (Op g i).
intros A B.
rewrite A.
rewrite B.
```

The reason I expect them to work is that this works:
```
Require Import Morphisms Setoid.

Set Typeclasses Debug.

Variable X : relation nat.
Variable Op : nat -> nat -> nat.


Variable Z : Proper
         (X  ==> X ==> X) Op.
Variable R : Equivalence X.

Lemma test f g h i : 
X f g  ->
X h i  ->
  X (Op f h) (Op g i).
intros A B.
rewrite A.
rewrite B.
```

#### Coq Version

Coq 8.9 with windows 10 (and CoqIDE)

**Comment by JasonGross** [comment] 2019-03-09 01:10
Both of these succeed if you add
```coq
Hint Unfold binary_relation arrows : typeclass_instances.
```

The issue is that your instances are not resolving because the types don't match, and this tells typeclass resolution to allow them to be unfolded.

I'm inclined to resolve this as INVALID, but if you think this hint (or a similar one) should be in the standard library, or if you have a request about how the typeclass log should expose this information (without it needing to spend any extra time doing convertibility checking), feel free to rename this issue and make it about that.

**Comment by JonasOberhauser** [comment] 2019-03-09 01:16
Thanks so much! It's been very frustrating. I'll think about it.

**Closed** 2019-03-09 04:08 UTC
Labels: part: tactics, part: typeclasses, resolved: invalid
