### ISSUE TITLE
Hint Resolve 0%Z : Z

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#12547] opened 2020-06-19 16:51 UTC
In Coq 8.12beta1, 

This declaration is fine:  `Hint Resolve Z0 : Z.`
But this gives a deprecation message:   `Hint Resolve 0%Z : Z.`
```
Declaring arbitrary terms as hints is deprecated; declare a
global reference instead [deprecated-hint-constr,deprecated]
```
Somehow I thought that Z0 and 0%Z are exactly the same term; that Notation is fully transparent.

**Comment by andrew-appel** [comment] 2020-06-19 17:36
Furthermore, it appears that 

`Hint Resolve @foo : whatever.`

is now deprecated in Coq 8.12beta1.  **I protest.**  It's extremely useful to be able use "naked" terms as Hints (whether for resolve or rewrite), without any implicit arguments.

**Comment by JasonGross** [comment] 2020-06-19 17:53
Contrary to what it looks like, `Hint Resolve foo` has always(?) been using the naked term `@foo`, and if you wanted the implicits, you'd have had to write `Hint Resolve (foo)`

**Comment by andrew-appel** [comment] 2020-06-19 18:00
Somehow I don't believe the "always".  I've been using Coq for 15 years, and some number of years ago I found that I had to put in the @ signs.

**Comment by JasonGross** [comment] 2020-06-19 18:39
Indeed, the `@` signs are needed by `Hint Rewrite`

**Comment by andrew-appel** [comment] 2020-06-19 20:33
OK, I admit, it's true experimentally that the @ signs are not needed in Hint Resolve.  But I still claim that in these two cases,  (Notation and @), the deprecation warning is being more strict than necessary; in each case the Hint _is_ a global reference.

**Comment by Zimmi48** [comment] 2020-06-26 09:57
Can we consider this issue a duplicate of #11970?
Also note the current attempt at improving the situation at #12493.
But given the sheer number of protests from users, I think we have no choice but to backtrack on this deprecation for now if we don't find a solution that satisfies everyone...

**Closed by Zimmi48** 2020-06-26 09:57 UTC
