### ISSUE TITLE
Opam package for Coq 8.14+rc1 fails in a local switch in a directory containing a dune-project file 

### ISSUE THREAD

**Issue by jhjourdan** [coq/coq#14941] opened 2021-09-27 15:11 UTC
The following commands fail with the following messages:

```
$ cd ~
$ mkdir tmp
$ cd tmp
$ opam switch create . 4.12.1
[...]
$ touch dune-project
$ opam pin add coq 8.14+rc1 -y
[...]
[ERROR] The compilation of coq failed at "/home/jjourdan/.opam/opam-init/hooks/sandbox.sh build ./configure -configdir /home/jjourdan/tmp/_opam/lib/coq/config -prefix /home/jjourdan/tmp/_opam -mandir
        /home/jjourdan/tmp/_opam/man -docdir /home/jjourdan/tmp/_opam/doc -libdir /home/jjourdan/tmp/_opam/lib/coq -datadir /home/jjourdan/tmp/_opam/share/coq -coqide no -native-compiler no".

#=== ERROR while compiling coq.8.14+rc1 =======================================#
# context     2.0.8 | linux/x86_64 | ocaml-base-compiler.4.12.1 | pinned(https://github.com/coq/coq/archive/V8.14+rc1.tar.gz)
# path        ~/tmp/_opam/.opam-switch/build/coq.8.14+rc1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure -configdir /home/jjourdan/tmp/_opam/lib/coq/config -prefix /home/jjourdan/tmp/_opam -mandir /home/jjourdan/tmp/_opam/man -docdir /home/jjourdan/tmp/_opam/doc -libdir /home/jjourdan/tmp/_opam/lib/coq -datadir /home/jjourdan/tmp/_opam/share/coq -coqide no -native-compiler no
# exit-code   1
# env-file    ~/.opam/log/coq-161340-d2c37b.env
# output-file ~/.opam/log/coq-161340-d2c37b.out
### output ###
# Error: mkdir: _build: Read-only file system
[...]
```

I consider this as a major bug in the package, since using a local opam switch in another project main directory is a very common use case.

**Comment by ejgallego** [comment] 2021-09-27 15:13
Duplicate of #14915

**Closed by ejgallego** 2021-09-27 15:13 UTC
