### ISSUE TITLE
Inversion failure on (Some a = Some b), dependent on type of a/b

### ISSUE THREAD

**Issue by anishathalye** [coq/coq#6273] opened 2017-11-28 17:51 UTC
tl;dr: inversion fails on (Some a = Some b) when a is a member of an inductive type with a single constructor.

I tried this with Coq 8.6.1 on macOS, and it was an issue. On Coq 8.6 on Linux, it seemed to work okay.

#### Version

```
$ coqtop -v
The Coq Proof Assistant, version 8.6.1 (October 2017)
compiled on Oct 8 2017 20:34:24 with OCaml 4.05.0
```

#### Operating system

macOS 10.13.1

#### Description of the problem

```coq
Inductive foo := foo_1.

Goal
  forall (a b : foo),
    Some a = Some b ->
    a = b.
Proof.
  intros a b H.
  inversion H.
  (* strangely, this didn't work; we still have

  a, b: foo
  H : Some a = Some b
  -------------------------------
  a = b

  *)
Abort.

Goal
  forall T (a b : T),
    Some a = Some b ->
    a = b.
Proof.
  intros T a b H.
  inversion H.
  (* this works, when we're doing the proof for any type T *)
  subst.
  reflexivity.
Qed.

Inductive bar := bar_1 | bar_2.

Goal
  forall (a b : bar),
    Some a = Some b ->
    a = b.
Proof.
  intros a b H.
  inversion H.
  (* apparently, this one works too, when the type has more than one constructor *)
  subst.
  reflexivity.
Qed.
```

**Comment by herbelin** [comment] 2017-11-28 18:07
Hi @anishathalye,

The reason of the failure is a bit tricky: your inductive type `foo` is what is called a "singleton" type (one constructor whose arguments are themselves typed by singleton types or by propositions). In practice, singleton types are identified with propositions and `inversion` does not take into account inhabitants of propositions.

Actually, `inversion` calls `injection` and it is `injection` which does nothing. Calling `injection` shows how to circumvent the problem: `Set Keep Proof Equalities.`.

So the following shall work:
```coq
Inductive foo := foo_1.
Set Keep Proof Equalities.
Goal forall (a b : foo), Some a = Some b -> a = b.
Proof.
  intros a b H.
  inversion H.
```
Another workaround is to force `foo` to be tagged as non-singleton, as follows:
```coq
Inductive foo : Set := foo_1.
Goal forall (a b : foo), Some a = Some b -> a = b.
Proof.
  intros a b H.
  inversion H.
```
I believe we can improve a bit here. I shall think about how Coq could understand that you want `foo` to be considered here as a type and not as a proposition.

PS: Linux should work like MacOS X here.

**Comment by ppedrot** [comment] 2017-11-28 18:08
Duplicate of #3125.

**Closed** 2017-11-28 18:09 UTC

**Comment by Zimmi48** [comment] 2017-11-28 20:07
Duplicate of #3125

**Comment by Zimmi48** [comment] 2017-11-28 20:10
Duplicate of #3125.

**Comment by Zimmi48** [comment] 2017-11-28 20:11
Duplicate of #3125

**Comment by Zimmi48** [comment] 2017-11-28 20:13
Sorry for the redundant message. That was for testing the "marking as duplicate" feature of GitHub. It seems it is stupid enough to be inhibited by a simple dot. Will report.

**Comment by anishathalye** [comment] 2017-11-28 22:01
Sorry for the duplicate report, and thank you for the quick response and fix!
