### ISSUE TITLE
Unable to compile .vo files in Coqide 8.8.2

### ISSUE THREAD

**Issue by zunction** [coq/coq#9255] opened 2018-12-20 08:41 UTC
#### Version 
8.8.2

#### Operating system 
Windows

#### Description of the problem
I'm trying to `compile buffer` for the `.v` files for the materials in [Programming Language Foundations](https://www.seas.upenn.edu/~cis500/current/sf/plf-current/index.html) to get the `.vo` file for the import. However, it doesn't seem to work. Even using `make` to run the `Makefile` doesn't compile the buffer for the `.v` files.

Another questions is I'm unable to access `coq` through the command prompt. Please advice too.

Thanks :)

**Comment by gares** [comment] 2018-12-20 09:48
Duplicate of #5212

**Comment by gares** [comment] 2018-12-20 09:49
> ven using `make` to run the `Makefile` doesn't compile the buffer for the `.v` files.

I'm not sure I understand this part of your message.
Which `Makefile`? What do you expect it to do? (you seved your buffer to, say, a.v and you want to compile it?)

**Comment by SkySkimmer** [comment] 2018-12-20 10:18
The Language Foundations makefile.

**Comment by gares** [comment] 2018-12-20 13:22
My point is: ff it is the Makefile generated by coq_makefile, the bug is appropriate here. If it is not our Makefile, I don't think we've much to do with it.

**Closed** 2019-02-28 11:01 UTC
