### ISSUE TITLE
Extraction of function with arguments in empty types extracts in invalid right-hand side OCaml code.

### ISSUE THREAD

**Issue by Mbodin** [coq/coq#14482] opened 2021-06-10 16:05 UTC
#### Description of the problem

The following code is accepted by Coq, but produces invalid OCaml code.
```coq
Fixpoint test (a : nat) (x : False) : nat := test a (match x with end).

Require Import Extraction.

Recursive Extraction test.
```
Here is the extracted code:
```ocaml
type nat =
| O
| S of nat

(** val test : nat -> nat **)

let rec test =
  test
```
Which is rejected by OCaml with the following error: `Error: This kind of expression is not allowed as right-hand side of 'let rec'`.

I would have expected a term like
```ocaml
let rec test a =
  test a
```

#### Coq Version
8.13.2

**Comment by ppedrot** [comment] 2021-06-10 16:09
Duplicate of #10744

**Closed by ppedrot** 2021-06-10 16:09 UTC

**Comment by herbelin** [comment] 2021-06-11 10:50
An ugly but possible workaround that prevents the here-illegal eta-reduction:
```
Fixpoint test (a : nat) (x : False) : nat := let a := id a in test a (match x with end).
```
