### ISSUE TITLE
Anomaly when running guardedness checker 

### ISSUE THREAD

**Issue by tchajed** [coq/coq#7555] opened 2018-05-18 19:24 UTC
#### Version

```text
The Coq Proof Assistant, version 8.8+alpha (May 2018)
compiled on May 18 2018 14:55:55 with OCaml 4.06.0
```

master, a0da3a68d121

#### Operating system

macOS 10.13

#### Description of the problem

The following results in `Anomaly "grounding a non evar-free term"`.

```coq
Definition trivial : unit.
  Guarded.
```

This does still work, but just about any other use of `Guarded.` doesn't:

```coq
Definition trivial : unit.
  exact tt.
  Guarded.
```

Not fixed by #7449 or #7530.

**Comment by ppedrot** [comment] 2018-06-20 18:07
Duplicate of #7286.

**Closed by ppedrot** 2018-06-20 18:07 UTC
Labels: kind: anomaly
