### ISSUE TITLE
[bug report] setoid_rewrite: Invalid_argument("decomp_pointwise")

### ISSUE THREAD

**Issue by olaure01** [coq/coq#11347] opened 2019-12-30 17:05 UTC
#### Description of the problem

The following code raises:

> Anomaly "Uncaught exception Invalid_argument("decomp_pointwise")."

```
Require Import Setoid.

Parameter T : Type.

Parameter R : T -> T -> Prop.
Parameter Rb : T -> T -> bool.
Axiom RbR : forall n m, Rb n m = true -> R n m.

Parameter f : forall n m, R n m -> bool.
Axiom f_ext : forall n m h1 h2, f n m h1 = f n m h2.

Definition g n m :=
  (if Rb n m as b return _
   then fun h => f _ _ (RbR _ _ h)
   else fun _ => true) eq_refl.

Lemma test n m : g n m = true.
 unfold g.
 setoid_rewrite f_ext.
```

#### Coq Version

Coq 8.9.1 / 8.10.2 / 8.12+alpha (master)

**Comment by ppedrot** [comment] 2019-12-30 17:52
Probably a duplicate of #4617.

**Comment by SkySkimmer** [comment] 2023-06-06 11:42
It seems to dislike commutative cuts
~~~coq
Require Import Setoid.

Lemma foo
  (b:bool)
  (eC : Prop)
  :
  (if b
   then fun  (C :  Prop) => C
   else fun  (C :   Prop) => C)
    eC.
Proof.
  setoid_rewrite or_comm. (* or any lemma that can be used for rewriting *)
~~~

**Closed** 2023-09-08 08:55 UTC
Labels: kind: anomaly
