### ISSUE TITLE
Neither "make -j 12" nor "make -j 12 coqide" builds coqide

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14214] opened 2021-04-30 03:22 UTC
```
$ dune exec -- dev/shim/coqide-prelude
File "ide/coqide/coqOps.ml", line 701, characters 31-44:
Error: This expression has type
         (Doc.id * (unit, Doc.id) Util.union) Interface.value ->
         unit Coq.task
       but an expression was expected of type
         Interface.add_rty Interface.value -> 'a Coq.task
       Type Doc.id * (unit, Doc.id) Util.union is not compatible with type
         Interface.add_rty =
           Interface.state_id *
           ((unit, Interface.state_id) Interface.union * string)
       Type (unit, Doc.id) Util.union = (unit, Doc.id) CSig.union
       is not compatible with type
         (unit, Interface.state_id) Interface.union * string
File "ide/coqide/fake_ide.ml", line 243, characters 16-72:
Error: This expression has type Interface.add_rty Interface.value
       but an expression was expected of type
         (Document.id * (unit, Document.id) Util.union) Interface.value
       Type
         Interface.add_rty =
           Interface.state_id *
           ((unit, Interface.state_id) Interface.union * string)
       is not compatible with type
         Document.id * (unit, Document.id) Util.union
       Type (unit, Interface.state_id) Interface.union * string
       is not compatible with type
         (unit, Document.id) Util.union = (unit, Document.id) CSig.union
$ make -j 12
make --warn-undefined-variable --no-builtin-rules -f Makefile.build
make[1]: Entering directory '/home/proj/coq'
DUNE      sources
DUNE      _build/default/user-contrib/Ltac2/ltac2_plugin.cmxs
DUNE      _build/default/doc/tools/docgram/doc_grammar.exe
DUNE      revision
make[1]: Leaving directory '/home/proj/coq'
$ make -j 12 coqide
make --warn-undefined-variable --no-builtin-rules -f Makefile.build coqide
make[1]: Entering directory '/home/proj/coq'
DUNE      sources
make[1]: Nothing to be done for 'coqide'.
make[1]: Leaving directory '/home/proj/coq'
```

**Comment by Zimmi48** [comment] 2021-04-30 09:56
@jfehrle What the point of you opening bug report after bug report with problems that are impossible to reproduce. I just tried `dune exec -- dev/shim/coqide-prelude`, and as expected I got a working CoqIDE (only problem was the warning from #14181). Please consider writing good quality reports (i.e. actually reproducible) if you want them taken care of. Otherwise, everyone is just losing their time.

**Comment by Zimmi48** [comment] 2021-04-30 09:59
BTW, the targets `world` / `coqide` of the legacy (aka hybrid) build system also work. `_build/install/default/bin/coqide` is generated although it won't work without `-coqlib` until #14176 is merged.

**Comment by jfehrle** [comment] 2021-04-30 17:08
> We cannot know more without knowing if -coqide no was passed to configure.

Nope.

To reproduce, modify a CoqIDE file so it won't compile.

```
$ ./configure -local
You have OCaml 4.07.1. Good!
You have OCamlfind 1.8.1. Good!
You have native-code compilation. Good!
You have the Zarith library 1.12 installed. Good!
LablGtk3 and LablGtkSourceView3 found (3.1.1), with native threads:
=> native CoqIde will be built.

  Architecture                : Linux
  Sys.os_type                 : Unix
  Coq VM bytecode link flags  : -dllib -lcoqrun -dllpath "/home/proj/coqdune/coq/kernel/byterun"
  Other bytecode link flags   :
  OCaml version               : 4.07.1
  OCaml binaries in           : /home/jfehrle/.opam/4.07.1/bin/
  OCaml library in            : /home/jfehrle/.opam/4.07.1/lib/ocaml
  OCaml flambda flags         :
  Native dynamic link support : true
  Lablgtk3 library in         : /home/jfehrle/.opam/4.07.1/lib/lablgtk3-sourceview3
  CoqIde                      : opt
  Documentation               : None
  Web browser                 : firefox -remote "OpenURL(%s,new-tab)" || firefox %s &
  Coq web site                : http://coq.inria.fr/
  Bytecode VM enabled         : true
  Native Compiler enabled     : ondemand

  Local build, no installation...

If anything is wrong above, please restart './configure'.

*Warning* To compile the system for a new architecture
          don't forget to do a 'make clean' before './configure'.

$ make -f Makefile.dune world
dune build  coq-core.install coq-stdlib.install coqide-server.install coqide.install
File "ide/coqide/coqOps.ml", line 11, characters 0-4:
Error: Unbound constructor JUNK
      coqdep user-contrib/Ltac2/Env.v.d
*** Warning: in file Env.v,
    required library Init matches several files in path
    (found Init.v in ../../theories/Classes and .; used the latter)
      coqdep user-contrib/Ltac2/Ind.v.d
*** Warning: in file Ind.v,
    required library Init matches several files in path
    (found Init.v in ../../theories/Classes and .; used the latter)
Makefile.dune:87: recipe for target 'world' failed
make: *** [world] Error 1

$ make -j 12
make --warn-undefined-variable --no-builtin-rules -f Makefile.build
make[1]: Entering directory '/home/proj/coqdune/coq'
MKDIR     BUILD_VO
DUNE      sources
COQDEP    VFILES
DUNE      sources
COQCBOOT  _build_vo/default/theories/Init/Notations.v

     <SNIP several hundred lines compiling .v files>

make[1]: Leaving directory '/home/proj/coqdune/coq'

$
```

**Comment by ejgallego** [comment] 2021-06-17 20:41
Likely some transient bug, can't reproduce on master.

**Closed by ejgallego** 2021-06-17 20:41 UTC
Labels: part: build
