### ISSUE TITLE
Functional Induction throws unrecoverable error

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#11761] opened 2020-03-05 17:40 UTC
#### Description of the problem

The tactic `functional induction` can throw a typing error that is not recoverable within Ltac, i.e. it cannot be caught by `try`. Example:
```coq
Require Import FunInd.

Function f (n: nat):= n.

Goal True.
Fail try functional induction f True.
```
This is due to the peculiar syntax of the functional induction. Normally, this would be written as `functional induction (f True)`, but the tactic allows the parentheses to be left out. The problem occurs here:
https://github.com/coq/coq/blob/8fb4fdf4eb0e817412b749794494219597ce3153/plugins/funind/g_indfun.mlg#L98-L107
On line 104 a new term is created that is not type-checked. Eventually, the term ends up here:
https://github.com/coq/coq/blob/8fb4fdf4eb0e817412b749794494219597ce3153/tactics/tactics.ml#L4667
There the type is checked and an exception is thrown, which is of course not catchable within Ltac.
I would submit a pull request that adds the type checking but I'm not entirely sure which function is best for this...

#### Coq Version

The Coq Proof Assistant, version 8.11.0 (January 2020)

**Comment by Matafou** [comment] 2020-03-06 18:42
Hi, I can't reproduce this bug in master. all I see is expected:

- With neither `Fail` nor `try`: it fails.
- With only `try`: it does not fail.
- with `Fail try` it fails
- with only `Fail` it does not fail and says "The command has indeed failed with message"

Do you see something else?

**Comment by LasseBlaauwbroek** [comment] 2020-03-07 06:11
Yes, I should have checked on master, it is no longer reproducible there. Apparently the `type_of` function no longer throws an exception.  I would still recommend an extra explicit typecheck in the lines quoted above, if only for error consistency:
```coq
Require Import FunInd.

Function f (n: nat):= n.

Goal True.
Fail functional induction f True.
(* Illegal application: 
The term "f" of type "nat -> nat"
cannot be applied to the term
 "P" : "Prop"
This term has type "Prop" which should be coercible to "nat". *)
Fail functional induction (f True).
(*The term "True" has type "Prop" while it is expected to have type "nat". *)
```
The first error message talks about a term `P`, which is not really there. It should instead refer to `True` it seems.

**Comment by ejgallego** [comment] 2020-05-13 23:50
> . I would still recommend an extra explicit typecheck in the lines quoted above, if only for error consistency:

@Matafou , what do you think?

**Comment by Matafou** [comment] 2020-05-14 08:28
I agree. We should add a check or make the un-parenthesized version forbidden. For compatibility reason maybe the check is probably better.

**Comment by Matafou** [comment] 2020-05-15 12:47
Thanks. If this goes well I will also adapt then (undocumented) "soft functional induction" the same way.
Also if this goes merged, should I provide something in doc/changelog/ ?

**Closed** 2020-05-16 17:47 UTC
Labels: part: funind
