### ISSUE TITLE
congruence fails if universes differ, results in weird f_equal behavior

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#9979] opened 2019-04-23 00:23 UTC
```
Set Universe Polymorphism.

Record Map(K V: Type) := {
  rep: Type;
  put: rep -> K -> V -> rep;
}.

Section Test.
  Universes u1 u2 u3 u4 u5 u6.

  Goal forall K V (M: Map K V) (k: K) (v: V) (m: rep K V M),
      put@{u1 u2 u3} K V M m k v = put@{u4 u5 u6} K V M m k v.
  Proof.
    intros.
    Fail congruence.
    reflexivity.
```

Desired behavior: `congruence` should succeed and solve the goal.

Moreover, since `f_equal` calls `congruence`, the following

```
  Goal forall K V (M: Map K V) (k: K) (v1 v2: V) (m: rep K V M),
      put@{u1 u2 u3} K V M m k v1 = put@{u4 u5 u6} K V M m k v2.
  Proof.
    intros.
    f_equal.
```
results in

```
2 subgoals (ID 28)
  
  K : Type
  V : Type
  M : Map K V
  k : K
  v1, v2 : V
  m : rep K V M
  ============================
  K = K -> V = V -> M = M -> m = m -> k = k -> v1 = v2 -> put K V M m k v1 = put K V M m k v2

subgoal 2 (ID 19) is:
 v1 = v2
```

instead of just the second subgoal.

Coq version: Both master (424c1973e96dfbf3b2e3245d735853ffa9600373, Apr 1), and 8.9 are affected.

Might be the same as https://github.com/coq/coq/issues/5481.

Thx @JasonGross for helping me isolate the problem.
/cc @andres-erbsen

**Comment by ejgallego** [comment] 2019-04-23 00:42
You can try ssreflect `congr put` which will work for this case; dunno if an improvement in general.

**Comment by samuelgruetter** [comment] 2019-04-23 01:00
If I do `Require Import ssreflect.`, then `congr put` and `congr _` indeed works. Why does ssreflect's `congr` need an extra argument?

**Comment by samuelgruetter** [comment] 2019-04-23 01:10
The [documentation](https://coq.inria.fr/refman/proof-engine/ssreflect-proof-language.html#coq:tacn.congr) of `congr` says that it "may expand some definitions or fixpoints". This sounds dangerous from a performance point of view and I would not like to depend on this, but rather use a `congruence` which does not do any unfolding.

**Comment by ppedrot** [comment] 2019-04-23 06:53
AFAICT this really looks like a duplicate of #5481.

**Comment by ppedrot** [comment] 2019-05-05 16:48
Duplicate of #5481

**Closed by ppedrot** 2019-05-05 16:48 UTC
