### ISSUE TITLE
Can‘t use coqdep，coqdoc，and coqchk

### ISSUE THREAD

**Issue by freemyselfxx** [coq/coq#15809] opened 2022-03-15 08:07 UTC
When I entry coqdep，coqdoc，and coqchk,there are some error:
~~~
zxx@ubuntu:~/Program/l2c-master$ coqdoc
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 27, in <module>
    from CommandNotFound.util import crash_guard
ModuleNotFoundError: No module named 'CommandNotFound'
~~~
~~~
Coq Version
zxx@ubuntu:~/Program/l2c-master$ coqtop -v
The Coq Proof Assistant, version 8.14.1
compiled with OCaml 4.10.2
~~~

**Comment by Alizter** [comment] 2022-03-15 13:23
What happens when you call `coqdep --help`, `coqdoc --help` and `coqchk --help`? The first looks like a python exception which is pretty baffling. Can you provide some more information about your setup such as how you installed coq etc.

**Comment by ejgallego** [comment] 2022-03-15 15:34
That's just Ubuntu not finding the command in path, then trying to call a user-interface that suggest what package to install. `which coqtop` and `which coqdep` will be much more informative.

This doesn't seem like a Coq bug, but an install problem.

**Comment by JasonGross** [comment] 2022-03-15 15:36
The Python error is probably explained [here] (https://unix.stackexchange.com/a/9585/45323), this looks like you just don't have coqdep, coqdoc, and coqchk in your `PATH`, and possibly also that your Python situation is corrupted.  What does `coqc -config` print?  What about `which coqtop` and `ls "$(dirname "$(which coqtop)")"` and `ls -la "$(dirname "$(which coqtop)")"/coq*`?  Also, what Ubuntu setup are you using, and what's your terminal configuration?  (I'm also interested in the output of `uname -a`, `lsb_release -a`, `ps -p $$`, and `echo "$SHELL"`.)

**Comment by Alizter** [comment] 2022-03-15 15:37
@freemyselfxx I've closed the issue, but we can still help with your installation.

**Comment by freemyselfxx** [comment] 2022-03-16 01:31
> @freemyselfxx I've closed the issue, but we can still help with your installation.
Thank you for your attention.
I install coq by installing coq-cover. When I'm done executing this command “ sudo snap install coq-prover”，I run "coqc -v" as the following:
zxx@ubuntu:~$ coqc -v
The Coq Proof Assistant, version 8.14.1
compiled with OCaml 4.10.2
So, I think I have successfully installed coq. But I can't use coqdep.et, I was confused.

**Comment by freemyselfxx** [comment] 2022-03-16 01:43
>It's a bit long, Thank you for your attention, I just wanted to discuss it, but it seems to have been sent in the wrong place. I'm so sorry，o(*￣▽￣*)ブ.
(1) zxx@ubuntu:~$ echo $PATH
/home/zxx/Program/node-v12.18.4-linux-x64/bin:/home/zxx/Program/jdk1.8.0_311/bin:/home/zxx/.opam/4.02.1/bin:/home/zxx/bin:/home/zxx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/zxx/Program/fprime/fpp-main/compiler/bin:/home/zxx/Program/fprime/fprime-layout-main/bin
(2)zxx@ubuntu:~$ coqc -config
COQLIB=/snap/coq-prover/28/coq-platform/2022-01-0/lib/coq/
COQCORELIB=/snap/coq-prover/28/coq-platform/2022-01-0/lib/coq/../coq-core//
DOCDIR=/root/parts/coq/install/coq-platform/2022-01-0/doc/coq/
OCAMLFIND=/root/parts/coq/install/coq-platform/2022-01-0/bin/ocamlfind
CAMLFLAGS=-thread -rectypes -w +a-4-9-27-41-42-44-45-48-58-67-68-70   -safe-string -strict-sequence
WARN=-warn-error +a-3
HASNATDYNLINK=true
COQ_SRC_SUBDIRS=config lib clib kernel library engine pretyping interp gramlib parsing proofs tactics toplevel printing ide stm vernac plugins/btauto plugins/cc plugins/derive plugins/extraction plugins/firstorder plugins/funind plugins/ltac plugins/micromega plugins/nsatz plugins/ring plugins/rtauto plugins/ssr plugins/ssrmatching plugins/ssrsearch plugins/syntax
COQ_NATIVE_COMPILER_DEFAULT=no
(3)zxx@ubuntu:~$ which coqtop
/snap/bin/coqtop
(4)zxx@ubuntu:~$ ls "$(dirname "$(which coqtop)")"
coqc           coq_makefile       coq-prover.coqidetop     coqtop
coqide         coq-prover.coqc    coq-prover.coq-makefile
coqidetop.opt  coq-prover.coqide  coq-prover.coqtop
(5)zxx@ubuntu:~$ ls -la "$(dirname "$(which coqtop)")"/coq*
lrwxrwxrwx 1 root root 15 Mar 14 15:40 /snap/bin/coqc -> coq-prover.coqc
lrwxrwxrwx 1 root root 17 Mar 14 15:40 /snap/bin/coqide -> coq-prover.coqide
lrwxrwxrwx 1 root root 20 Mar 14 15:40 /snap/bin/coqidetop.opt -> coq-prover.coqidetop
lrwxrwxrwx 1 root root 23 Mar 14 15:40 /snap/bin/coq_makefile -> coq-prover.coq-makefile
lrwxrwxrwx 1 root root 13 Mar 14 15:40 /snap/bin/coq-prover.coqc -> /usr/bin/snap
lrwxrwxrwx 1 root root 13 Mar 14 15:40 /snap/bin/coq-prover.coqide -> /usr/bin/snap
lrwxrwxrwx 1 root root 13 Mar 14 15:40 /snap/bin/coq-prover.coqidetop -> /usr/bin/snap
lrwxrwxrwx 1 root root 13 Mar 14 15:40 /snap/bin/coq-prover.coq-makefile -> /usr/bin/snap
lrwxrwxrwx 1 root root 13 Mar 14 15:40 /snap/bin/coq-prover.coqtop -> /usr/bin/snap
lrwxrwxrwx 1 root root 17 Mar 14 15:40 /snap/bin/coqtop -> coq-prover.coqtop
(6)zxx@ubuntu:~$ uname -a
Linux ubuntu 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
(7)zxx@ubuntu:~$ lsb_release -a
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 25, in <module>
    import lsb_release
ModuleNotFoundError: No module named 'lsb_release'
(9)zxx@ubuntu:~$ ps -p $$
   PID TTY          TIME CMD
  3791 pts/17   00:00:00 bash
(10)zxx@ubuntu:~$ echo "$SHELL"
/bin/bash

**Comment by JasonGross** [comment] 2022-03-16 01:53
> ```
> zxx@ubuntu:~$ ls "$(dirname "$(which coqtop)")"
> coqc           coq_makefile       coq-prover.coqidetop     coqtop
> coqide         coq-prover.coqc    coq-prover.coq-makefile
> coqidetop.opt  coq-prover.coqide  coq-prover.coqtop
> ```

So it looks like `sudo snap install coq-prover` fails to install `coqdep` and `coqchk` and `coqdoc`?

**Comment by freemyselfxx** [comment] 2022-03-16 01:56
> > ```
> > zxx@ubuntu:~$ ls "$(dirname "$(which coqtop)")"
> > coqc           coq_makefile       coq-prover.coqidetop     coqtop
> > coqide         coq-prover.coqc    coq-prover.coq-makefile
> > coqidetop.opt  coq-prover.coqide  coq-prover.coqtop
> > ```
> 
> So it looks like `sudo snap install coq-prover` fails to install `coqdep` and `coqchk` and `coqdoc`?

So maybe I should uninstall and reinstall.

**Comment by ejgallego** [comment] 2022-03-16 02:22
I'd also suggest cleaning up your `~/.opam` folder if you can afford it.

**Comment by freemyselfxx** [comment] 2022-03-16 02:33
> I'd also suggest cleaning up your `~/.opam` folder if you can afford it.
I will have a try,thank you.(●'◡'●)

**Comment by silene** [comment] 2022-03-16 05:28
I confirm that the Snap package only provides commands for `coqc`, `coqide`, `coqtop`, `coq_makefile` (named `coq-makefile`), and `coqide.top`, be they prefixed by `coq-prover.*` or directly as aliases, as per instructed by the `snapcraft.yaml` file. Other commands need to be fully qualified, e.g., `/snap/coq-prover/28/coq-platform/2022-01-0/bin/coqdep`, or run through the `coq_wrapper` script, which also needs to be fully qualified.

So, reopening, as the issue is valid. But I suspect the answer might be that it was too costly to have the Snap package export all the Coq commands in the first place. Thus, you are not supposed to use these missing commands directly, but instead you should access them only through the Makefile created by `coq_makefile`.

**Comment by gares** [comment] 2022-03-16 06:42
That was my rationale in not exposing all commands indeed. see also https://github.com/coq/platform/issues/224

**Comment by Zimmi48** [comment] 2022-03-16 09:06
Let's still close this issue as a duplicate of coq/platform#224, no?

**Closed** 2022-03-16 09:15 UTC
Labels: part: installation

**Comment by freemyselfxx** [comment] 2022-03-17 01:45
Thank you for your attention. I try to install with "sudo apt-get install coq proofgeneral coqide", and I successfully installed.
