### ISSUE TITLE
Proposal: provide Docker images for stable and dev versions of Coq

### ISSUE THREAD

**Issue by erikmd** [coq/coq#8474] opened 2018-09-13 13:20 UTC
Dear Coq developers,

I'm opening this issue to report on some experiments I recently performed with Docker, using in particular the Docker Hub registry and Travis CI.

(I believe the Coq infrastructure already uses Docker, but only to cache Coq's dependencies and not to distribute Coq itself.)

The suggested idea would be to provide Coq users with official Docker images of Coq, for the stable versions as well as the latest `master`. This would enable at the same time:
1. the creation of Docker images for projects that rely on (several versions of) Coq and which may require a large compilation time (e.g., MathComp),
2. the use of such images in the CI of Coq-based projects, so that they can easily test-compile against stable and dev version of Coq using a Docker-compatible CI platform (e.g., Travis CI),
3. and the ability to easily fetch a Docker image to quickly do some tests with a given version of Coq  
   (in the same way as it suffices to execute `docker run --rm -it python:3.7.0-stretch` to fetch and run a Python3 toplevel).

There are still a couple of things to test, in particular the automatic build of `dev` Docker images by the CI that @CohenCyril would like to set up for MathComp, but a first version of this approach has already been implemented for testing the [validsdp](https://github.com/validsdp/validsdp) library w.r.t. Coq 8.7 and 8.8 (see e.g. this [Travis build](https://travis-ci.com/validsdp/validsdp/builds/83516637)).

A summary of these experiments is available at the following URL:
https://github.com/erikmd/coq-images/wiki/Testing-Docker-Hub-for-Coq  
(Feel free to react if you have remarks or questions on some items of this wiki)

**Comment by ejgallego** [comment] 2018-09-13 13:38
Hi @erikmd , this is mostly a duplicate of #7753

**Comment by erikmd** [comment] 2018-09-13 14:05
Thanks @ejgallego! I had missed that issue.
So I guess you'd prefer to discuss this rather in #7753… I will post a comment there.
Anyway, I'm happy that you already plan to distribute Docker images of Coq.

**Comment by Zimmi48** [comment] 2018-09-13 21:02
Indeed.

**Closed by Zimmi48** 2018-09-13 21:02 UTC
