### ISSUE TITLE
8.7 won't install from OPAM on OSX

### ISSUE THREAD

**Issue by ChinaXing** [coq/coq#6637] opened 2018-01-23 10:55 UTC
#### Version
8.7.0

#### Operating system

Darwin localhost 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

#### Description of the problem

opam install coq

and print following : 

```
[coq: ./configure no] Command started
+ ./configure "-configdir" "/Users/LambdaCat/.opam/system/lib/coq/config" "-mandir" "/Users/LambdaCat/.opam/system/man" "-prefix" "/Users/LambdaCat/.opam/system" "-usecamlp5" "-camlp5dir" "/Users/LambdaCat/.opam/system/lib/camlp5" "-coqide" "no" "-debug" (CWD=/Users/LambdaCat/.opam/system/build/coq.8.7.0)
- You have OCaml 4.06.0. Good!
- You have Camlp5 7.03. Good!
- You have native-code compilation. Good!
- CoqIde manually disabled:
- => no CoqIde will be built.
- 
-   Architecture                : Darwin
-   Coq VM bytecode link flags  : -custom
-   Other bytecode link flags   : -custom
-   OS dependent libraries      : -cclib -lunix
-   OCaml version               : 4.06.0
-   OCaml binaries in           : /usr/local/bin/
-   OCaml library in            : /usr/local/lib/ocaml
-   OCaml flambda flags         : 
-   Camlp5 version              : 7.03
-   Camlp5 binaries in          : /Users/LambdaCat/.opam/system/bin
-   Camlp5 library in           : /Users/LambdaCat/.opam/system/lib/camlp5
-   Native dynamic link support : true
-   CoqIde                      : no
-   Documentation               : None
-   Web browser                 : open %s
-   Coq web site                : http://coq.inria.fr/
- 
-   Paths for true installation:
-   - the Coq binaries will be copied in /Users/LambdaCat/.opam/system/bin
-   - the Coq library will be copied in /Users/LambdaCat/.opam/system/lib/coq
-   - the Coqide configuration files will be copied in /Users/LambdaCat/.opam/system/lib/coq/config
-   - the Coqide data files will be copied in /Users/LambdaCat/.opam/system/share/coq
-   - the Coq man pages will be copied in /Users/LambdaCat/.opam/system/man
-   - the Coq documentation will be copied in /Users/LambdaCat/.opam/system/share/doc/coq
-   - the Coq Emacs mode will be copied in /Users/LambdaCat/.opam/system/share/emacs/site-lisp
-   - the Coqdoc LaTeX files will be copied in /Users/LambdaCat/.opam/system/share/texmf/tex/latex/misc
```

after some ouputs.. it ends with following errors:

```
- install: revision: No such file or directory
- make[1]: [install-library] Error 71 (ignored)
- ./install.sh  "/Users/LambdaCat/.opam/system/lib/coq" tools/CoqMakefile.in tools/make-one-time-file.py tools/TimeFileMaker.py tools/make-both-time-files.py tools/make-both-single-timing-files.py
- ./install.sh  "/Users/LambdaCat/.opam/system/lib/coq" lib/clib.cmxa lib/lib.cmxa kernel/kernel.cmxa intf/intf.cmxa library/library.cmxa engine/engine.cmxa pretyping/pretyping.cmxa interp/interp.cmxa proofs/proofs.cmxa parsing/parsing.cmxa printing/printing.cmxa tactics/tactics.cmxa vernac/vernac.cmxa stm/stm.cmxa toplevel/toplevel.cmxa parsing/highparsing.cmxa  lib/clib.a lib/lib.a kernel/kernel.a intf/intf.a library/library.a engine/engine.a pretyping/pretyping.a interp/interp.a proofs/proofs.a parsing/parsing.a printing/printing.a tactics/tactics.a vernac/vernac.a stm/stm.a toplevel/toplevel.a parsing/highparsing.a 
- install -d "/Users/LambdaCat/.opam/system/lib/coq"/toploop/
- install ide/coqidetop.cmxs "/Users/LambdaCat/.opam/system/lib/coq"/toploop/
- install -m 644 META.coq "/Users/LambdaCat/.opam/system/lib/coq"/META
[ERROR] Installation of coq.8.7.0 failed
[coq: rm] Command started
+ rm "-R" "/Users/LambdaCat/.opam/system/lib/coq" (CWD=/Users/LambdaCat/.opam/system/build/coq.8.7.0)

#=== ERROR while installing coq.8.7.0 =========================================#
Some files in ~/.opam/system/install/coq.install couldn't be installed:
  - /Users/LambdaCat/.opam/system/build/coq.8.7.0/bin/coqtop.byte to /Users/LambdaCat/.opam/system/bin



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions failed
  ∗  install coq 8.7.0
No changes have been performed
'opam install --verbose coq' failed.
```

**Comment by Zimmi48** [comment] 2018-01-23 11:08
Version 8.7.0 of Coq is known to be incompatible with OCaml 4.06.0. Could you try again with version 8.7.1?

**Comment by ejgallego** [comment] 2018-01-23 11:13
> Version 8.7.0 of Coq is known to be incompatible with OCaml 4.06.0

That is not entirely correct, in theory only CoqIDE 8.7.0 should have problems with 4.06.0.

> - install: revision: No such file or directory
> - make[1]: [install-library] Error 71 (ignored)

So it seems that the `revision` file went MIA and that's making the build fail. Maybe the reporter is missing some needed tool?

**Comment by ChinaXing** [comment] 2018-01-24 07:39
update opam configure, and install coq 8.7.1, succeed.

**Comment by Zimmi48** [comment] 2018-01-24 15:12
So, if there was a bug in Coq 8.7.0 preventing `opam install coq` with OCaml 4.06.0, it has been fixed in 8.7.1 (thanks @ChinaXing for checking this).
And this bug didn't occur for everyone (I've just checked that `opam pin add coq 8.7.0` works for me with a 4.06.0 switch).
So I don't know what to do. If we could get someone to reproduce this we could decide whether it is a Coq bug or a packaging bug and chose how to update the OPAM package for 8.7.0 to reflect this.
Adding @RalfJung to the discussion since he's the OPAM package maintainer.

**Comment by RalfJung** [comment] 2018-01-24 16:08
I know nothing about Macs, so I don't think I can help here, sorry.

I'm not convinced the missing revision file is the problem, there's more `install` executed later.

**Comment by Zimmi48** [comment] 2018-01-24 16:19
Any Mac user around to replicate this?

**Comment by anton-trunov** [comment] 2018-01-24 17:04
Mac user here. I remember on one of my two Macs I had that glitch once.
I just tried installing Coq 8.7.0 with several combinations of dependencies:
- num.1.1 vs num.1.0
- ocamlfind.1.7.3-1 vs ocamlfind.1.7.3

But I cannot replicate it.

**Comment by Zimmi48** [comment] 2018-01-24 17:08
Thanks a lot @anton-trunov for testing.
If we can't reproduce this soon, we'll have no other choice than simply close the issue.

@ChinaXing Out of curisosity, can you still reproduce the error now by running `opam pin add coq 8.7.0`?

**Comment by cartazio** [comment] 2018-01-25 00:18
I hit this issue helping a colleague setup coq.
One possible variable is that brew was the installer for both opam and ocaml itself. I'm seeing if doing an opam switch will fix up  the environment. Additionally we are/were using fish shell.

**Comment by ChinaXing** [comment] 2018-01-25 05:37
yes, ocaml and opam are both installed by brew:

localhost ➜  client git:(5.7) ✗ brew list  | grep opam
opam
localhost ➜  client git:(5.7) ✗ brew list  | grep ocaml
ocaml
ocaml-num
ocamlbuild

does this the reason of failure when install 8.7.0?

**Comment by ChinaXing** [comment] 2018-01-25 07:02
opam pin add coq 8.7.0 succeed:)

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
⊘  removed   coqide.8.7.1
⊘  removed   verdi.dev
⊘  removed   coq-mathcomp-ssreflect.1.6.4
⊘  removed   InfSeqExt.dev
⊘  removed   cheerios.dev
⊘  removed   StructTact.dev
⊘  removed   coq.8.7.1+1
∗  installed coq.8.7.0
∗  installed InfSeqExt.dev
∗  installed StructTact.dev
∗  installed cheerios.dev
∗  installed coq-mathcomp-ssreflect.1.6.4
∗  installed verdi.dev
Done.

```

**Comment by Zimmi48** [comment] 2018-02-07 17:06
It seems that there were some issues with OPAM with system switches on macOS (see #11316) and they have been fixed recently (and the Coq package correspondingly). So I'm going to assume that this was what was causing this hard-to-reproduce bug. If someone can still reproduce the bug with after doing `opam update`, we'll reopen.

**Closed by Zimmi48** 2018-02-07 17:06 UTC
Labels: help wanted, kind: compatibility, needs: feedback, part: installation, platform: macOS
