### ISSUE TITLE
0.33 failed to regression build against ocaml 5.1.1

### ISSUE THREAD

**Issue by chenrui333** [coq/coq#18415] opened 2023-12-16 18:47 UTC
👋 while trying to upgrade ocaml to 5.1.1, ran into some regression build failure on the homebrew side:

```
opam
exec
--
opam
install
.
--deps-only
-y
--no-depexts

Constructing initial basis...
Number of 0-1 knapsack inequalities = 967
Constructing conflict graph...
Conflict graph has 289 + 77 = 366 vertices
The following actions will be performed:
  ∗ install dune          3.12.1
  ∗ install conf-gmp      4
  ∗ install ocamlfind     1.9.6
  ∗ install stdlib-shims  0.3.0
  ∗ install zarith        1.13
  ∗ install ocamlgraph    2.1.0
  ∗ install coq-core      8.18.0
  ∗ install coqide-server 8.18.0
  ∗ install coq-stdlib    8.18.0
  ∗ install coq           8.18.0
===== ∗ 10 =====

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
∗ installed conf-gmp.4
⬇ retrieved coq.8.18.0  (https://opam.ocaml.org/cache)
⬇ retrieved coqide-server.8.18.0  (cached)
⬇ retrieved coq-stdlib.8.18.0  (https://opam.ocaml.org/cache)
⬇ retrieved coq-core.8.18.0  (https://opam.ocaml.org/cache)
⬇ retrieved ocamlfind.1.9.6  (https://opam.ocaml.org/cache)
⬇ retrieved stdlib-shims.0.3.0  (https://opam.ocaml.org/cache)
⬇ retrieved ocamlgraph.2.1.0  (https://opam.ocaml.org/cache)
⬇ retrieved dune.3.12.1  (https://opam.ocaml.org/cache)
⬇ retrieved zarith.1.13  (https://opam.ocaml.org/cache)
∗ installed ocamlfind.1.9.6
∗ installed zarith.1.13
∗ installed dune.3.12.1
∗ installed stdlib-shims.0.3.0
∗ installed ocamlgraph.2.1.0
∗ installed coq-core.8.18.0
[ERROR] The compilation of coq-stdlib.8.18.0 failed at "make dunestrap COQ_DUNE_EXTRA_OPT=-split".
∗ installed coqide-server.8.18.0

#=== ERROR while compiling coq-stdlib.8.18.0 ==================================#
# context              2.1.5 | macos/arm64 | ocaml.5.1.1 | https://opam.ocaml.org#a4b48f40
# path                 /private/tmp/ott-20231216-70997-wi7vii/ott-0.33/.opam/default/.opam-switch/build/coq-stdlib.8.18.0
# command              /opt/homebrew/Library/Homebrew/shims/mac/super/make dunestrap COQ_DUNE_EXTRA_OPT=-split
# exit-code            2
# env-file             /private/tmp/ott-20231216-70997-wi7vii/ott-0.33/.opam/log/coq-stdlib-71459-b17707.env
# output-file          /private/tmp/ott-20231216-70997-wi7vii/ott-0.33/.opam/log/coq-stdlib-71459-b17707.out
### output ###
# [...]
# 42 |   (source_tree plugins))
# 43 |  (action
# 44 |   (with-stdout-to %{targets}
# 45 |    (run tools/dune_rule_gen/gen_rules.exe Coq theories %{env:COQ_DUNE_EXTRA_OPT=}))))
# [gen_rules] Fatal error: Invalid_argument("failed to locate Coq plugins in split build mode: coq-core.plugins.number_string_notation")
# Raised at Coq_dune__Coq_rules.FlagUtil.findlib_plugin_flags in file "tools/dune_rule_gen/coq_rules.ml", line 56, characters 6-89
# Called from Coq_dune__Coq_rules.FlagUtil.plugin_flags in file "tools/dune_rule_gen/coq_rules.ml" (inlined), line 59, characters 18-41
# Called from Coq_dune__Coq_rules.Context.make in file "tools/dune_rule_gen/coq_rules.ml", line 172, characters 25-56
# Called from Dune__exe__Gen_rules.main in file "tools/dune_rule_gen/gen_rules.ml", line 71, characters 13-109
# Called from Dune__exe__Gen_rules in file "tools/dune_rule_gen/gen_rules.ml", line 106, characters 6-13
# 
# make: *** [.dune-stamp] Error 1



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build coq-stdlib 8.18.0
└─ 
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install conf-gmp      4
│ ∗ install coq-core      8.18.0
│ ∗ install coqide-server 8.18.0
│ ∗ install dune          3.12.1
│ ∗ install ocamlfind     1.9.6
│ ∗ install ocamlgraph    2.1.0
│ ∗ install stdlib-shims  0.3.0
│ ∗ install zarith        1.13
└─ 
```

relates to https://github.com/Homebrew/homebrew-core/pull/157350

**Comment by ejgallego** [comment] 2023-12-17 23:32
It seems that your package setup for `coq-core` produces an incorrect findlib config, so coq-stdtlib cannot find the path to Coq plugins.

Highly likely to be a packaging bug.

**Comment by Ddystopia** [comment] 2023-12-24 11:33
I have the same issue on arch linux

**Comment by FedericoBruzzone** [comment] 2024-01-05 10:14
I also have the same problem on a Mac on Intel. I installed coq using homebrew.

**Comment by thief-sty** [comment] 2024-01-26 11:57
Having the same issue on Arch Linux, installing via opam.

**Comment by li3zhen1** [comment] 2024-02-05 00:04
Same issue on arm macOS. Installing via opam.

**Comment by Wankupi** [comment] 2024-02-23 03:31
Having the same issue on Arch Linux, installing via opam 2.1.5.
opam installed by pacman

**Comment by psilospore** [comment] 2024-02-25 17:20
@SkySkimmer I tried this on a few versions of coq (8.17.0, 8.18.0, 8.19.0). First time attempting to install via opam on arch.

```
opam install coq
The following actions will be performed:
  ∗ install coq-core      8.17.0  [required by coq]
  ∗ install coqide-server 8.17.0  [required by coq]
  ∗ install coq-stdlib    8.17.0  [required by coq]
  ∗ install coq           8.17.0*
===== ∗ 4 =====
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved coq.8.17.0  (cached)
⬇ retrieved coq-core.8.17.0  (cached)
⬇ retrieved coq-stdlib.8.17.0  (cached)
⬇ retrieved coqide-server.8.17.0  (cached)
Processing  5/12: [coq-core: dune build]
∗ installed coq-core.8.17.0
[ERROR] The compilation of coq-stdlib.8.17.0 failed at "make dunestrap COQ_DUNE_EXTRA_OPT=-split".
∗ installed coqide-server.8.17.0

#=== ERROR while compiling coq-stdlib.8.17.0 ==================================#
# context     2.1.5 | linux/x86_64 | ocaml.5.1.0 | https://opam.ocaml.org#90d8c520
# path        ~/.opam/default/.opam-switch/build/coq-stdlib.8.17.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make dunestrap COQ_DUNE_EXTRA_OPT=-split
# exit-code   2
# env-file    ~/.opam/log/coq-stdlib-3036-124564.env
# output-file ~/.opam/log/coq-stdlib-3036-124564.out
### output ###
# [...]
# 51 |   (source_tree plugins)
# 52 |   (source_tree user-contrib/Ltac2))
# 53 |  (action
# 54 |   (with-stdout-to %{targets}
# 55 |    (run tools/dune_rule_gen/gen_rules.exe Ltac2 user-contrib/Ltac2 %{env:COQ_DUNE_EXTRA_OPT=}))))
# [gen_rules] Fatal error: Invalid_argument("failed to locate Coq plugins in split build mode: coq-core.plugins.number_string_notation")
# Raised at Coq_dune__Coq_rules.FlagUtil.findlib_plugin_flags in file "tools/dune_rule_gen/coq_rules.ml", line 56, characters 6-89
# Called from Coq_dune__Coq_rules.Context.make in file "tools/dune_rule_gen/coq_rules.ml", line 171, characters 25-63
# Called from Dune__exe__Gen_rules.main in file "tools/dune_rule_gen/gen_rules.ml", line 72, characters 13-109
# Called from Dune__exe__Gen_rules in file "tools/dune_rule_gen/gen_rules.ml", line 107, characters 6-13
#
# make: *** [Makefile:124: .dune-stamp] Error 1



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build coq-stdlib 8.17.0
└─
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install coq-core      8.17.0
│ ∗ install coqide-server 8.17.0
└─
# Run eval (opam env) to update the current shell environment

The former state can be restored with:
    /usr/bin/opam switch import "/home/psilospore/.opam/default/.opam-switch/backup/state-20240225171629.export"
Or you can retry to install your package selection with:
    /usr/bin/opam install --restore
```

**Comment by psilospore** [comment] 2024-02-26 17:02
Hi @ejgallego I see this
```
❯ ocamlfind list | grep coq
findlib: [WARNING] Package findlib has multiple definitions in /usr/lib/ocaml/findlib/META, /home/psilospore/.opam/default/lib/findlib/META
findlib: [WARNING] Package bytes has multiple definitions in /usr/lib/ocaml/bytes/META, /home/psilospore/.opam/default/lib/bytes/META
coq-core            (version: n/a)
coq-core.boot       (version: dev)
coq-core.clib       (version: dev)
coq-core.config     (version: dev)
coq-core.coqworkmgrapi (version: dev)
coq-core.engine     (version: dev)
coq-core.gramlib    (version: dev)
coq-core.interp     (version: dev)
coq-core.kernel     (version: dev)
coq-core.lib        (version: dev)
coq-core.library    (version: dev)
coq-core.parsing    (version: dev)
coq-core.plugins    (version: n/a)
coq-core.plugins.btauto (version: dev)
coq-core.plugins.cc (version: dev)
coq-core.plugins.derive (version: dev)
coq-core.plugins.extraction (version: dev)
coq-core.plugins.firstorder (version: dev)
coq-core.plugins.funind (version: dev)
coq-core.plugins.ltac (version: dev)
coq-core.plugins.ltac2 (version: dev)
coq-core.plugins.micromega (version: dev)
coq-core.plugins.nsatz (version: dev)
coq-core.plugins.number_string_notation (version: dev)
coq-core.plugins.ring (version: dev)
coq-core.plugins.rtauto (version: dev)
coq-core.plugins.ssreflect (version: dev)
coq-core.plugins.ssrmatching (version: dev)
coq-core.plugins.tauto (version: dev)
coq-core.plugins.tutorial (version: n/a)
coq-core.plugins.tutorial.p0 (version: dev)
coq-core.plugins.tutorial.p1 (version: dev)
coq-core.plugins.tutorial.p2 (version: dev)
coq-core.plugins.tutorial.p3 (version: dev)
coq-core.plugins.zify (version: dev)
coq-core.pretyping  (version: dev)
coq-core.printing   (version: dev)
coq-core.proofs     (version: dev)
coq-core.stm        (version: dev)
coq-core.sysinit    (version: dev)
coq-core.tactics    (version: dev)
coq-core.top_printers (version: dev)
coq-core.toplevel   (version: dev)
coq-core.vernac     (version: dev)
coq-core.vm         (version: dev)
coqide-server       (version: n/a)
coqide-server.core  (version: dev)
coqide-server.protocol (version: dev)
```

**Comment by ejgallego** [comment] 2024-02-26 17:07
@psilospore what do `opam pin` and `opam switch` output?

I think the problem is that your opam switch somehow got broken.

**Comment by ejgallego** [comment] 2024-02-26 20:18
Indeed I'd suggest unpinning Coq, and seeing if that helps.

But creating a new switch will for sure be better, try `opam switch create 4.14.1` for example.

**Comment by thief-sty** [comment] 2024-02-27 00:37
Installing coq in a new switch (be it 4.14.1, or 5.1.0) fixed it for me. Thanks!

**Comment by ejgallego** [comment] 2024-02-27 14:24
Glad to hear you were able to fix things folks; I'm closing this issue for now, as it seems to me that it turned into a bit of a collect bin for issues.

If you think that documentation wasn't clear, please don't hesistate to open a new issue so we can improve the docs.

**Closed by ejgallego** 2024-02-27 14:24 UTC
Labels: needs: triage

**Comment by psilospore** [comment] 2024-02-29 00:33
Worked for me as well. Thank you for all your help!!!
