### ISSUE TITLE
Possible Bug in Positive Occurrence Checking within Inductive Definitions

### ISSUE THREAD

**Issue by rudynicolop** [coq/coq#13478] opened 2020-11-25 23:38 UTC
#### Description of the problem

Coq occasionally gives me the `Non strictly positive occurrence` error when I define relations over lists in an inductive definition, even though I avoid placing the defined term to the left of an `->` embedded within a hypothesis.

##### Example

_My editor prettifies certain symbols_. 

For the type:
```coq
Inductive tree : Set := Leaf | Branch (ts : list (ℕ * tree)).
```
Coq accepts:
```coq
Inductive tree_prop : tree → tree → ℙ :=                                           
  | tp_leaf : tree_prop Leaf Leaf                                                  
  | tp_branch (ts1 ts2 : list (ℕ * tree)) :                                        
      Forall2 (λ t1 t2 ⇒ tree_prop (snd t1) (snd t2)) ts1 ts2 →                    
      tree_prop (Branch ts1) (Branch ts2).
```
But Coq rejects:
```coq
Inductive tree_prop : tree → tree → ℙ :=
  | tp_leaf : tree_prop Leaf Leaf
  | tp_branch (ts1 ts2 : list (ℕ * tree)) :
      Forall2 (λ '(_,t1) '(_,t2) ⇒ tree_prop t1 t2) ts1 ts2 →
      tree_prop (Branch ts1) (Branch ts2).
```
Emitting the error message:
```
Error: Non strictly positive occurrence of "tree_prop" in
"forall ts1 ts2 : list (nat * tree),                                           
Forall2 (fun '(_, t1) '(_, t2) => tree_prop t1 t2) ts1 ts2 ->                 
 tree_prop (Branch ts1) (Branch ts2)".
```
It seems that performing pattern-matching results in the error whereas projecting with `snd` is fine.

This seems like a potential bug...?

Thanks!

#### Coq Version

```bash
The Coq Proof Assistant, version 8.12.0 (October 2020)
compiled on Oct 3 2020 22:43:06 with OCaml 4.10.0
```

##### Operating System
Mac
Version 10.15.7

**Comment by ppedrot** [comment] 2020-11-26 08:16
The positivity checker doesn't go under pattern-matchings, which implicity appear as the `'(_, t1)` binders in your inductive. As such, it is a duplicate of #1433. Note that this is not a bug since the algorithm is explicitly described as only going through dependent products.

**Comment by ppedrot** [comment] 2020-11-26 08:16
Duplicate of #1433

**Closed by ppedrot** 2020-11-26 08:16 UTC
