### ISSUE TITLE
lia fails in the presence of dependent hypotheses

### ISSUE THREAD

**Issue by xavierleroy** [coq/coq#10756] opened 2019-09-14 13:56 UTC
Coq version: 8.9.1

Here is a repro:
```
Require Import Arith Psatz Recdef.

Lemma bug (a b: nat) (bpos: b > 0) (ge: ~ a < b) (e: lt_dec a b = right ge):
  a - b < a.
Proof.
  intros.
  Fail lia. (* Tactic failure:  Cannot find witness. *)
  clear e. lia.  (* Success *)
Qed.
```
Apparently, it's the useless hypothesis `lt_dec a b = right ge` that causes problems, since by clearing it the problem goes away.  Note that `omega` has no problems with the extra hypothesis `e`.

Such hypotheses are often generated by `Function` and `Program`.  Actually the repro case above comes from the following example that I used in a lecture:
```
Function Euclid (a b: nat) (bpos: b > 0) {wf lt a} : nat * nat :=
  if lt_dec a b
  then (0, a)
  else let '(q, r) := Euclid (a - b) b bpos in (q + 1, r).
```

**Comment by xavierleroy** [comment] 2019-09-14 13:59
Could be related to #10707.

**Comment by thery** [comment] 2019-09-14 14:03
and hopefully fixed by #9856

**Comment by maximedenes** [comment] 2019-09-16 06:26
Isn't this a duplicate of https://github.com/coq/coq/issues/7886 ?

**Comment by xavierleroy** [comment] 2019-09-16 07:44
Yes it is a duplicate.  Sorry if I didn't check well enough for previous reports.

**Comment by ppedrot** [comment] 2019-09-16 09:34
Duplicate of #7886

**Closed by ppedrot** 2019-09-16 09:34 UTC
