### ISSUE TITLE
Copyright dates in the manual are "1999-1970" when building with Nix.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7378] opened 2018-04-28 14:09 UTC
Originally to be seen at https://coq.inria.fr/distrib/current/refman/

Now, you need to build the manual with Nix to observe this behavior.

**Comment by Zimmi48** [comment] 2018-05-26 14:51
This has been fixed in master and v8.8.

**Comment by ejgallego** [comment] 2018-05-26 15:06
Well, this was closed but the website is still wrong.

**Comment by maximedenes** [comment] 2018-05-26 15:06
@Zimmi48 how did you build it? This is a bug I've observed on NixOS, due to timestamp 0 being put on sphinx files. I'm surprised you don't have the same issue since you use NixOS too.

**Comment by Zimmi48** [comment] 2018-05-26 15:55
So indeed, I don't know how I did it, but I'm back to seeing "1999-1970" again :(

**Comment by Zimmi48** [comment] 2018-05-26 16:49
Actually I know where I had seen correct dates: in the GitLab artifacts. So just use the artifact instead of what you generate on your machine next time you upload the manual.

**Comment by maximedenes** [comment] 2018-05-26 16:50
Yes, in fact the deployment should be automated of course. I plan to do that once we move the website to a standard provider.

**Comment by Zimmi48** [comment] 2018-05-26 16:54
Could you create an issue (on the website repo) so that others are informed of this plan?

**Comment by Zimmi48** [comment] 2018-05-27 10:16
BTW, if the copyright dates are based on a timestamp, I'm having a hard time understanding what this is useful for:

https://github.com/coq/coq/blob/b2f746e41abf53fc481f90804ba4d70edd73fc86/doc/sphinx/conf.py#L74

**Comment by Zimmi48** [comment] 2018-06-29 08:36
Fixed as part of https://coq.inria.fr/distrib/V8.8.1/refman/ by using the artifact from GitLab CI.
However, I'd still like to understand whether using timestamps for this is a good idea and what is the purpose of the line quoted above.

**Comment by Zimmi48** [comment] 2018-09-09 21:45
cc @cpitclaudel FTR I still see "© Copyright 1999-1970, Inria." when building on NixOS loading dependencies using `nix-shell`. I don't know if it's reproducible on non-NixOS when loading dependencies using `nix-shell` or if it goes away on NixOS when installing Python packages using `pip` (have never tried yet).

**Comment by ejgallego** [comment] 2018-09-28 00:04
Is this fixed @Zimmi48 ? [Seems so]

**Comment by Zimmi48** [comment] 2018-09-28 08:49
This is a Nix-specific problem that is still there. The workaround is to use the artifact generated by GitLab CI.

**Comment by ejgallego** [comment] 2018-09-28 08:54
Ok so should we retitle the bug?

**Comment by ejgallego** [comment] 2018-09-28 08:54
Do we want a new tag for "Nix"?

**Comment by Zimmi48** [comment] 2021-07-11 08:23
@Alizter has found a related issue in the sphinx repo: sphinx-doc/sphinx#3451

However, this one talks about the use of `today` in `conf.py`. Our `conf.py` file doesn't use `today`. It contains:

https://github.com/coq/coq/blob/225339de7e15ba0e181fd0d291eb2d4c5c0cfff1/doc/sphinx/conf.py#L111

And this is what is used when building the manual as witnessed by the fact that it doesn't automatically update to the current year when we forget about it. However, if one sets the `SOURCE_DATE_EPOCH` variable (as is done inside `nix-shell`), then suddenly the "2021" part of the copyright notice is changed to use the date from this environment variable instead (this is stupid and shouldn't happen since we didn't ask for it). E.g. my `nix-shell` currently sets this variable to `315532800` and I get "1980" instead of "2021" in my local build. If I set this variable to `1` then I get "1970". And if I unset this variable, then finally I get the correct copyright notice to be used.

IMHO this is a real Sphinx bug (or misfeature) and not one that was reported before.

**Comment by cpitclaudel** [comment] 2021-07-11 13:16
https://github.com/sphinx-doc/sphinx/blob/4a2f5df9ba277f6ce2ad77812a57133a822758e9/sphinx/config.py#L394-L404

**Comment by Zimmi48** [comment] 2021-07-11 15:31
@cpitclaudel Thanks for digging into this even further!

**Closed** 2021-07-13 20:49 UTC
Labels: kind: documentation, needs: triage, platform: Nix
