### ISSUE TITLE
[ssr] Search Blacklist does not work

### ISSUE THREAD

**Issue by CohenCyril** [coq/coq#9061] opened 2018-11-23 16:17 UTC
#### Version
```
The Coq Proof Assistant, version 8.8.2 (November 2018)
compiled on Nov 4 2018 11:41:44 with OCaml 4.06.1
```

#### Operating system
`Linux [...] 4.14.79 [...]-NixOS SMP Sun Nov 4 13:52:51 UTC 2018 x86_64 GNU/Linux`

#### Description of the problem

The following script
```coq
Require Import ssreflect.
Add Search Blacklist "or".
Search or.
```
does not filter out lemmas whose name contain "or", while it works for `coq` "normal" `Search` https://coq.inria.fr/distrib/current/refman/proof-engine/vernacular-commands.html?highlight=search#coq:table.search-blacklist-string

Side note:  it was not obvious to me from the doc of coq that the commands are `Add Search Blacklist string` and `Remove Search Blacklist string` and not `Search Blacklist string`.

**Comment by maximedenes** [comment] 2018-11-28 21:48
AFAICT, this is a duplicate of #8663.

**Closed by maximedenes** 2018-11-28 21:48 UTC
