### ISSUE TITLE
Cannot destruct if/then/else generated by Program with dependent annotation

### ISSUE THREAD

**Issue by jad-hamza** [coq/coq#6916] opened 2018-03-05 15:27 UTC
#### Version

8.7.2

#### Operating system

Debian

#### Description of the problem

https://gist.github.com/jad-hamza/aee0a3d2ba8d8c312c34a7aa15f69192

When proving the obligations that are generated by `h`, I would like to do a case analysis depending on the branch of the match using destruct. But I obtain this error message:

```coq
Error: Abstracting over the term "b" leads to a term
fun b0 : bool =>
(if b0 as anonymous' return (anonymous' = b0 -> bool)
 then
  fun Heq_anonymous : true = b0 => f (i - 1) (h_obligation_1 i Heq_anonymous)
 else fun _ : false = b0 => false) eq_refl = true -> 
(i + 1 >? 0) = true
which is ill-typed.
Reason is: Illegal application: 
The term "h_obligation_1" of type
 "forall i : Z,
  let filtered_var := i >? 0 in true = filtered_var -> (i - 1 >=? 0) = true"
cannot be applied to the terms
 "i" : "Z"
 "Heq_anonymous" : "true = b0"
The 2nd term has type "true = b0" which should be coercible to
 "true = (i >? 0)".
```

Edit: the style is awkward here because this code is generated automatically by translation from another programming language to Coq

**Comment by cmangin** [comment] 2018-03-07 15:27
This issue was discussed on IRC.
One solution is to first generalize `h_obligation_1 i` in the type of `h`, you can then eliminate `i >? 0` in whichever way you want.

I guess I am closing this issue, as this is not a bug, merely a tricky part of dealing with this kind of errors. Don't hesitate to reply if needed though.

**Closed by cmangin** 2018-03-07 15:27 UTC
Labels: resolved: won't fix

**Comment by jad-hamza** [comment] 2018-03-07 15:30
@cmangin My hope was to find a general solution that enables me to destruct these dependent matches, without requiring me to inspect the details of the example. 

For normal if/then/else, I can do:
```coq

**Comment by cmangin** [comment] 2018-03-07 16:03
I don't think this is specifically related to the if/then/else being dependent. You could write the following (admittedly contrived) example:

```coq
Require Import Omega.

Open Scope bool_scope.
Open Scope Z_scope.

Parameter F : forall i, (i >? 0) = (i >? 0) -> bool.

Goal forall i,
  (if (i >? 0) then F i eq_refl
              else true) = true.
Proof.
  intros i.
  Fail destruct (i >? 0).
  generalize (F i).
  destruct (i >? 0).
Abort.
```

You could even omit the if/then/else altogether in this example, and it would still fail, because the problem comes from this `F` function (in your case, `h_obligation_1`), not from the if/then/else.

Maybe someone else knows better, but I don't think there is a 100% failproof solution to this.

**Comment by jad-hamza** [comment] 2018-03-07 19:04
I see, thank you. Where's a good place to learn about this and about why this is failing?

I found a workaround that worked for this case, but I'm not sure how well it will generalize. I hide the dependent match in `myMatch` and then prove a lemma that allows me to do a case analysis on `myMatch`. I guess the same case analysis can be done directly on the dependent match with `dep_match2` above.

https://gist.github.com/jad-hamza/d6f8ca8b5d101892114f5dcd6b5260ad
