### ISSUE TITLE
Bullets accepted outside proofs.

### ISSUE THREAD

**Issue by Matafou** [coq/coq#15152] opened 2021-11-09 15:16 UTC
#### Description of the problem

Bullets seem to be accepted as a prefix to any command, even outside proofs. This feels like a bug, although not critical.

```
$ coqtop
Welcome to Coq 8.13.2 (September 2021)
Coq < - Definition x := 0%nat.
x is defined
Coq < + Print nat.
Inductive nat : Set :=  O : nat | S : nat -> nat
Arguments S _%nat_scope
```

Note that `{` `}` are not accepted outside proofs.

#### Coq Version

8.13.2

**Comment by SkySkimmer** [comment] 2021-11-09 15:18
Duplicate of #12138

**Closed by SkySkimmer** 2021-11-09 15:18 UTC
