### ISSUE TITLE
[tactic] apply ... in ident^+

### ISSUE THREAD

**Issue by olaure01** [coq/coq#12165] opened 2020-04-24 07:34 UTC
A naive question: is there a reason (or a already a way to do it) not to consider the use of `apply ... in ...` with the simultaneous use of multiple hypotheses?
That is, following the [documentation](https://coq.inria.fr/refman/proof-engine/tactics.html#coq:tacn.apply-in), to move from `apply ... in ident` to `apply ... in ident,^+`.

**Comment by Zimmi48** [comment] 2020-04-24 10:23
I personally don't understand your `^+` syntax. Could you provide an example to be more specific on what you would expect?

**Comment by olaure01** [comment] 2020-04-24 10:43
Sorry `^+` is just LaTeX notation for exponent (I mean non-empty sequence of `ident`).
A concrete example:
```coq
Parameter A : Type.
Parameter P Q : A -> Prop.
Axiom PisQ: forall a, P a <-> Q a.

Lemma QfromP : forall a b c, (P a -> P b -> P c) -> Q a -> Q b -> Q c.
Proof.
intros a b c HP HQa HQb.
apply PisQ in HQa; apply PisQ in HQb. (* Here I would like: apply PisQ in HQa, HQb. *)
apply PisQ. (* maybe happy to factorize this as well, but not sure it is natural *)
now apply HP.
Qed.
```

**Comment by Zimmi48** [comment] 2020-04-24 10:56
Right, thanks for the explanation. We have our own DSL for writing this kind of syntax (used throughout the reference manual): `{+, @ident }`.

And thanks for the example, now I realize that this is in fact the same enhancement request that I opened myself about a year ago :smile:

**Comment by Zimmi48** [comment] 2020-04-24 10:56
Duplicate of #9816

**Closed by Zimmi48** 2020-04-24 10:56 UTC
