### ISSUE TITLE
Binder unbound in match

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#10096] opened 2018-10-12 05:51 UTC
Consider the following Ltac1 code:

```
Ltac destruct_ex_keepnames :=
  repeat match goal with
         | [ H: exists x, _ |- _ ] =>
           let x' := fresh x in destruct H as [x' H]
         end.

Goal forall (a: nat),
    (exists b, a = 2 * b) ->
    (exists b, a = 3 * b) ->
    (exists b, a = 6 * b).
Proof.
  intros a D2 D3.
  destruct_ex_keepnames.
```

It results in the following goal:

```
  a, b0 : nat
  D2 : a = 2 * b0
  b : nat
  D3 : a = 3 * b
  ============================
  exists b1 : nat, a = 6 * b1
```

Note that the two variables introduced by `destruct` are called `b` and `b0`, i.e. their name is based on the name used in `exists`.

**Question:** How can I achieve this in Ltac2?

Here's what I tried:

```
Require Import Ltac2.Ltac2.

(* "destruct h as [x y]"
destruct2 : ident -> ident -> ident -> unit
*)
Ltac2 destruct2 h x y :=
  let use := fun _ => None in
  let ic := [{
    Std.indcl_arg := Std.ElimOnIdent h;
    Std.indcl_eqn := None;
    Std.indcl_as  := Some (Std.IntroOrPattern
              [[Std.IntroNaming (Std.IntroIdentifier x);
                Std.IntroNaming (Std.IntroIdentifier y)]]);
    Std.indcl_in := None
  }] in
  destruct0 false ic use.

Ltac2 rec map f l :=
  match l with
  | h :: t => f h :: map f t
  | [] => []
  end.

Ltac2 hypnames () :=
  map (fun e => match e with (n, _, _) => n end) (Control.hyps()).

Ltac2 myfresh basename :=
  Fresh.fresh (Fresh.Free.of_ids (hypnames ())) basename.

Fail Ltac2 destruct_ex_keepnames () :=
  repeat (match! goal with
          | [ h: exists x, _ |- ?g ] =>
            let x' := myfresh x in
            destruct2 h x' h
         end).
```

(It's a bit more verbose because it seems I can't use the `destruct` notation, because when it constructs my `induction_clause` it wraps `h`, which is already an `ident`, inside yet another `ident:`, and because I had to implement Ltac1 style `fresh` in terms of a more basic `fresh`).

This prints

```
The command has indeed failed with message:
         Unbound value x
```

So it seems that I do not have access to the name of `x` inside the match branch, which is a loss of expressivity compared to Ltac1.

Of course I could do this:

```
Ltac2 destruct_ex_keepnames () :=
  repeat (match! goal with
          | [ h: exists x, _ |- ?g ] =>
            let x' := myfresh @x in
            destruct2 h x' h
         end).

Goal forall (a: nat),
    (exists b, a = 2 * b) ->
    (exists b, a = 3 * b) ->
    (exists b, a = 6 * b).
Proof.
  intros a D2 D3.
  destruct_ex_keepnames ().
```

but then I get the following goal:

```
  a, x0 : nat
  D2 : a = 2 * x0
  x : nat
  D3 : a = 3 * x
  ============================
  exists b : nat, a = 6 * b
```

which uses `x` and `x0` for the new variables, instead of `b` and `b0`.

Note: The reason I care about these names is *not* that I want to rely on auto-generated variable names, I know that this is bad practice :wink:. It is that I find goals with meaningful variable names much easier to read than goals where my variables are just called `x`, `x0`, `x1` etc. And another reason is for debugging: Before instantiating an existential in the goal, I'd like to print a debug message saying something like "instantiating b := 42".

**Comment by ppedrot** [comment] 2021-04-23 18:28
Duplicate of #10114

**Closed by ppedrot** 2021-04-23 18:28 UTC
Labels: part: ltac2
