### ISSUE TITLE
[Ltac2] Ltac2 equaivalent of Ltac1 is extremely slow (minutes vs. 1s)

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10379] opened 2019-06-16 12:59 UTC
I am trying to convert my Ltac1 automation stuff to Ltac2. It basically works and Ltac2 is really nice, but I have one issue which stops me from making progress: in some cases Ltac2 is terribly slow compared to Ltac1. I test this in CoqIDE (8.10 GTK3 version) and since CoqIDE also crunches for quite some time (alternatingly with coqidetop) it might also be a bug in CoqIDE, but I don't see what difference it would make for CoqIDE if I do stuff with Ltac1 or Ltac2. The resulting proof states are identical.

I attached two variants of a stripped down example from the VFA part of software foundations which show the effect - one for Ltac1 and one for Ltac2. They should both run without any VFA context. The example tactic is a stripped down variant of my tactic for destructing match arguments.

The Ltac1 variants runs through in hardly a second.
With Ltac2 it takes a short while until Ltac2 seems to have finished processing (I inserted some prints to monitor this) and then it takes about 2 minutes until the proof context is updated in CoqIDE. Also if I step over the congruence lines, each line takes another 2 minutes. (I still have to find out what the equivalent of all: is in Ltac2).

It would really help if someone could try if this is the same with other IDEs. This really doesn't make a lot of sense to me.

[vfa.zip](https://github.com/coq/coq/files/3294115/vfa.zip)

**Comment by ppedrot** [comment] 2019-06-16 13:27
Might be related to #10090.

**Comment by ppedrot** [comment] 2019-06-16 15:05
So indeed, a (contrived) duplicate of #10090. The reason was that Ltac2 destruct was calling induction instead due to a typo, leading to an explosive behaviour. See #10381.

**Closed** 2019-06-16 21:12 UTC
Labels: kind: performance, part: IDE, part: ltac2

**Comment by MSoegtropIMC** [comment] 2019-06-17 07:54
Thanks, with this fix it works well.
