### ISSUE TITLE
"Show Proof" generates Retyping.RetypeError anomaly

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12234] opened 2020-05-02 21:19 UTC
Adding "Show Proof" after the line `generalize H3; clear; induction l; simpl; auto.` in Lemma `filter_split` in `SetoidList.v` generates an anomaly.

Discovered using a modified coqc that automatically applies a Show Proof after every tactic, then verified in the official release. In my modified master, I also see this error appear when "Show Proof" is used after 140 tactics while building the standard library at these additional locations but no others:
- ChoiceFacts.v lines 1060-1069
- Rtopology.v lines 690-823

**Comment by jfehrle** [comment] 2020-05-02 21:19
```

Anomaly "Uncaught exception Retyping.RetypeError(_)."
Please report at http://coq.inria.fr/bugs/.
frame @ file "ide/protocol/xmlprotocol.ml", line 667, characters 29-46
frame @ file "ide/idetop.ml", line 442, characters 12-15
frame @ file "ide/idetop.ml", line 232, characters 13-28
frame @ file "stm/stm.ml", line 2698, characters 12-50
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 2687, characters 4-60
frame @ file "stm/stm.ml", line 2561, characters 4-105
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 1006, characters 6-10
frame @ file "stm/stm.ml", line 2420, characters 16-43
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/vernacinterp.ml", line 260, characters 6-284
frame @ file "vernac/vernacinterp.ml", line 262, characters 18-43
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
frame @ file "vernac/vernacinterp.ml", line 218, characters 20-60
frame @ file "vernac/vernacinterp.ml", line 45, characters 4-13
frame @ file "vernac/vernacentries.ml", line 2268, characters 29-50
raise @ unknown
frame @ file "lib/pp.ml", line 272, characters 31-68
frame @ file "lib/pp.ml", line 253, characters 14-29
frame @ file "list.ml", line 88, characters 20-23
frame @ file "printing/printer.ml", line 82, characters 27-71
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 903, characters 21-204
raise @ unknown
frame @ file "interp/constrextern.ml", line 627, characters 8-15
frame @ file "interp/constrextern.ml", line 619, characters 17-37
frame @ file "interp/constrextern.ml", line 579, characters 19-43
frame @ file "interp/constrextern.ml", line 592, characters 49-73
frame @ file "interp/constrextern.ml", line 592, characters 49-73
raise @ unknown
raise @ file "camlinternalLazy.ml", line 34, characters 4-11
frame @ file "camlinternalLazy.ml", line 27, characters 17-27
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 913, characters 27-57
frame @ file "interp/constrextern.ml", line 952, characters 15-76
frame @ file "clib/cList.ml", line 414, characters 4-18
frame @ file "clib/cList.ml", line 406, characters 21-24
frame @ file "interp/constrextern.ml", line 1111, characters 17-43
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 909, characters 38-68
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 915, characters 14-55
frame @ file "interp/constrextern.ml", line 909, characters 38-68
frame @ file "interp/constrextern.ml", line 915, characters 14-55
frame @ file "interp/constrextern.ml", line 909, characters 38-68
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 915, characters 14-55
frame @ file "interp/constrextern.ml", line 903, characters 21-204
raise @ unknown
frame @ file "interp/constrextern.ml", line 627, characters 8-15
frame @ file "interp/constrextern.ml", line 619, characters 17-37
frame @ file "interp/constrextern.ml", line 579, characters 19-43
frame @ file "interp/constrextern.ml", line 579, characters 19-43
frame @ file "interp/constrextern.ml", line 592, characters 49-73
raise @ unknown
raise @ file "camlinternalLazy.ml", line 34, characters 4-11
frame @ file "camlinternalLazy.ml", line 27, characters 17-27
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 915, characters 14-55
frame @ file "interp/constrextern.ml", line 903, characters 21-204
raise @ unknown
frame @ file "interp/constrextern.ml", line 627, characters 8-15
frame @ file "interp/constrextern.ml", line 619, characters 17-37
frame @ file "interp/constrextern.ml", line 579, characters 19-43
frame @ file "interp/constrextern.ml", line 579, characters 19-43
frame @ file "interp/constrextern.ml", line 592, characters 49-73
raise @ unknown
raise @ file "camlinternalLazy.ml", line 34, characters 4-11
frame @ file "camlinternalLazy.ml", line 27, characters 17-27
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 909, characters 11-146
raise @ unknown
frame @ file "interp/constrextern.ml", line 627, characters 8-15
frame @ file "interp/constrextern.ml", line 619, characters 17-37
frame @ file "clib/cList.ml", line 414, characters 4-18
frame @ file "clib/cList.ml", line 406, characters 21-24
raise @ unknown
raise @ file "camlinternalLazy.ml", line 34, characters 4-11
frame @ file "camlinternalLazy.ml", line 27, characters 17-27
frame @ file "interp/constrextern.ml", line 909, characters 38-68
frame @ file "interp/constrextern.ml", line 966, characters 41-72
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 913, characters 27-57
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "interp/constrextern.ml", line 1067, characters 14-44
frame @ file "interp/constrextern.ml", line 923, characters 6-65
frame @ file "lib/dAst.ml", line 27, characters 12-25
raise @ file "camlinternalLazy.ml", line 34, characters 4-11
frame @ file "camlinternalLazy.ml", line 27, characters 17-27
frame @ file "pretyping/detyping.ml", line 768, characters 27-88
raise @ unknown
frame @ file "pretyping/detyping.ml", line 906, characters 18-64
frame @ file "pretyping/retyping.ml", line 202, characters 52-67
raise @ file "pretyping/retyping.ml", line 51, characters 22-44

```

**Comment by herbelin** [comment] 2020-05-03 06:18
Interesting test of robustness!

The cause is that `Show Proof` (`Vernacentries.show_proof`) is called with the wrong env. It is called with the environment of the 1st open subgoal, while it should be called with the environment of the initial goal extended with the side effects of the proof. In particular, section variables which have been cleared are missing.

@ejgallego is probably the specialist here. I guess it could take the same environment as `Qed` takes to register the proof (`Global.env()` + universes? + side effects?). At least, a better approximation would be `Global.env()` I believe.

#12233 is presumably a duplicate.

**Comment by SkySkimmer** [comment] 2020-05-03 08:48
See also https://github.com/coq/coq/issues/7622 (which I forgot why I closed)

**Comment by herbelin** [comment] 2020-05-03 09:16
> See also #7622 (which I forgot why I closed)

You closed it maybe we did not think it was a bug (at least, I did not realize at this time that the env used for `Show Proof` was indeed wrong). But indeed, this is a consequence of taking the wrong env.

**Comment by ejgallego** [comment] 2020-05-03 15:38
@herbelin analysis is correct.

**Closed** 2020-05-14 15:25 UTC
Labels: kind: anomaly
