### ISSUE TITLE
Anomaly "grounding a non evar-free term"

### ISSUE THREAD

**Issue by nlewycky** [coq/coq#8427] opened 2018-09-07 08:28 UTC
#### Version

master (eec96fbfe26a5c53bd1dcd7ca6a96bfa496fe686)

The Coq Proof Assistant, version 8.9+alpha (September 2018)
compiled on Sep 6 2018 23:01:06 with OCaml 4.05.0

#### Operating system
Debian unstable.

#### Description of the problem
```
Inductive list (X:Type) : Type :=
  | nil : list X
  | cons : X -> list X -> list X.

Arguments nil {X}.
Arguments cons {X} _ _.

Notation "x :: y" := (cons x y)
                     (at level 60, right associativity).
Notation "[ x ; .. ; y ]" := (cons x .. (cons y nil) ..).

Fixpoint fold {X Y: Type} (f: X->Y->Y) (l: list X) (b: Y)
                         : Y :=
  match l with
  | nil => b
  | h :: t => f h (fold f t b)
  end.

Definition fold_map {X Y: Type} (f: X -> Y) (l: list X) : list Y
:= fold (fun x l => (f x) :: l) l nil.

Compute fold_map fold_map (fun x => plus 3 x) [2;0;2].
Error: Anomaly "grounding a non evar-free term"
Please report at http://coq.inria.fr/bugs/.
```
Expected:
```
> Compute fold_map fold_map (fun x => plus 3 x) [2;0;2].
>                            ^^^^^^^^^^^^^^^^^
Error: The type of this term is a product while it is expected to be
 "list (?X -> ?Y)".
```

**Comment by ejgallego** [comment] 2018-09-07 13:47
Likely a duplicate of the quite a few bugs we have in this space #7538 #8155 #8224

There has been a pending patch that may solve this issue, but not yet integrated.

**Comment by gares** [comment] 2018-09-11 11:12
Duplicate of  #7538 #8155 #8224

**Comment by Zimmi48** [comment] 2018-09-11 11:28
This feature is horribly limited and useless basically you can only do:

**Comment by Zimmi48** [comment] 2018-09-11 11:28
Duplicate of #7538

**Comment by gares** [comment] 2018-09-12 12:03
Duplicate of #8155

**Comment by gares** [comment] 2018-09-12 12:03
Duplicate of #8224

**Comment by ejgallego** [comment] 2018-10-28 14:03
Duplicate information is incorrect here, this is only a duplicate of #8224

**Closed** 2018-11-02 20:43 UTC
Labels: resolved: duplicate
