### ISSUE TITLE
Hitting `default_evar_handler` when using a typeclass-resolved argument inside a `cofix`

### ISSUE THREAD

**Issue by Lapin0t** [coq/coq#18585] opened 2024-01-29 18:03 UTC
#### Description of the problem

The following snippet triggers an exception at the last line.

```
Class Foo := { identity {X : Type} : X -> X }.
Instance foo : Foo := {| identity _ x := x |} .

CoInductive loop := { obs : loop } .

CoFixpoint spin_ok1 := {| obs := identity spin_ok1 |} .
Definition spin_ok2 := cofix _spin := {| obs := @identity foo _ _spin |} .

Definition spin_bad := cofix _spin := {| obs := identity _spin |} .
```

It fails specifically when using an instance argument and inside a `cofix` expression.

Excerpt of the trace:
```
Error: Anomaly "File "kernel/constr.ml", line 1485, characters 26-32: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
Raised at Constr.default_evar_handler.(fun) in file "kernel/constr.ml", line 1485, characters 26-38
Called from CClosure.knht in file "kernel/cClosure.ml", line 1399, characters 18-53
Called from CClosure.knit in file "kernel/cClosure.ml", line 1516, characters 15-32
Called from CClosure.kni in file "kernel/cClosure.ml" (inlined), line 1514, characters 2-19
Called from CClosure.kh in file "kernel/cClosure.ml", line 1546, characters 34-54
Called from CClosure.whd_val in file "kernel/cClosure.ml" (inlined), line 1688, characters 41-59
Called from Reduction.whd_all in file "kernel/reduction.ml", line 32, characters 9-71
Called from Inductive.check_one_cofix.check_rec_call in file "kernel/inductive.ml", line 1486, characters 38-53
Called from Inductive.check_one_cofix.check_rec_call.process_args_of_constr in file "kernel/inductive.ml", line 1508, characters 22-73
Called from Inductive.check_cofix in file "kernel/inductive.ml", line 1577, characters 10-59
[...]
```

#### Coq Version

The Coq Proof Assistant, version 8.18.0, compiled with OCaml 4.12.1

**Comment by SkySkimmer** [comment] 2024-01-31 13:51
You can get a similar anomaly with `fix`:
~~~coq
Class Foo := { identity {X : Type} : X -> X }.
Instance foo : Foo := {| identity _ x := x |} .

Definition bad :=
  fix bad (x:nat) :=
  match x with
  | 0 => 0
  | S k => (bad (identity k))
  end.
~~~

**Comment by SkySkimmer** [comment] 2024-02-05 13:45
Duplicate of https://github.com/coq/coq/issues/18358

**Closed by SkySkimmer** 2024-02-05 13:45 UTC
