### ISSUE TITLE
assert_fails produces anomaly in Ltac2 

### ISSUE THREAD

**Issue by Ke-Duuuu** [coq/coq#19466] opened 2024-08-20 05:16 UTC
### Description of the problem

Running assert_fails in ltac2's ltac1 compatibility layer produces an anomaly:

> Error: Anomaly "print function not found for a value interpreted as ltac2:env."

### Small Coq file to reproduce the bug

```coq
Goal True. try (assert_fails idtac). (* this produces a proper error message *) Abort.
From Ltac2 Require Import Ltac2.
Set Default Proof Mode "Ltac2".
Goal True.
ltac1:(assert_fails idtac).
```

### Version of Coq where this bug occurs

8.19.2

**Comment by SkySkimmer** [comment] 2024-09-02 09:14
Works in master, probably duplicate of https://github.com/coq/coq/issues/18660

**Closed by SkySkimmer** 2024-09-02 09:14 UTC
Labels: kind: bug, needs: triage
