### ISSUE TITLE
Error: Anomaly "File "plugins/ltac/tacinterp.ml", line 1157

### ISSUE THREAD

**Issue by bollu** [coq/coq#7778] opened 2018-06-11 19:20 UTC
#### Version
```
Using Coq v8.7.2
```

#### Operating system
Linux (Ubuntu 16.04)

#### Description of the problem
Consider the proof script
```coq
Lemma foo: 1 = 2.
Proof.
  do 1! [
       match goal with
       | [|-  ?X ] => idtac
       end
     ].
 Abort.
```

This gives me the error:
```
Error:
Anomaly
"File "plugins/ltac/tacinterp.ml", line 1157, characters 35-41: Assertion failed."
Please report at http://coq.inria.fr/bugs/.

```

**Comment by ppedrot** [comment] 2018-06-11 20:09
Duplicate of #2800.

**Closed by ppedrot** 2018-06-11 20:09 UTC

**Comment by maximedenes** [comment] 2018-06-11 20:51
So what can we tell our users? To try out Ltac2? Or that we are working on a fix of #2800?

**Comment by ppedrot** [comment] 2018-06-11 20:55
I think we can use the fix proposed in #2800 by @Zimmi48 (IIRC). It's probably wrong w.r.t. composite types like `option tactic` but this is rare enough to be tolerable, and there is Ltac2 anyways knocking on the door.

**Comment by bollu** [comment] 2018-06-11 21:02
@ppedrot Could you explain the issue to me? I do not understand what #2800  is trying to say. Does it mean that tactics written in ML (which I assume `do` is one of) cannot take things like `match goal ...` as a parameter? Or am I wildly mis-understanding?

**Comment by ppedrot** [comment] 2018-06-11 21:20
@bollu No, you're right. There is a notion of syntactic non-value-like stuff in Ltac, and the ML notations break a dynamic invariant because Ltac semantics is a mess.
