### ISSUE TITLE
OSX version 8.7.1 crashes very easily

### ISSUE THREAD

**Issue by tdunning** [coq/coq#6525] opened 2017-12-31 06:19 UTC
CoqIDE 8.7.1

#### Operating system
OSX 10.12.6

#### Description of the problem

I downloaded CoqIDE and extracted it from the dmg

I ran the program by double-clicking CoqIDE in the dmg and also by dragging to Applications and double clicking there.

I can type into the *scratch* buffer. I can bring up help. It appears that I have a proofworker running.

When I try to paste into the *scratch* window, the program crashes.
When I type something into *scratch* and then select it using either the mouse or command-A, things go well. But attempting to copy the selected test crashes the IDE.

Copying or pasting crashes the program regardless of whether I use the keyboard shortcut or the menu item.

Program is unusable.

**Comment by Zimmi48** [comment] 2017-12-31 09:09
Thank you for the report.
This is a duplicate of #6509.

**Closed by Zimmi48** 2017-12-31 09:09 UTC
