### ISSUE TITLE
CoqIDE: double clicking to select a word

### ISSUE THREAD

**Issue by bcip** [coq/coq#11082] opened 2019-11-08 20:57 UTC
Word selection is not working properly on this version of CoqIDE. It effects in two cases, 1) double clicking to select a word for editing, and 2) use shortcut to show definition of an identifier. In previous versions, selecting word around `foo` in `apply Foo.foo.` will select `foo`, but in this version, it selects `Foo.foo.` including the dot at the end. To select the path `Foo.` may be good, the dot at the end should never be selected. This makes the second usage fails and I must manually select the word before checking for definition. And it is also not preferred for the first usage when editing code.

#### Coq Version

The Coq Proof Assistant, version 8.10.1 (October 2019)
compiled on Oct 25 2019 13:26:04 with OCaml 4.07.1

**Comment by silene** [comment] 2019-11-08 22:03
Duplicate of #11058.

**Closed by silene** 2019-11-08 22:03 UTC

**Comment by bcip** [comment] 2019-11-08 22:14
@silene I'm not sure whether https://github.com/coq/coq/pull/11069 has fixed this bug properly. I believe the problem is from the selection of a word. When selecting a word, the trailing dot shouldn't be included for both query and editing. Could you tell me whether it is fixed for both cases?

**Comment by silene** [comment] 2019-11-08 22:41
Yes.
