### ISSUE TITLE
Provide a way to dump all "global state" as text

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6887] opened 2018-03-02 10:41 UTC
#### Version

8.7.2

#### Operating system
Linux

#### Description of the problem

When failing to reproduce Coq issues in a minimal example, sometimes I have the suspicion that the issue is caused by a difference in the "global state" of Coq -- the state that stores options and other things that can be changed with vernaculars. By mere accident I learned about `Print Tables` (the name is not at all suggesting what this does, so it's pretty much impossible to find out about this even when looking at the docs), so what I do to rule out differences in this state is I `Print Tables` in both places and `diff` the result. However, it turns out that's not sufficient -- for example, I had to find out the hard way that the effect of `Generalizable All Variables` is not reflected in `Print Tabes`. That doesn't even [seem to be considered a bug](https://github.com/coq/coq/issues/6030#issuecomment-340228937).

So, this is a feature request to add some kind of printing command that actually prints *everything* that affects Coq behavior. This is kind of introspection is absolutely necessary to do reliable debugging.

**Comment by ejgallego** [comment] 2018-03-02 20:03
IMO I'd close this as "too vague".

The "global state" of Coq is nothing you want to really see as it is not geared towards human consumption and on the other hand it is really huge. I'd question its usefulness.

You can access Coq state using `Drop` or `SerAPI`. Indeed, I use `SerAPI` often for debugging, as for instance it can dump many internal tables in a convenient format.

**Comment by RalfJung** [comment] 2018-03-02 20:29
Well, I have no idea what kind of state I am talking about. Much of the state, like typeclass tables and such, already have commands showing it, so I don't literally mean "all state".  I mean "all options", except that some of the things I consider options are not considered options by Coq, like `Generalizable All Variables`. I don't know if there are any similar options. What I ask for is have all of that dumpable. There's only so many commands at https://coq.inria.fr/refman/command-index.html, so this state can't be *that* big.

If you want me to be less vague, I could ask concretely for "dumping all options plus the state of `Generalizable All Variables`" -- but there may well be other things that are like options but not really options. Only Coq exports could actually concretely express what they want here; I feel it's a bit unfair to ask that from a user.

**Comment by ejgallego** [comment] 2018-03-02 21:07
> there may well be other things that are like options but not really options.

There are all kind of objects in Coq state, really, the state is huge. I think you cannot approach that problem just like that.

For example, `Generalizable All Variables` is stored in the summary. Indeed, there are plans to serialize/query the summary, but we should discuss this in its proper issue.

I am still convinced that this functionality doesn't belong to Coq but to specific tools such as SerAPI.

**Comment by ejgallego** [comment] 2023-06-30 19:36
This seems stale, closing. Couple of comments:

- SerAPI can dump a lot of state, so that could be an option
- Please if you would like to reopen provide an actual use case were you are trying to debug a bug, as stated, the issue is too vague

**Closed by ejgallego** 2023-06-30 19:36 UTC
Labels: kind: feature
