### ISSUE TITLE
Anomaly "grounding a non evar-free term"

### ISSUE THREAD

**Issue by forestjulien** [coq/coq#8127] opened 2018-07-23 21:25 UTC
#### Version
master (git version 32415df7e24d4d79a00fae95a5f619980b006c61)

#### Operating system
linux (debian unstable)

#### Description of the problem
The following code : 

```
Require Import List.
Fixpoint fold f v0 (s:list (nat*nat)) :=
  match s with
  | nil => v0
  | (a,b)::s' =>
    fold f (List.fold_left f (a::b::nil) v0) s'
  end.
```

raises : 

Error: Anomaly "grounding a non evar-free term"
Please report at http://coq.inria.fr/bugs/.

**Comment by jashug** [comment] 2018-07-23 21:57
Possible duplicate of #7538

**Comment by ejgallego** [comment] 2018-07-24 09:16
> Possible duplicate of #7538

Spot on.

**Comment by ejgallego** [comment] 2018-07-24 09:17
duplicate of #7538

**Closed by ejgallego** 2018-07-24 09:17 UTC
Labels: kind: anomaly
