### ISSUE TITLE
./configure should explain better what incomplete lablgtk means

### ISSUE THREAD

**Issue by TimJSwan89** [coq/coq#6730] opened 2018-02-10 03:28 UTC
Similar to issue #6585 

#### Version

Building git sha `47e43e229ab02a4dedc2405fed3960a4bf476b58`.
```
$ coqtop -v
The program 'coqtop' is currently not installed. You can install it by typing:
sudo apt install coq
```

#### Operating system
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
#### Description of the problem
Essentially, `lablgtk.2.18.5` is reported successfully installed via opam, but the configure script reports that `LablGtk2` is not found.

Problem can be reproduced with all successful commands except the last here:
```
git clone https://github.com/coq/coq.git
cd coq/
sudo apt -y install opam
opam install Camlp5
sudo apt install gtk2.0
opam install LablGtk
./configure
```

Here are the results of the last two commands in that script:
```
$ opam install LablGtk
The following actions will be performed:
  ∗  install lablgtk 2.18.5

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lablgtk] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed lablgtk.2.18.5
Done.
$ ./configure
You have OCaml 4.03.1+dev0-2016-04-25. Good!
You have OCamlfind 1.7.3. Good!
You have Camlp5 7.03. Good!
You have native-code compilation. Good!
Incomplete LablGtk2 (via ocamlfind): no /home/timothy/.opam/4.03.0+k/lib/lablgtk2/gSourceView2.cmi.
No such directory '/home/timothy/.opam/4.03.0+k/lib/ocaml/lablgtk2' (in OCaml library).
LablGtk2 not found:
=> no CoqIde will be built.
```

**Comment by ejgallego** [comment] 2018-02-10 03:43
It seems you are missing the `lablgtk-extras` packages from OPAM. Indeed if that is the error message we should certainly improve it.

**Comment by ejgallego** [comment] 2018-02-12 21:17
I have checked install and indeed `lablgtk-extras` is correctly specified as a dependency.

**Comment by Zimmi48** [comment] 2018-02-13 08:49
That being said it would be great if `configure` was able to explain more clearly what is going on, no?

**Comment by ejgallego** [comment] 2018-02-13 13:43
I tried but didn't come upwith a mroe readable idea. Maybe:
```
Incomplete LablGtk2 (via ocamlfind): gSourceView2 was not found (expected at /home/timothy/.opam/4.03.0+k/lib/lablgtk2/gSourceView2.cmi.)
```

**Comment by Zimmi48** [comment] 2018-02-13 14:15
Reading this https://github.com/ocaml/opam-repository/issues/8135 (which is a very similar issue) and finding gSourceView2 in lablgtk and not lablgtk-extras, I now wonder how you concluded that the issue was that the lablgtk-extras package was missing. In fact, I just checked and I'm perfectly able to build CoqIDE without lablgtk-extras. I don't know where the belief that this is a dependency comes from.

**Comment by ejgallego** [comment] 2018-02-13 14:25
The belief comes from the `lablgtk` package having `conf-gtksourceview` in `depopts`, whereas `lablgtk-extras` has it as a hard requirement. Thus, the usual way to force the proper was to install `lablgtk-extras`.

I do agree that we could instead require `opam install conf-gtksourceview && opam install lablgtk` , but I guess the shorter version was preferred.

**Comment by TimJSwan89** [comment] 2018-02-13 14:28
Why was this marked with `invalid` label? Who's responsibility is it to mention `lablgtk-extras` as a requirement? `opam` or this project? I'm not sure, but I don't think the build feedback I received was good, so this issue should be useful. Doesn't `invalid` mean that the issue is wrong? What label do you put when you use the issue to report something wrong with the package manager?

**Comment by ejgallego** [comment] 2018-02-13 14:44
> Why was this marked with invalid label?

No answer in 3 days; it is not a bug in Coq but in your OPAM setup.

> Who's responsibility is it to mention lablgtk-extras as a requirement?

The dependency is correctly mentioned in the `INSTALL` file.

> Doesn't invalid mean that the issue is wrong?

Indeed, it is not a bug, but a user failing to install the documented required dependencies.

So far I see nothing wrong with the package manager. You are welcome to install `lablgtk-extras` [or `conf-gtksourceview` as @Zimmi48 suggested] and then reopen the issue if the problem still persists.

**Comment by ejgallego** [comment] 2018-02-13 14:46
> I don't think the build feedback I received was good

Well it clearly says "you are missing GtkSourceView" , so I wonder what more configure can do, apart from the minor rewording I suggested before.

**Comment by maximedenes** [comment] 2018-02-13 14:58
> No answer in 3 days

That was only one day, if you exclude non-working days (which you should). But I think closing with "invalid" label is fine regardless of the delay, if we believe there is no issue. Note that discussion can continue.

As for the issue itself, removing the `LablGtk2 not found` output in this situation (where it has been found but is incomplete) would probably induce less confusion.

Something that would be interesting to know is where you got the build instructions from, @TimJSwan89 , since it mentions `camlp5` but not `conf-gtksourceview` apparently.

**Comment by Zimmi48** [comment] 2018-02-13 15:04
> Something that would be interesting to know is where you got the build instructions from

Indeed, it would be useful for us to know that.

But there is no responsibility on the OPAM side either given that you are building Coq from sources, and not using OPAM. You are only using OPAM to install dependencies.

**Comment by Zimmi48** [comment] 2018-02-13 15:05
I want to add that the answer of @ejgallego might have sound harsh but we do absolutely value bug reports like this one, even when they end up being labeled as invalid. And as @maximedenes said, the discussion can continue as long as necessary.

**Comment by ejgallego** [comment] 2018-02-13 15:17
I don't see anything harsh in my first reply, neither in the second closing the bug by lack of response.

**Comment by TimJSwan89** [comment] 2018-02-13 16:17
```
I have checked INSTALL and indeed lablgtk-extras is correctly specified as a dependency.
```
```
Indeed, this issues is not a bug in Coq, but a user failing to install the documented required dependencies.
```
Ahh. That explains why it was labeled invalid. I didn't follow the instructions thoroughly enough when I was building the project.

**Comment by ejgallego** [comment] 2018-02-13 16:27
> That explains why it was labeled invalid. I didn't follow the instructions thoroughly enough when I was building the project.

Let us know if you found the `INSTALL` instructions unclear and how could we improve them

**Comment by TimJSwan89** [comment] 2018-02-13 16:44
I think my issue is valid as a problem somewhere. My original issue: 
```
Essentially, lablgtk.2.18.5 is reported successfully installed via opam, but the configure script reports that LablGtk2 is not found.
```
implies that, if nothing is wrong here, `opam` could be changed to provide the proper feedback. Should I report that to them or do you want to?

The fact that that contradictory statement was generated implies a bug somewhere. The bug does not depend on my response here or the state of my installation.

Sure, if the issue was "I cannot install opam," it would be invalid. But, "lablgtk.2.18.5 not recognized by configure" was the issue being reported, so how does my mistake of following instructions or response cause that report to be invalid? If someone, even someone else, does not have `lablgtk-extras` installed but does have `lablgtk.2.18.5` installed, then the script should report more than `LablGtk2 not found` and perhaps not even report that.

**Comment by ejgallego** [comment] 2019-02-10 23:03
This has gone away in the newer toolchain in particular in the GTK3 branch the test is not even there anymore. cc #9279

**Closed by ejgallego** 2019-02-10 23:03 UTC
Labels: kind: user messages, part: installation
