### ISSUE TITLE
Dune: "make clean" is required to switch from make to dune

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14193] opened 2021-04-27 22:46 UTC
As advertised in a recent email:

>One major consequence is that in principle, you should be able to switch between the dev modes of the two build systems (./configure -profile devel && make -j4 and make -f Makefile.dune world) without having to call make clean or git clean anymore.

Nope. This fails (at bottom).

Also, is `-local` still equivalent to `-profile devel`?  IIUC the former is commonly used in open source projects, would be nice to keep.

```
$ ./configure -profile devel
$ make -f Makefile.dune world
$ make -j 12
$ make -f Makefile.dune world
dune build  coq-core.install coq-stdlib.install coqide-server.install coqide.install
Error: Multiple rules generated for _build/default/META.coq-core:
- file present in source tree
- <internal location>
Hint: rm -f META.coq-core
Makefile.dune:89: recipe for target 'world' failed
make: *** [world] Error 1
```

**Comment by ejgallego** [comment] 2021-04-27 23:49
What you are doing is not supported; moreover it seems to me that you have some leftovers from a different tree.

It seems to me that this kind of questions are better asked in Zulip not in the bug tracker, as they are basic usability issues.

**Comment by Zimmi48** [comment] 2021-04-28 15:03
> Also, is `-local` still equivalent to `-profile devel`?

The latter includes a few more things, like making warnings fatal.

>What you are doing is not supported; moreover it seems to me that you have some leftovers from a different tree.

As I wrote in other places, I believe this is actually supported (it works for me). It's the leftovers from before pulling in the changes to the build system that are the problem.

**Comment by SkySkimmer** [comment] 2021-04-28 15:05
>The latter includes a few more things, like making warnings fatal.

Does that still work with dune? I think now it probably only impacts coq_makefile.

**Comment by Zimmi48** [comment] 2021-04-28 15:06
It was also used for warnings in the stdlib, wasn't it?

**Comment by jfehrle** [comment] 2021-04-28 15:36
> It's the leftovers from before pulling in the changes to the build system that are the problem.

No, this contradicts my example, in which I did a successful Dune build, a make and then a failing Dune build.  At the least, `make clean` or an equivalent should remove files extraneous files.  I spent a couple hours futzing with this yesterday while trying to get some work done.

**Comment by ejgallego** [comment] 2021-04-28 16:29
I can't reproduce, as pointed out before you seem to have some leftovers on the tree, while we could teach `make clean` to fix them, there are basically a ton of possibilities the tree could be arbitrarily dirty, thus hard to predict. Given that this kind of leftover problem is a one-time only thing I propose to close this one. Don't hesitate to open more bugs where this problem happens _from a clean tree_ . My build log:
```
$ ./configure -profile devel && make -f Makefile.dune world && make -j 8 && make -f Makefile.dune world
[...]
COQC      _build_vo/default/theories/setoid_ring/Rings_R.v
make[1]: se sale del directorio '/home/egallego/external/coq-master'
dune build  coq-core.install coq-stdlib.install coqide-server.install coqide.install
$ echo $?
0
```

**Closed by ejgallego** 2021-04-28 16:29 UTC
Labels: part: build

**Comment by Zimmi48** [comment] 2021-04-28 17:35
> > 
> 
> No, this contradicts my example, in which I did a successful Dune build, a make and then a failing Dune build. At the least, `make clean` or an equivalent should remove extraneous files. I spent a couple hours futzing with this yesterday while trying to get some work done.

I tested exactly this and it worked perfectly fine. It's likely that this was not all that you did and you had some leftover files.

**Comment by jfehrle** [comment] 2021-04-29 20:40
> I tested exactly this and it worked perfectly fine.

`./configure -profile devel./configure -profile devel` creates `META.coq`, `META.coq-core` and `revision`, all of which Dune complains about.  Perhaps you skipped that step?

`make clean` should remove these.

**Comment by ejgallego** [comment] 2021-04-29 21:00
@jfehrle that is strange, configure does not create any of these files, are you sure about it?

**Comment by jfehrle** [comment] 2021-04-29 21:30
My mistake.  It is the `make -j12` that creates it.  How about if we remove these files with `make clean`?

**Comment by jfehrle** [comment] 2021-04-29 21:31
Ah, it creates `_build/META*`.  Too many changes all at once.

**Comment by ejgallego** [comment] 2021-04-29 22:03
Yeah it is a bit of pain, but once we port the couple missing parts to create stuff under _build_vo / _build the problems with clean will be gone forever, just do rm -rf _build so the effort will pay off.

As a reminder, things that dirty the build tree:
- using Makefile.dune [nothing]
- using Makefile.make: sphinx build [fixing it very soon]; test-suite: will take a bit longer.

**Comment by jfehrle** [comment] 2021-04-29 22:41
On a slightly different topic: in developer builds, .vo files will have the associated .v file in the same directory?  It will be simpler for the debugger if this is true, otherwise it needs developer build-specific code to look in a different spot perhaps using a user-configured path.

**Comment by ejgallego** [comment] 2021-04-29 22:45
Yes, we are following the convention of placing a copy of .v files along the .vo files, tho in general Coq cannot locate .v files so any scheme is fragile for now.

**Comment by jfehrle** [comment] 2021-04-29 22:54
Just tweak the file path of the .vo file (some assembly required).  Almost done implementing that.

**Comment by ejgallego** [comment] 2021-04-29 22:59
> Just tweak the file path of the .vo file (some assembly required). Almost done implementing that.

Note that there are projects in the wild that use `coqc -o` + make to imitate hygienic builds , so in this case no approach will work 100%
