### ISSUE TITLE
Anomaly in SProp

### ISSUE THREAD

**Issue by patrick-nicodemus** [coq/coq#16982] opened 2022-12-11 02:46 UTC
Coq version 8.16.1, ocaml version 4.13.1
```
Record IsEquiv {A : Type} {B : Type} (f : A -> B) : Type := Build_IsEquiv
  { 
    equiv_inv : B -> A
  }.

Section StrictProp.
  Context (P Q : SProp).
  Context (P_to_Q : forall _ : P, Q).

Definition PQ_Equiv : IsEquiv P_to_Q.
```

last line gives error:
```
Error:
Anomaly
"File "kernel/inductive.ml", line 129, characters 19-25: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

**Comment by patrick-nicodemus** [comment] 2022-12-11 02:46
You can include or remove `Set Universes Cumulative`, it doesn't affect the error

**Comment by SkySkimmer** [comment] 2022-12-11 10:19
Duplicate of https://github.com/coq/coq/issues/16784

**Closed by SkySkimmer** 2022-12-11 10:19 UTC
Labels: part: kernel, kind: anomaly, part: SProp
