### ISSUE TITLE
Proof using Type includes letin variables even if they don't appear in the type

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#16953] opened 2022-12-07 15:49 UTC
#### Description of the problem

I often set `Default Proof Using "Type"`. However, it does not interact well with `Let` and setoid rewrite (which fails to use the `f_proper` lemma).

```coq
Require Import Morphisms Setoid.

(* removing the following line makes setoid_rewrite work *)
Set Default Proof Using "Type".

(* trivial PreOrder *)
Definition P (s t : unit) := True.

#[local] Instance P_preorder : PreOrder P.
Proof. constructor; repeat intro; apply I. Qed.

(* trivial function *)
Definition f (s: unit) : unit := tt.

Section MySection.

  Let dummy : unit := tt.

  #[local] Instance f_proper : Proper (P ++> P) f.
  Proof. intros ???. apply I. Qed.

  Lemma test (s t : unit) (E : P s t) : P (f s) (f t).
  Proof.
    clear dummy.
    now setoid_rewrite E. (* fails *)
    (*
    setoid rewrite failed: Unable to satisfy the following constraints:
    UNDEFINED EVARS:
    ?X16==[s t E |- relation unit] (internal placeholder) {?r}
    ?X17==[s t E (do_subrelation:=do_subrelation) |- 
            Proper (P ==> ?r) f] (internal placeholder) {?p}
    ?X19==[s t E |- relation unit] (internal placeholder) {?r0}
    ?X20==[s t E (do_subrelation:=do_subrelation)
            |- Proper (?r ==> ?r0 ==> Basics.flip Basics.impl) P]
            (internal placeholder) {?p0}
    ?X21==[s t E |- ProperProxy ?r0 (f t)] (internal placeholder) {?p1}
    TYPECLASSES:?X16 ?X17 ?X19 ?X20 ?X21
    SHELF:||
    FUTURE GOALS STACK:?X21 ?X20 ?X19 ?X17 ?X16||
    *)
  Qed.

End MySection.
```

#### Coq Version

The Coq Proof Assistant, version 8.16.0
compiled with OCaml 4.14.0

**Comment by SkySkimmer** [comment] 2022-12-07 15:54
same happens without Default Proof Using if you do
~~~coq
  #[local] Instance f_proper : Proper (P ++> P) f.
  Proof using Type. intros ???. apply I. Qed.
~~~

**Comment by SkySkimmer** [comment] 2022-12-07 16:07
simpler example:
~~~coq
Section S.

  Let x := 0.

  Definition foo : nat.
  Proof using Type. exact x. Qed.

  Goal nat.
    clear x.
    exact foo.
  Qed.
~~~

However note that 
~~~coq

Section S.

  Let x := 0.

  Definition bar : x = 0.
  Proof using Type. reflexivity. Qed.

  Goal False.
    clear x.
    pose proof bar.
    pose (x := 1).
    unfold x in H. clear x.
    inversion H.
  Qed.

End S.
~~~
should still fail at the "pose proof bar"

**Comment by JasonGross** [comment] 2022-12-07 16:52
Duplicate of #8153

**Closed by JasonGross** 2022-12-07 16:52 UTC

**Comment by JasonGross** [comment] 2022-12-07 16:56
> should still fail at the "pose proof bar"

This is not clear to me.  It seems plausible that instead what should happen is that any unavailable `let` binders should be delta-expanded when posing.  Perhaps better, though, would be to give context let binders the status of local definitions while the section is opened, and the ability to refer to them with a name qualified by the section.  So that clearing a let binder does not actually make it unavailable, it just shifts terms to using the named version, or something like that.
