### ISSUE TITLE
anomaly with unshelve open_constr pose proof

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#7951] opened 2018-06-28 15:55 UTC
#### Version

~~~~~
The Coq Proof Assistant, version 8.8.0 (May 2018)
compiled on May 3 2018 7:11:49 with OCaml 4.06.0
~~~~~

#### Operating system

Arch Linux, up to date as of today.

#### Description of the problem

~~~~~
Goal False.
  unshelve
  let e := open_constr:(_) in
  pose proof (@eq_refl nat e).
  (* Toplevel input, characters 0-69: *)
  (* > unshelve   let e := open_constr:(_) in   pose proof (@eq_refl nat e). *)
  (* > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ *)
  (* Error: *)
  (* Anomaly *)
  (* "File "plugins/ltac/tacinterp.ml", line 1053, characters 29-35: Assertion failed." *)
  (* Please report at http://coq.inria.fr/bugs/. *)
~~~~~

**Comment by SkySkimmer** [comment] 2018-06-28 16:04
OTOH this works fine
 ~~~coq
Goal False.
  unshelve
  (idtac;let e := open_constr:(_) in
  pose proof (@eq_refl nat e)).
~~~

**Comment by ppedrot** [comment] 2018-06-28 16:48
Duplicate of #2800.

**Closed by ppedrot** 2018-06-28 16:48 UTC
