### ISSUE TITLE
CoqIDE 8.14.0 does not recognize Γ or Δ

### ISSUE THREAD

**Issue by ianshil** [coq/coq#15257] opened 2021-11-29 01:09 UTC
I recently switched from CoqIDE 8.11.2 to 8.14.0, and in the latter symbols like Γ or Δ in  the .v files give the following error:

`Syntax Error: Lexer: Undefined token`

It seems that this error does not appear if one uses Proof General with coq version 8.14.0. So it must be a CoqIDE bug. Any way to fix this?

**Comment by ppedrot** [comment] 2021-11-29 07:41
I use these symbols on a daily basis with CoqIDE and never experienced this kind of problem. Furthermore, the error you mention comes from the Coq process, not the UI. So it'd mean that you have some issue with the Coq environment. Why it doesn't happen with PG is a mystery. Can you reproduce in a .v file?

**Comment by ianshil** [comment] 2021-11-29 23:33
Please excuse my ignorance and my poor diagnosis, I do not have a computer science background.

I use these symbols very often, and this problem never occurred before, hence my surprise when this happened. In any case, the .v file (called test.v) with this line only:

`Definition Γ := 3.`

gives me the following error (using coqc in the terminal): 

```
File "./test.v", line 1, characters 11-12:
Error: Syntax Error: Lexer: Undefined token 
```

Two things I noticed: 

1. CoqIDE does not complain when moving forward over these symbols, it is the compilation which fails.
2. When I close files containing such symbols and reopen them, these symbols are automatically replaced by their unicode (like \u0393 for Γ), and then CoqIDE does not move forward on lines containing these unicodes anymore.

It looks like my issue is very similar to #11526 (I am on macOS Monterey 12.0.1).

**Comment by ianshil** [comment] 2021-11-30 00:25
The issue #14447 might be of relevance too.

**Comment by ppedrot** [comment] 2021-11-30 07:26
> CoqIDE does not complain when moving forward over these symbols, it is the compilation which fails.

Ah, so you're actually saying that CoqIDE is corrupting your file when saving it. Can you check with another text editor that this is the case? That would explain the error at compilation. If the source is confirmed it's indeed a duplicate of #11526.

**Comment by ianshil** [comment] 2021-11-30 22:51
I created a file containing the only line "Γ0 Γ1 Δ0 Δ1" with Mac's TextEdit, saved it, closed it, reopened it, and the symbols did not get changed into their unicode.

**Comment by ppedrot** [comment] 2021-12-01 09:10
@ianshil I meant write this file with CoqIDE, save it, and open it with TextEdit.

**Comment by Zimmi48** [comment] 2021-12-01 17:28
You can also try the workaround that is now available at #11526 to confirm that it works for you too.

**Comment by ianshil** [comment] 2021-12-01 22:17
@ppedrot the symbols were replaced by their unicode in TextEdit. 

@Zimmi48 it works for me too! 

Thank you both.

**Comment by SkySkimmer** [comment] 2021-12-01 22:26
Let's close as duplicate of #11526 then

**Closed by SkySkimmer** 2021-12-01 22:26 UTC
Labels: part: IDE, needs: triage
