### ISSUE TITLE
destruct doesn't clear hypothesis if there is a section variable with the same name

### ISSUE THREAD

**Issue by whonore** [coq/coq#10649] opened 2019-08-10 00:06 UTC
#### Description of the problem

```
Section A.
Variable H : Type.
Goal True -> True.
Proof.
  clear.
  intros H.
  destruct H.
  Fail Fail destruct H.
Abort.
End A.
```

`H` is still in the context after `destruct H`. Without the `Variable H : Type` line `destruct H` clears `H`.

#### Coq Version

From 8.10 at least back to 8.5.

**Comment by ppedrot** [comment] 2019-08-10 08:54
Duplicate of #7518

**Closed by ppedrot** 2019-08-10 08:54 UTC
Labels: kind: bug

**Comment by whonore** [comment] 2019-08-10 16:23
I'm not sure this is exactly a duplicate of #7518 although the cause for the behavior may be the same. Unlike in #7518 I'm not trying to destruct a section variable (I've already cleared `H : Type` before introducing `H : True`), just a local one that happens to have the same name so I would expect `H` to be cleared as usual. It seems that maybe `destruct` decides whether to clear or not based on just the name regardless of if it is actually a section variable.

**Comment by ppedrot** [comment] 2019-08-10 18:08
@whonore Contrarily to proof-introduced hypotheses, clearing a section variable doesn't really clear it (at least not anywhere). This is a well-known evergreen issue in Coq. So what you see is a reflect of the implementation for the destruct algorithm that wrongly assumes that `H` is a section hypothesis.

**Comment by whonore** [comment] 2019-08-10 18:29
I see, thanks for explaining.
