### ISSUE TITLE
VST build broken in 8.8 / master

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7053] opened 2018-03-22 17:17 UTC
In 8.8, the file `veric/rmaps.v` seems to hang [still running after 30 minutes, in 8.7 it compiles almost instantly].

A bisect is needed.

**Comment by ejgallego** [comment] 2018-03-22 17:24
`coqc` hangs around this line:
```coq
  Axiom pre_rmap_core: forall A (m : f_pre_rmap A),
    exists P, core m = exist (valid' A) (core (proj1_sig m)) P.

End STRAT_MODEL.
```

**Comment by ejgallego** [comment] 2018-03-22 17:26
Command line to reproduce / bisect:

```
coqc -debug -stm-debug -Q msl VST.msl -Q sepcomp VST.sepcomp -Q veric VST.veric -Q floyd VST.floyd -Q progs VST.progs -Q concurrency VST.concurrency -Q ccc26x86 VST.ccc26x86 -Q wand_demo wand_demo -Q sha sha -Q fcf fcf -Q hmacfcf hmacfcf -Q tweetnacl20140427 tweetnacl20140427 -Q hmacdrbg hmacdrbg -Q aes aes -Q mailbox mailbox -R compcert compcert -time veric/rmaps.v
```

**Comment by ejgallego** [comment] 2018-03-22 18:46
So the problematic commit is 0ad26633a4589d77de1f864733d1d953dab9ea91:
```git
commit 0ad26633a4589d77de1f864733d1d953dab9ea91
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Sun Nov 19 22:53:28 2017 +0100

    Fix (partial) #4878: option to stop autodeclaring axiom as instance.
```
cc: @SkySkimmer

**Comment by ejgallego** [comment] 2018-03-22 18:50
@tchajed [comments](https://github.com/coq/coq/pull/6193#commitcomment-26201344) in #6193 are very relevant here:

> Why is this breaking change not documented anywhere? Our class's code was broken by this change and I had to bisect to find this.
> 
> The PR title is also misleading. It claims to fix a bug with an option to not auto-declare axioms as instances, but it actually changes the behavior of Coq and adds an option to restore the previous behavior.

IMHO this requires action before 8.8.0.

**Comment by Zimmi48** [comment] 2018-03-23 17:54
Thanks @ejgallego for your efforts in finding this issue but the result of your bisect tells me that this is not an actual regression. This is just bad and untested code. (That's just a guess, but I'm ready to bet a pint on it.)

Indeed, typeclass resolution is famous for being slow to fail when there are too many instances, even when it is fast to succeed. Here the change introduced by this commit means that some axiom that are automatically used as instances in 8.7 cease to be in 8.8. Thus, while the success with this instance might have been quick, without it is slow to fail.

My bet is more precisely that the fix is as simple as this: https://github.com/Zimmi48/VST/commit/b00b8ddff0e9491635fcc4c67e573e6d6761c585 (or something along those lines, as this is not yet tested).

**Comment by Zimmi48** [comment] 2018-03-23 18:00
Testing here: https://travis-ci.org/Zimmi48/coq/jobs/357515429

If my bet turns out to be right, it will just prove that once more, this was not a regression and we have lost time because VST just doesn't follow the rules to be in our CI: they don't test their code with Coq master before pushing to the branch we track while this is something that we explicitly request (cf. https://github.com/coq/coq/tree/master/dev/ci#information-for-external-library--plugin-authors).

**Comment by SkySkimmer** [comment] 2018-03-23 18:21
It's actually the next axiom, and I find `Declare Instance` to be cleaner.

**Comment by SkySkimmer** [comment] 2018-03-23 18:25
At the time vst was added (f29e577ef81e608cb8b3a68f4e171716c1280711), readme.ci said:
```

Travis CI provides a convenient way to perform testing of Coq changes
versus a set of curated libraries.

Are you an author of a Coq library who would be interested in having
the latest Coq changes validated against your development?

If so, keep reading! Getting Coq changes tested against your library
is easy, all that you need to do is:

1.- Put you development in a public repository tracking coq trunk.
2.- Make sure that your development builds in less than 35 minutes.
3.- Submit a PR adding you development.
4.- ?
5.- Profit! Your library is now part of Coq's continous integration!

Note that by partipating in this program, you assume a reasonable
compromise to discuss and eventually integrate compatibility changes
upstream.

Get in touch with us to discuss any special need your development may
have.
```
So they weren't expected to test with master and I don't think we notified them of the policy change (am I wrong?).

**Comment by Zimmi48** [comment] 2018-03-23 18:43
No, indeed, it's our job to notify them that they are not following the current policy. If you have tested your patch, can you submit it and close this issue? I'll take care of informing them about the CI policy.

**Comment by Zimmi48** [comment] 2018-03-24 07:37
I submitted https://github.com/PrincetonUniversity/VST/pull/160 for the fix as this was quite urgent. I'll open an issue to discuss their process later on.

**Comment by Zimmi48** [comment] 2018-03-25 20:55
The PR was merged. I'll still take care of the other step: notifying them of what our expectations are but this issue can already be closed.

**Closed by Zimmi48** 2018-03-25 20:55 UTC
Labels: kind: infrastructure, priority: blocker

**Comment by ejgallego** [comment] 2018-03-25 20:59
Thanks @Zimmi48

**Comment by ejgallego** [comment] 2018-03-25 21:02
We should definitively discuss more about CI in the next WG, IMHO given that our own CI is still not very stable it didn't make a lot of sense to push very hard requirements on users yet, but hopefully we manage to have a nice, "unlimited" CI setup soon and then we can indeed help 3rd party developers to achieve an improve CI setup.

[I write unlimited because for example right now we a not testing VST in full due to timeout limitations in our CI setup, that should hopefully be much improved with runners]

**Comment by Zimmi48** [comment] 2018-03-26 14:39
The shortcomings of our CI play no role in this story. The two occurrences when VST has pushed broken code have represented a huge time loss for several Coq developers investigating why, bisecting, communicating around this and considering whether this was a regression (this was your assumption in both cases) when it could have been used at more useful tasks (like improving the CI). Not counting the other developers who suddenly had to wonder why their PR was breaking VST (if they hadn't noticed this issue).
