### ISSUE TITLE
Variant breaks Scheme Equality

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7738] opened 2018-06-07 20:53 UTC
#### Version

8.8.0

#### Description of the problem

```coq
Variant Foo := foo | bar.
Scheme Equality for Foo.
(*
Error:
Unexpected error during scheme creation: Anomaly
                                         "Uncaught exception Type_errors.TypeError(_, _)."
Please report at http://coq.inria.fr/bugs/.
*)
```

**Comment by ppedrot** [comment] 2018-06-20 18:02
Duplicate of #6951.

**Closed by ppedrot** 2018-06-20 18:02 UTC
Labels: kind: anomaly
