### ISSUE TITLE
Parser inconsistently refuses inductive definition where the constructor has arguments with curly brackets

### ISSUE THREAD

**Issue by PierreCorbineau** [coq/coq#19638] opened 2024-10-03 11:42 UTC
### Description of the problem

The parser accepts the notBUGGY3 definition below, but refuses the BUGGY definition. 
These inductive definitions both contain curly braces {a:A} for constructor parameters.
The only difference is the presence or absence of the (optional) vertical bar before the first constructor specification.
One would expect both definitions to be treated similarly (both accepted ?).

### Small Coq file to reproduce the bug

```coq
(* These 3 definitions are accepted. *)

  Inductive notBUGGY1 (A:Type) :  Type :=
  | isnotBUGGY1 (a:A) : notBUGGY1 A.

  Inductive notBUGGY2 (A:Type) :  Type :=
    isnotBUGGY2 (a:A) : notBUGGY2 A.

  Inductive notBUGGY3 (A:Type) :  Type :=
  | isnotBUGGY3 {a:A} : notBUGGY3 A.

(* The definition below fails with
  Error: Syntax error: '.' expected after [gallina] (in [vernac_aux]).
*)

  Inductive BUGGY (A:Type) :  Type :=
    isBUGGY {a:A} : BUGGY A.
```

### Version of Coq where this bug occurs

8.19.1

**Comment by SkySkimmer** [comment] 2024-10-03 11:44
Duplicate of https://github.com/coq/coq/issues/17693

**Closed by SkySkimmer** 2024-10-03 11:44 UTC
Labels: kind: bug, needs: triage
