### ISSUE TITLE
File "kernel/safe_typing.ml", line 462, characters 2-8: Assertion failed.

### ISSUE THREAD

**Issue by bodoai** [coq/coq#18401] opened 2023-12-11 17:08 UTC
#### Description of the problem
Opening a Section and a Module

```
Section A.
Module B.

```
 leads to the following error message:

```
Anomaly
"File "kernel/safe_typing.ml", line 462, characters 2-8: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

##### output in coqide (Screenshot)
![Screenshot from 2023-12-11 18-01-28](https://github.com/coq/coq/assets/113357723/42bd9ce2-833b-423c-80cd-7f82fac8c9a1)

##### output in coqtop
```
$ coqtop
Welcome to Coq 8.18.0

Coq < Section A.

Coq < Module B.
Toplevel input, characters 0-9:
> Module B.
> ^^^^^^^^^
Error:
Anomaly
"File "kernel/safe_typing.ml", line 462, characters 2-8: Assertion failed."
Please report at http://coq.inria.fr/bugs/.

Coq < 

```

#### Coq Version

```
$ coqtop -v
The Coq Proof Assistant, version 8.18.0
compiled with OCaml 5.1.0

```
```
$ coqide -v
CoqIDE, version 8.18.0

```

**Comment by SkySkimmer** [comment] 2023-12-11 18:02
Duplicate of https://github.com/coq/coq/issues/18307

**Closed by SkySkimmer** 2023-12-11 18:02 UTC
