### ISSUE TITLE
Code duplication in checker and kernel

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#8678] opened 2018-10-08 16:57 UTC
While working with @vbgl on running coqchk on the test-suite and studying the bugs it revealed, we noticed that *a lot* of kernel bug fixes were never ported to coqchk. I'm not very familiar with the history of the checker. In particular, whether it was created by taking a snapshot of a subset of the kernel or not.

But today, AFAIK, `coqchk` does the same thing as Coq's kernel, except that it does not trust:
- functors
- sections
- VM / native_compute

and seems to check more things for universes at toplevel.

Maintaining a largely duplicated codebase is hard and costly, and of course the two codebases tend to diverge in uncontrolled way.

So why not provide instead a `coqc` flag (`--paranoid` or something like that), which would make the kernel behave like the checker today, while resolving the code duplication. Do experts like the idea? If yes, I could help with it.

**Comment by ejgallego** [comment] 2018-10-08 16:59
Well, you could start by factoring out the shared bits to a `KernelLib` maybe? I am not sure how much code is shared at the lower levels.

**Comment by maximedenes** [comment] 2018-10-08 17:07
> Well, you could start by factoring out the shared bits to a `KernelLib` maybe? I am not sure how much code is shared at the lower levels.

Right, that could be a good start. So removing the trick we did for `Names` (copying the sources)?

**Comment by ejgallego** [comment] 2018-10-08 17:11
Indeed, you could put the 4 files in the lib, and for sure a few more, going bottom-up should reveal the differences.

**Comment by SkySkimmer** [comment] 2018-10-08 17:13
checker univ.ml has some graph algorithm from before the current ugraph one
cclosure/reduction/typeops should be basically the same
no clue about module stuff
indtypes is different because the checker's input is different, inductive declarations have significant inferred data in them

**Comment by maximedenes** [comment] 2018-10-08 17:31
> no clue about module stuff

module stuff is significantly different but it is one of the areas where the checker does interesting things (defunctorialization)

> indtypes is different because the checker's input is different, inductive declarations have significant inferred data in them

right, but this is less satisfactory because it is still essentially doing the same things, and often not benefiting from kernel fixes (or inducing more work to port them)

**Comment by herbelin** [comment] 2018-10-08 18:55
> I'm not very familiar with the history of the checker. In particular, whether it was created by taking a snapshot of a subset of the kernel or not.

The checker was created by @barras by extracting code from the kernel. The idea was, obviously, to have a stand-alone checker, which could be used, e.g., for certification agencies being able to certify vo.

Up to some point, the idea was also that kernel changes were cross-(human)-checked by the checker maintainer(s).

On this last point, I don't know the plans of @mattam82, but the question is probably whether someone is willing to maintain the checker in the sense of independently validating (or not) kernel changes in the checker. If not, I guess that we can change the point of view and says that the checker is the stand-alone version of the kernel. Then, sharing code as much as possible between the kernel and the checker would be natural.

**Comment by ejgallego** [comment] 2018-10-08 19:03
> Then, sharing code as much as possible between the kernel and the checker would be natural.

We can also share a limited subset; for example we will soon have some support for "virtual" libraries, that is to say, interfaces that can be fulfilled by two different implementation. That could prove useful here.

**Comment by maximedenes** [comment] 2018-10-08 19:15
> The checker was created by @barras by extracting code from the kernel. The idea was, obviously, to have a stand-alone checker, which could be used, e.g., for certification agencies being able to certify vo.
> 
> Up to some point, the idea was also that kernel changes were cross-(human)-checked by the checker maintainer(s).
> 
> On this last point, I don't know the plans of @mattam82, but the question is probably whether someone is willing to maintain the checker in the sense of independently validating (or not) kernel changes in the checker. If not, I guess that we can change the point of view and says that the checker is the stand-alone version of the kernel. Then, sharing code as much as possible between the kernel and the checker would be natural.

Thanks @herbelin, that makes things clearer. We could try to go for sharing code, and in case anybody shows interest, base a new, independent checker on the Rust prototype for example. This way, we keep the current tool, which is valuable, while reducing the maintenance burden and leaving the door open for a more independent implementation.

**Comment by SkySkimmer** [comment] 2018-10-08 20:50
Checker folklore (I haven't seen this written down anywhere):
The checker links not against lib.cma (cmxa etc) but rather directly against the modules it needs (as stated in checker/check.mllib). This means for instance the checker is not linked against Spawn.
This peculiarity is not reproduced in the dune system.
(check.mllib does have some unecessary stuff (eg RemoteCounter) btw)

**Comment by ejgallego** [comment] 2018-10-08 21:15
> This peculiarity is not reproduced in the dune system.

I am aware of that; if that bothers you it can be fixed / reproduced.

**Comment by SkySkimmer** [comment] 2018-11-07 14:39
@maximedenes I'm closing this, feel free to reopen if there is some remaining duplication you want to remove.

**Closed by SkySkimmer** 2018-11-07 14:39 UTC
Labels: part: checker
