### ISSUE TITLE
"intros" invents surprising names needlessly

### ISSUE THREAD

**Issue by DanGrayson** [coq/coq#6589] opened 2018-01-15 19:33 UTC
#### Version 

8.7.1

#### Operating system 

Mac OS X

#### Description of the problem

This proof file:

```coq
Definition R := 1.
Lemma foo : forall (R:unit), unit.
  intros.
```

produces this state:

```
1 subgoal (ID 2)
  
  R0 : unit
  ============================
  unit
```

 , where `R0` is a surprising name.  It would be better not to violate the common-sense expectation of the user and to always use the declared name, which is `R` in this case.  That this is possible is shown by the behavior of automatic introduction, which does use the name `R` in this case.

**Comment by SkySkimmer** [comment] 2023-06-21 13:49
Duplicate of https://github.com/coq/coq/issues/3523 AFAICT

**Closed by SkySkimmer** 2023-06-21 13:49 UTC
Labels: part: tactics
