### ISSUE TITLE
Anomaly when building Verified Software Toolchain (VST)

### ISSUE THREAD

**Issue by brnbrnrd** [coq/coq#8010] opened 2018-07-06 12:25 UTC
#### Description of the problem
Building [VST](https://github.com/PrincetonUniversity/VST/) (`master` branch) with  `make all` fails with the following message:
```
$ make -k all
COQC fcf/RndListElem.v
File "./fcf/RndListElem.v", line 131, characters 6-29:
Warning: Nested proofs are deprecated and will stop working in a future Coq
version [deprecated-nested-proofs,deprecated]
File "./fcf/RndListElem.v", line 132, characters 4-8:
Error: Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/.

Makefile:400: recipe for target 'fcf/RndListElem.vo' failed
make: *** [fcf/RndListElem.vo] Error 129
```

Same thing with v2.2 version of VST.

Two more points:
 * `make` works fine,
 * same behaviour with Coq 8.8.0.

**Comment by robblanco** [comment] 2018-07-06 12:35
The issue is triggered by nested proofs inside a theorem; un-nesting them solves the issue. See PrincetonUniversity/VST#250.

**Comment by ppedrot** [comment] 2019-01-03 12:39
Duplicate of #7362

**Closed by ppedrot** 2019-01-03 12:39 UTC
Labels: kind: anomaly
