### ISSUE TITLE
Coq Schemes are produced wrong

### ISSUE THREAD

**Issue by motrellin** [coq/coq#19442] opened 2024-08-01 20:58 UTC
### Description of the problem

It seems like the schemes generated by the `Scheme`-Command do not behave as descriped in the [docs](https://coq.inria.fr/doc/V8.19.2/refman/proofs/writing-proofs/reasoning-inductives.html?highlight=scheme#coq:cmd.Scheme):
- `Induction` and `Elimination` produce the same scheme.
- `Case` and Minimality produce the same scheme.

A small code is provided inside of [this gist](https://gist.github.com/motrellin/74e149f83a18b1da6a22f138de1a66ad) or below.

### Small Coq file to reproduce the bug

```coq
From Coq Require Import Nat.


Scheme Elimination for nat Sort Type.
Check nat_caset.
Check nat_rect.

Scheme Case for nat Sort Type.
Scheme Minimality for nat Sort Type.
Check nat_caset_nodep.
Check nat_rect_nodep.
```

### Version of Coq where this bug occurs

8.19.1

**Comment by SkySkimmer** [comment] 2024-08-01 21:00
duplicate of https://github.com/coq/coq/issues/10816

**Closed by SkySkimmer** 2024-08-01 21:00 UTC
Labels: resolved: duplicate(d), kind: bug
