### ISSUE TITLE
"fresh" does not always generate a fresh name

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#18109] opened 2023-10-02 12:34 UTC
#### Description of the problem

Here's some example code:
```coq
Ltac _internal tac :=
  (* For reasons, we need a temporary name. *)
  let x := fresh in
  pose proof I as x;
  tac ();
  clear x.

Tactic Notation "mydestruct" constr(c) "as" simple_intropattern(pat) :=
  _internal ltac:(fun _ => destruct c as pat).

Goal (True \/ True) -> True.
intros H.
let x := fresh in mydestruct H as [x|x].
```
This is a greatly reduced version of some real-world code, where we are writing a destruct-like tactic. The problem is that the `fresh` in `_internal` generates the same name as the `fresh` all the way at the top-level, and then we get an error saying that we cannot destruct since the name is already used.

Bizarrely, if I add an unused argument `pat` to `_internal` and pass in the pattern, this proof script starts working!
There must be some absolutely crazy stuff going on where `fresh` goes through the terms available in the context and takes them into account for `fresh`, or something like that. But seemingly that logic does not descend into the environment of the `tac` closure, and that's why this particular proof script fails. We use such closures a lot to control execution order (which otherwise is very hard to predict in Ltac).

#### Coq Version

8.18.0

**Comment by SkySkimmer** [comment] 2023-10-02 12:40
>There must be some absolutely crazy stuff going on where fresh goes through the terms available in the context and takes them into account for fresh

It specifically looks through the intropatterns in the context

**Comment by RalfJung** [comment] 2023-10-02 12:49
> It specifically looks through the intropatterns in the context 

Yeah that explains what I see. Debugging this took forever since who expects entirely unused terms in the context to ever make a difference for program behavior...

This at least shows a work-around, which is that we can pass around some useless `simple_intropattern` arguments to steer `fresh` in the right direction. But obviously that not a satisfying solution. Should `extract_ids` recurse into closure environments? That's doubling-down on some rather unusual semantics, but at least it should "do the right thing" in more cases.

I wonder how Ltac2 handles this. Cc @ppedrot

**Comment by SkySkimmer** [comment] 2023-10-02 12:50
I don't think ltac2 exposes `fresh`.

**Comment by RalfJung** [comment] 2023-10-02 13:45
In fact it's not even always a `fresh`. The user might just write `mydestruct c as H` and fresh also happens to pick `H` and then we have a problem.

**Comment by JasonGross** [comment] 2023-10-02 15:17
Duplicate of #6559

**Comment by JasonGross** [comment] 2023-10-02 15:22
> it seems `pat ()` has delayed evaluation which prevents using the result in an intropattern

If you want to go down the rabbit hole of more terrible kludges, replace `pat ()` with `match goal with _ => pat () end` to force eager evaluation.

Another option is to pass a thunk to be used in place of fresh, so that you call `mydestruct (using (fun _ => fresh)) v as ...`, then the context inspection will happen in the ambient environment where hopefully the user will know what constants are lying around.  This isn't modular, though, and Ltac2 is probably better.  (Might be useful to add a `Free.of_simple_intropattern` though to support your usecase)

**Comment by RalfJung** [comment] 2023-10-02 15:27
I already mentioned that option above. It does not work since the argument to fresh is ignored when name mangling is enabled.

**Comment by RalfJung** [comment] 2023-10-02 15:39
Ah sorry looks like I forgot to mention the `fresh "name"` option.

Anyway that duplicate you mention sounds accurate. So far the only plausible work-around I have found is to just also pass the intropattern argument to the closure-invoking function so that it is right there in the context when `fresh` is invoked. Your proposal of passing in `fresh` would then have it take into account the stuff from the user context but would risk collisions with other stuff declared inside our ltac, I think...

And yeah it sounds like Ltac2 would be just a lot more verbose here if I have to thread through the intropatterns manually everywhere... the really convenient API would involve having some implicit global state where a name gets reserved so that future `fresh` know not to pick it, or a `FreshCtx` type that tracks the names that were already picked (i.e., the same state, but explicit rather than implicit), or something like that.

**Comment by RalfJung** [comment] 2023-10-02 15:43
Hm actually `(fun _ => fresh)` doesn't seem to work, it complains that the expression must evaluate to a tactic but got an intropattern instead...

**Comment by JasonGross** [comment] 2023-10-02 15:48
> the really convenient API would involve having some implicit global state where a name gets reserved so that future `fresh` know not to pick it, or a `FreshCtx` type that tracks the names that were already picked (i.e., the same state, but explicit rather than implicit), or something like that.

If https://github.com/coq/coq/pull/13982 had been merged, then you could implement this yourself in Ltac2.  As it stands, you can parameterize all your tactics over a global state object holding a mutable set of names to avoid, and update that every time you call your custom fresh.  (You can for sure already implement the explicit version in Ltac2, just wrap `fresh` in something that adds the generated name to set of names to avoid.)

**Comment by RalfJung** [comment] 2023-10-02 15:51
That all sounds rather painful... it certainly doesn't encourage me to try Ltac2 next time if I have to hand-build even basic ingredients for tactic programming, such as name generation.

**Comment by JasonGross** [comment] 2023-10-02 21:33
What is missing currently in Ltac2 is not fresh name generation but global state.  You can write
```coq
From Ltac2 Require Import Ltac2 Fresh.

Ltac2 make_fresh () : Free.t -> ident -> ident :=
  let avoid := { contents := Free.of_ids [] } in
  let fresh (extra : Free.t) (id : ident) :=
    let id := Fresh.fresh (Free.union (avoid.(contents)) extra) id in
    avoid.(contents) := Free.union (avoid.(contents)) (Free.of_ids [id]);
    id in
  fresh.
```
and get your hands on a `fresh` that will avoid ids it's already generated pretty easily, but sharing the state across multiple tactics implicitly is not yet wired in.  (@ppedrot @SkySkimmer are there plans in the works for this?)

**Comment by RalfJung** [comment] 2023-10-02 21:45
We need to also avoid ids that are present in the input provided by the user (e.g. via intro patterns that come in as tactic arguments).

**Closed** 2023-10-02 22:36 UTC
Labels: part: ltac, resolved: duplicate(d)

**Comment by JasonGross** [comment] 2023-10-02 22:41
Ltac2 is deliberately a language with less magic going on behind the scenes than Ltac1.  If you want to avoid ids passed in particular arguments in Ltac2, you need to extract the ids.  Currently much of the infrastructure is missing, but we'd be happy to have `Fresh.Free.of_simple_intropattern` in the standard library, and similarly for whatever other kind of data structures you want to handle.  (I think recursing into closures is too much magic; Ltac1 didn't support it because it's too hard, I think, and the result is this sort of confusing behavior.  Ltac2 doesn't support it, but you'll never expect it to support this case, so will structure your code / API to avoid needing to recurse into closures.  At least, that's the hope.)

**Comment by RalfJung** [comment] 2023-10-03 06:23
Yeah I fully approve of "less magic". But then the alternative shouldn't have to be "everything takes 3 times as much code to do". As you say it's probably a matter of adding a lot of missing infrastructure. But that also creates a chicken-and-egg situation where when I have only a few hours per week to do tactic hacking, I will get nothing done if I use Ltac2 because I first need to implement myself all the missing functionality that comes built-in with Ltac.

**Comment by JasonGross** [comment] 2023-10-03 14:01
I would suggest trying to write small bits in Ltac2 and using the compat interface to call Ltac1 from Ltac2 and vice versa.  When there's a piece of missing infrastructure, switch back to Ltac1 and make an issue here on the Coq repo requesting it
