### ISSUE TITLE
coqdoc error messages should report file names

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14119] opened 2021-04-15 19:56 UTC
#### Description of the problem

I'm not sure what to make of
```
Line 383, character 58, warning: missing newline after ">>" block
Line 19, character 3, warning: unterminated inline ">>"
Line 135, character 6, warning: missing newline after ">>" block
Line 146, character 79, warning: missing newline after ">>" block
Line 115, character 8, warning: missing newline after ">>" block
Line 83, character 65, warning: missing newline after ">>" block
Line 26, character 6, warning: unterminated inline ">>"
Line 32, character 6, warning: unterminated inline ">>"
Line 7, character 6, warning: unterminated inline ">>"
Line 59, character 6, warning: unterminated inline ">>"
Line 347, character 6, warning: unterminated inline ">>"
Line 354, character 6, warning: unterminated inline ">>"
Line 360, character 9, warning: unterminated inline ">>"
Line 14, character 8, warning: unterminated inline ">>"
Line 26, character 8, warning: unterminated inline ">>"
Line 63, character 8, warning: unterminated inline ">>"
Line 87, character 6, warning: unterminated inline ">>"
Line 109, character 6, warning: unterminated inline ">>"
Line 125, character 6, warning: unterminated inline ">>"
Line 17, character 6, warning: unterminated inline ">>"
Line 23, character 6, warning: unterminated inline ">>"
Line 25, character 6, warning: unterminated inline ">>"
Line 151, character 6, warning: unterminated inline ">>"
Line 176, character 6, warning: unterminated inline ">>"
Line 308, character 6, warning: unterminated inline ">>"
Line 128, character 8, warning: unterminated inline ">>"
Line 17, character 6, warning: unterminated inline ">>"
Line 23, character 6, warning: unterminated inline ">>"
Line 93, character 6, warning: unterminated inline ">>"
Line 51, character 6, warning: unterminated inline ">>"
Line 129, character 6, warning: unterminated inline ">>"
Line 279, character 6, warning: unterminated inline ">>"
Line 320, character 6, warning: unterminated inline ">>"
Line 115, character 6, warning: unterminated inline ">>"
Line 127, character 6, warning: unterminated inline ">>"
Line 97, character 24, warning: missing newline after ">>" block
Line 121, character 60, warning: missing newline after ">>" block
Line 197, character 46, warning: missing newline after ">>" block
Line 154, character 14, warning: missing newline after ">>" block
Line 272, character 14, warning: missing newline after ">>" block
Line 367, character 14, warning: missing newline after ">>" block
Line 731, character 9, warning: unterminated inline ">>"
Line 737, character 9, warning: unterminated inline ">>"
```
at https://github.com/HoTT/HoTT/runs/2353786837?check_suite_focus=true#step:5:2860

#### Coq Version

8.13

**Comment by silene** [comment] 2021-04-17 07:15
Duplicate of #13747

**Closed by silene** 2021-04-17 07:15 UTC
Labels: part: coqdoc
