### ISSUE TITLE
Coqide: no icons

### ISSUE THREAD

**Issue by davidnowak** [coq/coq#11505] opened 2020-02-02 09:50 UTC
#### Description of the problem and Coq Version

On macOS Catalina 10.15.3, I have updated Opam to 2.0.6 with an up-to-date Homebrew, and then I have installed Coqide 8.11.0 with Opam.

When I start Coqide, the following warnings are displayed and no icons are visible (see the screenshot below):
```
(coqide:4853): Gtk-WARNING **: 10:44:30.633: Error loading theme icon 'document-save' for stock: L’icône « document-save » n’est pas présente dans le thème Adwaita

(coqide:4853): Gtk-WARNING **: 10:44:30.634: Error loading theme icon 'window-close' for stock: L’icône « window-close » n’est pas présente dans le thème Adwaita

(coqide:4853): Gtk-WARNING **: 10:44:30.634: Error loading theme icon 'go-down' for stock: L’icône « go-down » n’est pas présente dans le thème Adwaita

(coqide:4853): Gtk-WARNING **: 10:44:30.634: Error loading theme icon 'go-up' for stock: L’icône « go-up » n’est pas présente dans le thème Adwaita

(coqide:4853): Gtk-WARNING **: 10:44:30.635: Error loading theme icon 'go-jump' for stock: 

(coqide:4853): Gtk-WARNING **: 10:44:30.635: Error loading theme icon 'go-top' for stock: L’icône « go-top » n’est pas présente dans le thème Adwaita

(coqide:4853): Gtk-WARNING **: 10:44:30.635: Error loading theme icon 'go-bottom' for stock: L’icône « go-bottom » n’est pas présente dans le thème Adwaita

(coqide:4853): Gtk-WARNING **: 10:44:30.635: Error loading theme icon 'system-run' for stock: L’icône « system-run » n’est pas présente dans le thème Adwaita

(coqide:4853): Gtk-WARNING **: 10:44:30.635: Error loading theme icon 'process-stop' for stock: L’icône « process-stop » n’est pas présente dans le thème Adwaita

(coqide:4853): Gtk-WARNING **: 10:44:30.635: Error loading theme icon 'go-previous' for stock: 

(coqide:4853): Gtk-WARNING **: 10:44:30.635: Error loading theme icon 'go-next' for stock: 

(coqide:4853): Gtk-WARNING **: 10:44:30.730: Error loading theme icon 'document-new' for stock: L’icône « document-new » n’est pas présente dans le thème Adwaita

(coqide:4853): Gtk-WARNING **: 10:44:30.730: Error loading theme icon 'window-close' for stock: L’icône « window-close » n’est pas présente dans le thème Adwaita

(coqide:4853): Gtk-WARNING **: 10:44:30.799: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node header owner GtkNotebook)

(coqide:4853): Gtk-WARNING **: 10:44:30.800: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tabs owner GtkNotebook)

(coqide:4853): Gtk-WARNING **: 10:44:30.800: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)
```

![coqide](https://user-images.githubusercontent.com/22745394/73606339-6127a880-45a9-11ea-9c04-40d47b55d3fd.jpg)

**Comment by ejgallego** [comment] 2020-02-02 12:18
This was due to some missing gnome packages I do believe; we fixed it in our OSX images build; the set of installed packages is:
```
      brew install gnu-time opam pkg-config gtksourceview3 adwaita-icon-theme
```
I guess Coq's `INSTALL` file may be missing this indeed.

**Comment by ejgallego** [comment] 2020-02-02 12:18
@davidnowak please confirm that installing `adaita-icon-theme` does fix this problem and we'll update the readme.

**Comment by davidnowak** [comment] 2020-02-02 15:33
> @davidnowak please confirm that installing `adaita-icon-theme` does fix this problem and we'll update the readme.

I confirm that it fixes the problem.

I was expecting Opam to deal with that through _opam-depext_, as it does with other external dependencies.

**Comment by ejgallego** [comment] 2020-02-02 16:11
Thanks for the confirmation; indeed both the README and the opam package should be improved.

**Comment by ppedrot** [comment] 2022-02-27 15:36
Duplicate of #14324

**Closed by ppedrot** 2022-02-27 15:36 UTC
Labels: part: IDE, platform: macOS
