### ISSUE TITLE
Anomaly "A universe comparison can only happen between variables."

### ISSUE THREAD

**Issue by meduzik** [coq/coq#6843] opened 2018-02-26 16:46 UTC
#### Version
8.7.2 (in CoqIDE)

#### Operating system
Windows 7

#### Description of the problem

```coq
Require Import Coq.Lists.List.

Inductive SumType : Type :=
| sum_type : list (list SumType) -> SumType.

Fixpoint get_constr (st:SumType) (n:nat) : option (list SumType) :=
  match st with
  | sum_type ls => nth_error ls n
  end.

Inductive Tuple : list Type -> Type :=
| t_nil : Tuple nil
| t_cons : forall (T:Type) TS, T -> Tuple TS -> Tuple (T::TS).

Inductive ValueOf : SumType -> Type :=
| value_ev : forall (n:nat) (ls:list SumType) (st:SumType), 
  Some ls = get_constr st n -> 
  Tuple (map ValueOf ls) ->
  ValueOf st.
```

The ValueOf declaration results in 

> Anomaly "A universe comparison can only happen between variables."
> Please report at http://coq.inria.fr/bugs/.

**Comment by SkySkimmer** [comment] 2018-02-26 16:52
Confirmed in master.

**Comment by maximedenes** [comment] 2018-03-06 09:57
@SkySkimmer you added the 8.8+beta1 milestone but didn't assign to yourself. Do you plan to work on it before the beta or not?

**Comment by SkySkimmer** [comment] 2018-03-06 12:17
>Do you plan to work on it before the beta or not?

I don't.

**Comment by mattam82** [comment] 2018-03-06 17:33
I'll make a pass today or tomorrow on what I can do for the freeze. If this looks like a backward compatible bugfix I'll schedule it for afterwards

**Comment by SkySkimmer** [comment] 2021-09-29 15:21
Modern coq gets `Error: Universe inconsistency. Cannot enforce Tuple.u0 = max(Set, Tuple.u0+1, Tuple.u1+1).` which is correct.

**Closed by SkySkimmer** 2021-09-29 15:21 UTC
Labels: kind: anomaly, part: universes
