### ISSUE TITLE
Compile error in theories/Numbers/Cyclic/Int63/PrimInt63.v

### ISSUE THREAD

**Issue by florath** [coq/coq#18568] opened 2024-01-26 14:15 UTC
#### Description of the problem
When running `coqc theories/Numbers/Cyclic/Int63/PrimInt63.v` the following error is logged:

```coq
File "./PrimInt63.v", line 38, characters 0-49:
Error: The reference Coq.Numbers.Cyclic.Int63.PrimInt63.int_wrapper
was not found in the current environment.
```

My idea is, that each file should be self-containing in the way that it can be separately compiled without any further imports.

#### Coq Version

The Coq Proof Assistant, version 8.16.1

Commit hash of the file `theories/Numbers/Cyclic/Int63/PrimInt63.v`: 5d2ec17f6cbf92e4999c41faeb475c0797914600

**Comment by SkySkimmer** [comment] 2024-01-26 14:17
Duplicate of https://github.com/coq/coq/issues/18510

**Closed by SkySkimmer** 2024-01-26 14:17 UTC
