### ISSUE TITLE
Inline ltac:() and notation scopes don't work well together

### ISSUE THREAD

**Issue by vmurali** [coq/coq#8706] opened 2018-10-10 23:52 UTC
#### Version
8.8.2

#### Operating system
Mac OSX

#### Description of the problem

The following code does not work:

```
Notation "@ a" := a%nat (at level 100): my_scope.
Delimit Scope my_scope with my.

Notation "& b" := ltac:(exact (b)%my) (at level 100): my_scope.
Definition test := (& (@4))%my.

```

But the following code works:
```
Notation "@ a" := a%nat (at level 100): my_scope.
Delimit Scope my_scope with my.

Notation "& b" := b (at level 100): my_scope.
Definition test := (& (@4))%my.
```

It also works if I explicity provide the scope as `(@4)%my`.

This bug has been plaguing me since inlined ltac has been introduced in 8.6(?). Is there any plan to fix it or a workaround that supports scoping within inline ltacs?

**Comment by tchajed** [comment] 2018-10-15 15:12
With your first example's notations `Open Scope my_scope` also fixes the problem, so it seems like only local notation scopes are not being propagated through inline Ltac while global scopes are being respected.

Also I noticed you have `exact b%my` in your Ltac - I don't think this is necessary or has any effect. The `%my` affects only the interpretation of the ltac code itself, letting you use notations within the tactic - `b` is just a variable, not arbitrary tokens whose interpretation you can change. Otherwise you could do crazy things like within Ltac dynamically re-parse expressions, potentially in multiple different ways, eg, `ltac:(exact b%my || exact b%arith)`.

**Comment by vmurali** [comment] 2018-10-15 15:29
Yes, `Open Scope my_scope` fixes the problem, but I am trying to avoid using global scopes because that pollutes my interpretation stack.

I don't see anything wrong with allowing dynamic re-parsing of expressions, `ltac:(exact b%my || exact b%arith)`.

That said, I am open to a solution which conditionally creates an interpretation stack for a notation - something like, if I am within interpretation scope A, then interpret this as B. This sounds like a sillier solution though.

**Comment by JasonGross** [comment] 2018-10-15 16:47
Duplicate of #3468

**Closed by JasonGross** 2018-10-15 16:47 UTC
Labels: part: ltac, part: notations

**Comment by JasonGross** [comment] 2018-10-15 17:03
The behavior of `ltac:(exact b%my || exact b%arith)` should be identical to the behavior of `match b%my, b%arith with b0, b1 => ltac:(exact b0 || exact b1) end`, i.e., `Error: b is here used in scope my_scope while it was elsewhere used in scope arith_scope`.

The expected behavior is straightforward.  The code
```coq
Ltac bar := exact (sum (Set + Set) (Set + Set)) || exact (Set + Set)%type.
```
works and, under `Set Printing All`, prints as
```coq
Ltac bar := exact (sum (sum Set Set) (sum Set Set)) || exact (sum Set Set)
```
because, at Ltac definition time, Coq knows what scope stack to interpret each thing in (and then the scopes disappear before running the tactic).  In any variable used in Ltac which is bound in the notation context, Coq should assign to it the scope stack it lands in at Ltac/Notation definition time, and check that the scope stack is consistent across all uses.
