### ISSUE TITLE
CoqIde crash when clicking on the proof wizard button

### ISSUE THREAD

**Issue by bruno-cadorette** [coq/coq#8016] opened 2018-07-07 17:10 UTC
The Coq Proof Assistant, version 8.8.1 (June 2018)
compiled on Jun 30 2018 1:16:10 with OCaml 4.05.0

Distributor ID: neon
Description:    KDE neon User Edition 5.12
Release:        16.04
Codename:       xenial

I clicked on the "proof wizard button" and CoqIde crashed. Here's the terminal logs:

(coqide:29621): GtkSourceView-WARNING **: 13:01:32.068: Failed to load '/nix/store/5p3mykffzp7cxkrjj82fb22mjhbzqvpq-coq-8.8.1/share/coq/coq.lang': could not find the RelaxNG schema file
Unable to locate theme engine in module_path: "adwaita",
Unable to locate theme engine in module_path: "adwaita",
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
Coqide internal error: Source ID 7471 was not found when attempting to remove it
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
Coqide internal error: Source ID 11945 was not found when attempting to remove it
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
Coqide internal error: Source ID 32726 was not found when attempting to remove it
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
Coqide internal error: Source ID 79462 was not found when attempting to remove it
Coqide internal error: Source ID 106678 was not found when attempting to remove it
Coqide internal error: Source ID 107753 was not found when attempting to remove it
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
gtktextbtree.c:4096: char offset off the end of the line

**Comment by Zimmi48** [comment] 2018-07-07 22:09
Hello @bruno-cadorette, could you say how you have obtained the Coq 8.8.1 package?
Seeing `/nix/store/5p3mykffzp7cxkrjj82fb22mjhbzqvpq-coq-8.8.1/share/coq/coq.lang'`, it looks like you have installed the package using Nix. Is this correct? (If not, I would be worried how such a path could have ended up there.)
Could you also say if you have clicked on the proof wizard button right after loading CoqIDE or, if not, what you have done before? And can you reproduce this behavior consistently? I have tried to reproduce using the same Nix package, on NixOS, but I couldn't.

**Comment by ppedrot** [comment] 2020-02-03 15:59
Fixed by #10581

**Closed by ppedrot** 2020-02-03 15:59 UTC
Labels: part: IDE
