### ISSUE TITLE
Unable to load library from the same folder

### ISSUE THREAD

**Issue by weitaoxin** [coq/coq#7311] opened 2018-04-19 16:38 UTC
#### Description of the problem

In CoqIDE, I am unable to load a pre-compiled library from the same folder in which the file I opened in buffer located.

I believe this problem is caused by CoqIDE, because I can directly compile the source file using `coqc xxx.v` without error but cannot when using CoqIDE.

**Comment by Zimmi48** [comment] 2018-04-26 20:31
Could you please provide concrete steps so that we can reproduce your problem and provide guidance?

**Comment by weitaoxin** [comment] 2018-04-27 13:16
@Zimmi48 Actually that was all I know, and I just found that I can load library if I open the CoqIDE from the terminal that exactly in that folder, but if I open it from other location it fails. So maybe some environment variables are not correctly set.

**Comment by Zimmi48** [comment] 2018-04-27 15:05
When I say "we need concrete steps to be able to reproduce", I mean tell us what to put in a file, how you name it, how you compile it, how you try to load it, etc. But if you have a solution that satisfies you, we can also just close this issue.

**Comment by weitaoxin** [comment] 2018-04-28 12:31
@Zimmi48 I'm sorry for not understanding your questions.

The steps are:
First, create **TestA.v** and **TestB.v** in the same folder, then put some code in **TestA.v** like:
```
Theorem modus_ponens : forall (P Q:Prop),
  ((P -> Q) /\ P) -> Q.
Proof. intros. destruct H. auto. Qed.
```

In **TestB.v**:
```
Require Export TestA.
```

Then compile **TestA.v** using `coqc TestA.v`, and in CoqIDE open **TestB.v**.
Forward one command, an error occurs which says:

> Unable to locate library TestA.

A screenshot describing this problem:
https://ibb.co/mHmrBx

**Comment by Zimmi48** [comment] 2018-04-28 13:41
OK thanks so indeed, this is not a bug but the expected behavior: CoqIDE won't be looking for libraries where the file was saved but where you launched it. To still be able to import your file, you can use the command [`Add LoadPath`](https://coq.inria.fr/refman/proof-engine/vernacular-commands.html#coq:cmd.add-loadpath):

```
Add LoadPath "/tmp/test". (* where I put TestA and TestB *)
Require Export TestA. (* success *)
```

I'm closing this issue now but the conversation is still open. If you need, you can continue to ask questions.

**Closed by Zimmi48** 2018-04-28 13:41 UTC
