### ISSUE TITLE
Cost priority in eauto (follow up)

### ISSUE THREAD

**Issue by QinshiWang** [coq/coq#15558] opened 2022-01-27 05:01 UTC
I replied in https://github.com/coq/coq/issues/15529 but got ignored.
```coq
Axiom A : Prop.
Axiom B : nat -> Prop.
Axiom C : Prop.
Axiom A_to_B : A -> B 0.
Axiom B_to_C : forall x, (B x) -> C.

Create HintDb x.
Hint Resolve A_to_B B_to_C : x.
Hint Extern 10 C => (shelve) : x.

Lemma foo : A -> C.
  intros.
  info_eauto 5 with nocore x.
Abort.
```
Result:
```
(* info eauto: *)
(*external*) shelve.
```
So `shelve` was applied before `simple eapply B_to_C` because the latter introduces an evar. I'm not sure if this is desired.

**Comment by ppedrot** [comment] 2022-01-27 09:28
This is not related to evars, it's another quirk of the eauto semantics. Despite the documentation, eauto will apply tactics that solve the goal before any other tactic. Since shelve makes the goal disappear it's considered solving, thus applied first.

**Comment by ppedrot** [comment] 2022-01-27 09:30
Duplicate of #5163

**Closed by ppedrot** 2022-01-27 09:30 UTC
