### ISSUE TITLE
Discrepancy between coqchk and Print Assumptions ? 

### ISSUE THREAD

**Issue by proux01** [coq/coq#11853] opened 2020-03-18 10:07 UTC
### Description of the problem

On the following code
```coq
Module Type T.
Parameter t : True.
End T.

Module M : T.
Lemma t : True.
Proof. exact I. Qed.
End M.

Lemma l : True.
Proof.
exact M.t.
Qed.

Print Assumptions l.
```
`Print Assumptions` reports `Closed under the global context` whereas `coqchk -silent -o` reports
```
* Axioms:
    f.M.t
```
Is that expected? After all, I feel my lemma is fully proved and I'd like it not to appear as an axiom. Am I wrong? If it's a bug, does anyone have any idea on how to fix this (i'd be happy to help)?

For an example of a concrete instance of this : https://prosa.mpi-sws.org/releases/v0.1/artifact/ (look at "Running the Proof Checker").

#### Coq Version

master (and released versions)

**Comment by SkySkimmer** [comment] 2020-03-18 10:54
Duplicate of https://github.com/coq/coq/issues/5030

**Closed by SkySkimmer** 2020-03-18 10:54 UTC
Labels: part: checker

**Comment by proux01** [comment] 2020-03-18 11:01
@SkySkimmer thanks! I had a quick look before reporting but didn't found something that old.
