### ISSUE TITLE
ssreflect printing  forgets "as" for list in pattern

### ISSUE THREAD

**Issue by thery** [coq/coq#7110] opened 2018-03-29 09:41 UTC
The ssreflect printing of list [:: _; _; _] seems to forget the "as" construct in pattern
#### Version

8.7.2
#### Operating system

linux

#### Description of the problem

```
Require Import List.

Definition foo (l : list nat) := 
  match l with
  | a :: ((b :: l) as l1) => l1
  | _ => l
end.

Print foo.

(*   ok

foo = 
fun l : list nat =>
match l with
| nil => l
| _ :: nil => l
| _ :: (_ :: _) as l1 => l1
end
*)

From mathcomp Require Import all_ssreflect.

Print foo.

(* not ok

foo = 
fun l : seq nat =>
match l with
| [::] => l
| [:: _] => l
| [:: _, _ & _] => l1
end
*)
```

**Comment by Zimmi48** [comment] 2018-03-29 10:47
This bug does not occur with a simple `From Coq Require Import ssreflect.` so I'm unsure this is the appropriate place to report this problem.

**Comment by thery** [comment] 2018-03-29 11:08
oops I copy the message to mathcomp

**Comment by thery** [comment] 2018-03-29 11:10
https://github.com/math-comp/math-comp/issues/188

**Comment by Zimmi48** [comment] 2018-03-29 11:20
So closing as "moved" but feel free to reopen if this was actually a bug on the Coq-SSReflect side.

**Comment by SkySkimmer** [comment] 2018-03-29 11:20
>This bug does not occur with a simple From Coq Require Import ssreflect. so I'm unsure this is the appropriate place to report this problem.

It seems like a notation bug that the binder gets hidden.
For instance if we do 
```coq
Inductive Box := box : forall n : nat, Box.

Definition rebox b := match b with box n => box n end.

Arguments box {_}.
Print rebox.

Notation "■" := (box).
Print rebox.
```
The first Print gives us `@box n => box` and the second `@box n => ■` ie it doesn't use the notation for the match pattern.

Meanwhile in the bug we print `[:: _, _ & _] => l1` with the name `l1` appearing unbound.

**Comment by gares** [comment] 2018-03-29 14:29
The bug must be in the notation system an is triggered by some notations in seq.v

Math-comp is just .v code now.

**Comment by thery** [comment] 2018-03-29 14:59
Here is a self contained version of the problem

```
Require Import List.

Notation "[ :: x1 , x2 , .. , xn & s ]" := (x1 :: x2 :: .. (xn :: s) ..)
  (at level 0).

Definition foo (l : list nat) := 
  match l with
  | a :: ((b :: l) as l1) => l1
  | _ => l
end.

Print foo.
```

**Comment by gares** [comment] 2018-03-29 14:59
In the seq notation the term denoted l1 is not an argument of the notation. So I ve no clue how as could be rendered here. Imo the simplest fix is to not display the notation if  the subterm to which as applies is not an argument of the notation

**Comment by gares** [comment] 2018-03-29 15:00
Not sure it is the same bug found by Gaetan

**Comment by SkySkimmer** [comment] 2018-03-29 15:08
I didn't find a bug, I just said that this issue is a bug in Coq not ssr.

**Comment by herbelin** [comment] 2018-03-29 16:24
Indeed, a test of the absence of an `as` clause is missing in the algorithm trying to match the pattern to print with a notation (`Notation_ops.match_cases_pattern`). I shall come up with a fix.

**Comment by herbelin** [comment] 2018-03-29 17:00
Note: @SkySkimmer's example seems to be a bug too. I don't see why we would not like the notation to be used there.

**Comment by herbelin** [comment] 2018-03-29 17:15
No, it is not a bug, sorry (the dependence in `n` blocks the possibility to use a notation).

**Closed** 2018-04-09 14:09 UTC
