### ISSUE TITLE
Typeclasses feature request: per-Instance mode

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#17945] opened 2023-08-08 14:12 UTC
#### Description of the problem

It is fairly common that for a given typeclass, different instances want different `Hint Mode`: some instances just don't make sense if certain subterms are still an evar. In Iris we are currently working around this by splitting the typeclass into several different typeclasses with different modes, but that is hard to discover, harder to explain and even harder to get right. It would be much easier if we could just restrict some instances to not apply when parts of the goal are still an evar.

This also just came up again for me where I wanted to add some new `subrelation` instances, but I cannot, since Coq will pick them up in the most inopportune moments. (rewriting seems to do searches of the form `subrelation ?r iff`, and I really don't want it to pick up my instance as a random superrelation of `iff`.) This doesn't just cost performance through unnecessary detours during TC search, it actually breaks some of my proofs since these instances have parameters `n : nat` that Coq cannot infer, and leaves behind for the user to resolve. (This particular problem could possible be resolved by setting a Hint Mode for `subrelation` -- guessing a random superrelation seems unlikely to ever be useful. But the general case still stands, I think. Also if per-instance modes were a thing I wouldn't have to wait for the Coq standard library to add a mode to `subrelation`, I could add the new instances today.)

**Comment by SkySkimmer** [comment] 2023-08-08 14:49
There would then be 2 ways to interpret Hint Mode:
- instances without a specified mode get the Hint Mode of their class at resolution time
- instances without a specified mode get the Hint Mode of their class at declaration time

The 1st way should be backwards compatible, is there any reason to try to do the 2nd way?

**Comment by SkySkimmer** [comment] 2023-08-08 14:50
Actually there may be a 3rd way: at resolution time combine the mode of the class and the mode of the instance somehow
Not sure if that makes any sense though.

**Comment by RalfJung** [comment] 2023-08-08 15:11
Combining modes usually means "any one of the modes must apply". So when class and instance have modes, do they get combined or does the instance trump the class? I think I would prefer the latter... otherwise a class with a mode can never have instances that restrict the mode further.

**Comment by RalfJung** [comment] 2023-08-08 15:13
I think my intuitive understand would be that the two modes are applied independently:
- first a check is done whether any of the class modes apply. if not, just skip this goal and try to make progress elsewhere.
- then during instance search, for each instance considered its mode is checked.

So, if the instance has no mode, everything behaves as it does now. If instance and class both have modes, then any class mode *and* the instance mode must apply.

**Comment by SkySkimmer** [comment] 2023-08-08 15:17
So it's not possible to have an instance with a mode which is (effectively) less strict than the class mode?

**Comment by JasonGross** [comment] 2023-08-17 04:15
Duplicate of #14126

**Closed by JasonGross** 2023-08-17 04:15 UTC
