### ISSUE TITLE
Critical bug with VM and universes

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#6677] opened 2018-01-31 13:58 UTC
```coq
Require Import Hurkens.

Set Universe Polymorphism.
Set Printing Universes.
Set Printing All.

Definition T@{i} := Type@{i}.
Definition U@{i} := (T@{i} <: Type@{i}).
Definition eqU@{i j} : @eq T@{j} U@{i} T@{i} := eq_refl.
Definition bad : False := TypeNeqSmallType.paradox U eqU.
Print Assumptions bad.
```

We are probably missing a universe level substitution.

It seems at least 8.6, 8.7 and master are impacted. I'm probably responsible for this one. Sorry about that! Although maybe it was already there in the original VM univ code, I haven't checked. While I should have realized I was doing something wrong, I'm not confident that with the current universe API, I won't be doing this kind of mistakes again, unfortunately.

Something that I find very surprising, and that led me to find this bug, is that the kernel accepts terms with unsubstituted universe levels (`Var(i)`). How can that be, if the kernel interface is safe?

```coq
Set Universe Polymorphism.
Set Printing Universes.
Definition U@{i} := Type@{i}.
Definition V := Eval vm_compute in U@{Set}.
Print V.
```

Note that this last example uses the VM bug only in the pretyper, not the kernel. So why isn't `V` rejected ?!

**Comment by ppedrot** [comment] 2018-01-31 14:02
@maximedenes It's normal for the kernel to accept `Var` universes as long as they are bound in the current environment. You should think of universes as some kind of domain-specific term syntax where `Var` stand for DeBruijn indices. It's hard to statically forbid some variables to appear, but it should be doable to split between variable-only stuff and generic-level stuff.

What is probably lacking is some check in the kernel that all universe variables are bound...

**Comment by maximedenes** [comment] 2018-01-31 14:05
> What is probably lacking is some check in the kernel that all universe variables are bound...

Yes, that's what my question is about. Don't we have such a check at least ?! `Print V` shows the variable as unbound if I read it correctly.

**Comment by SkySkimmer** [comment] 2018-01-31 14:08
I think the kernel doesn't accept binders, it generates them. You can use `Var` as a name like `Level` but that's super hacky.
Isn't the check basically #891?

**Comment by ppedrot** [comment] 2018-01-31 14:11
@SkySkimmer Indeed, this looks like #891 is what we need.

Also, I think that the kernel shouldn't be concerned about universe variable generation, such an abstraction procedure should be delegated to the upper level.

**Comment by SkySkimmer** [comment] 2018-01-31 14:12
>Also, I think that the kernel shouldn't be concerned about universe variable generation, such an abstraction procedure should be delegated to the upper level.

I'm not against but that's not how it works currently.

**Comment by ppedrot** [comment] 2018-01-31 14:15
I've got a few patches in that direction, but it's hard due to some trickeries in both module checking and cumulative inductive types. I'm waiting for #6092 before going further.

**Comment by SkySkimmer** [comment] 2018-01-31 14:18
Do you really want #6092 or is #6128 enough? (I changed the dependency order recently)

**Comment by ppedrot** [comment] 2018-01-31 14:18
Indeed, #6128 would be already enough.

**Comment by Zimmi48** [comment] 2018-02-06 13:29
Normally the schedule was to release Coq 8.7.2 by Feb, 15th. Will the fix for this critical bug be ready by this date? Will it be ready much before and should the release date be sooner?

**Comment by maximedenes** [comment] 2018-02-06 13:34
I think the fix will be ready by then (I'll work on it this week) and we should keep that target given that it is very close.

**Comment by anton-trunov** [comment] 2018-02-06 13:38
>It seems at least 8.6, 8.7 and master are impacted.

I cannot reproduce it with v8.7.1:

```
$ coqc critical_bug_6677.v
File "./critical_bug_6677.v", line 8, characters 21-39:
Error:
The term "T@{i}" has type "Type@{i+1}" while it is expected to have type
 "Type@{i}".

$  coqc -v
The Coq Proof Assistant, version 8.7.1 (December 2017)
compiled on Dec 29 2017 13:54:32 with OCaml 4.06.0
```

Line 8 being `Definition U@{i} := (T@{i} <<: Type@{i}).`

I'm on macOS High Sierra 10.13.2 (17C88). Coq was installed via OPAM.

**Comment by maximedenes** [comment] 2018-02-06 13:40
Ooops, there was a typo in the code. It should be `<:`, not `<<:`.

**Comment by anton-trunov** [comment] 2018-02-06 13:41
And now I can reproduce it.

**Closed** 2018-02-14 13:24 UTC
Labels: part: VM, part: universes, priority: critical
