### ISSUE TITLE
coqdep emits warnings that lie both about its input and output

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12251] opened 2020-05-04 23:06 UTC
#### Description of the problem

Consider the `_CoqProject` file:
```
-R . Top
foo/A.v
A.v
B.v
```
where `foo/A.v` and `A.v` are both empty, and `B.v` has the single line
```coq
From Top.foo Require Import A.
```
Then `coq_makefile -f _CoqProject -o Makefile && make` emits
```
COQDEP VFILES
*** Warning: in file B.v,
    required library A matches several files in path
    (found A.v in foo and .; used the latter)
COQC foo/A.v
COQC A.v
COQC B.v
```
This warning is wrong, because there is only one match, not two.  Moreover, coqdep claims that it's choosing the incorrect version of `A.v`, i.e., `Top.A`, not `Top.foo.A`, even though I explicitly asked for the `A` in `Top.foo`.

But it seems that `coqdep` in fact chose `foo/A`, contrary to its warning:
```
foo/A.vo foo/A.glob foo/A.v.beautified foo/A.required_vo: foo/A.v
foo/A.vio: foo/A.v
foo/A.vos foo/A.vok foo/A.required_vos: foo/A.v
A.vo A.glob A.v.beautified A.required_vo: A.v
A.vio: A.v
A.vos A.vok A.required_vos: A.v
B.vo B.glob B.v.beautified B.required_vo: B.v foo/A.vo
B.vio: B.v foo/A.vio
B.vos B.vok B.required_vos: B.v foo/A.vos
```

#### Coq Version

8.11.1

**Comment by ejgallego** [comment] 2020-05-05 12:12
Duplicate of #11631

**Closed** 2020-05-06 16:43 UTC
Labels: kind: bug, part: coqdep
