### ISSUE TITLE
match goal fails to match primitive projections after reduction

### ISSUE THREAD

**Issue by jwiegley** [coq/coq#6994] opened 2018-03-14 19:00 UTC
#### Version

8.7.2

#### Operating system

macOS 10.13.3

#### Description of the problem

The attached code shows a case where after changing the goal and using `vm_compute`, I cannot use `match goal` to match exactly what is in the goal.

I was unable to reproduce this with a toy example, so I've reduced my full problem down to this attachment.

[Bug.zip](https://github.com/coq/coq/files/1812662/Bug.zip)

**Comment by jwiegley** [comment] 2018-03-14 19:29
The purpose behind this code is to provide a reflection-based rewriting tactics, so that I can rewrite categorical compositions regardless of associativity.  The impact of the reported bug is that I only get to use the tactic exactly once.

**Comment by JasonGross** [comment] 2018-03-14 23:33
This is an issue with primitive projections.  Here's a reduced example:
```coq
Set Primitive Projections.
Class Setoid A := { equiv : A -> A -> Type }.

Goal forall A B C D, @equiv A B C D.
  intros.
  lazymatch goal with
  | [ |- @equiv _ _ _ _ ] =>
    idtac
  end. (* success *)
  vm_compute.
  lazymatch goal with
  | [ |- @equiv _ _ _ _ ] =>
    idtac
  end. (* fails *)
```

**Comment by jwiegley** [comment] 2018-03-14 23:46
@JasonGross Thank you!

**Comment by RalfJung** [comment] 2019-03-12 14:19
I think I just ran into this. I wasted an hour debugging why `eauto` with our custom hints would not solve a goal, and it boils down to `match goal` not matching a pattern with a goal when the pattern definitely applies. The term that fails to match is a primitive projection. I was unable to reproduce this in any smaller example.

**Comment by mattam82** [comment] 2019-03-12 15:14
This is due to the dreaded `unfolded` status of primitive projections that was introuced for compatibility with non-primitive ones (if you unset primitive projections, you'll see that indeed the second match goal cannot succeed).

**Comment by ppedrot** [comment] 2019-03-12 15:39
> This is due to the dreaded unfolded status of primitive projections

Pretty please, let's get rid of that wart a soon as possible and the devil with the *borken* compat layer.

**Comment by RalfJung** [comment] 2019-03-12 16:12
Yes please indeed. Can we throw MPI consortium resources at this?^^

**Comment by math-fehr** [comment] 2020-04-17 21:22
I also ran into this, not after doing a reduction, but when matching on a record that has primitive projections:

```Coq
Local Set Primitive Projections.
Record r {T: Type} := constr { arg1: T; arg2: T }.
Arguments r : clear implicits.
Arguments constr {T} arg1 arg2 : assert.

Definition foo (x: r bool) :=
  match x with
  | constr true _ => true
  | constr _ _ => false
  end.

Goal forall x, foo x = false -> True.
  intros.
  unfold foo in *.
  (* This match fails *)
  Fail match goal with
       | [ H: (if arg1 _ then _ else _) = _ |- _ ] => idtac H
       end.
Abort.
```

**Comment by ppedrot** [comment] 2022-02-05 17:20
Fixed by #15559.

**Closed by ppedrot** 2022-02-05 17:20 UTC
Labels: part: primitive records
