### ISSUE TITLE
Coq does not keep some notations

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#9180] opened 2018-12-10 14:29 UTC
#### Version

8.10+alpha (cb287591722e4d44671eb8c90138cf063ac5b707)

#### Operating system

- macOS 10.14
- Debian 4.9.110-3+deb9u3 (2018-08-19) x86_64 

#### Description of the problem

Here is some code from Mathcomp's `ssrnat`, illustrating the issue.
```coq
Notation succn := (Datatypes.S).

Notation "n .+1" := (succn n) (at level 2, left associativity,
  format "n .+1") : nat_scope.

Locate ".+1".
(* Notation *)
(* "n .+1" := S n : nat_scope (default interpretation) *)
(** so Coq does not apply succn notation *)

Goal forall x : nat, x.+1 = x.+1.
(* forall x : nat, succn x = succn x *)
(** here Coq should keep ".+1" notations *)
```

Reported by @mr-ohman.

**Comment by ejgallego** [comment] 2018-12-10 15:02
Is this a recent regression? If so #8187 could have something to do.

**Comment by anton-trunov** [comment] 2018-12-10 15:41
It seems that 82eacb323837acc73c2a5bf6b22a7169bbb61e6d didn't have it. And we noticed it last week around Dec 4th or 5th.

**Comment by ejgallego** [comment] 2018-12-10 18:15
cc: @herbelin

**Comment by ejgallego** [comment] 2018-12-10 22:44
Labelling tentatively as regression.

**Comment by herbelin** [comment] 2018-12-11 12:36
It is indeed a new rule (and actually the purpose) of #8187 that printing is governed by looking at the ordered stack of open scopes, rather than by the order of `Notation` commands. Something had to be done for isolated notations and the decision was to interleave them with the scopes. So, here, the `succn` rule takes precedence over `nat_scope` which was opened before.

When to prefer or not isolated notations over notations in a scope is still an open question (this includes in particular abbreviations, i.e. a `Notation` with a name rather than a string). So examples are useful to understand what to do.

In the above, put in its real context, can you explain the motivation for the `succn` abbreviation since there is already a `.+1` notation?

**Comment by anton-trunov** [comment] 2018-12-11 13:54
> In the above, put in its real context, can you explain the motivation for the `succn` abbreviation since there is already a `.+1` notation?

I think the purpose of that is to have a self-explanatory notation for the successor function when it's not applied to an argument (CC: @ggonthier @CohenCyril @gares).

We are also experiencing some breakage of notations in FCSL library. I'll try to provide a minimized example.

**Comment by herbelin** [comment] 2018-12-11 15:00
> I guess the intended fix for this should be changing the scope of the last notation into nat_scope

Yes, that's a possible fix. Otherwise, the notation for `+` in `nat_scope` takes precedence over the notation for `(f (fst x) + f (snd x))` in `fun_scope` (since you opened `nat_scope` more recently than `fun_scope`).

**Comment by ggonthier** [comment] 2018-12-11 15:36
Regarding the `succn n` / `n.+1` issue, as @anton-trunov hinted, this is a fairly common instance of having one abbreviation for a function, and an infix notation for the application of that function to enough arguments.
I don't see how this should be decided by priority on notations, rather than top-down analysis of the term to be displayed. In looking at the `Datatypes.S n` expression when `nat_scope` is open, the `n.+1` notation matches and the `succn` abbreviation doesn't, so there is no conflict. In displaying
`@map nat Datatypes.S (iota m n)` the `_.+1` notation can't be used and the succn abbreviation applies and `map succn (iota m n)` should be displayed. So what causes the conflict?

**Comment by herbelin** [comment] 2018-12-11 17:02
> Regarding the succn n / n.+1 issue, as @anton-trunov hinted, this is a fairly common instance of having one abbreviation for a function, and an infix notation for the application of that function to enough arguments.

Are you implicitly saying that you are unsatisfied with reusing the name `S`?

> I don't see how this should be decided by priority on notations, rather than top-down analysis of the term to be displayed.

That's right, something clever should be possible here.

The point is that application nodes are (up to now) treated differently than other nodes, not considering `t` to be a subterm of `t u`.

Let me compare with the following situation:
```
Notation "n .+1" := (S n) (at level 2, left associativity, format "n .+1") : nat_scope.
Notation "'succn'" := (Datatypes.S) : nat_scope.
Goal forall x : nat, x.+1 = x.+1.
```
The "legacy" behavior (say 8.9) is already to use `succn`, because `succn` is defined after `.+1` and takes precedence (using the notation declaration order), even though `.+1` matches first in the subterm order.

So, shortly, is there some form of consensus (typically motivated by experience), to consider that, even for applicative nodes, it is expected that the subterm order takes precedence on both scope order and notation declaration order (knowing that this is not the case up to now). If yes, I can implement it (or help someone in implementing it if someone volunteers - the treatment of applicative nodes is a bit complex, especially because of implicit arguments, but I guess that ordering the applicative notations by the number of arguments they expect should do the work).

**Comment by ggonthier** [comment] 2018-12-11 17:20
At least in the context of abstract algebra, `S` is much too likely to clash with a conventional local variable name to be used as a global constant (that applies to other single-letter constants, too).
  In older versions of Coq, we avoided the conflict by defining the infix notation after the constant abbreviation. This has been broken silently in recent versions, in a way undetected by regression builds (which check comparability and not display), and subtle (things still worked in `ssrnat.v` but not in files importing it).
  I'd vote for looking for notation for full applications first. Legitimately, partial applications should be looked up with a different scope stack - with `function_scope` pushed on top.

**Comment by gares** [comment] 2018-12-11 17:21
The reason why people alias `S` to a longer name is that `S` is likely to be used as a variable name.

**Comment by herbelin** [comment] 2018-12-11 18:20
@gares, @ggonthier: I agree. Using `S` for such pervasive notion easily comes to be a source of confusion.

As you can guess, one reason I'm asking is that there are situations where mathcomp or ssreflect take different notations for reasons which are not always clear. So, if, one day, you could motivate your choices, that'd be useful I think. When there are objective reasons to prefer a notation over another, it is probably worth to do so that everyone can take benefit of it.

> This has been broken silently in recent versions.

What do you mean? Are you referring to #8187?

>  Legitimately, partial applications should be looked up with a different scope stack - with function_scope pushed on top.

Looks indeed like the intuitive thing to do. In practice, the (e.g.) standard library is missing examples using `function_scope` and I'm personally not able to evaluate the impact it would have. Do you have (simple) concrete examples where it would matter to explicitly open a generic function scope in partial applications (compared e.g. to using more specific scopes)?

**Comment by ggonthier** [comment] 2018-12-11 18:31
I'm afraid I don't have any example either - I was just pointing this out as a matter of principle. In fact just after I wrote that comment I realised that I was more concerned that whatever transient scope was pushed for to the full expression should probably be popped (and replaced with `function_scope`) for partial applications, because they certainly don't have the type it was bound to.

**Comment by herbelin** [comment] 2018-12-11 21:36
@ggonthier: ah, ok, similar observation then.

Continuing thinking at respecting the lambda-calculus subterm order in applicative nodes, I realized that with @anton-trunov's generic notation for functions, the following happens (from 8.6 to master):
```
Notation "f '.s' x" := (f (fst x)) (at level 10, format "f '.s'  x").
Check fun (f:nat->nat->nat) (x y:nat *nat) => f (fst x) (fst y).
(* fun (f : nat -> nat -> nat) (x y : nat * nat) => (f.s x) (fst y) *)
```
Should we instead expect `fun (f : nat -> nat -> nat) (x y : nat * nat) => (f.s x).s y`?

**Comment by anton-trunov** [comment] 2018-12-12 07:55
> Should we instead expect `fun (f : nat -> nat -> nat) (x y : nat * nat) => (f.s x).s y`?

I would agree with your analysis.

**Comment by herbelin** [comment] 2018-12-12 12:17
Following the discussion, I'm proposing #9207. By the way, what is the motivation for the "blocker" tag?

**Comment by gares** [comment] 2018-12-12 13:21
It is a bug that, IMO, makes the system pretty unusable on (a lot of) code that existed.
The purpose is not to forget to address the issue before releasing Coq.

Another way to put it: if we had good tests, the regression would have been spotted by CI and make math-comp fail badly. In that case the PR would have not been merged without a fix. The semantic of blocker is that the current state (merged, but without a fix) should not be released.

**Comment by herbelin** [comment] 2018-12-12 14:00
What reported @anton-trunov does not seem to refer to a "pretty unusable" situation since simply removing the `succn` notation, or simply re-issueing a `Open Scope nat_scope` after the `succn` notation would resolve the problem.

Even using a `critical` status would seem exaggerated to me.

So, it seems to me that the choice of the tag `blocker` is mostly reflecting the emotion induced by the observation of the change, rather than by an objective analysis of the situation. May I be right?

**Comment by ejgallego** [comment] 2018-12-12 14:13
Indeed @herbelin a big pending issue we have is how to tag / milestone issues, here I guess the problem is that we cannot agree on a common procedure, as we have done for PRs.

**Comment by gares** [comment] 2018-12-12 15:22
I disagree, not displaying `.+1` in mathcomp is, to my eyes, a very big problem. It is used literally everywhere.

One of the criteria used in Debian to decide the severity of bugs is how many users are affected at at what extent you are making their life hard. A terminal that beeps whenever you touch a key is never likely to make the system fail to boot, and may have an easy work around, but if it affects all users and I'm pretty sure you don't want to release an OS with that bug in there. You don't want to release an OS that does not boot either. I'd say both bugs are critical, but they are very different. The one being discussed here is, to me, pretty close to the terminal that beeps all the times.

**Comment by herbelin** [comment] 2018-12-12 16:02
@gares: first, this is _not a bug_ per se. There is a new model for printing notations and it is normal that we evaluate this new model. Second, there is no intention to damage the use of the MathComp library. When you change `coq_makefile` and that it behaves differently, forcing mostly all users to adapt, is it a bug? And when you change the behavior of `coqtop` and I spend two hours to fix the environment I'm used to work with, how would you qualify it? Let's be reasonable: we are discussing about a feature which is for 8.10beta, even not for 8.9. We do want that Coq evolved right? It was good to have a `coq_makefile` based on more regular model and it is normal that changes of models induce compromises. We are discussing about a feature which, I repeated it often enough, needs to be used so as to be confrounted to the reality of usages.

So, keep the blocker tag if you feel better with it, but I find it misplaced and overkill.

By the way, it is several years that I'm suggesting that we make the step to add the `.+1` notation (which I like a lot) in the standard library, but I never succeeded to get support from other people. Maybe the right time to do it?

**Comment by ggonthier** [comment] 2019-02-06 11:21
We'd been pursuing this discussion in #9207, but I believe it would now be useful to repatriate it here, because after pondering a lot over the issue I've come to the conclusion that, as is, #8187 breaks a large number of MathComp notations in a way that cannot be fixed, even with improvements like #9207 and other functionality that we discussed within that PR. The only way I see of ensuring compatibility would be to restrict the use of scope stack precedence to specifically marked scopes - I'll detail that at the end of this comment.
    I gather that #8187 had two aims:
  (1) Replace the declaration/import printing notation priorities with more declarative and flexible ones based on the scopes and their order in the scope stack.
  (2) Grant a feature request, giving users a more flexible way of displaying lists in alternative way than (re)`Import`ing declarations, for example based on argument positions.
I'd object that (1) is only partly achieved, because within the same scope order-of-declaration is still used (and declarations in the same scope can be in multiple files), and (2) was already largely available through the use of undelimited notations (and MathComp makes use of this).
   My main objection, however, to #8187, is that it seems to assume that `Notation` declarations mostly link concrete syntax to a single constant, like `Infix` does. This is not the case in MathComp, where many notations link syntax to _specialisations_ of a constant:
   - `x < y < z` specialises `andb` to comparisons (in multiple scopes).
   - `(A == B)%MS` specialises `andb` to `subsetmx`.
   - `m = n %[mod p]` specialises `eq` to `modn _ p` arguments; likewise `m == n %[mod p]` (also in multiple scopes for 
   - `(p %| z)%Z` specialises `in_mem` to `dvdz`.
   - `\sum_i F i` specialises `bigop` to `0` and `addn`, or `Gring.add`, or `addsmx`, etc.
   - `'N_G(H)` and `'C_G(H)` specialise `setI` to `normaliser` and `centraliser`.
   - `p \is monic` and `x \is a GRing.unit` specialise `in_mem` to `has_quality`.
   - `A \in R` specialises `subsetmx` to `mxvec`.
Except for the last two, the specialised generic constant has its own notation in a _different_ scope, which is often globally opened and/or bound to the return type of the constant (e.g., `bool_scope`), and in all such cases #8187 breaks display of the specialised notation. This is particularly egregious for  generics like `andb` with notations in `bool_scope`, because it is bound to `bool` and thus has top priority in any context where a `bool` is expected, and thus overrides (and breaks) all the specialised variants. These are often in non-opened scopes, with the delimiter part of the intended syntax, such as `(A <= B)%MS` for `subsetmx`. Putting all specialised notations in `bool_scope` is not possible because this would break overloading and/or cause the wrong delimiter to be printed, and binding multiple scopes to `bool` does not work because this does not affect the `Arguments` scopes of existing constants (and it would entail putting the specialised notation in different, bespoke scopes, with different delimiters - breaking interfaces and backward compatibility).
   To summarizes #8187 breaks many MathComp notations in a way that cannot be fixed - at least I haven't been able to think of a fix/extension of #8187 that meets goal (1) as stated. For the purposes of giving priority to more specialised notation, the last recently declared policy works just fine because the notation for the generic operator will have been declared before the specialised notation is given. Indeed the generic notation usually appear in the right hand side of the specialised notation. So, in essence, that priority is not "broken", and does not need to be "fixed".
  The only way I see of making #8187 workable would be to restrict it to specifically marked scopes, say with `Declare Scope my_list_scope : printing`. Only those would be given priority when opened, and disabled when not opened (along with undelimited scopes for the latter). Absent this, things would work as before #8187, i.e., all other (accessible) scopes are lumped together and priority is given to the most recently declared notation.

**Comment by maximedenes** [comment] 2019-04-02 09:31
This is marked as a beta blocker, but has no assignee. Please assign within a few days, or we risk having to consider a pre-release revert.

**Comment by ejgallego** [comment] 2019-04-02 09:46
The situation here is very complex, also aggravated with the maintainers being busy with other affairs. A revert certainly seems counter productive and should not happen again, but we should implement:

> The only way I see of ensuring compatibility would be to restrict the use of scope stack precedence to specifically marked scopes

until we can converge on the rest.

**Comment by maximedenes** [comment] 2019-04-02 09:55
> but we should implement

Ok, but who is "we"? Of course, I'd prefer not to revert, but leaving the issue open with no assignee is not going to make it solve itself magically, I'm afraid.

**Comment by ggonthier** [comment] 2019-04-02 15:09
From what I understand, my suggestion 

> to restrict the use of scope stack precedence to specifically marked scopes

mostly amounts to reverting #8187, since by default all existing notation would follow the old rules; it would nevertheless provide support for users of the new precedence (e.g., Mtac2). It may involve some non-trivial merging, however: it's not just a matter of adding a `printing` flag to scopes, some vernacular to set it, and lumping together all non-marked scopes; one has to reinstate the scope visibility checks for undelimited scopes, which I believe were removed in #8187.

**Comment by maximedenes** [comment] 2019-04-03 16:40
@ejgallego did you assign me by mistake? I'm not competent to work on this issue, I'm afraid.

**Comment by ejgallego** [comment] 2019-04-03 16:42
I am following what @vbgl mentioned, no more issues with milestone but without an assignee.

This leaves the blocker ones, so in this case I am assigning to you as I understood you would be the person that would revert the patch, but maybe that person will be @vbgl ?

**Comment by maximedenes** [comment] 2019-04-03 16:45
Before preparing a revert, I'd like to get confirmation that nobody is working on fixing the issue. @herbelin, maybe?

**Comment by vbgl** [comment] 2019-04-23 14:35
No confirmation is as good as a confirmation that nobody is working on it.

I’m afraid we are going to need to prepare a revert this week.

**Comment by herbelin** [comment] 2019-04-28 14:11
In the last months, I've indeed been busy with other affairs, and overwhelmed with the hundreds of notifications piling without knowing in which priority order to read them (I'm now trying another way to received more focussed notifications). I'm sorry.

In particular, I haven't seen @ggonthier's summary above. In any case, a revert is the reasonable thing to do for 8.10, especially from the moment @vgbl succeeded in preparing a PR.

More in the next comment.

**Comment by herbelin** [comment] 2019-04-28 14:14
@ggonthier: thanks a lot for rapatriating the discussion in a central place. I mostly agree with your summary of objectives and I would like to make a step in better understanding what to do.

> I gather that #8187 had two aims:
> (1) Replace the declaration/import printing notation priorities with more declarative and flexible ones based on the scopes and their order in the scope stack.
> (2) Grant a feature request, giving users a more flexible way of displaying lists in alternative way than (re)Importing declarations, for example based on argument positions.

Yes, this was my view and this is what I told you. After more thinking, I think that point (2) is more general than that. I would say that it is simply about honoring priority of scopes when some `%key` is used in a notation. An example is given [here](https://github.com/coq/coq/issues/8805#issuecomment-432281939) as part of #8805.

> I'd object that (1) is only partly achieved, because within the same scope order-of-declaration is still used (and declarations in the same scope can be in multiple files), 

What do you expect more than using order-of-declaration within the same scope? Are you e.g. thinking at taking explicit user-given priority? Or are you thinking at automatically determining when a notation is a specialization of another (see also below)?

> and (2) was already largely available through the use of undelimited notations (and MathComp makes use of this).

If I remember correctly, your trick to e.g. print lists in more than one way was to declare the extra rules at the end (in declaration order) and to put them in a non-delimited scope. Since the scope is non-delimited, you're not allowed to use a key and then have to force the use of a scope using a `Bind Scope`, was that your idea? It seems to me that #8187 then allows to do it in a more natural way (as e.g. [here](https://github.com/coq/coq/blob/ae4239d6a5f4afcd9b7321dba790ffd4a64994a1/test-suite/output/Notations3.v#L420-L473))?

So, before going further, we have to answer the question: are you ok with the idea that objective (1) is worth and that honoring scopes in notations as in #8805 is worth. I.e., are you ok to go on with #8187 and finding solutions providing more flexibility also for the purpose of MathComp?

If yes, I started to make propositions in this [comment](https://github.com/coq/coq/pull/9207#issuecomment-448957039). Point 3 (some `Promote Scope` command) still looks reasonable to me to address the `%MS` style of issue. I will postpone thinking at the delicate point 1 (scoped abbreviations) for the moment. For point 2, which seems to be the most common current drawback of #8187, I'm now thinking to another approach which is to teach the notation system about notations being specializations of others.

Let's summarize what you already pointed out elsewhere: disambiguation is of a different kind at parsing and printing. The notation database is made of pairs `(notation,interpretation)` and the relation is functional in neither a way nor the other.

Let's consider a typical ambiguous set of notations which seems to cover the kind of ambiguities we want to address:
```
("A /\ B", and A B)
("A /\ B", andb A B)
("a < b", le a b)
("a < b", leb a b)
("a < b < c", and (le a b) (le a b))
("a < b < c", andb (leb a b) (leb a b))
("A & B", and A B)
```
Disambiguation from left to right (parsing) is done using scopes. Disambiguation from right to left (printing) was done using order-of-declaration and we are discussing about whether we can also make it consistent with the scope stack. For instance, it seems relatively natural to me to be able to disambiguate `("A /\ B", and A B)` and `("A & B", and A B)` on demand using a notion of scopes rather than to be dependent on the order of declarations.

Where there is a problem, it is with a subset such as:
```
("A /\ B", and A B)
("A /\ B", andb A B)
("a < b < c", and (le a b) (le a b))
```
where `and A B` is to be differentiated both from `andb A B` (when parsing `/\`) and from `and (le a b) (le a b)` (when printing).

My (naive) idea was that we can always dispatch conflicting notations into fine-grained enough scopes so that no conflicts exist in a scope, neither at printing nor at parsing. However, splitting scopes into smaller subscopes has drawbacks. What was once a single scope, e.g. `type_scope`, is split for printing into several subscopes, e.g. `type_generic_scope` and `type_nat_scope` but from the point of view of parsing, we still want `type_generic_scope` and `type_nat_scope` to form one single scope, with the lack of robustness wrt pre-existing argument scopes declarations mentioned by @ggonthier.

An alternative I'm now thinking would be to store the information that a notation is a specialization of another notation. Then when the scope containing the more general notation is open, say S, all the specializations of its notations which belong to an open scope are automatically considered to be part of S. Thus, in the [`m <= n <= p`](https://github.com/coq/coq/pull/9207#issuecomment-446658128) situation, locally opening `bool_scope` would pull with it the specialization in `nat_scope`.

Recognizing that a notation is a specialization of a previous one could be done automatically or, for more expressiveness, by using a special incantation, so that it can be used also to dynamically change the order of declaration.

I'll stop here, but, of course, there are also the other, sometimes unrelated, issues which arose during the discussion and which I shall eventually discuss at their place (this includes e.g. #9180 and #9311). But first, I need to understand if we agree on objectives.

PS: Writing this comment took me several hours and I would not be surprised that answering comments also takes a lot of time to @ggonthier. This is not per se a lost of time since the discussion can then hopefully be useful for anyone reading this thread, but, @ggonthier, if ever you pass in Paris intra-muros one of these days, we can also try to meet so as to be more efficient than by writing. We can then later summarize our discussions on github.

PS2: Despite the time taken to write this comment, I did not survey all what we discussed in December and January. So, if I'm missing something important of our discussions, please tell. E.g., do you think we should discuss more the idea of `Declare Scope my_list_scope : printing` or are you ok with first focussing on whether it is worth to provide native support for specialization?

**Closed** 2019-04-29 18:11 UTC
Labels: kind: regression, part: notations, priority: blocker

**Comment by herbelin** [comment] 2019-05-19 10:10
Note: #9751 is another example which shows a regression with #8187. It would also be fixed by inheriting in a scope all later notations from another scope featuring a more specific pattern (namely, referring to #9751, at the time of adding a lonely notation for `cons a nil`, since the latter refines `cons a b`, it would be considered also in the scope in which `cons a b` lives, i.e. in `test_scope`.
